force-app/main/default/objects/exceptions__c/exceptions__c.object-meta.xml
<CustomObject>
    <label>exceptions</label>
    <nameField>
        <label>exceptions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>exceptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/exceptions__c/fields/error__c.field-meta.xml
<CustomField>
    <fullName>error__c</fullName>
    <label>error</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/exceptions__c/fields/error_type__c.field-meta.xml
<CustomField>
    <fullName>error_type__c</fullName>
    <label>error_type</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/logger__c/logger__c.object-meta.xml
<CustomObject>
    <label>logger</label>
    <nameField>
        <label>logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>loger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/logger__c/fields/message__c.field-meta.xml
<CustomField>
    <fullName>message__c</fullName>
    <label>message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/logger__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>loger</relationshipLabel>
    <relationshipName>loger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <description>Account number for gas choice premises</description>
    <inlineHelpText>Account number for gas choice premises</inlineHelpText>
    <label>Account Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the order active (ie, not expired or replaced by a more current order?)</description>
    <inlineHelpText>Is the order active (ie, not expired or replaced by a more current order?)</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Confirmation_Code__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Code__c</fullName>
    <description>Gas choice confirmation codes</description>
    <inlineHelpText>Gas choice confirmation codes</inlineHelpText>
    <label>Confirmation Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Control__c.field-meta.xml
<CustomField>
    <fullName>Control__c</fullName>
    <description>Control number for NE/WY Choice account</description>
    <inlineHelpText>Control number for NE/WY Choice account</inlineHelpText>
    <label>Control</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Confirmed_Verification_Code__c.field-meta.xml
<CustomField>
    <fullName>Order_Confirmed_Verification_Code__c</fullName>
    <description>System verification number from whoever received the order.  Ex REP API transaction # or a SourceGas Verification Number</description>
    <inlineHelpText>System verification number from whoever received the order.  Ex REP API transaction # or a SourceGas Verification Number</inlineHelpText>
    <label>Order Confirmed Verification Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <description>This field captures why the REP rejected a customer.</description>
    <inlineHelpText>This field captures why the REP rejected a customer.</inlineHelpText>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Rejection</fullName>
            </value>
            <value>
                <fullName>Credit quality</fullName>
            </value>
            <value>
                <fullName>Customer Rescinded</fullName>
            </value>
            <value>
                <fullName>Deposit Unpaid</fullName>
            </value>
            <value>
                <fullName>Inaccurate address</fullName>
            </value>
            <value>
                <fullName>Inaccurate ESID</fullName>
            </value>
            <value>
                <fullName>Other (enter comments)</fullName>
            </value>
            <value>
                <fullName>Permit Problem</fullName>
            </value>
            <value>
                <fullName>Prior payment history</fullName>
            </value>
            <value>
                <fullName>Should have been a move</fullName>
            </value>
            <value>
                <fullName>Switch Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/response__c.field-meta.xml
<CustomField>
    <fullName>response__c</fullName>
    <label>response</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PartnerAPI__c/PartnerAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PartnerAPI</label>
</CustomObject>

force-app/main/default/objects/PartnerAPI__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The API is not used unless the active box is checked</description>
    <inlineHelpText>The API is not used unless the active box is checked</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SourceGasMgr.cls
public class SourceGasMgr {

public static boolean firstRun = true;    
    
public static void  sourcegas(id order)
{

String orderpass = order;

		
	
   Order__c orders = [select id,order_status__c, Rejection_Reason__c,Control__c,Confirmation_code__c,Account_Number__c, Order_Confirmed_Verification_Code__c , exception__c, response__c from order__c where id =: order];

if (orders.Order_Confirmed_Verification_Code__c == null)
{    
sourceComm(orderpass);
}

}
    
@future (callout= true)
public static void sourceComm(String orderId )
{
	triggerhelper.recursiveHelper(true);
	

system.debug('Order______________________________________'+ orderId);	
   Order__c order = [select id,order_status__c, Rejection_Reason__c,Control__c,Confirmation_code__c,Account_Number__c, Order_Confirmed_Verification_Code__c , exception__c, response__c from order__c where id =: orderId];
      Logger__c log = new Logger__c(
              
			   Name = 'Apex Action Source Gas call - ' + System.now(),
			   Message__c = string.valueof(order),Order__c = orderId
			  );
		Logger__c log2 = new Logger__c(
              
			   Name = 'Apex Action Source Gas call good - ' + orderId + System.now(),Order__c = orderId
			  );
SourceGasPrd.ZCgSelfservEnrlRfcResponse_element resp ;
    Try{
        
  
       SourceGasPrd.ZBN_CG_SIGNUP signup = new SourceGasPrd.ZBN_CG_SIGNUP();
  
 
        String IvAnlage = '';
        //String IvCaNo;
        //String IvConfCode;
        //String IvControlNo;
        String IvEnrlMeth = 'WEBSERVICE';
        String IvSubmit = 'X';
        
         //string IvCaNo = '211012415467';
         //string IvConfCode = '36028';//enrollment period is closed
         //string IvControlNo = '700531268';
    
         string IvCaNo = order.Account_Number__c;
         string IvConfCode = order.Confirmation_code__c;//enrollment period is closed text 30
         string IvControlNo = order.Control__c; // text 10
    
    
    
          signup.inputHttpHeaders_x = new map<String,String>();
          signup.outputHttpHeaders_x = new map<String,String>();
          signup.inputHttpHeaders_x.put('Authorization', getSGAuthHeader());
          
        
         resp = signup.ZCgSelfservEnrlRfc(IvAnlage, IvCaNo, IvConfCode, IvControlNo, IvEnrlMeth, IvSubmit);
           log2.message__c = string.valueof(resp);
           
          system.debug(resp);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line1);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line2);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line3);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line4);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line5);
          system.debug('resp.EsEadrln:   '+resp.EsEadrln.Line6);
          
          
          system.debug('resp.EsMessage:  '+resp.EsMessage.Id);
          system.debug('resp.EsMessage:  '+resp.EsMessage.Message);
          system.debug('resp.EsReturn:   '+resp.EsReturn.Id);
          system.debug('resp.EsReturn:   '+resp.EsReturn.LogMsgNo);
          system.debug('resp.EsReturn:   '+resp.EsReturn.LogNo);
          system.debug('resp.EsReturn:   '+resp.EsReturn.Message);
          system.debug('resp.EsReturn:   '+resp.EsReturn.MessageV1);
          system.debug('resp.EsReturn:  '+resp.EsReturn.MessageV2);
          system.debug('resp.EsReturn:   '+resp.EsReturn.MessageV3);
          system.debug('resp.EsReturn:  '+resp.EsReturn.MessageV4);
          system.debug('resp.EsReturn:  '+resp.EsReturn.Number_x);
          system.debug('resp.EsReturn:  '+resp.EsReturn.Type_x);
          
          system.debug('resp.EvAnlage:  '+resp.EvAnlage);
          system.debug('resp.EvName1:   '+resp.EvName1);
          system.debug('resp.EvName2:   '+resp.EvName2);
          system.debug('resp.EvPriceOpt:  '+resp.EvPriceOpt);
          system.debug('resp.EvServId:  '+resp.EvServId);
          system.debug('resp.EvServProv:  '+resp.EvServProv);
          system.debug('resp.EvVerifNoe:  '+resp.EvVerifNo);
          
          order.response__c  = string.valueof(resp);
        if (resp.EsMessage != null && resp.EsMessage.Id.length() > 0 && resp.EsMessage.id != 'E05')
        {
        order.Rejection_Reason__c = 'Code:'+ resp.EsMessage.Id + 'Message:' + resp.EsMessage.Message;
         order.order_status__c = 'Rejected';
         update order;
        }else if ( resp.EvVerifNo != null)
        {
         order.Order_Confirmed_Verification_Code__c= resp.EvVerifNo;
         order.Order_status__c = 'Success';
         update order;
        }else if( resp.Esmessage.id.contains('E0'))
        {
         order.Rejection_Reason__c = 'Code:'+ resp.EsMessage.Id + 'Message:' + resp.EsMessage.Message;
         order.order_status__c = 'Rejected';
         update order;
        
        }
        }

       catch (CalloutException ce){
         
         Exceptions__c error = new Exceptions__c(
              
			   Name = 'Apex Exception - ' + System.now(),
			   Error__c = ce.getMessage(),
			   Error_Type__c = ce.getTypeName()
			  );
			   
			  insert error;

         order.exception__c = ce.getTypeName() + ':' + ce.getMessage();
         order.order_status__c = 'API Error';
         update order;
			    
    } 
     
     catch(exception e)
     {
       
        Exceptions__c error = new Exceptions__c(
              
			   Name = 'Apex Exception - ' + System.now(),
			   Error__c = e.getMessage(),
			   Error_Type__c = e.getTypeName()
			  );
			   
			  insert error;
			  
         order.exception__c = e.getmessage();
         order.response__c  = string.valueof(resp);
         order.order_status__c = 'Failed';
         update order;
     }
     finally {
  insert log;
  insert log2;

}
}

public static string getSGAuthHeader(){
  PartnerAPI__c Papi = PartnerAPI__c.getInstance('SourceGas');
   Blob headerValue = Blob.valueOf(Papi.username__c + ':' + Papi.password__c);
   String authorizationHeader = 'Basic ' + EncodingUtil.base64Encode(headerValue);
   system.debug(authorizationHeader);
   return authorizationHeader;
}

public static void sourceCommMan(String orderId )
{
	
system.debug('Order______________________________________'+ orderId);	
   Order__c order = [select id,order_status__c, Rejection_Reason__c,Control__c,Confirmation_code__c,Account_Number__c, Order_Confirmed_Verification_Code__c , exception__c, response__c from order__c where id =: orderId];
    
	SourceGasPrd.ZCgSelfservEnrlRfcResponse_element resp ;
  PartnerAPI__c Papi = PartnerAPI__c.getInstance('SourceGas');

	if (order.Order_Confirmed_Verification_Code__c == null && Papi.Active__c){
    Try{
        
         
       SourceGasPrd.ZBN_CG_SIGNUP signup = new SourceGasPrd.ZBN_CG_SIGNUP();
 
        String IvAnlage = '';
        //String IvCaNo;
        //String IvConfCode;
        //String IvControlNo;
        String IvEnrlMeth = 'WEBSERVICE';
        String IvSubmit = 'X';
        
         //string IvCaNo = '211012415467';
         //string IvConfCode = '36028';//enrollment period is closed
         //string IvControlNo = '700531268';
    
         string IvCaNo = order.Account_Number__c;
         string IvConfCode = order.Confirmation_code__c;//enrollment period is closed text 30
         string IvControlNo = order.Control__c; // text 10
    
    
    
          signup.inputHttpHeaders_x = new map<String,String>();
          signup.outputHttpHeaders_x = new map<String,String>();
           signup.inputHttpHeaders_x.put('Authorization', getSGAuthHeader());
          
          
         resp = signup.ZCgSelfservEnrlRfc(IvAnlage, IvCaNo, IvConfCode, IvControlNo, IvEnrlMeth, IvSubmit);
          
          system.debug(resp);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line1);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line2);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line3);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line4);
          system.debug('resp.EsEadrln:  '+resp.EsEadrln.Line5);
          system.debug('resp.EsEadrln:   '+resp.EsEadrln.Line6);
          
          
          system.debug('resp.EsMessage:  '+resp.EsMessage.Id);
          system.debug('resp.EsMessage:  '+resp.EsMessage.Message);
          system.debug('resp.EsReturn:   '+resp.EsReturn.Id);
          system.debug('resp.EsReturn:   '+resp.EsReturn.LogMsgNo);
          system.debug('resp.EsReturn:   '+resp.EsReturn.LogNo);
          system.debug('resp.EsReturn:   '+resp.EsReturn.Message);
          system.debug('resp.EsReturn:   '+resp.EsReturn.MessageV1);
          system.debug('resp.EsReturn:  '+resp.EsReturn.MessageV2);
          system.debug('resp.EsReturn:   '+resp.EsReturn.MessageV3);
          system.debug('resp.EsReturn:  '+resp.EsReturn.MessageV4);
          system.debug('resp.EsReturn:  '+resp.EsReturn.Number_x);
          system.debug('resp.EsReturn:  '+resp.EsReturn.Type_x);
          
          system.debug('resp.EvAnlage:  '+resp.EvAnlage);
          system.debug('resp.EvName1:   '+resp.EvName1);
          system.debug('resp.EvName2:   '+resp.EvName2);
          system.debug('resp.EvPriceOpt:  '+resp.EvPriceOpt);
          system.debug('resp.EvServId:  '+resp.EvServId);
          system.debug('resp.EvServProv:  '+resp.EvServProv);
          system.debug('resp.EvVerifNoe:  '+resp.EvVerifNo);
        }

       catch (CalloutException ce){
         order.exception__c = ce.getMessage();
    
    }
       system.debug('______________'+ resp.esmessage.id);
        if (resp.EsMessage.Id.length() >0)
        {
        order.Rejection_Reason__c = 'Code:'+ resp.EsMessage.Id + 'Message:' + resp.EsMessage.Message;
         order.order_status__c = 'Rejected';
         update order;
        }else{
         //order.response__c = stringvalueof(resp);
         order.Order_Confirmed_Verification_Code__c= resp.EvVerifNo;
         order.Order_status__c = 'Success';
         update order;
        }
	}
          //Order_Confirmed_Verification_Code__c

}
}