force-app/main/default/objects/Month_Estimate__c/Month_Estimate__c.object-meta.xml
<CustomObject>
    <label>Month Estimate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Month Estimate Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Estimate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Month_Estimate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Month Estimate</relationshipLabel>
    <relationshipName>Month_Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/recordTypes/Commercial.recordType-meta.xml
<RecordType>
    <fullName>Commercial</fullName>
    <active>true</active>
    <description>Shows the fields relevant to commercial rates.</description>
    <label>Commercial</label>
</RecordType>

force-app/main/default/objects/Rate__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <description>Shows the fields relevant to residential rates.</description>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/Saved_Plan__c/Saved_Plan__c.object-meta.xml
<CustomObject>
    <description>Links the Rate__c and AccountPremiseAssociation__c so that users can save plans to their accounts.</description>
    <label>Saved Plan</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Plan__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Saved Plans</relationshipLabel>
    <relationshipName>Saved_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ValidZipCode__c/ValidZipCode__c.object-meta.xml
<CustomObject>
    <description>Zip Codes and their Corresponding TDSPs</description>
    <label>Zip Code</label>
    <nameField>
        <label>ValidZipCode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ValidZipCode__c/fields/Served_by_TrueCost__c.field-meta.xml
<CustomField>
    <fullName>Served_by_TrueCost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This zip code is served by TrueCost</description>
    <inlineHelpText>This zip code is served by TrueCost</inlineHelpText>
    <label>Served by TrueCost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ValidZipCode__c/fields/TDSP_Lookup__c.field-meta.xml
<CustomField>
    <fullName>TDSP_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TDSP Lookup</label>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Zip Codes</relationshipLabel>
    <relationshipName>Zip_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TC2SwitchReminderPlans.cls
public with sharing class TC2SwitchReminderPlans  {

      public string recipientId;
      public string relatedToId;

      public Lead recipient {get;set;}
      public Lead relatedTo {get;set;}

      public string getRecipientId() {return recipientId; }
      public void setRecipientId(string inString) {
        recipientId = inString;
        recipient = [SELECT id,name,email FROM Lead WHERE id = :recipientId];
      }

      public string getRelatedToId() { return relatedToId;}
      public void setRelatedToId(string inString) {
        relatedToId = inString;
        relatedTo = [SELECT id,name,email FROM Lead WHERE id = :relatedToId];
      }

      public TC2SwitchReminderPlans() {
        // Whatever code you need in the constructor....
      }

      public list<ResultsContainer> getPlans(){
          list<ResultsContainer> result = ShopRemote(recipient.Zip__c);
          list<ResultsContainer> newList = new List<ResultsContainer>();
          for(Integer i = 0; i< 3;i++){
            newList.add(result[i]);
          }
          return newList;
      }

      public list<ResultsContainer> ShopRemote(string zipcode){

        list<ResultsContainer> PricedRates;
        id tdspid=TDSPIDfromZipCode(zipcode);
        list<rate__c> planlist2 = TrueCostCalc.getActivePlans2(null, tdspid, 'Residential');
        list<Saved_Plan__c> savedplans = new list<Saved_Plan__c>();
        string loadcurve; //starts null, which is fine for all but commercial.
        PricedRates = SimpleResults(TrueCostCalc.makeTempMonthEstimates(null,planlist2), planlist2, TrueCostUtilities.pullTheMonthlyUsage(null));
        return PricedRates;
    }
    public static string TDSPIDfromZipCode(string zip2check){ //checks to see if the entered zip code is served by TrueCost or in our expansion plans
        list<validzipcode__c> ziplist = new list<validzipcode__c>();
        ziplist= [select id, name, tdsp_lookup__r.name, tdsp_lookup__r.id, served_by_TrueCost__c from ValidZipCode__c where name =: zip2check];
        system.debug(ziplist);
        if (ziplist.size()==0) return null;
        if (ziplist.size()==1) {
            system.debug('returning ' + ziplist[0].tdsp_lookup__r.id);
            return ziplist[0].tdsp_lookup__r.id;
        }
        //if (ziplist.size()>1)
        return ziplist[0].tdsp_lookup__r.id; // if ziplist.size() is not 0 or 1 then it must be >1
        //return null;
    }
    public list<resultscontainer> SimpleResults(list<Month_Estimate__c> estimates,  list<Rate__c> planlist, list<Monthly_Usage__c> usage){

       list<resultscontainer> scoringresults = new list<resultscontainer> ();
       map<id, string> rewardmap = TrueCostUtilities.GrabRewardsText2(planlist);
       map<id, decimal> MEMAP = TrueCostCalc.MakeMonthEstimateMap(estimates);

        for (rate__c pi:planlist){
            resultscontainer rc=new resultscontainer(pi); //TrueCostUtilities.resultscontainer rc=new TrueCostUtilities.resultscontainer(pi);
            rc.rewardstext=rewardmap.get(pi.id);
            rc.price=MEMAP.get(pi.id);
            rc.pricekWh=rc.price/(TrueCostCalc.totaltheusage(usage) );      //calculate cents per kWh
            scoringresults.add(rc);
        }
        return scoringresults;
    }
}