force-app/main/default/objects/Index__c/Index__c.object-meta.xml
<CustomObject>
    <label>Index</label>
    <nameField>
        <label>Index Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Index__c/recordTypes/Index.recordType-meta.xml
<RecordType>
    <fullName>Index</fullName>
    <active>true</active>
    <description>This rate refers to an index (published or calculated)</description>
    <label>Index</label>
</RecordType>

force-app/main/default/objects/Index_Future__c/Index_Future__c.object-meta.xml
<CustomObject>
    <label>Index Future</label>
    <nameField>
        <label>Index Future Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Index Futures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Index_Future__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <description>What month is this for delivery (For example, 5/1/2014 mean May 2014 delivery)</description>
    <inlineHelpText>What month is this for delivery (For example, 5/1/2014 mean May 2014 delivery)</inlineHelpText>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Index_Future__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Index</label>
    <referenceTo>Index__c</referenceTo>
    <relationshipLabel>Index Futures</relationshipLabel>
    <relationshipName>Index_Futures</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Index_Future__c/fields/Index_Settlement__c.field-meta.xml
<CustomField>
    <fullName>Index_Settlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Index Settlement</label>
    <referenceTo>Index_Settlement__c</referenceTo>
    <relationshipLabel>Index Futures</relationshipLabel>
    <relationshipName>Index_Futures</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Index_Future__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE(MONTH(Delivery_Date__c),
1, &quot;Jan&quot;,
2, &quot;Feb&quot;,
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;,
7, &quot;Jul&quot;,
8, &quot;Aug&quot;,
9, &quot;Sep&quot;,
10, &quot;Oct&quot;,
11, &quot;Nov&quot;,
12, &quot;Dec&quot;,
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Index_Future__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Index_Future__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(YEAR(Delivery_Date__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Index_Settlement__c/Index_Settlement__c.object-meta.xml
<CustomObject>
    <label>Index Settlement</label>
    <nameField>
        <label>Index Settlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Index Settlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Index_Settlement__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <label>Index</label>
    <referenceTo>Index__c</referenceTo>
    <relationshipLabel>Index Settlements</relationshipLabel>
    <relationshipName>Index_Settlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Index_Settlement__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <description>For Ordering the Months in Report</description>
    <formula>CASE(MONTH(Effective_Date__c), 
1, &quot;Jan&quot;, 
2, &quot;Feb&quot;, 
3, &quot;Mar&quot;, 
4, &quot;Apr&quot;, 
5, &quot;May&quot;, 
6, &quot;Jun&quot;, 
7, &quot;Jul&quot;, 
8, &quot;Aug&quot;, 
9, &quot;Sep&quot;, 
10, &quot;Oct&quot;, 
11, &quot;Nov&quot;, 
12, &quot;Dec&quot;, 
&quot;None&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Index_Settlement__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <formula>TEXT(YEAR( Effective_Date__c ))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Year</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NymexNaturalGasFuturePriceTableCtrlTest.cls
@isTest
public class NymexNaturalGasFuturePriceTableCtrlTest {
    static testMethod void getIndexRecTest(){
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        system.assertEquals(3, indexMap.keySet().size());
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        if (uw != null) {
        	system.assertEquals(30, uw.listOfFirstThirtyFutures.size());
        	system.assertEquals(30, uw.listOfSecondThirtyFutures.size());
        }
    }
    static testMethod void getIndexRecTestForMonth1(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Year__c, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+1, 1);
        }
        indexFutureList[12].Delivery_Date__c = date.newInstance(system.today().year()+1, system.today().month()+1, 1);
        indexFutureList[24].Delivery_Date__c = date.newInstance(system.today().year()+1, system.today().month()+1, 1);
        indexFutureList[36].Delivery_Date__c = date.newInstance(system.today().year()+1, system.today().month()+1, 1);
        indexFutureList[48].Delivery_Date__c = date.newInstance(system.today().year()+1, system.today().month()+1, 1);
        
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    static testMethod void getIndexRecTestForMonth2(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+2, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    static testMethod void getIndexRecTestFoMonth3(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+3, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    static testMethod void getIndexRecTestForMonth4(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+4, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    static testMethod void getIndexRecTestForMonth5(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+5, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth6(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+6, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth7(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+7, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth8(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+8, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth9(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+9, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth10(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+10, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }static testMethod void getIndexRecTestForMonth11(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+11, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    static testMethod void getIndexRecTestForMonth12(){
        List<Index_Future__c> indexFutureList = [select id, Month__c, name, Index__c, Price__c, Delivery_Date__c from Index_Future__c];
        For(Index_Future__c inf: indexFutureList){
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month()+12, 1);
        }
        update indexFutureList;
        Map<String,String> indexMap = NymexNaturalGasFuturePriceTableCtrl.getIndexMap();
        NymexNaturalGasFuturePriceTableCtrl.UsageWrapper uw = NymexNaturalGasFuturePriceTableCtrl.getIndexRec();
        
    }
    @testSetup static void setup() {
        
		// system.debug('NymexNaturalGasFuturePriceTableCtrlTest setup: ');        
        
        List<Index_Settlement__c> indexSettlementList = new List<Index_Settlement__c>();
        List<Index_Future__c> indexFutureList = new List<Index_Future__c>();
        List<Index__c> indexList = new List<Index__c>();
        List<String> lstOfStr = new List<String>{'DTN HO DELAYED','DTN Propane DELAYED','DTN CL DELAYED','DTN GNG DELAYED'};
            
            for(integer i=0;i<lstOfStr.size();i++){
                Index__c indx = new Index__c();
                indx.name = lstOfStr[i];
                indexList.add(indx);
            }
        
        insert indexList;
        
        for(integer i=0;i<indexList.size();i++){
            Index_Future__c inf = new Index_Future__c();
            inf.name = 'Test Index Future';
            inf.Index__c = indexList[i].id;
            inf.Price__c = 12.345;
            inf.Delivery_Date__c = date.newInstance(system.today().year(), system.today().month(), 1);
            indexFutureList.add(inf);
        }
        
        // initialize with actual start date based on method
        Date testDeliveryDate = NymexNaturalGasFuturePriceTableCtrl.getFirstFutureMonthDate();
        
        for(integer i=0;i<60;i++){
            Index_Future__c inf = new Index_Future__c();
            inf.name = 'Test Index Future';
            inf.Index__c = indexList[3].id;   //; 'DTN GNG DELAYED'
            inf.Price__c = 12.345;
            inf.Delivery_Date__c = testDeliveryDate;
            indexFutureList.add(inf);
            
            // add one month for each delivery period out to 60 months
            testDeliveryDate = testDeliveryDate.addMonths(1);            
        }
        insert indexFutureList;
        
		// system.debug('indexFutureList: ' + indexFutureList);
        
    }
}