force-app/main/default/objects/HSP_S__c/HSP_S__c.object-meta.xml
<CustomObject>
    <description>Home Service Plan South Region</description>
    <label>Home Service Plan South</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>HSP-S Plan</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Home Service Plans South</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HSP_S__c/fields/Activation_Date__c.field-meta.xml
<CustomField>
    <fullName>Activation_Date__c</fullName>
    <description>Date of plan activation</description>
    <label>Activation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Activate this plan</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Confirmation_Name__c.field-meta.xml
<CustomField>
    <fullName>Confirmation_Name__c</fullName>
    <description>Confirmation name of product</description>
    <label>Confirmation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/downsell__c.field-meta.xml
<CustomField>
    <fullName>downsell__c</fullName>
    <defaultValue>true</defaultValue>
    <description>A downsell is displayed after the user is provided a bundle and does NOT select the bundle.</description>
    <inlineHelpText>Downsell is followed by skipping a bundle</inlineHelpText>
    <label>Downsell</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Headline__c.field-meta.xml
<CustomField>
    <fullName>Headline__c</fullName>
    <description>Plan Headline</description>
    <label>Headline</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Icon__c.field-meta.xml
<CustomField>
    <fullName>Icon__c</fullName>
    <description>Plan icon</description>
    <label>Icon</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/leading__c.field-meta.xml
<CustomField>
    <fullName>leading__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If an upsell is represented a leading must first be chosen. The user first sees the leading plan and if they select the leading plan they are then seen taken to an upsell plan.</description>
    <inlineHelpText>This will be the first plan to display to the user before an upsell.</inlineHelpText>
    <label>leading</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Plan_Id__c.field-meta.xml
<CustomField>
    <fullName>Plan_Id__c</fullName>
    <label>Plan Id</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Price_List__c.field-meta.xml
<CustomField>
    <fullName>Price_List__c</fullName>
    <description>List price</description>
    <label>Price List</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Price_Net__c.field-meta.xml
<CustomField>
    <fullName>Price_Net__c</fullName>
    <description>The listed price for the plan</description>
    <inlineHelpText>Base Price</inlineHelpText>
    <label>Price Net</label>
    <precision>17</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Product_Body__c.field-meta.xml
<CustomField>
    <fullName>Product_Body__c</fullName>
    <description>Plan description</description>
    <label>Product Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Product_Details_Link__c.field-meta.xml
<CustomField>
    <fullName>Product_Details_Link__c</fullName>
    <description>Link to more information about the product</description>
    <label>Product Details Link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product Name</description>
    <label>Product Name</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/sort_order__c.field-meta.xml
<CustomField>
    <fullName>sort_order__c</fullName>
    <label>sort_order</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/HSP_S__c/fields/Terms_URL__c.field-meta.xml
<CustomField>
    <fullName>Terms_URL__c</fullName>
    <description>Link to terms</description>
    <label>Terms URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/HSP_S__c/recordTypes/list.recordType-meta.xml
<RecordType>
    <fullName>list</fullName>
    <active>true</active>
    <label>list</label>
</RecordType>

force-app/main/default/classes/HSPSController.cls
public class HSPSController {

    public list<HSP_S__c> objlist {get;set;}
    
    public HSPSController() {

        objlist = [SELECT 
            Name,
            Headline__c, 
            Product_Body__c,
            Product_Name__c,
            Active__c, 
            Activation_Date__c, 
            Confirmation_Name__c, 
            Icon__c, 
            Plan_Id__c, 
            Price_List__c, 
            Price_Net__c, 
            Product_Details_Link__c, 
            Terms_URL__c,
            sort_order__c,
            downsell__c,
            leading__c
        FROM HSP_S__c WHERE Active__c = true ORDER BY sort_order__c];
        
    }    
}