force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Plan__c/Saved_Plan__c.object-meta.xml
<CustomObject>
    <description>Links the Rate__c and AccountPremiseAssociation__c so that users can save plans to their accounts.</description>
    <label>Saved Plan</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Plan__c/fields/AccountPremiseAssociation__c.field-meta.xml
<CustomField>
    <fullName>AccountPremiseAssociation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AccountPremiseAssociation</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Saved Plans</relationshipLabel>
    <relationshipName>Saved_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ControllerForSavedPlansComponent.cls
public with sharing class ControllerForSavedPlansComponent {
	public list<saved_plan__c> sp {get;set;}
	public id APAid{get;set;}
	AccountPremiseAssociation__c APA {get;set;}
	
	public ControllerForSavedPlansComponent(){
		try{
		if (APAid!=null) {
			APA = [select id from AccountPremiseAssociation__c where id=:APAid];
		} else {
			APA = [select id from AccountPremiseAssociation__c where id=: TrueCostUtilities.getTheAPAs(UserInfo.getUserId())];
		}
		sp = TrueCostUtilities.fetchSavedPlans(APA);	
		} catch(exception e){}
	}
}