force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Estimated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meter Data Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The account has provided permission to retrieve data for this premise</description>
    <inlineHelpText>The account has provided permission to retrieve data for this premise</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Request_Status__c</fullName>
    <label>Meter Data Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error-Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Service Address</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Meter/ESID Match</fullName>
            </value>
            <value>
                <fullName>Error-No REP of Record</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/X50KVA__c.field-meta.xml
<CustomField>
    <fullName>X50KVA__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This premise is is commercial.</description>
    <inlineHelpText>This premise is is commercial.</inlineHelpText>
    <label>&gt;50KVA</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which account premise association the usage is linked to</description>
    <inlineHelpText>Which account premise association the usage is linked to</inlineHelpText>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Estimated__c.field-meta.xml
<CustomField>
    <fullName>Estimated__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This value is estimated by TrueCost and is not from an external system</description>
    <inlineHelpText>This value is estimated by TrueCost and is not from an external system</inlineHelpText>
    <label>Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer at this premise authorized us to use its meter data?</description>
    <inlineHelpText>Has the customer at this premise authorized us to use its meter data?</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/uhitmessage__c.object-meta.xml
<CustomObject>
    <label>uhitmessage</label>
    <nameField>
        <label>uhitmessage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>uhitmessage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uhitmessage__c/fields/ActKWH__c.field-meta.xml
<CustomField>
    <fullName>ActKWH__c</fullName>
    <label>ActKWH</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/BilledKVA__c.field-meta.xml
<CustomField>
    <fullName>BilledKVA__c</fullName>
    <label>BilledKVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <externalId>true</externalId>
    <label>ESID</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/item__c.field-meta.xml
<CustomField>
    <fullName>item__c</fullName>
    <label>item</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/LoadProfile__c.field-meta.xml
<CustomField>
    <fullName>LoadProfile__c</fullName>
    <label>LoadProfile</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/MeteredKVA__c.field-meta.xml
<CustomField>
    <fullName>MeteredKVA__c</fullName>
    <label>MeteredKVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/MeterReadCycle__c.field-meta.xml
<CustomField>
    <fullName>MeterReadCycle__c</fullName>
    <label>MeterReadCycle</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/PowerFactor__c.field-meta.xml
<CustomField>
    <fullName>PowerFactor__c</fullName>
    <label>PowerFactor</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>uhitmessage</relationshipLabel>
    <relationshipName>uhitmessage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/RateCode__c.field-meta.xml
<CustomField>
    <fullName>RateCode__c</fullName>
    <label>RateCode</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/RequestStatus__c.field-meta.xml
<CustomField>
    <fullName>RequestStatus__c</fullName>
    <label>RequestStatus</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/UHITRequest__c.object-meta.xml
<CustomObject>
    <label>UHITRequest</label>
    <nameField>
        <label>UHITRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHITRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UHITRequest__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>UHITRequest</relationshipLabel>
    <relationshipName>UHITRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <label>ESID</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UsageRequestManager.cls
public  class UsageRequestManager {

	public void reply(uhitmessage__c  message){

		try{
			//data setup
			system.debug('start process +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++' + message);
			String requestId = '%'+message.requestId__c+'%';
			system.debug('requestid +++++++++++++++++++++++++++++++++++++++++++++' + requestId);
			uhitrequest__c msg = [SELECT APA__c,RequestId__c  FROM UHITRequest__c where requestId__c LIKE :requestId limit 1];
			system.debug('msg size_____________________________________________'+ msg);
			AccountPremiseAssociation__c apa = [SELECT Account__c, Id, X50KVA__c, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,premise__r.id FROM AccountPremiseAssociation__c where id=:msg.APA__c limit 1];
			system.debug('apa_______________________________________________' + apa);

			list<uhitmessage__c> dataPassed = [SELECT item__c, ActKWH__c,BilledKVA__c,EndDate__c,ESID__c,Id,MeteredKVA__c,MeterReadCycle__c,PowerFactor__c,LoadProfile__c, RateCode__c,RequestId__c,RequestStatus__c,StartDate__c,status__c FROM uhitmessage__c where requestId__c LIKE :requestId order by item__c];

			UsageRequestManager.sharedDataProcessing(apa, dataPassed);

			AsyncRequest__c ASR = new AsyncRequest__c(type__c='UHITDaily', params__c=APA.id);
			insert ASR;

			System.debug('seting complete');
			
		}catch(exception e){
			system.debug(e);
		}
	}

	public static void processManualUHM(string APAid){
		//get the APA
		AccountPremiseAssociation__c apa = [SELECT Account__c, Id, X50KVA__c, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,premise__r.id, premise__r.ESID__c FROM AccountPremiseAssociation__c where id=:APAid];

		//get all the UHM for that APAid
		list<uhitmessage__c> dataPassed = [SELECT item__c, ActKWH__c,BilledKVA__c,EndDate__c,ESID__c,Id,MeteredKVA__c,MeterReadCycle__c,PowerFactor__c,LoadProfile__c, RateCode__c,RequestId__c,RequestStatus__c,StartDate__c, Status__c 
			FROM uhitmessage__c 
			where ESID__c =:apa.premise__r.ESID__c];

		UsageRequestManager.sharedDataProcessing(apa, dataPassed);



	}

	public static void sharedDataProcessing(AccountPremiseAssociation__c apa, list<uhitmessage__c> dataPassed){
		//the premise for updating
		Premises__c premiseReq = [SELECT id, Load_Profile__c FROM Premises__c where id=:apa.Premise__c];

		dataPassed = DedupeUHIT(dataPassed); //dedupe by start date
		
		AllocateUsage(dataPassed, apa); //turning into monthly usages

		apa.Meter_Data_Request_Status__c = 'Complete';
		//billed KVA > 50, then flip flag on APA.
		if (!apa.X50KVA__c){
			for (uhitmessage__c uhm:dataPassed){
				if (uhm.BilledKVA__c>50){
					apa.X50KVA__c=true;
				}
			}
		}
		update apa;

		//set load profile on premise
		premiseReq.Load_Profile__c = dataPassed[0].LoadProfile__c;
		system.debug('before update complete___________________________________________________________'+ premiseReq);
		update premiseReq;
		system.debug('after update complete___________________________________________________________'+ premiseReq);

	}

	public static list<uhitmessage__c> DedupeUHIT(list<uhitmessage__c> data){
		map<date, uhitmessage__c> DedupeMap = new map<date, uhitmessage__c>();
		for (uhitmessage__c uhm:data){
			DedupeMap.put(uhm.StartDate__c, uhm);
		}
        return DedupeMap.values();
	}

	public static void AllocateUsage(list<uhitmessage__c> data, AccountPremiseAssociation__C APA){

		list<monthly_usage__c> output = new list<monthly_usage__c>();

		//build the output set with the month numbers, premise, APA, and usage ==0 
		for (integer x=1; x<13; x++){
			monthly_usage__C mu = new monthly_usage__c();
			mu.month_number__c = x;
			mu.APA__c = APA.id;
			mu.premise__c = APA.premise__r.id;
			mu.Usage__c = 0;
			mu.estimated__c = false;
			output.add(mu);    

		}
		system.debug('output'+ output);

		for (uhitmessage__c row:data){
			integer startmonth = row.StartDate__c.month(); system.debug('=========================================StartMonth is '+ startmonth);
			integer endmonth = row.EndDate__c.month();  system.debug('=========================================EndMonth is '+ endmonth);
			integer startmonthdays;
			integer endmonthdays;            
			decimal startmonthusage;
			decimal endmonthusage;

			//startmonth is endmonth
			if(startmonth == endmonth){
				output[startmonth-1].usage__c=output[startmonth-1].usage__c + row.ActKWH__c;
				system.debug('==========================usage is '+row.ActKWH__c + ' for month' + startmonth);
			}
			
			//consecutive months
			if(endmonth == startmonth + 1 || (endmonth ==1 && startmonth ==12 )){
				startmonthdays = date.daysInMonth(row.StartDate__c.month(), row.StartDate__c.year()) - row.StartDate__c.day()+1; //how many days in month 1
				endmonthdays = row.EndDate__c.day();
				startmonthusage = row.ActKWH__c*startmonthdays/(startmonthdays+endmonthdays); 
				system.debug('==========================startmonthusage is '+startmonthusage + ' for ' + startmonthdays + 'days');
				endmonthusage = row.ActKWH__c*endmonthdays/(startmonthdays+endmonthdays);  
				system.debug('==========================endmonthusage is '+endmonthusage + ' for ' + endmonthdays + 'days');
				output[startmonth-1].usage__c=output[startmonth-1].usage__c + startmonthusage;
				output[endmonth-1].usage__c=output[endmonth-1].usage__c + endmonthusage;
			}

			//3 month range
			if(endmonth == startmonth + 2 || (endmonth ==1 && startmonth ==11 ) || (endmonth ==2 && startmonth ==12 )){
				decimal midmonthusage; //need extra variables for ths case
				integer midmonth;
				integer midmonthdays;
				
				startmonthdays = date.daysInMonth(row.StartDate__c.month(), row.StartDate__c.year()) - row.StartDate__c.day()+1; //how many days in month 1
				midmonth = math.mod(startmonth +1, 12);
				if (midmonth == 0){
					midmonth = startmonth +1;
				}
				midmonthdays = date.daysinMonth(row.StartDate__c.addDays(15).month(),  row.StartDate__c.addDays(15).year()    );  //add 15days to start and get the days of that month
				endmonthdays = row.EndDate__c.day(); //how many days in month 3
				startmonthusage = row.ActKWH__c*startmonthdays/(startmonthdays+endmonthdays+midmonthdays); 
				system.debug('==========================startmonthusage is '+startmonthusage + ' for ' + startmonthdays + 'days');
				midmonthusage = row.ActKWH__c*midmonthdays/(startmonthdays+endmonthdays+midmonthdays);
				system.debug('==========================midmonthusage is '+midmonthusage + ' for ' + midmonthdays + 'days');
				endmonthusage = row.ActKWH__c*endmonthdays/(startmonthdays+endmonthdays+midmonthdays);  
				system.debug('==========================endmonthusage is '+endmonthusage + ' for ' + endmonthdays + 'days');
				system.debug('==========================start month is.. '+startmonth );
				system.debug('==========================mid month is.. '+midmonth );
				system.debug('==========================end month is '+endmonth );
				output[midmonth-1].usage__c=output[midmonth-1].usage__c + midmonthusage;

				output[startmonth-1].usage__c=output[startmonth-1].usage__c + startmonthusage;
				
				output[endmonth-1].usage__c=output[endmonth-1].usage__c + endmonthusage;

			}
		}
		//now, round all the stuff off!
		for (monthly_usage__c mu:output){
			mu.usage__c = math.round(mu.usage__c);
		}
		List<monthly_usage__c> oldValues= [select id from monthly_usage__c where APA__c =:apa.id ];
		system.debug('_________________olld values'+ oldvalues);
		delete oldValues;
		insert output;
	
	}




}