force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>For email templates</description>
    <formula>Premise__r.Meter_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For email templates</inlineHelpText>
    <label>Meter Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Account Premise Association is the one the customer has selected for current shopping.</description>
    <inlineHelpText>This Account Premise Association is the one the customer has selected for current shopping.</inlineHelpText>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_State2__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_State2__c</fullName>
    <description>Electric Service Address State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_Zip__c</fullName>
    <description>The zip code for the electric service address</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Meter number can be found on electric bills and on the meter itself</description>
    <inlineHelpText>Meter number can be found on electric bills and on the meter itself</inlineHelpText>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerForUHITButtons.cls
public class ControllerForUHITButtons {

    public pageReference ActionDoer(){
            system.debug ('APA id is ' + ApexPages.currentPage().getParameters().get('id'));
            AccountPremiseAssociation__c APA = [select id, Account__c, Premise__r.id, Selected__c, 
              premise__r.ESID__c, premise__r.Meter_Number__c, premise__r.Electric_Service_Address__c,
              premise__r.Electric_Service_Address_City__c, premise__r.Electric_Service_Address_State2__c, 
              premise__r.Electric_Service_Address_Zip__c
            from AccountPremiseAssociation__c where id =: ApexPages.currentPage().getParameters().get('id')];
            if (!apa.selected__c) {

                list <AccountPremiseAssociation__c> OtherSelectedAPAs = [select id, Selected__c from AccountPremiseAssociation__c where Selected__c = true and Account__c =: APA.Account__c];    
                
                if (!OtherSelectedAPAs.isEmpty()) {
                    for (AccountPremiseAssociation__c apas: OtherSelectedAPAs) {
                        apas.Selected__c = false;
                   }

                    update OtherSelectedAPAS;
              }
                apa.selected__c = true;
                update APA;
            }
            
          /*UHITBatchMgr UHBM = new UHITBatchMgr();
          UHBM.uhitFix(APA.premise__r.id);*/
          //UsageRequestManager urm = new UsageRequestManager();
          //public void sendRequest(Premises__c premise, AccountPremiseAssociation__c apapassed,  String callType)
          //urm.sendRequest(apa.Premise__r, apa, 'Summary Billing Data');
          UhitAsync.UHITSummaryCalloutFuture(APA.id);

      PageReference PR = new PageReference('/' + (ApexPages.currentPage().getParameters().get('ret')));
      return PR;
    }
}