force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <formula>Premise__r.TDSP_Lookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDSP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Load_Curve__c/Load_Curve__c.object-meta.xml
<CustomObject>
    <description>These are standardized load curves to be used when a user doesn&#39;t have actual meter data</description>
    <label>Load Curve</label>
    <nameField>
        <label>Load Curve Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Load Curves</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Load_Curve__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which TDSP does the load curve represent</description>
    <inlineHelpText>Which TDSP does the load curve represent</inlineHelpText>
    <label>TDSP</label>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Load Curves</relationshipLabel>
    <relationshipName>Load_Curves</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which TDSP has this rate available?</description>
    <inlineHelpText>Which TDSP has this rate available?</inlineHelpText>
    <label>TDSP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <filterItems>
            <field>TDSP__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TDSP</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Business_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Start_Date__c</fullName>
    <description>When did you start serving the Texas retail electric market?</description>
    <inlineHelpText>When did you start serving the Texas retail electric market?</inlineHelpText>
    <label>Business Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Customer_Service_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone_Number__c</fullName>
    <description>What number should TrueCost customers use to contact you about their account?</description>
    <inlineHelpText>What number should TrueCost customers use to contact you about their account?</inlineHelpText>
    <label>Customer Service Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Deposit_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Instructions__c</fullName>
    <description>What steps should a customer follow to pay a deposit?  This will be sent to customers via email.</description>
    <inlineHelpText>What steps should a customer follow to pay a deposit?  This will be sent to customers via email.</inlineHelpText>
    <label>Deposit Instructions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Escalated_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Issues_Email__c</fullName>
    <description>Email for any other issues requiring QUICK response.</description>
    <inlineHelpText>Email for any other issues requiring QUICK response.</inlineHelpText>
    <label>Escalated Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Escalated_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Issues_Phone__c</fullName>
    <description>Phone number for any other issues requiring QUICK response.</description>
    <inlineHelpText>Phone number for any other issues requiring QUICK response.</inlineHelpText>
    <label>Escalated Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/General_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>General_Issues_Email__c</fullName>
    <description>Email for when REP response is needed for bill, plan, or rewards questions.</description>
    <inlineHelpText>Email for when REP response is needed for bill, plan, or rewards questions.</inlineHelpText>
    <label>General Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/General_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>General_Issues_Phone__c</fullName>
    <description>Phone number for when REP response is needed for bill, plan, or rewards questions.</description>
    <inlineHelpText>Phone number for when REP response is needed for bill, plan, or rewards questions.</inlineHelpText>
    <label>General Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Home_Page__c.field-meta.xml
<CustomField>
    <fullName>Home_Page__c</fullName>
    <description>Enter in the url for your home page.</description>
    <inlineHelpText>Enter in the url for your home page.</inlineHelpText>
    <label>Home Page</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Full legal name of REP</description>
    <inlineHelpText>Full legal name of REP</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Maximum_Switch_Days__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Switch_Days__c</fullName>
    <defaultValue>90</defaultValue>
    <description>How many days in advance can a customer schedule a switch</description>
    <inlineHelpText>How many days in advance can a customer schedule a switch</inlineHelpText>
    <label>Maximum Switch Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Order_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Issues_Email__c</fullName>
    <description>Email address for cancellation, date change, order errors, inadvertent switch, or other issues.</description>
    <inlineHelpText>Email address for cancellation, date change, order errors, inadvertent switch, or other issues.</inlineHelpText>
    <label>Order Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Order_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>Order_Issues_Phone__c</fullName>
    <description>Phone number for cancellation, date change, order errors, inadvertent switch,or other issues.</description>
    <inlineHelpText>Phone number for cancellation, date change, order errors, inadvertent switch,or other issues.</inlineHelpText>
    <label>Order Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/PUC_Scorecard_Ranking__c.field-meta.xml
<CustomField>
    <fullName>PUC_Scorecard_Ranking__c</fullName>
    <description>1-5 ranking from http://www.powertochoose.org/scorecard/Scorecard.pdf</description>
    <inlineHelpText>1-5 ranking from http://www.powertochoose.org/scorecard/Scorecard.pdf</inlineHelpText>
    <label>PUC Scorecard Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
                <default>true</default>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Soonest_Move_Date__c.field-meta.xml
<CustomField>
    <fullName>Soonest_Move_Date__c</fullName>
    <defaultValue>3</defaultValue>
    <description>How soon can a customer be moved from now (in days)?  0 means today, 1 means tomorrow, etc.</description>
    <inlineHelpText>How soon can a customer be moved from now (in days)?  0 means today, 1 means tomorrow, etc.</inlineHelpText>
    <label>Soonest Move Date Available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Soonest_Switch_Date__c.field-meta.xml
<CustomField>
    <fullName>Soonest_Switch_Date__c</fullName>
    <defaultValue>3</defaultValue>
    <description>How soon can a customer be switched from now (in days)?  0 means today, 1 means tomorrow, etc.</description>
    <inlineHelpText>How soon can a customer be switched from now (in days)?  0 means today, 1 means tomorrow, etc.</inlineHelpText>
    <label>Soonest Switch Date Available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Star_ranking__c.field-meta.xml
<CustomField>
    <fullName>Star_ranking__c</fullName>
    <defaultValue>000.50</defaultValue>
    <description>How do your customer-given star ratings compare to other REPs on TrueCost?  The higher the percentage, the higher your approval is versus other REPs.</description>
    <inlineHelpText>How do your customer-given star ratings compare to other REPs on TrueCost?  The higher the percentage, the higher your approval is versus other REPs.</inlineHelpText>
    <label>Star Ranking</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Saved_Plan__c/Saved_Plan__c.object-meta.xml
<CustomObject>
    <description>Links the Rate__c and AccountPremiseAssociation__c so that users can save plans to their accounts.</description>
    <label>Saved Plan</label>
    <nameField>
        <displayFormat>SP-{0}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Saved Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Saved_Plan__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Saved Plans</relationshipLabel>
    <relationshipName>Saved_Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TrueCostUtilities_Test.cls
@isTest(SeeAllData=true)

private class TrueCostUtilities_Test {
    
    static testMethod void test(){
        // mccann fix, stage data
        Id planrType = Schema.SObjectType.Plan__c.getRecordTypeInfosByName().get('C&I Product').getRecordTypeId();
        Id utilrType = Schema.SObjectType.TDSP__c.getRecordTypeInfosByName().get('TDSP').getRecordTypeId();
        
        REP_Profile__c rp = new REP_Profile__c();
        rp.Name = 'Test Rep';
        rp.Legal_Name__c = 'Test Legal';
        rp.Business_Start_Date__c = Date.newInstance(2012, 12, 12);
        rp.Star_ranking__c = .01;
        rp.PUC_Scorecard_Ranking__c = '3';
        rp.Deposit_Instructions__c = 'deposit';
        rp.Maximum_Switch_Days__c = 1;
        rp.Soonest_Switch_Date__c = 1;
        rp.Soonest_Move_Date__c = 1;
        rp.Mailing_Street_Address__c = '123 st';
        rp.Mailing_City__c = 'Houston';
        rp.Mailing_Zip__c = '77042';
        rp.Customer_Service_Phone_Number__c = '7135551234';
        rp.Home_Page__c = 'www.url.com';
        rp.Order_Issues_Email__c = 'email@test.com';
        rp.Order_Issues_Phone__c = '2818320884';
        rp.General_Issues_Email__c = 'email2@test.com';
        rp.General_Issues_Phone__c = '8325551234';
        rp.Escalated_Issues_Email__c = 'email3@test.com';
        rp.Escalated_Issues_Phone__c = '7135554321';
        insert rp;
        
        TDSP__c util = new TDSP__c();
        util.Name = 'CenterPoint TestClass';
        util.RecordTypeId = utilrType;
        insert util;

        Plan__c p = new Plan__c();
        p.RecordTypeId = planrType;
        p.Name = 'Test Plan';
        p.REP_Profile__c = rp.Id;
        insert p;
        
        Rate__c rt = new Rate__c();
        rt.Plan__c = p.Id;
        rt.Name = 'Test Rate5';
        rt.TDSP__c = util.Id;
        rt.Minimum_Annual_Usage__c = 1;
        rt.Maximum_Annual_Usage__c = 1;
        rt.Energy_Base_Rate_cents__c = 1;
        rt.non_demand_1500_kWh_rate_cents__c = 1;
        rt.non_demand_2500_kWh_rate_cents__c = 1;
        rt.non_demand_3500_kWh_rate_cents__c = 1;
        rt.Cancellation_Fee__c = 10.99;
        rt.Confirmation_Code_Year__c = '2012';
        
        Load_Curve__c lc = new Load_Curve__c();
        lc.Name = 'CenterPoint TestClass';
        lc.January__c = 978;
        lc.February__c = 807;
        lc.March__c = 743;
        lc.April__c = 831;
        lc.May__c = 981;
        lc.June__c = 1232;
        lc.July__c = 1573;
        lc.August__c = 1676;
        lc.September__c = 1616;
        lc.October__c = 1374;
        lc.November__c = 1048;
        lc.December__c = 860;
        lc.Usage_Profile__c = '1000 kWh';
        lc.TDSP__c = util.Id;
        insert lc;
        
        
        TrueCostUtilities.CalculateCommission(6);
        TrueCostUtilities.showOnlyPublished();
        TrueCostUtilities.getRatingWrapperForREP();
        list <REP_Profile__c> REPlist = [select id from REP_Profile__c ];
        for (REP_Profile__c r:REPlist){
            TrueCostUtilities.getRatingWrapperForREP(r.id);
        }
    
        list<TDSP__c> tdsplist = [select id from TDSP__c where name!=:'None' and name like '%centerpoint%'];
        for (TDSP__c tdsp:tdsplist){
            //TrueCostUtilities.pullAverageUsage(tdsp.id, '500 kWh');
            //TrueCostUtilities.pullAverageUsage(tdsp.id, '1000 kWh');
            //TrueCostUtilities.pullAverageUsage(tdsp.id, '2000 kWh');
        }
        TrueCostUtilities.pullGuestMonthlyUsage();
        user usero = TrueCostTestUtilities.createTestAccountContactUserPremiseAPA();
        TrueCostUtilities.getTheAPAs(usero.id);
    
    //test saved plans
    /*
        Rate__c rate = [select id from rate__c limit 1];
        AccountPremiseAssociation__c APA =  [select id from AccountPremiseAssociation__c where id =: TrueCostUtilities.getTheAPAs(usero.id) ];
        TrueCostUtilities.SavePlan(  APA    , rate.id);
        list<saved_plan__c> sps = TrueCostUtilities.fetchSavedPlans(APA);
        TrueCostUtilities.UnsavePlan(APA    , rate.id);
      */  
        
    }
    
    
}