force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/lastDaily__c.field-meta.xml
<CustomField>
    <fullName>lastDaily__c</fullName>
    <label>lastDaily</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Estimated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meter Data Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The account has provided permission to retrieve data for this premise</description>
    <inlineHelpText>The account has provided permission to retrieve data for this premise</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Request_Status__c</fullName>
    <label>Meter Data Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error-Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Service Address</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Meter/ESID Match</fullName>
            </value>
            <value>
                <fullName>Error-No REP of Record</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/fields/Account_Premise_Association__c.field-meta.xml
<CustomField>
    <fullName>Account_Premise_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Premise Association</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Which date this usage occurred on</description>
    <inlineHelpText>Which date this usage occurred on</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Intervals__c.field-meta.xml
<CustomField>
    <fullName>Intervals__c</fullName>
    <description>Stores interval data, matches UHIT spec</description>
    <label>Intervals</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Month_Number__c.field-meta.xml
<CustomField>
    <fullName>Month_Number__c</fullName>
    <formula>MONTH(Date__c  )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Total_for_the_day__c.field-meta.xml
<CustomField>
    <fullName>Total_for_the_day__c</fullName>
    <label>Total for the day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which account premise association the usage is linked to</description>
    <inlineHelpText>Which account premise association the usage is linked to</inlineHelpText>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Estimated__c.field-meta.xml
<CustomField>
    <fullName>Estimated__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This value is estimated by TrueCost and is not from an external system</description>
    <inlineHelpText>This value is estimated by TrueCost and is not from an external system</inlineHelpText>
    <label>Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Month_Number__c.field-meta.xml
<CustomField>
    <fullName>Month_Number__c</fullName>
    <description>Which month this data is from (Jan=1, Dec=12)</description>
    <inlineHelpText>Which month this data is from (Jan=1, Dec=12)</inlineHelpText>
    <label>Month Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Total kWh usage for the specified time period.</description>
    <inlineHelpText>Total kWh usage for the specified time period.</inlineHelpText>
    <label>Usage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MeterDataUtilities.cls
global class MeterDataUtilities {    

    global static void CompactMeterDataMonthly(string APAid){
        AccountPremiseAssociation__c APA = [select Account__c, Id, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,lastdaily__c 
        FROM AccountPremiseAssociation__c
        where id=:APAid];

        MeterDataUtilities.DailiesToMonthlies(apa);
        MeterDataUtilities.AppendDailies(apa);
    }

    global static void DailiesToMonthlies(AccountPremiseAssociation__c APA){
        id premise;
        if (APA.premise__c ==null){ //only query if we have to.
        	premise = [select id, premise__c from AccountPremiseAssociation__c where id =: APA.id].premise__c;
        } else premise = APA.Premise__c;
        
        list<daily_usage__c> data = QueryAll(APA);
        if (!data.isempty()){
            //SOMETHING ABOUT DEDUPLICATION!
            data = DedupeByDateAndSortAscending(data);

            system.debug('first record is ' + data[0] + ' and last record is ' + data[data.size()-1]);        
            map<integer, decimal> monthvalues = new map<integer, decimal>{1=>0, 2=>0, 3=>0, 4=>0, 5=>0, 6=>0, 7=>0, 8=>0, 9=>0, 10=>0, 11=>0, 12=>0};
            
            system.debug('first record is ' + data[0] + ' and last record is ' + data[data.size()-1]);
            for (daily_usage__c d:data){
                if (d.Date__c > data[data.size()-1].Date__c.addyears(-1) ){
            		monthvalues.put(d.Date__c.month(), monthvalues.get(d.Date__c.month()) + d.Total_for_the_day__c);
                }
            }
            
            list<Monthly_Usage__c> replacementMonths = new list<Monthly_Usage__c>();
            
            for (integer x=1; x<13; x++){
                replacementMonths.add(new Monthly_Usage__c(Month_Number__c=x, APA__c = APA.id, Usage__c=monthvalues.get(x), Premise__c=premise, Estimated__c=false));
            }
            
            try{delete [select id from Monthly_Usage__c where APA__c =: APA.id];}catch(exception e){}
            insert replacementMonths;
        }
        
    }

    global static list<daily_usage__c> DedupeByDateAndSortAscending(list<daily_usage__c> incoming){
        map<date, daily_usage__c> DateMap = new map<date, daily_usage__c>();
        for (daily_usage__c du:incoming){
            DateMap.put(du.date__c, du); //will eliminate duplicate dates
        }
        list<date> DateList = new list<date>(DateMap.keyset());
        DateList.sort(); //ascending order
        list<daily_usage__c> output = new list<daily_usage__c>();
        for (date d:DateList){
            output.add(DateMap.get(d));
        }
        return output;
    }
        
    global static void AppendDailies(AccountPremiseAssociation__c APA){
    	list<daily_usage__c> toPut = getExistingJSONfromAttachment(APA);
        toPut.addAll(getOlderDailies(APA));

        if (!toPut.isEmpty()){
            IntervalsToJSONAttachment(toPut, APA.id);
            CleanDailies(APA);
        }
    }
    
    global static void CleanDailies (AccountPremiseAssociation__c APA){
    	list<daily_usage__c> Intervals = [select id, Date__c, Total_for_the_day__c, Intervals__c from daily_usage__c where date__c < LAST_N_DAYS:30 and Account_Premise_Association__c =: APA.id order by date__c ASC];      
        delete Intervals;
    }    
    
    global static list<daily_usage__c> getDailies (AccountPremiseAssociation__c APA){
    	list<daily_usage__c> Intervals = [select Date__c, Total_for_the_day__c, Intervals__c from daily_usage__c where Account_Premise_Association__c =: APA.id order by date__c ASC];      
        return Intervals;
    }
    
    global static list<daily_usage__c> getOlderDailies (AccountPremiseAssociation__c APA){
    	list<daily_usage__c> Intervals = [select Date__c, Total_for_the_day__c, Intervals__c from daily_usage__c where date__c < LAST_N_DAYS:30 and Account_Premise_Association__c =: APA.id order by date__c ASC];      
        return Intervals;
    }
    
    global static list<daily_usage__c> getExistingJSONfromAttachment (AccountPremiseAssociation__c APA){    	
        try{
            attachment a = [select id, body from attachment where name = 'IntervalDataAsJSON.txt' and parentID=:APA.id order by createddate DESC limit 1];
        	system.debug(string.valueof(a.body));
            list<daily_usage__c> output = (List<daily_usage__c>) Json.deserialize(a.body.toString(), list<daily_usage__c>.class);   
        	delete a;
            return output;
        }catch(exception e){
            system.debug(e); 
            list<daily_usage__c> output = new list<daily_usage__c>();
            return output;}
        return null;
    }
    
    global static void IntervalsToJSONAttachment(list<daily_usage__c> input, id parentid){
        input = DedupeByDateAndSortAscending(input); //first, dedupe

		string JSONString = Json.serialize(input);
        attachment a = new attachment();
        a.body = blob.valueof(JSONString);
        a.Name = 'IntervalDataAsJSON.txt';
        a.parentID=parentid;
        insert a;
    }
    
    global static list<daily_usage__c> QueryAll(AccountPremiseAssociation__c APA){
    	list<daily_usage__c> output = new list<daily_usage__c>();
        try{
            attachment a = [select id, body from attachment where name = 'IntervalDataAsJSON.txt' and parentID=:APA.id order by createddate DESC limit 1];
        	system.debug(string.valueof(a.body));
            output = (List<daily_usage__c>) Json.deserialize(a.body.toString(), list<daily_usage__c>.class);   
        }catch(exception e){system.debug(e); }
        output.addAll(getDailies(APA));
        //would you want to verify that there are no overlaps? 
        return output;        
    }
    
    
}