force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Heating_System__c.field-meta.xml
<CustomField>
    <fullName>Heating_System__c</fullName>
    <description>What type of fuel the premise uses for heating</description>
    <label>Heating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Data_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Status__c</fullName>
    <description>If the customer has provided access to their meter data, have we completed the request?</description>
    <inlineHelpText>If the customer has provided access to their meter data, have we completed the request?</inlineHelpText>
    <label>Meter Data Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
                <default>true</default>
                <label>Not requested</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Estimated</fullName>
            </value>
            <value>
                <fullName>Estimated with user adjustment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Occupants__c.field-meta.xml
<CustomField>
    <fullName>Occupants__c</fullName>
    <description>How many people live at the premise?</description>
    <inlineHelpText>How many people live at the premise?</inlineHelpText>
    <label>Occupants</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the home have a swimming pool?</description>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <description>How many square feet of living space are in the premise</description>
    <label>Square Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <description>The year of this premise&#39;s construction.</description>
    <inlineHelpText>The year of this premise&#39;s construction.</inlineHelpText>
    <label>Year Built</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_of_Construction__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Construction__c</fullName>
    <description>What year the premise was built</description>
    <label>Year of Construction</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControllerForUpdatePremise.cls
public with sharing class ControllerForUpdatePremise {
	
	private premises__c thepremise;
	
	public premises__c getthepremise(){
		return thepremise;
	}
	
	
	
	public ControllerForUpdatePremise(){
		AccountPremiseAssociation__c  theAPA = APAUtilities.GetACtiveAPA(TrueCostUtilities.GetTheAccount(UserInfo.getUserId()));
		List<premises__c> p = new List<premises__c>();
		p = [select id, Heating_System__c, Occupants__c, Year_of_Construction__c, Year_Built__c, Pool__c, Square_Feet__c, Meter_Data_Status__c
		from premises__c
		where id=:theAPA.premise__r.id]; 
		if (!p.isEmpty()) {
			thepremise = p[0]; 
		}
	}
	
	public PageReference updatePremise(){		
        
        try {
            update thepremise;            
        } catch(DmlException e) {
            ApexPages.addMessages(e);
            return null;
        }
    return Page.MyAccount;
	}
	
	public PageReference MakeEstimate(){		
		TrueCostEstimator.MakeEstimateThenSave(thepremise);
        thepremise.Meter_Data_Status__c = 'Estimated';
		try {
            update thepremise;            
        } catch(DmlException e) {
            ApexPages.addMessages(e);
            return null;
        }        
        
		return Page.ShopPlans; //needs to be the new estimate confirmation page
	}
	
	
	public PageReference Back(){
		return Page.MyAccount;
	}
	
	public PageReference BacktoShop(){
		return Page.Shopplans;
	}
}