force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Customer_Selected_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Selected_Profile__c</fullName>
    <description>Which of the PUCT load curves the customer says they belong to</description>
    <inlineHelpText>Which of the PUCT load curves the customer says they belong to</inlineHelpText>
    <label>Customer-Selected Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Estimated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meter Data Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The account has provided permission to retrieve data for this premise</description>
    <inlineHelpText>The account has provided permission to retrieve data for this premise</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Request_Status__c</fullName>
    <label>Meter Data Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error-Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Service Address</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Meter/ESID Match</fullName>
            </value>
            <value>
                <fullName>Error-No REP of Record</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>For email templates</description>
    <formula>Premise__r.Meter_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For email templates</inlineHelpText>
    <label>Meter Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Public_Data__c.field-meta.xml
<CustomField>
    <fullName>Public_Data__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer has elected to share their meter data in public</description>
    <inlineHelpText>Customer has elected to share their meter data in public</inlineHelpText>
    <label>Public Data</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Account Premise Association is the one the customer has selected for current shopping.</description>
    <inlineHelpText>This Account Premise Association is the one the customer has selected for current shopping.</inlineHelpText>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/fields/Account_Premise_Association__c.field-meta.xml
<CustomField>
    <fullName>Account_Premise_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Premise Association</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Customer_Selected_Profile__c.field-meta.xml
<CustomField>
    <fullName>Customer_Selected_Profile__c</fullName>
    <description>Which of the PUCT load curves the customer says they belong to</description>
    <inlineHelpText>Which of the PUCT load curves the customer says they belong to</inlineHelpText>
    <label>Customer-Selected Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Small</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Large</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_State2__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_State2__c</fullName>
    <description>Electric Service Address State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_Zip__c</fullName>
    <description>The zip code for the electric service address</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer at this premise authorized us to use its meter data?</description>
    <inlineHelpText>Has the customer at this premise authorized us to use its meter data?</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Meter number can be found on electric bills and on the meter itself</description>
    <inlineHelpText>Meter number can be found on electric bills and on the meter itself</inlineHelpText>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <description>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</description>
    <inlineHelpText>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</inlineHelpText>
    <label>Premise Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/TDSP_Lookup__c.field-meta.xml
<CustomField>
    <fullName>TDSP_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TDSP__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>only ACTIVE utilities are being returned</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/APAUtilities.cls
global class APAUtilities {
    
    public class APAWrapper{        
        public string PremiseAddress{get;set;}
        public id APAid{get;set;}
        public boolean selected{Get;set;}
        public boolean DataPermission{Get;set;}
        public datetime createddate{Get;set;}
        public string PremiseType{get;set;}
        public boolean PublicData{get;set;}
        
        public APAWrapper(AccountPremiseAssociation__c APA){
            PublicData = APA.public_data__c;
            PremiseAddress = APA.premise__r.Electric_Service_Address__c;
            APAid = APA.id;
            selected = APA.selected__c;
            DataPermission = APA.meter_data_permission__c;
            createddate = APA.createddate;
            PremiseType = APA.premise__r.premise_type__c;
        
        }
    }
    
    public static AccountPremiseAssociation__c getActiveAPA(id user){
																	
        list<AccountPremiseAssociation__c> theActivelist=[select id, selected__c, public_data__c, premise__r.Electric_Service_Address__c, Customer_Selected_Profile__c, meter_data_permission__c,Meter_Data_Request_Status__c, premise__r.Electric_Service_Address_Zip__c, meter_data_estimated__c, account__c, account__r.id, premise__c, premise__r.id, premise__r.tdsp_lookup__c, premise__r.tdsp_lookup__r.id from AccountPremiseAssociation__c where account__r.id =: user and selected__c =: true order by LastModifiedDate DESC];
    	//return the active one.  If there are more than one selected (shame on us) then return the most recently modified selected one.
        if (theActivelist.size()>0){
           return theActivelist[0];
        } else {
           //if no active ones, return the most recently modified one? 
           list<AccountPremiseAssociation__c> thelist=[select id, selected__c, public_data__c, premise__r.Electric_Service_Address__c, Customer_Selected_Profile__c, meter_data_permission__c,Meter_Data_Request_Status__c, account__c, account__r.id, premise__c, premise__r.id, premise__r.tdsp_lookup__c, premise__r.tdsp_lookup__r.id from AccountPremiseAssociation__c where account__r.id =: user order by LastModifiedDate DESC ];
            if(thelist.size()>0) {
                return thelist[0];
            }
        }
        AccountPremiseAssociation__c empty = new AccountPremiseAssociation__c();
        return empty; //just in case nothing was found
        
    }
    
    public static list<AccountPremiseAssociation__c> GetAllAPAs (id user){
       list<AccountPremiseAssociation__c> thelist=[select id, public_data__c, createddate, selected__c, premise__r.premise_type__c, premise__r.Electric_Service_Address__c, Customer_Selected_Profile__c, meter_data_permission__c, account__c, account__r.id, premise__c, premise__r.id, premise__r.tdsp_lookup__c, premise__r.tdsp_lookup__r.id from AccountPremiseAssociation__c where account__r.id =: user order by selected__c DESC, LastModifiedDate DESC ];
       return thelist;
    }
    
    public static void makeapa(id acct, id premid){
        accountpremiseassociation__c newapa = new accountpremiseassociation__c(); 
        newapa.account__c=acct;
        newapa.premise__c=premid;
        newapa.selected__c=true;
        insert newapa;
        //TrueCostUtilities.grantMeterDataPermission(premid);  
        ChangeSelectedAPA (newapa.id, acct);
    }
    
    public static void ChangeSelectedAPA (id SelectedAPA, id whichAccount){       
        list<accountPremiseAssociation__C> APAlist = [select id, selected__c from accountPremiseAssociation__C where account__r.id=:whichAccount];
        //deactivate all but the selected one
        for (accountPremiseAssociation__C apa:APAlist ){
            if (apa.id!=SelectedAPA) {
                system.debug(apa.id + '===================is not the selected APA');
                apa.selected__c = false;
            }else {
                apa.selected__c = true;
                system.debug(apa.id + '===================We found the selected APA');
            }
            
        }
        update APAlist;  system.debug(apaList);
    }
        public static decimal GetMaxFromStringList(string stuff){
        //takes a list of comma separated values
        decimal output=0;
        //chop the string into a list
        for (string s:stuff.split(',', 0)){
            if (decimal.valueOf(s)>output) output = decimal.valueOf(s);
        }
        
        return output;
        
    }
    
           
    /*Webservice static string RequestIntervalData(id APAid){
        try{
            string CallType = 'Interval Data';
            id APApremid = [select premise__r.id from AccountPremiseAssociation__c where id=:APAid].id;
            list<premises__c> Premlist = [select id, meter_number__C, meter_data_permission__c, 
                              
                              Electric_Service_Address__c, ESID__c, Electric_Service_Address_City__c,  Electric_Service_Address_State2__c,Electric_Service_Address_Zip__c from premises__c where id=:APApremid];
        
            list<daily_usage__c> UsageList = [select id from daily_usage__c where Account_Premise_Association__r.id =: APAid];                                          
            UsageRequestManager uhitReq = new UsageRequestManager();
            uhitReq.sendBatchRequest(Premlist, CallType); 
            return 'done';
        }catch(exception e){return string.valueof(e);}
    } */
}