force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/Month_Number__c.field-meta.xml
<CustomField>
    <fullName>Month_Number__c</fullName>
    <description>Which month this data is from (Jan=1, Dec=12)</description>
    <inlineHelpText>Which month this data is from (Jan=1, Dec=12)</inlineHelpText>
    <label>Month Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Total kWh usage for the specified time period.</description>
    <inlineHelpText>Total kWh usage for the specified time period.</inlineHelpText>
    <label>Usage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ControllerForConfirmEstimatedUsage_Test.cls
@isTest 
private class ControllerForConfirmEstimatedUsage_Test{
    private testmethod static void test(){
        /*Account acc = [select id from Account where isPersonAccount = true limit 1];
        Contact cont = [select id from Contact where accountID = :acc.ID limit 1];
        User oUser = [select contactId from User where contactId =: cont.ID limit 1];
         /*
        String searchESID = 'sic12345';
        Premises__c premise = new Premises__c (ESID__c = searchESID);
        insert premise;
        
        AccountPremiseAssociation__c apa = new AccountPremiseAssociation__c(Premise__c = premise.ID,account__c = acc.ID);
        insert apa;
        

        
        user oUser=TrueCostTestUtilities.createTestAccountContactUserPremiseAPA(); 
        
           
        System.Runas(oUser){
            ControllerForConfirmEstimatedUsage controller = new ControllerForConfirmEstimatedUsage();
           // //controller.MakeTheEstimate();
           //// controller.getmulistdata();
            //controller.getchartdata();
            //controller.mulist = new list<monthly_usage__c>{new monthly_usage__c(month_number__C = 1, usage__c = 10.0,premise__c = premise.ID)};
           //// controller.ShopWithEstimateUsage();
           //// controller.RaiseEstimate();
           //// controller.LowerEstimate();
            
        }
        */ 
    }
}