force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which account premise association the usage is linked to</description>
    <inlineHelpText>Which account premise association the usage is linked to</inlineHelpText>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Total kWh usage for the specified time period.</description>
    <inlineHelpText>Total kWh usage for the specified time period.</inlineHelpText>
    <label>Usage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControllerForConfirmEstimatedUsage.cls
public class ControllerForConfirmEstimatedUsage {

	list<monthly_usage__c> mulist {Get;set;}
	public AccountPremiseAssociation__c activeAPA{get;set;} 
	public list<decimal> stuffForChart {get;set;}
	
	public ControllerForConfirmEstimatedUsage(){
		system.debug('===============loading the constructor==============');
		ActiveAPA = APAUtilities.GetActiveAPA( TrueCostUtilities.getTheAccount(UserInfo.getUserId()) );
		if (ApexPages.CurrentPage().getParameters().get('mode')=='Adjust'){
			mulist = TrueCostUtilities.pullTheMonthlyUsage(ActiveAPA);
		} 	else {
				mulist = TrueCostEstimator.makeUsageEstimateList(ActiveAPA);		
			} 
		system.debug('===============finished constructor==============');
		stuffForChart = new decimal[12];
		updateStuffForChart();
	}
		
	public void MakeTheEstimate(){ 
		mulist = TrueCostEstimator.makeUsageEstimateList(ActiveAPA);
		system.debug('=============Controller knows mulist is ===========         ' + mulist);
		stuffForChart = new decimal[12];
		updateStuffForChart();
	}
	
	public list<monthly_usage__c> getmulistdata(){
		return mulist;
	}
	
	public void updateStuffForChart(){
	
			for (integer k = 0; k<12; k++){
				system.debug('==================starting iteration=================             ' + k  );				
				stuffForChart[k] = mulist[k].usage__c; system.debug('============adding   ' + mulist[k].usage__c + '   to list');
				
				}
			system.debug('==================list is now=================           ' + stuffForChart );
				
			
			system.debug('============================list complete============================');
		
		
	}
	
	
	public PageReference updateUsageEstimate(){	
		try{
			list<monthly_usage__c> existing = [select id from monthly_usage__c where APA__r.id =: ActiveAPA.id and isdeleted=false and id not in: mulist]; 	
			delete existing;
			
			} 	catch(DMLexception e){
				//could put a admin notification here?
				}	
		try{  //if it's a new one
			insert mulist;
		} catch(dmlexception e){update mulist;}
		updateStuffForChart();
		return null;
	}
	
	public PageReference updateUsageEstimateNoChart(){	
		try{
			list<monthly_usage__c> existing = [select id from monthly_usage__c where APA__r.id =: ActiveAPA.id and isdeleted=false and id not in: mulist]; 	
			delete existing;
			
			} 	catch(DMLexception e){
				//could put a admin notification here?
				}	
		try{  //if it's a new one
			insert mulist;
		} catch(dmlexception e){update mulist;}
		return null;
	}
	
	public pageReference ShopWithEstimateUsage(){ 
		updateUsageEstimate();
		return Page.ShopPlans;
	}
	
	public PageReference RaiseEstimate(){
		for (monthly_usage__c mu:mulist){
			if (! (mu.usage__c>0 ) ) mu.usage__c =0;
			mu.usage__c=math.round(1.05*mu.usage__c);
		}
		updateStuffForChart();
		return null;
		}
	
	public PageReference LowerEstimate(){
		for (monthly_usage__c mu:mulist){
			if (! (mu.usage__c>0 ) ) mu.usage__c =0;
			mu.usage__c=math.round(0.95*mu.usage__c);
		}
		updateStuffForChart();
		return null;	
		}
		
	public PageReference updateChart(){
		return null;
	}
}