force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which account premise association the usage is linked to</description>
    <inlineHelpText>Which account premise association the usage is linked to</inlineHelpText>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Estimated__c.field-meta.xml
<CustomField>
    <fullName>Estimated__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This value is estimated by TrueCost and is not from an external system</description>
    <inlineHelpText>This value is estimated by TrueCost and is not from an external system</inlineHelpText>
    <label>Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Month_Number__c.field-meta.xml
<CustomField>
    <fullName>Month_Number__c</fullName>
    <description>Which month this data is from (Jan=1, Dec=12)</description>
    <inlineHelpText>Which month this data is from (Jan=1, Dec=12)</inlineHelpText>
    <label>Month Number</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Total kWh usage for the specified time period.</description>
    <inlineHelpText>Total kWh usage for the specified time period.</inlineHelpText>
    <label>Usage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Heating_System__c.field-meta.xml
<CustomField>
    <fullName>Heating_System__c</fullName>
    <description>What type of fuel the premise uses for heating</description>
    <label>Heating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Occupants__c.field-meta.xml
<CustomField>
    <fullName>Occupants__c</fullName>
    <description>How many people live at the premise?</description>
    <inlineHelpText>How many people live at the premise?</inlineHelpText>
    <label>Occupants</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the home have a swimming pool?</description>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <description>How many square feet of living space are in the premise</description>
    <label>Square Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <description>The year of this premise&#39;s construction.</description>
    <inlineHelpText>The year of this premise&#39;s construction.</inlineHelpText>
    <label>Year Built</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_of_Construction__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Construction__c</fullName>
    <description>What year the premise was built</description>
    <label>Year of Construction</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/recordTypes/Point.recordType-meta.xml
<RecordType>
    <fullName>Point</fullName>
    <active>true</active>
    <description>Delivery and/or Receipt Points</description>
    <label>Point</label>
</RecordType>

force-app/main/default/classes/TrueCostEstimator.cls
/*
1/26/2012   Shane McLaughlin    Added scale factor >0.5 as exit condition to avoid SQL query limit.
2/16/2012   Shane Mclaughlin    Removed the year of construction from the comp criteria.

*/
public class  TrueCostEstimator {

    //the good version
    public static void MakeEstimateThenSave(AccountPremiseAssociation__c APA){        
        system.debug('==============================================APA id is' + APA.id);
        list<monthly_usage__c> mulist = [select id from monthly_usage__c where APA__c =: APA.id];
        if ( ! mulist.isempty() ) {
            try{
                delete mulist;
            } catch (dmlexception e){}
        }
        mulist = makeUsageEstimateList(APA);
        insert mulist;
    }
    
    public static list<monthly_usage__c> makeUsageEstimateList(AccountPremiseAssociation__c APA){        
        system.debug('==============================================APA id is' + APA.id);
        AccountPremiseAssociation__c APA2 = [select id, premise__c, premise__r.id,  premise__r.Pool__c, premise__r.Square_Feet__c, premise__r.Year_Built__c, premise__r.Heating_System__c, premise__r.Occupants__c
                            from AccountPremiseAssociation__c where id =: APA.id];
        system.debug('==============================================APA2 id is' + APA2.id);
        list<Monthly_Usage__c> mulist = new list<Monthly_Usage__c>();
        mulist=averageComps(APA2);
        for (monthly_usage__C mu:mulist){
            mu.estimated__c = true;
            system.debug('===========starting iteration=========            ');            
            system.debug('===========month number=========            ' );            
            system.debug('===========mulist is=========            ' + mulist);            
        }
        system.debug('===========mulist complete=========            ' + mulist);
        system.debug('===========mulist size is=========            ' + mulist.size());
        return mulist;
    }
    
    public static list<monthly_usage__C> averageComps(AccountPremiseAssociation__c APA){
        decimal scalefactor = 0.1; //starting entry for sample size...Increase if not getting enough data for estimate
        decimal squarefoothigh = (1+scalefactor)*APA.premise__r.Square_Feet__c;
        decimal squarefootlow = (1-scalefactor)*APA.premise__r.Square_Feet__c;
        integer yearfactor = 5;
        decimal startyear = integer.valueof(APA.premise__r.Year_Built__c)-yearfactor;
        decimal endyear = integer.valueof(APA.premise__r.Year_Built__c)+yearfactor;
        list<monthly_usage__c> mucomplist = new list<monthly_usage__c>(); //list used to create estimate
        do {
            mucomplist = [select id, month_number__c, usage__c from monthly_usage__c 
                          where premise__r.square_feet__c>: squarefootlow
                             and premise__r.square_feet__c <: squarefoothigh 
                             and premise__r.Year_of_Construction__c >=: startyear
                             and premise__r.Year_of_Construction__c <=: endyear                            
                            limit 600];                       
            scalefactor = scalefactor+0.1;
            yearfactor++;
        } while (mucomplist.size()<360&&scalefactor<0.5);
                    
        system.debug('================================mu comp list size is ' + mucomplist.size());      
        
        list<monthly_usage__c> muestimate = new list<monthly_usage__c>();  //list that is the returned estimate
        
        if (!mucomplist.isempty() ){
            for (integer k =1; k<13; k++){
            
                AggregateResult x = [select avg(usage__c) Avg from monthly_usage__c where id in: mucomplist and month_number__c =: k];
            
                monthly_usage__c muitem = new monthly_usage__C();
                muitem.month_number__c=k;
                muitem.Usage__c = (decimal)x.get('Avg');
                if (muitem.Usage__C == null) {muitem.Usage__c = 0;}
                muitem.usage__c = math.round(muitem.usage__c);
                muitem.Premise__c=APA.premise__r.id;
                muitem.APA__c = APA.id;
                muestimate.add(muitem);
            }
        } else { //it's empty
            system.debug('we did not get any comps.  Switching to guest usage');
            muestimate = TrueCostUtilities.pullGuestMonthlyUsage();
            for (monthly_usage__c muitem:muestimate){
                muitem.Premise__c=APA.premise__r.id;
                muitem.APA__c = APA.id;
            }
        }
        return muestimate;
    }
    //deprecating everything below this point for an APA-based estimator
    public static void MakeEstimateThenSave(premises__c prem){
        
        list<monthly_usage__c> mulist = [select id from monthly_usage__c where premise__c =: prem.id];
        if ( ! mulist.isempty() ) {
            try{
                delete mulist;
            } catch (dmlexception e){}
        }
        mulist = makeUsageEstimateList(prem);
        insert mulist;
    }
    
    
    
    public static list<monthly_usage__c> makeUsageEstimateList(premises__c prem){
        
        list<Monthly_Usage__c> mulist = averageComps(prem);
        
                            
        for (monthly_usage__C mu:mulist){
            mu.estimated__c = true;
        
        
            system.debug('===========starting iteration=========            ');
            
            system.debug('===========month number=========            ' );
            
            system.debug('===========mulist is=========            ' + mulist);
            
        }
        system.debug('===========mulist complete=========            ' + mulist);
        system.debug('===========mulist size is=========            ' + mulist.size());
        return mulist;
    }
    
    
    
    public static list<monthly_usage__C> averageComps(premises__c prem){
        decimal scalefactor = 0.1; //starting entry for sample size...Increase if not getting enough data for estimate
        decimal squarefoothigh = (1+scalefactor)*prem.Square_Feet__c;
        decimal squarefootlow = (1-scalefactor)*prem.Square_Feet__c;
        integer yearfactor = 5;
        //decimal startyear = prem.Year_of_Construction__c-yearfactor;
        //decimal endyear = prem.Year_of_Construction__c+yearfactor;
        list<monthly_usage__c> mucomplist = new list<monthly_usage__c>(); //list used to create estimate
        do {
            mucomplist = [select id, month_number__c, usage__c from monthly_usage__c 
                          where premise__r.square_feet__c>: squarefootlow
                             and premise__r.square_feet__c <: squarefoothigh 
                             //and premise__r.Year_of_Construction__c >: startyear
                             //and premise__r.Year_of_Construction__c <: endyear                            
                            limit 600];                       
            scalefactor = scalefactor+0.1;
            yearfactor++;
        } while (mucomplist.size()<360&&scalefactor<0.5);
                    
        system.debug('================================mu comp list size is ' + mucomplist.size());      
        
        list<monthly_usage__c> muestimate = new list<monthly_usage__c>();  //list that is the returned estimate
        
        if (!mucomplist.isempty() ){
            for (integer k =1; k<13; k++){
            
                AggregateResult x = [select avg(usage__c) Avg from monthly_usage__c where id in: mucomplist and month_number__c =: k];
            
                monthly_usage__c muitem = new monthly_usage__C();
                muitem.month_number__c=k;
                muitem.Usage__c = (decimal)x.get('Avg');
                if (muitem.Usage__C == null) {muitem.Usage__c = 0;}
                muitem.usage__c = math.round(muitem.usage__c);
                muitem.Premise__c=prem.id;
                muestimate.add(muitem);
            }
        }
        
        
        
        
        return muestimate;
    }
}