force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <formula>Premise__r.TDSP_Lookup__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>TDSP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Month_Estimate__c/Month_Estimate__c.object-meta.xml
<CustomObject>
    <label>Month Estimate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Month Estimate Key</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Month Estimate</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Month_Estimate__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Month Estimate</relationshipLabel>
    <relationshipName>Month_Estimate</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>In months, how long is the contract?</description>
    <inlineHelpText>In months, how long is the contract?</inlineHelpText>
    <label>Contract Length (# of months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Description__c.field-meta.xml
<CustomField>
    <fullName>Plan_Description__c</fullName>
    <description>Information shown to the customers who want more detail about this plan</description>
    <inlineHelpText>Information shown to the customers who want more detail about this plan</inlineHelpText>
    <label>Plan Description</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Rate_Class_del__c.field-meta.xml
<CustomField>
    <fullName>Rate_Class_del__c</fullName>
    <description>What rate class is this plan available for?</description>
    <inlineHelpText>What rate class is this plan available for?</inlineHelpText>
    <label>Rate Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Bandwidth_Swing_Allowed__c.field-meta.xml
<CustomField>
    <fullName>Bandwidth_Swing_Allowed__c</fullName>
    <description>By what percentage do customers have to be within their historical usage to have this rate?</description>
    <inlineHelpText>By what percentage do customers have to be within their historical usage to have this rate?</inlineHelpText>
    <label>Bandwidth/Swing % Allowed</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Basis_Charge_Included__c.field-meta.xml
<CustomField>
    <fullName>Basis_Charge_Included__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are the costs for a customer’s contribution to congestion or the costs they contribute to managing the distribution of power across the grid included in this rate?</description>
    <inlineHelpText>Are the costs for a customer’s contribution to congestion or the costs they contribute to managing the distribution of power across the grid included in this rate?</inlineHelpText>
    <label>Basis/Nodal Charge Included?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/EFL_Url__c.field-meta.xml
<CustomField>
    <fullName>EFL_Url__c</fullName>
    <description>Links to the EFL related to the Rate listed.</description>
    <inlineHelpText>Links to the EFL related to the Rate listed.</inlineHelpText>
    <label>EFL Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Link_for_EFL__c.field-meta.xml
<CustomField>
    <fullName>Link_for_EFL__c</fullName>
    <description>Hyperlink for your EFL.  please include http:// or https://</description>
    <inlineHelpText>Hyperlink for your EFL.  please include http:// or https://</inlineHelpText>
    <label>Link for EFL</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Link_for_TOS__c.field-meta.xml
<CustomField>
    <fullName>Link_for_TOS__c</fullName>
    <description>Hyperlink for the Terms of Service.  Please include http:// or https://</description>
    <inlineHelpText>Hyperlink for the Terms of Service.  Please include http:// or https://</inlineHelpText>
    <label>Link for TOS</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Link_for_YRAC__c.field-meta.xml
<CustomField>
    <fullName>Link_for_YRAC__c</fullName>
    <description>Hyperlink for the Your Rights as a Customer document for this rate.  Please include http:// or https://</description>
    <inlineHelpText>Hyperlink for the Your Rights as a Customer document for this rate.  Please include http:// or https://</inlineHelpText>
    <label>Link for YRAC</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Load_Factor__c.field-meta.xml
<CustomField>
    <fullName>Load_Factor__c</fullName>
    <description>What load factor does this rate require a premise to have?</description>
    <inlineHelpText>What load factor does this rate require a premise to have?</inlineHelpText>
    <label>Load Factor</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
            <value>
                <fullName>Less Than 50 KVA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/RUC_Nodal_Fees__c.field-meta.xml
<CustomField>
    <fullName>RUC_Nodal_Fees__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Are the ERCOT Reliability Unit Commitment (RUC) passed through in this rate?</description>
    <inlineHelpText>Are the ERCOT Reliability Unit Commitment (RUC) passed through in this rate?</inlineHelpText>
    <label>RUC Included?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which TDSP has this rate available?</description>
    <inlineHelpText>Which TDSP has this rate available?</inlineHelpText>
    <label>TDSP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <filterItems>
            <field>TDSP__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TDSP</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/TOS_Url__c.field-meta.xml
<CustomField>
    <fullName>TOS_Url__c</fullName>
    <description>Links to the TOS related to the Rate listed.</description>
    <inlineHelpText>Links to the TOS related to the Rate listed.</inlineHelpText>
    <label>TOS Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/YRAC_Url__c.field-meta.xml
<CustomField>
    <fullName>YRAC_Url__c</fullName>
    <description>Links to the YRAC related to the Rate listed.</description>
    <inlineHelpText>Links to the YRAC related to the Rate listed.</inlineHelpText>
    <label>YRAC Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TC2_Plan_Details.cls
@RestResource(urlMapping='/plan-details/*')
global class TC2_Plan_Details {

    static string selectedmonth{get;set;}
    static AccountPremiseAssociation__c theAPA {get;set;}
    static list<ResultsContainer> scoringresults = new list<ResultsContainer>{};
    static list<month_estimate__c> monthEstimateList= new list<month_estimate__c>{};
    
    @HttpGet
    global static rate__c getPlanDetails(){
        
        RestRequest request = RestContext.request;
        String planId = request.params.get('planId');
        
        //selectedmonth = string.valueof(date.today().addDays(15).month());
        theAPA=new AccountPremiseAssociation__c();
        
        TrueCostCalc tcc = new TrueCostCalc();
        list<Monthly_Usage__c> usage = TrueCostUtilities.pullTheMonthlyUsage(theAPA);
        // monthestimateList = tcc.makeTempMonthEstimates(theAPA, getPlanById( planId ) );
        // scoringresults = tcc.scoreMyEstimatesSimpler(monthEstimateList, getPlanById( planId ), usage);
        
        return getPlanById(planId);
    }
    
    global static List<Monthly_Usage__c> getPlanUsages(){
        
        theAPA=new AccountPremiseAssociation__c();
        list<Monthly_Usage__c> usage = TrueCostUtilities.pullTheMonthlyUsage(theAPA);
        return usage;
    }
    
    global static rate__c getPlanById(string planId) {        
        try {
            rate__c detailRate = [select id, plan__r.name, recordtypeid, plan__r.rate_class_del__c, tdsp__r.name,
                            RUC_Nodal_Fees__c, Basis_Charge_Included__c, Bandwidth_Swing_Allowed__c,
                            plan__r.plan_description__c, plan__r.contract_length__c, plan__r.REP_profile__r.logo_url__c, plan__r.REP_Profile__r.About_Us__c, load_factor__c,
                            TOS_Url__c, YRAC_Url__c, EFL_Url__c, plan__r.REP_profile__r.star_rating_avg__c, plan__r.REP_profile__r.total_reviews__c,
                            Record_Type_Name__c, plan__r.REP_Profile__r.id, plan__r.REP_Profile__r.name, Link_for_EFL__c, Link_for_TOS__c, Link_for_YRAC__c, plan__r.REP_profile__r.PUC_Scorecard_Ranking__c
                    from rate__c
                    where id =: planId];                
            return detailRate;
        } catch (Exception e) {
            System.debug(e);
        }
        
        return null;
    }
}