force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uhitmessage__c/uhitmessage__c.object-meta.xml
<CustomObject>
    <label>uhitmessage</label>
    <nameField>
        <label>uhitmessage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>uhitmessage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/uhitmessage__c/fields/ActKWH__c.field-meta.xml
<CustomField>
    <fullName>ActKWH__c</fullName>
    <label>ActKWH</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/uhitmessage__c/fields/BilledKVA__c.field-meta.xml
<CustomField>
    <fullName>BilledKVA__c</fullName>
    <label>BilledKVA</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MeterDataUtilities_Test.cls
@isTest

private class MeterDataUtilities_Test {

    static testMethod void testUHITDeduper(){

        //let's give it 12
        list<uhitmessage__c> UHMs = UsageRequestManager.DedupeUHIT(MakeUHMs());
        system.assert(UHMs.size()==12);

        //now give it the same 12 again
        UHMS.addAll(MakeUHMs());
        system.assert(UHMs.size()==24);
        UHMS=UsageRequestManager.DedupeUHIT(UHMS);
        system.assert(UHMs.size()==12);



    }


        /*
        MeterDataUtilities.AppendDailies(AccountPremiseAssociation__c APA);
        MeterDataUtilities.CleanDailies(AccountPremiseAssociation__c APA);
        MeterDataUtilities.getDailies(AccountPremiseAssociation__c APA);
        MeterDataUtilities.getExistingJSONfromAttachment(AccountPremiseAssociation__c APA);
        MeterDataUtilities.IntervalsToJSONAttachment(LIST input, Id parentid);
        MeterDataUtilities.QueryAll(AccountPremiseAssociation__c APA);
        */
        //TrueCostTestUtilities.createAlltheData();
        /*TrueCosttestUtilities.createTestZipCodes();
        TrueCosttestUtilities.makeREP();
        TrueCosttestUtilities.makePlan();
        TrueCosttestUtilities.createTestPremisewithUsage();
        User u = TrueCosttestUtilities.createTestAccountContactUserPremiseAPA();
        */
        //User u=TrueCosttestUtilities.createTestAccountContactUserPremiseAPA();
        
        
        //MeterDataUtilities.AppendDailies(APAUtilities.getActiveAPA(u.id));
        /*
        MeterDataUtilities.CleanDailies(a);
        MeterDataUtilities.getDailies(a);
        MeterDataUtilities.getExistingJSONfromAttachment(a);
        //MeterDataUtilities.IntervalsToJSONAttachment(LIST input, Id parentid);
        MeterDataUtilities.QueryAll(a);*/

    public static list<Daily_Usage__c> MakeDUs(){
        list<Daily_Usage__c> output = new list<Daily_Usage__c>();
        return output;
    }

    public static list<uhitmessage__c> MakeUHMs(){
        list<uhitmessage__c> output = new list<uhitmessage__c>();
        for (integer x=1; x<13; x++){
            output.add(new uhitmessage__c(ActkWh__c=x*100, BilledKVA__c=25, StartDate__c=Date.newinstance(2014, x, 5), EndDate__c = Date.newinstance(2014, x, 5).addmonths(1).addDays(-1)));
        }        
        return output;
    }

 }