force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>5</defaultValue>
    <inlineHelpText>Customer rating (1=low, 5=high)</inlineHelpText>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControllerForAnonymousRating_Test.cls
@isTest(seeAllData=true)

private class ControllerForAnonymousRating_Test {
  static testmethod void testControllerForAnonymousRating(){
    REP_Rating__c newrating = new REP_Rating__c(Rating__c=1);
    insert newrating ;
    attachment a = new attachment();
    a.name='abc';
    a.Body=Blob.valueOf('abc');
    a.ParentId = newRating.id;
    insert a;
    ControllerForAnonymousRating  cf=new ControllerForAnonymousRating();
    cf.fileBody =a.Body;
    cf.fileName =a.Name;
    cf.UploadFile();
    cf.saverating();
    cf.its1();
    cf.its2();  
    cf.its3();
    cf.its4();
    cf.its5();
  }
}