force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which TDSP has this rate available?</description>
    <inlineHelpText>Which TDSP has this rate available?</inlineHelpText>
    <label>TDSP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <filterItems>
            <field>TDSP__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TDSP</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RateRewardAssociation__c/RateRewardAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Rate and Rewards.</description>
    <label>Reward For This Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RateRewardAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateRewardAssociation__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The rate that the reward is linked to.</description>
    <inlineHelpText>The rate that the reward is linked to.</inlineHelpText>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipName>RateRewardAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateRewardAssociation__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The reward that is linked to the rate.</description>
    <inlineHelpText>The reward that is linked to the rate.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Rewards__c</referenceTo>
    <relationshipName>RateRewardAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rewards__c/Rewards__c.object-meta.xml
<CustomObject>
    <description>Customer incentives and rewards.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rewards__c/fields/Reward_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_End_Date__c</fullName>
    <description>When does this offer become unavailable?</description>
    <inlineHelpText>When does this offer become unavailable?</inlineHelpText>
    <label>Reward End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_Start_Date__c</fullName>
    <description>What is the soonest date that this offer is available?</description>
    <inlineHelpText>What is the soonest date that this offer is available?</inlineHelpText>
    <label>Reward Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Type__c.field-meta.xml
<CustomField>
    <fullName>Reward_Type__c</fullName>
    <description>What kind of reward option is this? If this is a reward program, select &quot;Reward Program.&quot;</description>
    <inlineHelpText>What kind of reward option is this? If this is a reward program, select &quot;Reward Program.&quot;</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Airline Miles</fullName>
            </value>
            <value>
                <fullName>Bill Credit</fullName>
            </value>
            <value>
                <fullName>Cash Back (% of bill)</fullName>
            </value>
            <value>
                <fullName>Cash Back (flat $ amount)</fullName>
            </value>
            <value>
                <fullName>Charitable Donation</fullName>
            </value>
            <value>
                <fullName>Credit Card Points</fullName>
            </value>
            <value>
                <fullName>Electronics/Home Devices</fullName>
            </value>
            <value>
                <fullName>Home Protection</fullName>
            </value>
            <value>
                <fullName>Hotel Points</fullName>
            </value>
            <value>
                <fullName>Retail Items</fullName>
            </value>
            <value>
                <fullName>Reward Program</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Value__c.field-meta.xml
<CustomField>
    <fullName>Reward_Value__c</fullName>
    <description>What is the $ value of this reward or incentive?  This does not apply to Airline Miles or Hotel Points.</description>
    <inlineHelpText>What is the $ value of this reward or incentive?  This does not apply to Airline Miles or Hotel Points.</inlineHelpText>
    <label>$ Value</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/RewardList.cls
public with sharing class RewardList {
	
	public Rate__c TheRate;
	list<rate__c> theRates = new list<rate__c>();
	
	public RewardList(ApexPages.StandardController stdController){
		theRates = [select id, tdsp__c from Rate__c where id =:ApexPages.currentPage().getParameters().get('Id') ];	
		if ( theRates.size()>0 )theRate = theRates[0];
	}
	public id selectedreward {get;set;}
	public boolean refreshpage {get;set;}
	
	public list<rewards__c> GetRewards(){ 
		if ( theRates.size()>0 ) {
			set<id> blacklist = new set<id>();
			
			list<RateRewardAssociation__c> existing = [select id, reward__r.id from RateRewardAssociation__c where rate__r.id =: therate.id]; //don't show ones already used
			if (existing.size()>0 ) {			
				
				for (RateRewardAssociation__c RRA:existing){
					blacklist.add(RRA.reward__r.id);
				
				}
			}
			list<rewards__c> rewardList = [select name, Reward_End_Date__c, Reward_Start_Date__c, Reward_Type__c, Reward_Value__c  from Rewards__c where id not IN:blacklist order by name];
			blacklist.clear();
			return rewardList;
		} else {return null;}
	}

	public pagereference addReward(){
		RateRewardAssociation__c theRRA= new RateRewardAssociation__c ();
		theRRA.Rate__c = therate.id;
		theRRA.Reward__c = selectedreward;
		insert theRRA;
		refreshpage = true;
		return null;
	}
}