force-app/main/default/objects/Account/recordTypes/Consultant.recordType-meta.xml
<RecordType>
    <fullName>Consultant</fullName>
    <active>true</active>
    <description>Brokers, Consultants, and other channel partners.</description>
    <label>Consultant</label>
</RecordType>

force-app/main/default/objects/Bill_Group__c/Bill_Group__c.object-meta.xml
<CustomObject>
    <description>Bill Groups are groups of billing (a group of facilities that belong to a single customer)</description>
    <label>Bill Group</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Bill Group ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bill Groups</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_Group__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Which Account (Customer) owns this bill group?</description>
    <inlineHelpText>Which Account (Customer) owns this bill group?</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill Groups</relationshipLabel>
    <relationshipName>Bill_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_Group__c/fields/Bill_Group_Batch__c.field-meta.xml
<CustomField>
    <fullName>Bill_Group_Batch__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <inlineHelpText>this is the &quot;Safari Billing Cycle&quot; and is dependent upon the CES Office field to be populated</inlineHelpText>
    <label>Bill Group Batch</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Bill_Group_Batch__c.CES_Office__c</field>
            <operation>equals</operation>
            <valueField>$Source.CES_Office__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Bill_Group_Batch__c</referenceTo>
    <relationshipLabel>Bill Groups</relationshipLabel>
    <relationshipName>Bill_Groups</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_Group__c/fields/CES_Office__c.field-meta.xml
<CustomField>
    <fullName>CES_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CES Office</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>CES Location</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill Groups (CES Office)</relationshipLabel>
    <relationshipName>Bill_Groups1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Bill_Group__c/fields/Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Number__c</fullName>
    <label>Customer Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bill_Group__c/fields/Fax__c.field-meta.xml
<CustomField>
    <fullName>Fax__c</fullName>
    <label>Fax</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Bill_Group_Batch__c/Bill_Group_Batch__c.object-meta.xml
<CustomObject>
    <description>Grouping of Bill Groups for Invoice Batch Processing</description>
    <label>Bill Group Batch</label>
    <nameField>
        <label>Bill Group Batch Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bill Group Batches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bill_Group_Batch__c/fields/Bill_Batch_Type__c.field-meta.xml
<CustomField>
    <fullName>Bill_Batch_Type__c</fullName>
    <label>Bill Batch Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Calendar</fullName>
            </value>
            <value>
                <fullName>Consumption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Bill_Group_Batch__c/fields/CES_Office__c.field-meta.xml
<CustomField>
    <fullName>CES_Office__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CES Office</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bill Group Batches</relationshipLabel>
    <relationshipName>Bill_Group_Batches_del</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Mark the contact inactive if the contact is no longer at that company</description>
    <inlineHelpText>Mark the contact inactive if the contact is no longer at that company</inlineHelpText>
    <label>Active Contact?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CESCommonObjectControllerTest.cls
@isTest 
public class CESCommonObjectControllerTest {
    static testMethod void test1() {
        Account acc = new Account();
        acc.Name = 'Test';
        // BDM specify record type otherwise not recognized
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        insert acc;
        
        // BDM CESOffice and Bill Group Batch record creation required for legacy bill groups
        Account office = new Account(Name='CES-Illinios', Customer_Number__c='LIVE', AccountNumber='1', Location_Code__c='IL');
        office.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('CES Location').getRecordTypeId();
        insert office;
        
        Bill_Group_Batch__c bgb = new Bill_Group_Batch__c(Name='Test Billing Batch', CES_Office__c=office.id, Bill_Batch_Type__c='Calendar', Active__c=true);
        insert bgb;
        
        Bill_Group__c bg = new Bill_Group__c();
        bg.Account__c = acc.Id;
        // BDM field population required for legacy field validations
        bg.First_Name__c = 'Test';
        bg.Last_Name__c = 'Billing';
        bg.Phone__c = '713-207-1234';
        bg.Fax__c = '713-207-3456';
        bg.Email__c = 'billtest@test.com';
        bg.CES_Office__c = office.Id;
        bg.Bill_Group_Batch__c = bgb.id;
        insert bg;
        
        Profile p = [
            SELECT Id, Name
            FROM Profile
            WHERE Name ='MyCES Consultant'
            LIMIT 1
        ];
        
        
		System.debug('CESCommonObjectControllerTest | getCommonAccountRecordList as admin');        
        // as admin
        List<Account> testAccountsAsAdmin = CESCommonObjectController.getCommonAccountRecordList();
        
        // Setup test data
        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile myTestUserProfile = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User myTestUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', ProfileId = myTestUserProfile.Id,
                            TimeZoneSidKey='America/Los_Angeles',
                            UserName=uniqueUserName);
        


        System.runAs(myTestUser) {
            // as user
            // 
			System.debug('CESCommonObjectControllerTest | getCommonAccountRecordList as Standard User');
            List<Account> testAccountsAsUser = CESCommonObjectController.getCommonAccountRecordList();
        }
        
        CESCommonObjectController.getCommonMonthMap ();
        CESCommonObjectController.getCommonMonthList ();
        CESCommonObjectController.getCommonBillingGroupList(acc.Id);
        //CESCommonObjectController.isMyCESProfileValid(p);
        CESCommonObjectController.getAccountRecordName(acc.Id);
        CESCommonObjectController.getCommonBillingGroupListByReferencedDate(acc.Id);
        
        CESCommonObjectController.getBillGroupRecordName(bg.Id);
        CESCommonObjectController.logRecentlyViewedBillGroupForReference(bg.Id);
        
		boolean isMyCESProfileValid;
	
		isMyCESProfileValid = CESCommonObjectController.isMyCESProfileValid(p);

        p = [
            SELECT Id, Name
            FROM Profile
            WHERE Name ='The System Q219'
            LIMIT 1
        ];		
		
        isMyCESProfileValid = CESCommonObjectController.isMyCESProfileValid(p);        
        
        List<Profile> profileList = CESCommonObjectController.getMyCESProfileList();
     
        // testing CommonAccountRecordList for actual contact
        // 
        //AccountContactRelation acr = new AccountContactRelation();
        //acr.Accountid = acc.id;
        //acr.Contactid = c.id;
        //acr.IsActive = true;
        //insert acr;


        // Setup test data
        //
        // Create Group for Trigger Logic
		Group testGroup = new Group(Name='CES Community All Members');
        
        // Create a unique UserName
        String uniqueUserName2 = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // Adding Contact
        // 
        Contact c = new Contact();
            c.firstname = 'test';
            c.lastname = uniqueUserName2;
            c.phone = '(612) 321-5081';
            c.fax = '(612) 321-5081';
            c.email = 'standarduser@testorg.com';
            c.accountid = acc.id;
		insert c;
         
System.debug('CESCommonObjectControllerTest | myTestContact : ' + c);
        
        // This code runs as the system user
        Profile myCommunityUserProfile2 = [SELECT Id FROM Profile WHERE Name='MyCES ExtFA'];
        
        User myTestUser2 = new User(Alias = 'standt', Email='standarduser@testorg.com',
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', ProfileId = myCommunityUserProfile2.Id,
                            TimeZoneSidKey='America/Los_Angeles',
                            UserName=uniqueUserName2, ContactId=c.Id);        
        insert myTestUser2;
System.debug('CESCommonObjectControllerTest | myTestUser2 : ' + myTestUser2);
        
        System.runAs(myTestUser2) {
            // as user
            // 
			System.debug('CESCommonObjectControllerTest | getCommonAccountRecordList as myCES User');            
            List<Account> testAccountsAsUser = CESCommonObjectController.getCommonAccountRecordList();
        }
        
    }
    
    @IsTest(SeeAllData=true)
    static void testWithAllDataAccess() {
        
        // Setup test data
        // Create a unique UserName
        String uniqueUserName = 'standarduser' + DateTime.now().getTime() + '@testorg.com';
        // This code runs as the system user
        Profile myTestUserProfile = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User myTestUser = new User(Alias = 'standt', Email='standarduser@testorg.com',
                            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                            LocaleSidKey='en_US', ProfileId = myTestUserProfile.Id,
                            TimeZoneSidKey='America/Los_Angeles',
                            UserName=uniqueUserName);
        
		insert myTestUser;

System.debug('CESCommonObjectControllerTest - testWithAllDataAccess | myTestUser: ' + myTestUser);            
        
        Account acc = new Account();
        acc.Name = 'Test Account-ChatterAPI';
        // BDM specify record type otherwise not recognized
        acc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
        
        acc.OwnerId = myTestUser.Id;
        insert acc;        
        
System.debug('CESCommonObjectControllerTest - testWithAllDataAccess | Account: ' + acc);        
        
        CESCommonObjectController.chatterCommunityActivity('myCES', 'monthly usage review', acc.Id, '98d');
        //CESCommonObjectController.chatterCommunityActivity(null, 'monthly usage review', acc.Id, '98d');        
        //CESCommonObjectController.chatterCommunityActivity('myCES', 'monthly usage review', acc.Id, null);
		//CESCommonObjectController.chatterCommunityActivity('myCES', 'monthly usage review', null, null);       
		//CESCommonObjectController.chatterCommunityActivity(null, 'monthly usage review', null, null);        
		//CESCommonObjectController.chatterCommunityActivity('myCES', null, null, null);                       
    }
}