force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>An account that does not yet fit into another category, or fits into multiple.</description>
    <label>Generic</label>
</RecordType>

force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Selected__c.field-meta.xml
<CustomField>
    <fullName>Selected__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This Account Premise Association is the one the customer has selected for current shopping.</description>
    <inlineHelpText>This Account Premise Association is the one the customer has selected for current shopping.</inlineHelpText>
    <label>Selected</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerForChangeAPA.cls
public class ControllerForChangeAPA {
    
    public id accountID {get;set;}
    public string SelectedAPA {get;set;}
    
    public ControllerForChangeAPA(){
               accountID = [select id from account where id=:TrueCostUtilities.GetTheAccount(Userinfo.getuserid())][0].id;
               //selectedAPA = APAUtilities.getActiveAPA(accountID).id;
    }
    
    public list<SelectOption> getAPAOPtions(){
        list<AccountPremiseAssociation__c> APAs = APAUtilities.GetAllAPAs(AccountID);
        List<SelectOption> options = new List<SelectOption>();
        //first, add the selected one
        for(AccountPremiseAssociation__c APA:APAs){
            if (APA.selected__c){options.add(new SelectOption( APA.id, APA.premise__r.Electric_Service_Address__c));}
        }
        //then, add the other ones
        for(AccountPremiseAssociation__c APA:APAs){
            if (!APA.selected__c){options.add(new SelectOption(APA.id, APA.premise__r.Electric_Service_Address__c));}
        }
        //then, add the other standard options
        options.add(new SelectOption( 'New', 'Add a new Service Address'));
        options.add(new SelectOption( 'Manage', 'Manage Service Addresses'));
        //then return
        return options;        
    }
    public list<SelectOption> getAPAOPtionsNoManage(){
        list<AccountPremiseAssociation__c> APAs = APAUtilities.GetAllAPAs(AccountID);
        List<SelectOption> options = new List<SelectOption>();
        //first, add the selected one
        for(AccountPremiseAssociation__c APA:APAs){
            if (APA.selected__c){options.add(new SelectOption( APA.id, APA.premise__r.Electric_Service_Address__c));}
        }
        //then, add the other ones
        for(AccountPremiseAssociation__c APA:APAs){
            if (!APA.selected__c){options.add(new SelectOption(APA.id, APA.premise__r.Electric_Service_Address__c));}
        }
        //then, add the other standard options
        options.add(new SelectOption( 'New', 'Add a new Service Address'));

        //then return
        return options;        
    }
        
    public pageReference Submit(){
        system.debug('=============================SelectedAPA is '+selectedAPA);
        if (SelectedAPA=='New'){return page.AddAddressAfterRegistration;}
        if (SelectedAPA=='Manage'){return page.MyAccount;}        
        APAUtilities.ChangeSelectedAPA(SelectedAPA, accountID); //set the selected on as active
        PageReference pr = ApexPages.CurrentPage();
        pr.setredirect(true);
        return pr;        
    }

    public pageReference ShopPlans(){
        system.debug('=============================SelectedAPA is '+selectedAPA);
        if (SelectedAPA=='New'){return page.AddAddressAfterRegistration;}
        if (SelectedAPA=='Manage'){return page.MyAccount;}        
        APAUtilities.ChangeSelectedAPA(SelectedAPA, accountID); //set the selected on as active
        PageReference pr = new PageReference('/Account_Profile?redirect=Shop_Plans');

        //PageReference pr = ApexPages.CurrentPage();
        //PageReference pr = new PageReference('/Shop_Plans');
        //pr.setredirect(true);
        return pr;        
    }
    
    public pageReference ShopPlansCommercial(){
        system.debug('=============================SelectedAPA is '+selectedAPA);
        if (SelectedAPA=='New'){return page.AddAddressAfterRegistration;}
        if (SelectedAPA=='Manage'){return page.MyAccount;}        
        APAUtilities.ChangeSelectedAPA(SelectedAPA, accountID); //set the selected on as active
        PageReference pr = new PageReference('/Account_Profile?redirect=Shop_Plans_Commercial');

        //PageReference pr = ApexPages.CurrentPage();
        //PageReference pr = new PageReference('/Shop_Plans');
        //pr.setredirect(true);
        return pr;        
    }
    
    public pageReference SubmitRefresh(){
        system.debug('=============================SelectedAPA is '+selectedAPA);
        if (SelectedAPA=='New'){return page.AddAddressAfterRegistration;}
        if (SelectedAPA=='Manage'){return page.MyAccount;}        
        APAUtilities.ChangeSelectedAPA(SelectedAPA, accountID); //set the selected on as active
        
        return null;        
    }
    
    
    public list<APAUtilities.APAWrapper> getAPAstoManage(){ 
        list<APAUtilities.APAWrapper> output = new list<APAUtilities.APAWrapper>();
        for(AccountPremiseAssociation__c item:APAUtilities.GetAllAPAs(AccountID)){
            APAUtilities.APAWrapper wrapper = new APAUtilities.APAWrapper(item);
            output.add(wrapper);
        }
        
        return output;
        
    }
    
    public PageReference DeleteAPA(){
        
        AccountPremiseAssociation__c APA2Delete = [select id from AccountPremiseAssociation__c where id=: SelectedAPA];
        try{delete APA2Delete;} catch(exception e){}
        return null;
    }
    
}