force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>An account that does not yet fit into another category, or fits into multiple.</description>
    <label>Generic</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/ESIID_Number__c.field-meta.xml
<CustomField>
    <fullName>ESIID_Number__c</fullName>
    <description>The ESIID number of the meter to be switched to a plan</description>
    <inlineHelpText>The Electric Service Identifier ID number of the meter to be switched on for a plan.</inlineHelpText>
    <label>ESIID Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Failure_Reason__c</fullName>
    <label>Failure Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer Rescinded</fullName>
            </value>
            <value>
                <fullName>Expired Order</fullName>
            </value>
            <value>
                <fullName>Invalid ESIID</fullName>
            </value>
            <value>
                <fullName>Not Field Completed</fullName>
            </value>
            <value>
                <fullName>Permit Issues</fullName>
            </value>
            <value>
                <fullName>Switch Hold</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Other (enter comments)</fullName>
            </value>
            <value>
                <fullName>---Select a reason---</fullName>
                <default>true</default>
                <label>---Select a reason---</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/InitialDateofService__c.field-meta.xml
<CustomField>
    <fullName>InitialDateofService__c</fullName>
    <description>Initial date of service.</description>
    <inlineHelpText>Date the change to new REP will occur.</inlineHelpText>
    <label>Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Expiration_Date__c</fullName>
    <description>When the order expires.</description>
    <label>Order Expiration Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Failure_Comments__c.field-meta.xml
<CustomField>
    <fullName>Order_Failure_Comments__c</fullName>
    <description>Notes about why switch/MVI could not be completed at the meter.</description>
    <inlineHelpText>Notes about why switch/MVI could not be completed at the meter.</inlineHelpText>
    <label>Failure Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Rejection_Comments__c.field-meta.xml
<CustomField>
    <fullName>Order_Rejection_Comments__c</fullName>
    <description>Notes about rejection reason. Comes from REP.</description>
    <inlineHelpText>Notes about rejection reason. Comes from REP.</inlineHelpText>
    <label>Rejection  Comments</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this order.</description>
    <inlineHelpText>TrueCost account for this order.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Parent Account)</relationshipLabel>
    <relationshipName>OrdersPlaced</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Premise_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Order_Type__c</fullName>
    <description>The type of premise for this order.</description>
    <formula>Premise__r.Premise_Type__c</formula>
    <inlineHelpText>The type of premise for this order.</inlineHelpText>
    <label>Premise Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Reason__c</fullName>
    <description>This field captures why the REP rejected a customer.</description>
    <inlineHelpText>This field captures why the REP rejected a customer.</inlineHelpText>
    <label>Rejection Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Admin Rejection</fullName>
            </value>
            <value>
                <fullName>Credit quality</fullName>
            </value>
            <value>
                <fullName>Customer Rescinded</fullName>
            </value>
            <value>
                <fullName>Deposit Unpaid</fullName>
            </value>
            <value>
                <fullName>Inaccurate address</fullName>
            </value>
            <value>
                <fullName>Inaccurate ESID</fullName>
            </value>
            <value>
                <fullName>Other (enter comments)</fullName>
            </value>
            <value>
                <fullName>Permit Problem</fullName>
            </value>
            <value>
                <fullName>Prior payment history</fullName>
            </value>
            <value>
                <fullName>Should have been a move</fullName>
            </value>
            <value>
                <fullName>Switch Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderProcessing.cls
public with sharing class OrderProcessing {

    public list<xOrder> neworders {get; set;}
    public list<xOrder> pendingConfirmation{get; set;}
    public list<xOrder> pendingDeposit{get;set;}
    public list<xOrder> confirmedOrders {get; set;}
    public Order__c Rejectedorder {get; set;}
    public Order__c Failedorder {get; set;}
    public String repprofile {get; set;}
       
//This feeds the data to the new Orders tab 
    public List<xOrder> getNewOrderList() {
        if(newOrders == null) {
            neworders = new List<xOrder>();
            for (Order__c o: [ select ID, name, InitialDateofService__c, order_status__c,  Order_Expiration_Date__c, CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                              Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c  from Order__c where (order_status__c = 'New' or order_status__c = 'New/Successfully Submitted')]){
                repprofile= o.REP_Profile__c;
                neworders.add(new xOrder(o));
            }
        }
        return neworders;
    }
//This feeds the data to the Pending Deposit tab 
    public List<xOrder> getPendingDepositOrderList() {
        if(pendingDeposit== null) {
            pendingDeposit= new List<xOrder>();
            for (Order__c o: [ select ID, InitialDateofService__c, Order_Expiration_Date__c, name, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c from Order__c where order_status__c = 'Approved Pending Deposit']){
                pendingDeposit.add(new xOrder(o));
            }
        }
        return pendingDeposit;
    }
    
//This feeds the data to the Pending Orders tab 
    public List<xOrder> getPendingConfirmationOrdersList() {
        if(pendingConfirmation== null) {
            pendingConfirmation= new List<xOrder>();
            for (Order__c o: [ select ID, InitialDateofService__c, Order_Expiration_Date__c, name, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c from Order__c where order_status__c = 'Approved Pending Confirmation']){
                pendingConfirmation.add(new xOrder(o));
            }
        }
        return pendingConfirmation;
    }
//This feeds the data to the Confirmed Orders tab 
    public List<xOrder> getConfirmedOrdersList() {
        if(confirmedorders == null) {
            confirmedorders= new List<xOrder>();
            
            for (Order__c o: [ select ID, InitialDateofService__c, name, Order_Expiration_Date__c, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount, 
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c from Order__c where order_status__c = 'Confirmed' order by lastmodifieddate limit 500]){
                confirmedorders.add(new xOrder(o));
            }
        }
        return confirmedorders;
    }
    public void OrderListResetter() {
        pendingDeposit.clear();
        neworders.clear();
        pendingconfirmation.clear();
        confirmedorders.clear();
        rejectedOrder=null;
        FailedOrder=null;
        for (Order__c o: [ select ID, InitialDateofService__c, Order_Expiration_Date__c, name, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c
                            from Order__c 
                            where order_status__c = 'New' or order_status__c = 'New/Successfully Submitted']){
                neworders.add(new xOrder(o));
            }
        for (Order__c o: [ select ID, InitialDateofService__c, name, Order_Expiration_Date__c, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c
                            from Order__c
                            where order_status__c = 'Approved Pending Confirmation']){
                pendingConfirmation.add(new xOrder(o));
        }
        for (Order__c o: [ select ID, InitialDateofService__c, name, Order_Expiration_Date__c, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c
                            from Order__c
                            where order_status__c = 'Confirmed' order by lastmodifieddate limit 500]){
                confirmedorders.add(new xOrder(o));
            }    
        for (Order__c o: [ select ID, InitialDateofService__c, name, Order_Expiration_Date__c, order_status__c,  CreatedDate, ESIID_Number__c, Parent_Account__r.Name, Parent_Account__r.IsPersonAccount,
                            Failure_Reason__c,Order_Failure_Comments__c, Order__c.Rejection_Reason__c,Order__c.Order_Rejection_Comments__c,Premise_Order_Type__c,REP_Profile__c
                            from Order__c
                            where order_status__c = 'Approved Pending Deposit']){
                pendingDeposit.add(new xOrder(o));
            }   
    }   
        
//This changes the orders from new to Approved pending confirmation
   public pageReference Approve() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:GetNewOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        for(xOrder xOrd:GetPendingDepositOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        
        for(Order__c ord: CheckedOrders){    
            ord.order_status__c='Approved Pending Confirmation';
            
        }
        update CheckedOrders;
        neworders.clear();
        pendingconfirmation.clear();
        confirmedorders.clear();
        orderlistresetter();
        return null;
    }
    //changes orders from new to approved pending deposit
    public pageReference ApproveWithDeposit() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:GetNewOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }        
        for(Order__c ord: CheckedOrders){    
            ord.order_status__c='Approved Pending Deposit';            
        }
        update CheckedOrders;
        neworders.clear();
        pendingconfirmation.clear();
        confirmedorders.clear();
        orderlistresetter();
        return null;
    }
    
    
//This changes the orders from new to Confirmed
   public pageReference Renew() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:GetNewOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        
        for(Order__c ord: CheckedOrders){    
            ord.order_status__c='Confirmed';
            
        }
        update CheckedOrders;
        neworders.clear();
        pendingconfirmation.clear();
        confirmedorders.clear();
        orderlistresetter();  
        return null;
    }        
//This changes the orders from Approved pending confirmation to confirmed
   public pageReference Confirm() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:getPendingConfirmationOrdersList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        
        for(Order__c ord: CheckedOrders){    
            ord.order_status__c='Confirmed';
            
        }
        update CheckedOrders;
        orderlistresetter();
        return null;
    }
    public pageReference DepositRequired() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:getPendingConfirmationOrdersList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        for(Order__c ord: CheckedOrders){    
            ord.order_status__c='Approved Pending Deposit';            
        }
        update CheckedOrders;
        orderlistresetter();
        return null;
    }
    
    public PageReference Fail() {
        system.debug('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~fail section started');
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:getpendingConfirmationOrdersList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        if (CheckedOrders.size()==1){
            FailedOrder=CheckedOrders[0];
            }
            else{
                if (CheckedOrders.size()>1){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'You have to fail orders one at a time'));   
                }
            }
            return null;
    }
    public PageReference FinishFail() {
        if (failedorder.failure_reason__c == 'Other (enter comments)' && (failedorder.order_failure_comments__c == '' || failedorder.order_failure_comments__c == null) ){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'You have to add comments if you select "other" '));
            return null;
        }      
        failedOrder.order_status__c='Failed';
        update failedOrder;
        failedOrder=null;
        pendingconfirmation.clear();
        orderlistresetter();
        return null;
    }
    public PageReference CancelFail() {
        failedorder=null;
        orderlistresetter();
        return null;
        
    }
        
        
    public PageReference startReject() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:getNewOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        
        if (CheckedOrders.size()==1){
            RejectedOrder=CheckedOrders[0];
            }
            else{
                if (CheckedOrders.size()>1){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'You have to reject orders one at a time'));   
                }
            }
        return null;    
    }
    public PageReference RejectFromDeposit() {
        List<order__c> CheckedOrders = new list<order__c>();
        for(xOrder xOrd:getPendingDepositOrderList()){
            if(xOrd.selected == true) {
                CheckedOrders.add(xOrd.ord);
            }
        }
        
        if (CheckedOrders.size()==1){
            RejectedOrder=CheckedOrders[0];
            }
            else{
                if (CheckedOrders.size()>1){
                    ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'You have to reject orders one at a time'));   
                }
            }
        return null;    
    }
    
    
    
    
    public PageReference FinishReject() {
        if (rejectedOrder.rejection_reason__c == 'Other (enter comments)' && (rejectedOrder.order_rejection_comments__c == '' || rejectedOrder.order_rejection_comments__c == null) ){
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'You have to add comments if you select "other" '));
            return null;
        }
        rejectedOrder.order_status__c='Rejected';
        update rejectedOrder;
        orderlistresetter();
        return null;
   }
   public PageReference CancelReject() {
        rejectedorder=null;
        orderlistresetter();
        return null;
        
    }
    
    public class xOrder {
          public Order__c ord {get; set;}
          public Boolean selected {get; set;}    
          public xOrder(Order__c x) {
            ord = x;
            selected = false;
        }
   }
    public pageReference nada(){
        
        return null;
    }    
    
}