force-app/main/default/objects/TrueCostSystemVariables__c/TrueCostSystemVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variables to control the TrueCost site without touching code.  These can differ from one environment to another.</description>
    <label>TrueCostSystemVariables</label>
</CustomObject>

force-app/main/default/objects/TrueCostSystemVariables__c/fields/REST_URL__c.field-meta.xml
<CustomField>
    <fullName>REST_URL__c</fullName>
    <label>REST URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerGetRepOrder.cls
public with sharing class ControllerGetRepOrder {

public string ssnx {get;set;}


	public ControllerGetRepOrder(){ 
			String order = ApexPages.currentPage().getParameters().get('id');	
			TrueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
			
			String json;
			String session = userInfo.getSessionId();
			
			//String url = 'https://cs12.salesforce.com/services/apexrest/OrderSSN?id='+order;
			String url = tcsv.REST_URL__c+'OrderSSN?id=';
			url = url+order;
		
			http h = new http();
			httprequest req = new httprequest();


			req.setEndpoint(url);
			req.setMethod('POST');
			req.setHeader('Authorization', 'OAuth ' + session);
			req.setHeader('Content-Type', 'text/xml;charset=utf-8');
			req.setBody('{ \"order\": '+order+'}');
			req.setTimeout(60000);
 
			httpresponse res = h.send(req);
			String result = res.getBody();

			json = res.getBody().replace('\n', '');
			
			ssnx = json;
			ssnx = ssnx.replace('"','');
			ssnx = 'Customer : ' + ssnx;

}

}