force-app/main/default/objects/TrueCostSystemVariables__c/TrueCostSystemVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variables to control the TrueCost site without touching code.  These can differ from one environment to another.</description>
    <label>TrueCostSystemVariables</label>
</CustomObject>

force-app/main/default/objects/TrueCostSystemVariables__c/fields/Show_only_Published_content__c.field-meta.xml
<CustomField>
    <fullName>Show_only_Published_content__c</fullName>
    <defaultValue>false</defaultValue>
    <description>All content displayed must have published = true.  This can be used to allow temporary content, previews in QA, and other tricks. 

This must not change in production once the site is live.</description>
    <inlineHelpText>All content displayed must have published = true.  This can be used to allow temporary content, previews in QA, and other tricks. 

This must not change in production once the site is live.</inlineHelpText>
    <label>Show only Published content</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ControllerforContentItems_Test.cls
@isTest
private class ControllerforContentItems_Test {
static testmethod void testControllerforContentItems(){
        ControllerforContentItems c = new ControllerforContentItems();
        c.whichcontent='testcontent';
        c.getmycontent();
        
        //flip the flag to get the other else statement to work
        /*TrueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        tcsv.Show_only_Published_content__c = !tcsv.Show_only_Published_content__c;
        update tcsv;
        //rerun the test from above     
        c.getmycontent();
        */
                    }
    }