force-app/main/default/objects/TrueCost_Case__c/TrueCost_Case__c.object-meta.xml
<CustomObject>
    <description>Like a case, only free</description>
    <label>TC Case</label>
    <nameField>
        <displayFormat>Case-{0000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TrueCost_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this case.</description>
    <inlineHelpText>TrueCost account for this case.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TC Cases</relationshipLabel>
    <relationshipName>TrueCost_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <description>Put the name of the person calling</description>
    <inlineHelpText>Put the name of the person calling</inlineHelpText>
    <label>Caller&#39;s Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <description>What type of entity originated this case?</description>
    <inlineHelpText>What type of entity originated this case?</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>REP</fullName>
            </value>
            <value>
                <fullName>TDSP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Non_Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Non_Account_Email__c</fullName>
    <inlineHelpText>Email of people who don&#39;t have an account already</inlineHelpText>
    <label>Non-Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <inlineHelpText>Where did the case come from (phone, email, web?)</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerforContactUs.cls
public with sharing class ControllerforContactUs {
    
    public truecost_case__C tcc {get; set;}{tcc=new truecost_case__c();}
    public boolean Page1 {get;set;}{Page1=true;}
    
    public ControllerforContactUs(){
    	
    	if (userinfo.getName()!='TrueCost Site Guest User' ){
	    	tcc.Caller_Name__c = UserInfo.getName();
	    	tcc.Account__c = TrueCostUtilities.getTheAccount(  UserInfo.getUserId()  ) ;
	    	tcc.Non_Account_Email__c = userinfo.getUserName();
    	}
    }
    
    
    
    public void saveCase(){
        page1=false;
        tcc.origin__c='web';
        tcc.Entity_Type__c='Customer';
        insert tcc;
        
    }
   }