force-app/main/default/objects/TrueCost_Case__c/TrueCost_Case__c.object-meta.xml
<CustomObject>
    <description>Like a case, only free</description>
    <label>TC Case</label>
    <nameField>
        <displayFormat>Case-{0000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TrueCost_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this case.</description>
    <inlineHelpText>TrueCost account for this case.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TC Cases</relationshipLabel>
    <relationshipName>TrueCost_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <description>Put the name of the person calling</description>
    <inlineHelpText>Put the name of the person calling</inlineHelpText>
    <label>Caller&#39;s Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>How the customer describes the case</description>
    <inlineHelpText>How the customer describes the case</inlineHelpText>
    <label>Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <description>What type of entity originated this case?</description>
    <inlineHelpText>What type of entity originated this case?</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>REP</fullName>
            </value>
            <value>
                <fullName>TDSP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What lead is this case associated with?</description>
    <inlineHelpText>What lead is this case associated with?</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>TrueCost_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Non_Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Non_Account_Email__c</fullName>
    <inlineHelpText>Email of people who don&#39;t have an account already</inlineHelpText>
    <label>Non-Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <inlineHelpText>Where did the case come from (phone, email, web?)</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Medium</fullName>
                <default>true</default>
                <label>Medium</label>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>What is the status of the case?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Waiting for Customer Response</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Escalated</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved/In Progress</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Quick subject for the case</description>
    <inlineHelpText>If this case is from web or email, then this is the subject line</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TrueCostCaseEmailHandler.cls
/**
 * Email services are automated processes that use Apex classes
 * to process the contents, headers, and attachments of inbound
 * email.
 */
 
 /*
 2/28/2012	Shane McLaughlin	Added isConverted to lead filter (you can't mess with converted leads without getting errors)
 
 */
global class TrueCostCaseEmailHandler implements Messaging.InboundEmailHandler {

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {
        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();
		
		TrueCost_Case__c tcc = new TrueCost_Case__c();
		//Is there an existing case open specified in the email?  If so, add this email and its attachments to the case
			integer casenumberstart;
			try{casenumberstart = email.plaintextbody.indexOf('Case-')+5;} catch(exception e){}
			
			if(casenumberstart!=4){
				string messagedivider = '**************************************************************************';
				string casenumber = email.plaintextbody.substring(casenumberstart, casenumberstart+7);
				system.debug('======================================The CaseNumber is ' + casenumber);
				tcc = [select id, status__c, description__c from TrueCost_Case__c where name =:('Case-'+casenumber)];
				tcc.status__c = 'New';
				tcc.description__c = tcc.description__c + '\n' + messagedivider + '\n';
				tcc.description__c = tcc.Description__c + system.now() + '\n';
				tcc.description__c = tcc.Description__c + email.plaintextbody;
				update tcc;
			} else{   //if it's not from an existing case
				//Check to see if it's someone we know--Accounts
				List<Account> AccountList = new List<Account>();
				AccountList = [select Name, Id from Account where email__c = :email.fromAddress or PersonEmail = :email.fromAddress limit 5000];
				if (AccountList.size() != 0) {
					TCC.Account__c = AccountList[0].Id;
				}
				
				//If it's not an account, maybe it's a lead?
				List<Lead> LeadList = new List<Lead>();
				LeadList = [select Name, Id from Lead where email= :email.fromAddress and isConverted = false];
				if (LeadList.size() != 0) {
					TCC.Lead__c= LeadList[0].Id; 
				}
				
				//If not, create the case
				tcc.Non_Account_Email__c = email.fromAddress;
				tcc.Origin__c = 'Email';
				tcc.Subject__c = email.subject;
				tcc.Description__c = email.plaintextbody;
				tcc.Caller_Name__c = email.fromname;
				tcc.priority__c = 'Medium';
				tcc.Status__c = 'New';
				tcc.Entity_Type__c = 'Customer';
				insert tcc;
				
			}
			//OK, now that we've added/updated the case, let's get the attachment(s)
		
		if (email.binaryAttachments != null && email.binaryAttachments.size() > 0) {
	      	for (integer i = 0 ; i < email.binaryAttachments.size() ; i++) {
	        Attachment attachment = new Attachment();
	        // attach to the newly created contact record
	        attachment.ParentId = tcc.Id;
	        attachment.Name = email.binaryAttachments[i].filename;
	        attachment.Body = email.binaryAttachments[i].body;
	        insert attachment;
	      }
    }
        return result;
    }
}