force-app/main/default/objects/Account/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>Billing address city name</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <description>This is a backend, system-only object that should not have data saved to it.  It is used to get around the lack of access to the account object for our authenticated sites license.</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_State2__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_State2__c</fullName>
    <description>Electric Service Address State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_Zip__c</fullName>
    <description>The zip code for the electric service address</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <description>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</description>
    <inlineHelpText>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</inlineHelpText>
    <label>Premise Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/TDSP_Lookup__c.field-meta.xml
<CustomField>
    <fullName>TDSP_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TDSP__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>only ACTIVE utilities are being returned</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/recordTypes/Point.recordType-meta.xml
<RecordType>
    <fullName>Point</fullName>
    <active>true</active>
    <description>Delivery and/or Receipt Points</description>
    <label>Point</label>
</RecordType>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDSP__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ControllerForAddServiceAddress.cls
/*
Shane McLaughlin     7/5/2012     Removed commercial address check since they're now ok for use.
*/
public with sharing class ControllerForAddServiceAddress {
    
    public ControllerForAddServiceAddress () {
    
        dummyenrollment=new enrollment__C();
        dummyenrollment.Address__c = ApexPages.currentpage().GetParameters().get('a');
        if (dummyenrollment.Address__c == 'null') dummyenrollment.Address__c =null;
        dummyenrollment.Zip__c = ApexPages.currentpage().GetParameters().get('z');
        ZipCodeLightboxFlag = false;
        if (dummyenrollment.Zip__c == 'null') dummyenrollment.Zip__c =null;
        
        
    }
    
    public static boolean ZipCodeLightboxFlag {get;set;}
    public integer zipcodelightboxmessage {get; set;}
    
    public string SearchESID {get;set;}
    public id selectedpremiseid {get;set;}
    public boolean wantmeterdata{Get;set;}
    public enrollment__c dummyenrollment{Get;set;}{}
    public premises__c dummypremise{Get;set;}   
    public string whichresult{get;set;}{whichresult='default';}
    public list<premises__C> premiselist {get;set;}
    public user u {get;set;}{u = new User();}  
        
    public void falseTheZipcodeLightboxFlag(){  //action method for the zipcode lightbox, used by the lightbox component
        zipcodelightboxflag=false;
    }
     
    /*public submitzip() {
        string zipcodecheck=TrueCostUtilities.checkZipCode(dummyenrollment.zip__c);
        if (zipcodecheck=='Now'){return null;}
                else{if (zipcodecheck=='Later'){
                        zipcodelightboxmessage=1;
                        zipcodelightboxflag=true;
                        return null;}
                    else{
                        zipcodelightboxmessage=0;
                        zipcodelightboxflag=true;
                        return null;}
                }
    }*/
    
    public PageReference AddressSearch() {       
       
        if (dummyenrollment.Address__c.length()<2) {
            ApexPages.Message msg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Your address is not long enough to search');
            ApexPages.addMessage(msg);
            
            return null;
        }
        
        string zipcodecheck=TrueCostUtilities.checkZipCode(dummyenrollment.zip__c);
        if (zipcodecheck == 'Later'){
        	zipcodelightboxmessage=1;
            zipcodelightboxflag=true;
            return null;
        } else {
        	if (zipcodecheck != 'Now'){
		    	zipcodelightboxmessage=0;
		        zipcodelightboxflag=true;
		        return null;
        	}                        
        }
        
        whichresult=null;
        
        if (searchESID==null||searchESID.length()<2){ //length >2 prevents error thrown by lookup method
            premiselist = TrueCostUtilities.exactMatchServiceAddress(dummyenrollment.address__c, dummyenrollment.zip__c);
                if(premiselist.size()==0){whichresult='no match';}
                    else{if(premiselist.size()==1){whichresult='one match';selectedpremiseid=premiselist[0].id;}
                        else{if(premiselist.size()>1){whichresult='multi match';}
                        }
                    }                
            return null;
        }
        
        if (searchESID!=null&&searchESID.length()>=2){  //length >2 prevents error thrown by lookup method
            premiselist = TrueCostUtilities.searchByESID(searchESID);
                if(premiselist.size()==0){whichresult='no match';}
                    else{if(premiselist.size()==1){whichresult='one match';selectedpremiseid=premiselist[0].id;}
                        else{if(premiselist.size()>1){whichresult='multi match';}
                        }
                    }
            searchESID = null;    
            return null;
        }
        return null;   
    }
        //first, let's get that service address matched.  Try an exact match
    public list<premises__c> getmatch(){    
               return premiselist;
    }
        
    public void nada(){} //kludge sometimes used to make rerenders happen
        
    public pagereference confirmSingleAddress() {                 
        premises__c selectedpremise2 = [select id, Electric_Service_Address_City__c,Premise_Type__c, Electric_Service_Address__c, 
                                                    Electric_Service_Address_State2__c, Electric_Service_Address_Zip__c, tdsp_lookup__r.name
                                                    from premises__C where id=:selectedpremiseid];
        
        list<account> newuseraccount = new list<account>();   
        newuseraccount = [select Billing_City__c, State__c, Billing_Adrs_Line_1__c, Billing_zip_code__c, Search_Zip_Code__c from Account where id=:TrueCostUtilities.getTheAccount(UserInfo.getUserId() )];
        
        //if the user doesn't have a billing address saved, why not assume it's the premise they're creating?
        if(newuseraccount[0].Billing_Adrs_Line_1__c==null){
        newuseraccount[0].Billing_City__c=selectedpremise2.Electric_Service_Address_City__c;
        newuseraccount[0].Billing_Adrs_Line_1__c=selectedpremise2.Electric_Service_Address__c;
        newuseraccount[0].State__c=selectedpremise2.Electric_Service_Address_State2__c;
        newuseraccount[0].Billing_zip_code__c=selectedpremise2.Electric_Service_Address_Zip__c.substring(0,5);
        }        
        if(newuseraccount[0].Search_Zip_Code__c==null){
        	newuseraccount[0].Search_Zip_Code__c=selectedpremise2.Electric_Service_Address_Zip__c.substring(0,5);
        }        
        update newuseraccount[0];        
        APAUtilities.makeapa(newuseraccount[0].id, selectedpremiseid);
        if (selectedpremise2.tdsp_lookup__r.name != 'CenterPoint Energy'){
            return page.Shopplans; //no point doing calculation choice if they're not UHIT/CEHE eligible!
        }
        if (selectedpremise2.premise_type__c != 'Residential'){
            PageReference PR = Page.Calculation_Choice; //if you're not resi, you need to get meter data!
            PR.getparameters().put('mode', 'MeterData');
            return pr;
        }        
        return Page.Calculation_Choice;
    }    
    
        
    public pagereference AddressSelect(id SelectedPremise) {
        return null;}
        
   



}