force-app/main/default/objects/Account/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>Billing address city name</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>An account that does not yet fit into another category, or fits into multiple.</description>
    <label>Generic</label>
</RecordType>

force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/lastDaily__c.field-meta.xml
<CustomField>
    <fullName>lastDaily__c</fullName>
    <label>lastDaily</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Daily_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Daily_Status__c</fullName>
    <label>Meter_Data_Daily_Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Not Requested</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Request_Status__c</fullName>
    <label>Meter Data Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error-Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Service Address</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Meter/ESID Match</fullName>
            </value>
            <value>
                <fullName>Error-No REP of Record</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>For email templates</description>
    <formula>Premise__r.Meter_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For email templates</inlineHelpText>
    <label>Meter Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/fields/Account_Premise_Association__c.field-meta.xml
<CustomField>
    <fullName>Account_Premise_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Premise Association</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Which date this usage occurred on</description>
    <inlineHelpText>Which date this usage occurred on</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_State2__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_State2__c</fullName>
    <description>Electric Service Address State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_Zip__c</fullName>
    <description>The zip code for the electric service address</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Meter number can be found on electric bills and on the meter itself</description>
    <inlineHelpText>Meter number can be found on electric bills and on the meter itself</inlineHelpText>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/RequestId__c.field-meta.xml
<CustomField>
    <fullName>RequestId__c</fullName>
    <label>RequestId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/TDSP_Lookup__c.field-meta.xml
<CustomField>
    <fullName>TDSP_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TDSP__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>only ACTIVE utilities are being returned</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCostSystemVariables__c/TrueCostSystemVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variables to control the TrueCost site without touching code.  These can differ from one environment to another.</description>
    <label>TrueCostSystemVariables</label>
</CustomObject>

force-app/main/default/objects/TrueCostSystemVariables__c/fields/UHITCallback__c.field-meta.xml
<CustomField>
    <fullName>UHITCallback__c</fullName>
    <label>UHITCallback</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/UHITRequest__c.object-meta.xml
<CustomObject>
    <label>UHITRequest</label>
    <nameField>
        <label>UHITRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHITRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UHITRequest__c/fields/APA__c.field-meta.xml
<CustomField>
    <fullName>APA__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>APA</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>UHITRequest</relationshipLabel>
    <relationshipName>UHITRequest</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <label>ESID</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <label>StatusCode</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UHITAsync.cls
public with sharing class UHITAsync {
    
    
    @future (callout=true)
    public static void UHITSummaryCalloutFuture(string apaid){
        MakeUHITCalloutSummary(apaid);
    }

    public static UsageRequest.PremiseHistoricalUsageRequestAckList_element[] calloutSender(UsageRequest.PremiseHistoricalUsageRequestList reqList){
        //TrueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();


        UsageRequest.PremiseHistoricalUsageRequestAckList_element[] rep ;

        String Party        = 'ThirdParty';
        String ReqId        = '838611739';
        String CallBackURI  = 'https://centerpoint-sbx.us-e1.cloudhub.io/uhit/HistoricalUsage'; 
        //String CallBAckURI =  tcsv.UHITCallback__c;
        String techEmail    = 'shane.mclaughlin@centerpointenergy.com';

        UsageRequest.ExecutePortType prt = new UsageRequest.ExecutePortType();
        
        system.debug('requestmgr reqList'+reqList);

        rep = prt.RequestForHistoricalUsage(Party, ReqId, CallBackURI, techEmail, reqList );       

        system.debug('requestmgr req result'+rep);

        return rep;
    }


    public static void MakeUHITCallout(string ApaID){
        AccountPremiseAssociation__c APA = getAPA(APAid);
        if (APA.Premise__r.TDSP_Lookup__r.Name!='CenterPoint Energy Houston Electric') return;

        //OUTPUT OBJECTS
        List<UsageRequest.PremiseHistoricalUsageRequest> lst = new  List<UsageRequest.PremiseHistoricalUsageRequest>(); 

        UsageRequest.PremiseHistoricalUsageRequestList reqList = new UsageRequest.PremiseHistoricalUsageRequestList();

        //Organizing the Callout info
        lst.add(BuildRequest(APA, true));
        reqList.PremiseHistoricalUsageRequest = lst;
        
        //Make The Callout 
        UsageRequest.PremiseHistoricalUsageRequestAckList_element[] rep  = calloutSender(reqList);

        String requestId = rep[0].PremiseHistoricalUsageAck.RequestID;

        system.debug('requestmgr req id'+requestId);

        UHITRequest__c  request = new UHITRequest__c(
            APA__c=APA.id,
            requestId__c=rep[0].PremiseHistoricalUsageAck.RequestID,
            ESID__c=rep[0].PremiseHistoricalUsageAck.ESIID
        );

        
        
        apa.Meter_Data_Daily_Status__c = 'In Progress';
        apa.Meter_Data_Request_Status__c = 'Complete' ;   
        apa.lastDaily__c = Datetime.now();
        apa.RequestId__c = requestId;

        update apa;
        insert request;
    }   

    public static void MakeUHITCleanupCallout(string ApaID){
        AccountPremiseAssociation__c APA = getAPA(APAid);
        if (APA.Premise__r.TDSP_Lookup__r.Name!='CenterPoint Energy Houston Electric') return;

        //OUTPUT OBJECTS
        List<UsageRequest.PremiseHistoricalUsageRequest> lst = new  List<UsageRequest.PremiseHistoricalUsageRequest>(); 

        UsageRequest.PremiseHistoricalUsageRequestList reqList = new UsageRequest.PremiseHistoricalUsageRequestList();

        //Organizing the Callout info
        lst.add(BuildCleanupRequest(APA, true));
        reqList.PremiseHistoricalUsageRequest = lst;
        
        //Make The Callout 
        UsageRequest.PremiseHistoricalUsageRequestAckList_element[] rep  = calloutSender(reqList);

        String requestId = rep[0].PremiseHistoricalUsageAck.RequestID;

        system.debug('requestmgr req id'+requestId);

        UHITRequest__c  request = new UHITRequest__c(
            APA__c=APA.id,
            requestId__c=rep[0].PremiseHistoricalUsageAck.RequestID,
            ESID__c=rep[0].PremiseHistoricalUsageAck.ESIID
        );

        
        
        apa.Meter_Data_Daily_Status__c = 'In Progress';
        apa.Meter_Data_Request_Status__c = 'Complete' ;   
        apa.lastDaily__c = Datetime.now();
        apa.RequestId__c = requestId;

        update apa;
        insert request;
    }   


    public static void MakeUHITCalloutSummary(string ApaID){
        AccountPremiseAssociation__c APA = getAPA(APAid);

        if (APA.Premise__r.TDSP_Lookup__r.Name!='CenterPoint Energy Houston Electric') return;

        //OUTPUT OBJECTS
        List<UsageRequest.PremiseHistoricalUsageRequest> lst = new  List<UsageRequest.PremiseHistoricalUsageRequest>(); 

        UsageRequest.PremiseHistoricalUsageRequestList reqList = new UsageRequest.PremiseHistoricalUsageRequestList();

        //Organizing the Callout info
        lst.add(BuildRequest(APA, false));
        reqList.PremiseHistoricalUsageRequest = lst;
        
        //Make The Callout
        try{ 
            UsageRequest.PremiseHistoricalUsageRequestAckList_element[] rep  = calloutSender(reqList);
           
            String requestId = rep[0].PremiseHistoricalUsageAck.RequestID;

            system.debug('requestmgr req id'+requestId);

            UHITRequest__c  request = new UHITRequest__c(
                APA__c=APA.id,
                requestId__c=rep[0].PremiseHistoricalUsageAck.RequestID,
                ESID__c=rep[0].PremiseHistoricalUsageAck.ESIID
            );
            
            apa.Meter_Data_Request_Status__c = 'In Progress';
            apa.RequestId__c = requestId;

            update apa;
            insert request;
        } catch(CalloutException e){
            system.debug('callout exception ' +e);
            apa.Meter_Data_Request_Status__c = 'Error-'+e;
            update apa;
            //throw an exception so that UHIT retries on the next batch of ASR
            throw new UHITErrorCodeException('Callout Exception ' +e);          

            
        }   
    }



    public static UsageRequest.PremiseHistoricalUsageRequest BuildRequest(AccountPremiseAssociation__c APA, boolean interval){

        //variables
        string CallType;
        date mydate = date.today()-1;
        UsageRequest.PremiseHistoricalUsageRequest req = new  UsageRequest.PremiseHistoricalUsageRequest() ;

        //Shared data for all calls
        req.AuthorizationType                                       = 'Unlimited';
        req.AuthorizationOnFile                                     = true;
        req.ESIID                                                   = APA.premise__r.ESID__c;
        req.MeterNumber                                             = APA.premise__r.Meter_Number__c;
        req.ServiceAddress                                          = APA.premise__r.Electric_Service_Address__c;
        req.ServiceCity                                             = APA.premise__r.Electric_Service_Address_City__c;
        req.ServiceState                                            = APA.premise__r.Electric_Service_Address_State2__c;
        req.ServiceZip                                              = APA.premise__r.Electric_Service_Address_Zip__c.substring(0,5);
        //  req.TypeOfData                                              = 'Summary Billing Data';
        //req.TypeOfData                                              = CallType;
        req.CustomerNameGrantingAuthorization                       = APA.account__r.Name;
        req.CustomerTitleGrantingAuthorization                      = 'Owner';
        req.CustomerTelephoneNumberGrantingAuthorization            = APA.account__r.PersonHomePhone;
        req.CustomerBillingStreetAddressGrantingAuthorization       = APA.account__r.Billing_Adrs_Line_1__c;
        req.CustomerBillingCityGrantingAuthorization                = APA.account__r.Billing_City__c;
        req.CustomerBillingStateGrantingAuthorization               = APA.account__r.Billing_State_Code__c;
        if (APA.premise__r.Electric_Service_Address_Zip__c != null){
            req.CustomerBillingZipGrantingAuthorization                 = APA.premise__r.Electric_Service_Address_Zip__c.substring(0,5);
        }else{
            req.CustomerBillingZipGrantingAuthorization                 = APA.premise__r.Electric_Service_Address_Zip__c;
        }
        req.OriginalAuthorizationDate = mydate;

        //specific to one branch or the other

        if (interval){
            req.TypeOfData='Interval Data';
            List<AggregateResult>  queryDate  = [select max(Date__c) day FROM Daily_Usage__c WHERE Account_Premise_Association__c =: apa.id]; 

            if(String.ValueOf(queryDate[0].get('day')) != null )    {               
                date d= date.valueof(queryDate[0].get('day'));
                req.UsageStartDate = d.adddays(1);
            }
        } else{
            req.TypeOfData='Summary Billing Data';
            req.UsageEndDate = date.today()-2;
        }       

        return req;
    }
    
    public static UsageRequest.PremiseHistoricalUsageRequest BuildCleanupRequest(AccountPremiseAssociation__c APA, boolean interval){

        //variables
        string CallType;
        date mydate = date.today()-1;
        UsageRequest.PremiseHistoricalUsageRequest req = new  UsageRequest.PremiseHistoricalUsageRequest() ;

        //Shared data for all calls
        req.AuthorizationType                                       = 'Unlimited';
        req.AuthorizationOnFile                                     = true;
        req.ESIID                                                   = APA.premise__r.ESID__c;
        req.MeterNumber                                             = APA.premise__r.Meter_Number__c;
        req.ServiceAddress                                          = APA.premise__r.Electric_Service_Address__c;
        req.ServiceCity                                             = APA.premise__r.Electric_Service_Address_City__c;
        req.ServiceState                                            = APA.premise__r.Electric_Service_Address_State2__c;
        req.ServiceZip                                              = APA.premise__r.Electric_Service_Address_Zip__c.substring(0,5);
        //  req.TypeOfData                                              = 'Summary Billing Data';
        //req.TypeOfData                                              = CallType;
        req.CustomerNameGrantingAuthorization                       = APA.account__r.Name;
        req.CustomerTitleGrantingAuthorization                      = 'Owner';
        req.CustomerTelephoneNumberGrantingAuthorization            = APA.account__r.PersonHomePhone;
        req.CustomerBillingStreetAddressGrantingAuthorization       = APA.account__r.Billing_Adrs_Line_1__c;
        req.CustomerBillingCityGrantingAuthorization                = APA.account__r.Billing_City__c;
        req.CustomerBillingStateGrantingAuthorization               = APA.account__r.Billing_State_Code__c;
        if (APA.premise__r.Electric_Service_Address_Zip__c != null){
            req.CustomerBillingZipGrantingAuthorization                 = APA.premise__r.Electric_Service_Address_Zip__c.substring(0,5);
        }else{
            req.CustomerBillingZipGrantingAuthorization                 = APA.premise__r.Electric_Service_Address_Zip__c;
        }
        req.OriginalAuthorizationDate = mydate;

        //specific to one branch or the other

        if (interval){
            req.TypeOfData='Interval Data';
            
                req.UsageStartDate = date.valueof('2013-09-28');
                req.UsageEndDate = date.valueof('2014-08-27');
            }


        return req;
    }

    public static void UHITRequestTriggerHandler(list<UHITRequest__c> UHRs, map<id, UHITRequest__c> oldUHRs){
        list<AsyncRequest__c> ASRs = new list<AsyncRequest__c>();

        for (UHITRequest__c UHR:UHRs){
            if (UHR.StatusCode__c !=null){ //it has an error
                if (UHR.StatusCode__c != oldUHRs.get(UHR.id).StatusCode__c){ //and didn't before
                    ASRs.add(
                        new AsyncRequest__c(
                            type__c='UHITRequestError', 
                            params__c=UHR.APA__c+','
                            +UHR.StatusCode__c)
                        );
                }
            }
        }

        insert ASRs;
    }

    public static void ProcessErrorASR(string params){
        string APAid = params.split(',')[0];
        string errorCode = params.split(',')[1];

        AccountPremiseAssociation__c APA = [select id, Meter_Data_Request_Status__c from AccountPremiseAssociation__c where id=:APAid];

        if (errorCode=='21'){ //meter number problem
            APA.Meter_Data_Request_Status__c='Error-Invalid Meter/ESID Match';
            } else if (errorCode=='7'){ //no rep of record
                APA.Meter_Data_Request_Status__c='Error-No REP of Record';
                } else if (errorCode=='9'){ //service address issue
                    APA.Meter_Data_Request_Status__c='Error-Invalid Service Address';
                    } else if (errorCode=='1'){ //service address issue
                        //do nothing, it's just a warning about the date range.
                        } else if (errorCode=='14'){ //service address issue
                            //do nothing--that's multiple requests per day not allowed
                            } else if (errorCode=='13'){ //service address issue
                                APA.Meter_Data_Request_Status__c='Error-ServiceZip does not match the address CEHE has' ;
                                } else if (errorCode=='22'){ //service address issue, needs to reauthorize with present owner of premise
                                    APA.Meter_Data_Request_Status__c='Error-MVI/MVO completed after authorization date' ;
                                    }else if (errorCode==''){
                                        throw new UHITErrorCodeException('UHIT Error Code Is Null');
                                        } else {
                                            throw new UHITErrorCodeException('Unknown UHIT Error Code');
                                        }
        update APA;
    }

    public class UHITErrorCodeException extends Exception {}


    //just for handling a common query for UHIT
    public static AccountPremiseAssociation__c GetAPA(string APAid){
        return [select id,      
        Premise__r.meter_number__c, meter_data_permission__c,
        Premise__r.Electric_Service_Address__c, premise__r.ESID__c, premise__r.Electric_Service_Address_City__c, premise__r.Electric_Service_Address_State2__c, premise__r.Electric_Service_Address_Zip__c,

        Premise__r.TDSP_Lookup__r.Name,

        Account__r.id, Account__r.Name, Account__r.PersonHomePhone, Account__r.ispersonAccount, Account__r.PersonEmail, Account__r.phone, Account__r.Billing_Adrs_Line_1__c, Account__r.Billing_Adrs_Line_2__c, Account__r.Billing_City__c, Account__r.Billing_State_Code__c, Account__r.State__c, Account__r.Billing_zip_code__c,

        Meter_Data_Daily_Status__c, Meter_Data_Request_Status__c, lastDaily__c, RequestId__c

        from AccountPremiseAssociation__c
        where id=:ApaID];
    }
}