force-app/main/default/objects/Account/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <description>Billing address city name</description>
    <label>City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this order.</description>
    <inlineHelpText>TrueCost account for this order.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Parent Account)</relationshipLabel>
    <relationshipName>OrdersPlaced</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What plan did the customer sign up for?</description>
    <inlineHelpText>What plan did the customer sign up for?</inlineHelpText>
    <label>Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plan__c.REP_Profile__c</field>
            <operation>equals</operation>
            <valueField>$Source.REP_Profile__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who wrote this review</description>
    <inlineHelpText>Who wrote this review</inlineHelpText>
    <label>Author</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>5</defaultValue>
    <inlineHelpText>Customer rating (1=low, 5=high)</inlineHelpText>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Which REP is this review about?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Wants_Contact__c.field-meta.xml
<CustomField>
    <fullName>Wants_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Customer wants REP contact about this</description>
    <inlineHelpText>Customer wants REP contact about this</inlineHelpText>
    <label>Okay to Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ControllerForCreateRating.cls
public class ControllerForCreateRating {
    
    public rep_rating__c newrating{get; set;}
    public account whichaccount{get;set;}
    public order__c CurrentPlan{get;set;}    
    
    public ControllerForCreateRating(){
        try{
            newrating = [select id, Author__c, Review__c, wants_contact__c, REP_Profile__c, Rating__c, Order__c, Plan__c from rep_rating__c where id =:ApexPages.CurrentPage().GetParameters().get('ratingid')];
                } catch (exception e){
                    newrating=new rep_rating__c(); 
                    newrating.Rating__c=5;
                }
        try{
            whichaccount=[select id, ispersonaccount, Personemail, phone, Billing_Adrs_Line_1__c, Billing_Adrs_Line_2__c, Billing_City__c, State__c, Billing_zip_code__c from account where id=:TrueCostUtilities.getTheAccount(UserInfo.getUserId()) limit 1];
        } catch (exception e){whichaccount = new account();}
        try{
            CurrentPlan= [select id, parent_account__r.id, rep_profile__r.name, rep_profile__r.id, plan__r.id from order__c where id=:ApexPages.CurrentPage().GetParameters().get('orderid')];
        } catch (exception e){}
    }
    
    public pageReference saverating(){
        try{
            if(whichaccount.id == CurrentPlan.Parent_Account__r.id){
                newrating.Author__c=whichaccount.id;
                newrating.REP_Profile__c=CurrentPlan.REP_Profile__R.id;
                newrating.Order__c=CurrentPlan.id;
                newrating.Plan__c=CurrentPlan.plan__r.id;
                upsert newrating;
            } else {
                ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'There has been an error saving your review.');
                ApexPages.addMessage(myMsg);
                return null;
            }
        } catch(exception e){
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL, 'There has been an error saving your review.');
            ApexPages.addMessage(myMsg);
            return null;
        }
        
    return Page.Myaccount;        
}
    
 
//Methods to set valus on Rating Stars

public void its1(){newrating.Rating__c=1;}
public void its2(){newrating.Rating__c=2;}
public void its3(){newrating.Rating__c=3;}
public void its4(){newrating.Rating__c=4;}
public void its5(){newrating.Rating__c=5;}


    public list<rep_rating__c> getRecentReviews(){        
        return TrueCostUtilities.getRatingsForREP(CurrentPlan.REP_profile__r.id);
    }
    
}