force-app/main/default/objects/Account/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <description>Used for promotional / referral codes</description>
    <label>Promo Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <description>This is a backend, system-only object that should not have data saved to it.  It is used to get around the lack of access to the account object for our authenticated sites license.</description>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Enrollment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Promo_Code__c.field-meta.xml
<CustomField>
    <fullName>Promo_Code__c</fullName>
    <description>Used for promotional / referral codes</description>
    <label>Promo Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/Monthly_Usage__c.object-meta.xml
<CustomObject>
    <description>Monthly usage.</description>
    <label>Monthly Usage</label>
    <nameField>
        <displayFormat>Usage-{0}</displayFormat>
        <label>Monthly Usage</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Monthly Usage</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Monthly Usage</relationshipLabel>
    <relationshipName>Monthly_Usage</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <formula>Premise__r.RecordType.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Premise Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Usage__c/fields/Usage__c.field-meta.xml
<CustomField>
    <fullName>Usage__c</fullName>
    <description>Total kWh usage for the specified time period.</description>
    <inlineHelpText>Total kWh usage for the specified time period.</inlineHelpText>
    <label>Usage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Heating_System__c.field-meta.xml
<CustomField>
    <fullName>Heating_System__c</fullName>
    <description>What type of fuel the premise uses for heating</description>
    <label>Heating System</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>Electric</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Occupants__c.field-meta.xml
<CustomField>
    <fullName>Occupants__c</fullName>
    <description>How many people live at the premise?</description>
    <inlineHelpText>How many people live at the premise?</inlineHelpText>
    <label>Occupants</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Pool__c.field-meta.xml
<CustomField>
    <fullName>Pool__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Does the home have a swimming pool?</description>
    <label>Pool</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <description>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</description>
    <inlineHelpText>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</inlineHelpText>
    <label>Premise Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Square_Feet__c.field-meta.xml
<CustomField>
    <fullName>Square_Feet__c</fullName>
    <description>How many square feet of living space are in the premise</description>
    <label>Square Feet</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_Built__c.field-meta.xml
<CustomField>
    <fullName>Year_Built__c</fullName>
    <description>The year of this premise&#39;s construction.</description>
    <inlineHelpText>The year of this premise&#39;s construction.</inlineHelpText>
    <label>Year Built</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Year_of_Construction__c.field-meta.xml
<CustomField>
    <fullName>Year_of_Construction__c</fullName>
    <description>What year the premise was built</description>
    <label>Year of Construction</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDSP__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NC</fullName>
            </value>
            <value>
                <fullName>ND</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MyAccount.cls
public class MyAccount {
    public boolean ShareMeterData { get; set; }
    public AccountPremiseAssociation__c theAPA { get; set; }
    public Account whichaccount { get; set; }
    public Enrollment__c theaccount { get; set; }
    public Premises__c thepremise { get; set; }
    public string dataRequestStatus { get; set; }
    //these are the months of the year, used to feed the usage table
    public boolean MeterDataPermission { get; set; }
    public order__C orderInProgress { Get; set; }
    private list < monthly_usage__c > usage { get; set; }
    public decimal Jan { get; set; }
    public decimal Feb { get; set; }
    public decimal Mar { get; set; }
    public decimal Apr { get; set; }
    public decimal May { get; set; }
    public decimal Jun { get; set; }
    public decimal Jul { get; set; }
    public decimal Aug { get; set; }
    public decimal Sep { get; set; }
    public decimal Oct { get; set; }
    public decimal Nov { get; set; }
    public decimal Dec { get; set; }

    public MyAccount() {
      
        try {

            ShareMeterData = false;
            whichaccount = new account();
            whichaccount = [select id, ispersonaccount, Personemail, phone, PersonMailingStreet, PersonMailingCity, PersonMailingState, PersonMailingPostalCode, Promo_Code__c from account where id = : TrueCostUtilities.getTheAccount(UserInfo.getUserId()) limit 1];
            theaccount = new enrollment__C();
            theaccount.phone__c = whichaccount.phone;
            theaccount.email__c = whichaccount.personemail;
            theaccount.address__c = whichaccount.PersonMailingStreet;
            theaccount.city__c = whichaccount.PersonMailingCity;
            theaccount.state__c = whichaccount.PersonMailingState;
            theaccount.zip__c = whichaccount.PersonMailingPostalCode;
            theaccount.Promo_Code__c = whichaccount.Promo_Code__c;

            theAPA = APAUtilities.getACtiveAPA(whichaccount.id);
            thepremise = [select id, ESID__c, premise_type__c, Electric_Service_Address__c, Square_Feet__c, Year_Built__c, Year_of_Construction__c, Heating_System__c, Pool__c, Occupants__c from premises__c where id = : theAPA.premise__r.id limit 1];
            MeterDataPermission = TrueCostUtilities.checkMeterDataPermission(theAPA.id);
            dataRequestStatus = TrueCostCalc.getMeterDataStatus(theAPA);
            ShareMeterData = theAPA.public_data__c;
            orderinprogress = TrueCostUtilities.orderinprogressNoDML(whichaccount.id, thepremise.id);
            system.debug('orderinprogress' + orderinprogress);
            usage = TrueCostUtilities.pullTheMonthlyUsage(theAPA);
            dec = usage[11].usage__c;
            nov = usage[10].usage__c;
            oct = usage[9].usage__c;
            sep = usage[8].usage__c;
            aug = usage[7].usage__c;
            jul = usage[6].usage__c;
            jun = usage[5].usage__c;
            may = usage[4].usage__c;
            apr = usage[3].usage__c;
            mar = usage[2].usage__c;
            feb = usage[1].usage__c;
            jan = usage[0].usage__c;

        } catch (exception e) {
            system.debug('=================================================NO APA found===========================================');
        }
    }

    public void makeDataPrivate() {
        theAPA.public_data__c = false;
        ShareMeterData = false;
        update theAPA;
    }

    public void makeDataPublic() {
        theAPA.public_data__c = true;
        ShareMeterData = true;
        update theAPA;
    }

    //tells page whether to show the order in progress area

    public boolean getMeterDataPermission() {
        return theAPA.Meter_Data_Permission__c;
    }

    public boolean getshowOrderinProgress() {
        try {
            return orderInProgress.name != null;
        } catch (exception e) {
            return false;
        }
    }

    public order__c GetCurrentPlan() {
        try {
            list < order__c > orderlist = [select id, order_status__c, REP_Profile__r.name, REP_Profile__r.id, Contract_Length__c, Plan_Expiration__c, plan__r.name, name
                from order__c where Plan_Expiration__c >= : system.today() and premise__c = : thepremise.id and(order_status__c = 'Confirmed') and Parent_Account__r.id = : whichaccount.id order by createddate DESC limit 1
            ];
            if (orderlist.size() > 0) {
                return orderlist[0];
            } else {
                return null;
            }
        } catch (exception e) {
            return null;
        }
    }

    public list < order__c > GetPreviousPlans() {
        try {
            list < order__c > oldplans = new list < order__c > ();
            oldplans = [select id, order_status__c, REP_Profile__r.name, REP_Profile__r.id, Contract_Length__c, Plan_Expiration__c, plan__r.name, createddate
                from order__c where(Plan_Expiration__c <= : system.today() or Plan_Expiration__c = null) and premise__c = : thepremise.id and(order_status__c = 'Confirmed') and Parent_Account__r.id = : whichaccount.id order by createddate DESC
            ];

            return oldplans;
        } catch (exception e) {
            return null;
        }
    }

    public decimal CurrentPlanRating { get; set; }
    public rep_rating__c newrating { get; set; } {
        newrating = new rep_rating__c();
    }

    public decimal getcurrentplanstars() {
        Order__c CurrentPlan = GetCurrentPlan();
        list < rep_rating__c > l = [select id, rating__c, review__c from rep_rating__c where order__c = : CurrentPlan.id order by createddate DESC limit 1];
        if (l.size() > 0) {
            CurrentPlanRating = l[0].Rating__c;
            newrating.rating__c = l[0].rating__c;
            newrating.Review__c = l[0].Review__c;
        }
        return CurrentPlanRating;
    }

    public pageReference rateyourrepedit() {
        //PageReference ratethem = Page.createrating;
        //ratethem.getParameters().put('o2r', CurrentPlan.id);
        PageReference pr = Page.Rating;
        pr.getParameters().put('orderid', GetCurrentPlan().id);
        list < rep_rating__c > l = [select id from rep_rating__c where order__c = : GetCurrentPlan().id and published__c = true order by createddate DESC limit 1];
        pr.getParameters().put('orderID', l[0].id);
        return PR;
    }
    public pageReference rateyourrep() {
        //PageReference ratethem = Page.createrating;
        //ratethem.getParameters().put('o2r', CurrentPlan.id);
        PageReference pr = Page.rating;
        pr.getParameters().put('orderID', GetCurrentPlan().id);
        return PR;
    }

    public pageReference saverating() {
        Order__c CurrentPlan = GetCurrentPlan();
        newrating.Author__c = whichaccount.id;
        newrating.REP_Profile__c = Currentplan.REP_Profile__R.id;
        newrating.Order__c = Currentplan.id;
        newrating.Plan__c = Currentplan.plan__r.id;
        upsert newrating;

        return Page.Myaccount;
    }
    public pageReference grantMeterDataPermission() {
        pageReference pageref = page.Calculation_Choice;
        pageref.getParameters().put('mode', 'MeterData');
        return pageref;
    }

    //Methods to set valus on Rating Stars

    public void its1() {
        newrating.Rating__c = 1;
    }
    public void its2() {
        newrating.Rating__c = 2;
    }
    public void its3() {
        newrating.Rating__c = 3;
    }
    public void its4() {
        newrating.Rating__c = 4;
    }
    public void its5() {
        newrating.Rating__c = 5;
    }

    //
    public list < rep_rating__c > getRecentReviews() {
        Order__c CurrentPlan = GetCurrentPlan();
        return TrueCostUtilities.getRatingsForREP(currentplan.REP_profile__r.id);
    }

    public list < rep_rating__c > getAnonReviews() {
        return [select id, rating__c, REP_without_Order__c from rep_rating__c where CreatedById = : UserInfo.getUserId() and Order__c = null];
    }

    public list < monthly_usage__c > getAverageUsage() {
        list < monthly_usage__c > alist = new list < monthly_usage__c > ();
        try {
            alist = TrueCostUtilities.pullAverageUsage(theAPA.premise__r.tdsp_lookup__r.id, '2018 Usage Per Customer');
        } catch (exception e) {
            alist = TrueCostUtilities.pullGuestMonthlyUsage();
        }
        return alist;

    }

}