force-app/main/default/objects/Account/fields/Record_Type_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Name__c</fullName>
    <formula>$RecordType.DeveloperName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Record Type Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <description>An account that does not yet fit into another category, or fits into multiple.</description>
    <label>Generic</label>
</RecordType>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Authorized_Representative__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Representative__c</fullName>
    <description>The customer has selected someone who can speak to their REP on their behalf</description>
    <inlineHelpText>The customer has selected someone who can speak to their REP on their behalf</inlineHelpText>
    <label>Authorized Representative</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>How long is the contract (in months)</description>
    <inlineHelpText>12 for a 12 month contract, 0 for a month to month contract</inlineHelpText>
    <label>Contract Length</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Customer_Date_of_Birth__c</fullName>
    <label>Customer Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone_Number__c</fullName>
    <inlineHelpText>The customer&#39;s primary phone number</inlineHelpText>
    <label>Customer Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Email_Address__c.field-meta.xml
<CustomField>
    <fullName>Email_Address__c</fullName>
    <description>Customer Email address.</description>
    <inlineHelpText>Customer Email address.</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Enrollment_Type__c.field-meta.xml
<CustomField>
    <fullName>Enrollment_Type__c</fullName>
    <formula>IF(PMVI_Flag__c  = TRUE, &quot;Move-In&quot;, IF(ISBLANK( InitialDateofService__c), &quot;Standard Switch&quot;, &quot;Self-Selected Switch&quot;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Enrollment Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ESIID_Number__c.field-meta.xml
<CustomField>
    <fullName>ESIID_Number__c</fullName>
    <description>The ESIID number of the meter to be switched to a plan</description>
    <inlineHelpText>The Electric Service Identifier ID number of the meter to be switched on for a plan.</inlineHelpText>
    <label>ESIID Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Fixed_Energy_Rate__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Energy_Rate__c</fullName>
    <label>Fixed Energy Rate</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/InitialDateofService__c.field-meta.xml
<CustomField>
    <fullName>InitialDateofService__c</fullName>
    <description>Initial date of service.</description>
    <inlineHelpText>Date the change to new REP will occur.</inlineHelpText>
    <label>Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/kWh_rate_1000__c.field-meta.xml
<CustomField>
    <fullName>kWh_rate_1000__c</fullName>
    <description>For the rate the customer signed up for, what was the PUC 1000 kWh/month rate?</description>
    <inlineHelpText>For the rate the customer signed up for, what was the PUC 1000 kWh/month rate?</inlineHelpText>
    <label>kWh rate 1000</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Language_Preference__c.field-meta.xml
<CustomField>
    <fullName>Language_Preference__c</fullName>
    <description>What language does the customer want to receive communications in?</description>
    <inlineHelpText>What language does the customer want to receive communications in?</inlineHelpText>
    <label>Language Pref.</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Last_4_SSN_of_Authorized__c.field-meta.xml
<CustomField>
    <fullName>Last_4_SSN_of_Authorized__c</fullName>
    <label>Last 4 SSN of Authorized</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Phone_of_Authorized__c.field-meta.xml
<CustomField>
    <fullName>Phone_of_Authorized__c</fullName>
    <description>Phone number of the customer&#39;s authorized agent</description>
    <inlineHelpText>Phone number of the customer&#39;s authorized agent</inlineHelpText>
    <label>Phone of Authorized</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Premise_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Order_Type__c</fullName>
    <description>The type of premise for this order.</description>
    <formula>Premise__r.Premise_Type__c</formula>
    <inlineHelpText>The type of premise for this order.</inlineHelpText>
    <label>Premise Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Account__c.field-meta.xml
<CustomField>
    <fullName>REP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What REP Account is this order tied to?</description>
    <inlineHelpText>What REP Account is this order tied to?</inlineHelpText>
    <label>REP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (REP Account)</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REPStatus__c.field-meta.xml
<CustomField>
    <fullName>REPStatus__c</fullName>
    <label>REPStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If applicable.</description>
    <inlineHelpText>If applicable.</inlineHelpText>
    <label>Reward Chosen</label>
    <referenceTo>Rewards__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <label>Service Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_City__c.field-meta.xml
<CustomField>
    <fullName>Service_City__c</fullName>
    <label>Service City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_State__c.field-meta.xml
<CustomField>
    <fullName>Service_State__c</fullName>
    <label>Service State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TX</fullName>
                <default>true</default>
                <label>TX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_Zip__c.field-meta.xml
<CustomField>
    <fullName>Service_Zip__c</fullName>
    <label>Service Zip</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <label>TDSP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/REP_Account__c.field-meta.xml
<CustomField>
    <fullName>REP_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>REP Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>REP Profiles</relationshipLabel>
    <relationshipName>REP_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TDSP__c/fields/email_address__c.field-meta.xml
<CustomField>
    <fullName>email_address__c</fullName>
    <label>email address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/classes/REPAPI_REST_OrderService_v1.cls
@RestResource(urlMapping='/rep-api/v1/*')
global with sharing class REPAPI_REST_OrderService_v1  {

    /****************************************************************************************************
    HOW TO PUBLIC TEST:
    Go To https://workbench.developerforce.com/restExplorer.php
    Here you can perform GET and POST methods once authenticated
    ****************************************************************************************************/


    /****************************************************************************************************
    * Description - Sample Apex REST service with GET method
        /services/apexrest/rep-api/v1/a0P3000000AEq8tEAD

    ****************************************************************************************************/
    global class GetResponseWrapper {
        List<Order__c> orderlist;
        String status;
        String message;

        public GetResponseWrapper(){

        }
    }
    @HttpGet
    global static GetResponseWrapper getOrder() {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        String accountId = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        GetResponseWrapper response = new GetResponseWrapper();

        try {
            User userId = [Select contactid from User where id =: Userinfo.getUserid()];
            List<AccountTeamMember> ATM = [SELECT Id, UserId, AccountID, SystemModstamp, TeamMemberrole FROM AccountTeamMember WHERE AccountId=:accountId AND UserId=:userId.id];
            List<REP_Profile__c> REP = [SELECT Id, Name, REP_Account__c from REP_Profile__c where REP_Account__c =:ATM[0].AccountID];

            List<Order__c> orderlist = [
            select
                Name,
                rep_profile__r.id,
                repstatus__c,
                id,
                order_status__c,
                Record_Type_Name__c,
                Enrollment_Type__c,
                InitialDateofService__c,
                ESIID_Number__c,
                TDSP__c,
                Premise_Order_Type__c,
                Plan_ID__c,
                kWh_rate_1000__c,
                Fixed_Energy_Rate__c,
                Reward__c,
                Contract_Length__c,
                First_Name__c,
                Last_Name__c,
                Email_Address__c,
                Customer_Email__c,
                Customer_Phone_Number__c,
                SSN__c,
                Customer_Date_of_Birth__c,
                Language_Preference__c,
                Authorized_Representative__c,
                Phone_of_Authorized__c,
                Last_4_SSN_of_Authorized__c,
                Service_Address__c,
                Service_City__c,
                Service_State__c,
                Service_Zip__c,
                Mailing_Street_Address__c,
                Mailing_City__c,
                Mailing_State__c,
                Mailing_Zip_Code__c,
                Customer_Acceptance_of_Plan_Terms__c,
                Customer_IP_Address__c,
                Created_Date_Formula__c,
                DBA_Name__c,
                Tax_Id__c,
                DUNS__c
            from Order__c
            where rep_profile__c = :REP[0].Id AND Created_Date_Formula__c > LAST_N_MONTHS:1
            limit 200];
            response.status = 'Success';
            response.message = 'You may review your recent orders';
            response.orderlist = orderlist;

        } catch(Exception exc) {

            res.StatusCode = 500;
            response.orderlist = null;
            response.status = 'Error';
            response.message = 'Your request failed with the following error: ' + exc.getMessage();
        }

        return response;
    }

    /****************************************************************************************************
     * Description - Sample Apex REST service with POST method
     // URI: /services/apexrest/rep-api/v1/00130000017qL6h/332956
    {
        "updateOrder": {
            "order_status": "Confirmed",
            "Rejection_Reason": "Credit Quality",
            "Order_Rejection_Comments": "Fix the address",
            "Plan_Expiration": "2020-08-04",
            "Deposit": "34.22",
            "Deposit_Requested": true,
            "REPOrderSubStatus": "Anything can go here",
            "repstatus": "Good to go",
            "Exception_Date": "2020-04-06"

        }
    }
    ****************************************************************************************************/
    global class RequestWrapper {
        String Record_Type_Name;
        String order_status;
        String Rejection_Reason;
        String Order_Rejection_Comments;
        Date Plan_Expiration;
        Decimal Deposit;
        Boolean Deposit_Requested;
        String REPOrderSubStatus;
        String repstatus;
        String Exception_Date;
    }

    global class PostResponseWrapper {
        List<Order__c> order;
        String requestURI;
        String status;
        String message;
        //User user;
        //String orderName;
        //String accountId;
        //List<AccountTeamMember> accountTeamMember;
        public PostResponseWrapper(){

        }
    }

    @HttpPost
    global static PostResponseWrapper updateOrder(RequestWrapper updateOrder) {

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        PostResponseWrapper response = new PostResponseWrapper();
        List<String> uriArr = req.requestURI.split('/');
        String accountId = uriArr[3];
        String orderName = req.requestURI.substring(req.requestURI.lastIndexOf('/')+1);
        Boolean flag = false;
        User userId;
        List<AccountTeamMember> ATM;
        List<REP_Profile__c> REP;

        try{

            userId = [Select contactid from User where id =: Userinfo.getUserid()];

        } catch(Exception exc) {

            res.StatusCode = 403;
            response.order = null;
            response.status = 'Not Authorized';
            response.message = 'Your update failed with the following error: User cannot be found';
            return response;
        }

        try{

            ATM = [SELECT Id, UserId, AccountID, SystemModstamp, TeamMemberrole FROM AccountTeamMember WHERE AccountId=:accountId AND UserId=:userId.id];

        } catch(Exception exc) {

            res.StatusCode = 403;
            response.order = null;
            response.status = 'Not Authorized';
            response.message = 'Your update failed with the following error: Account Team Member does not exist';
            return response;
        }

        try{

            REP = [SELECT Id, Name, REP_Account__c from REP_Profile__c where REP_Account__c =:ATM[0].AccountID];

        } catch(Exception exc) {

            res.StatusCode = 403;
            response.order = null;
            response.status = 'Not Authorized';
            response.message = 'Your update failed with the following error: Unauthorized access';
            return response;
        }

        try {

            List<Order__c> order = [
            select
                Name, // Order Number
                Record_Type_Name__c, // Order Name
                id, // Order Number
                order_status__c, // Order Status
                Rejection_Reason__c, // Rejection Reason
                Order_Rejection_Comments__c, // Rejection Comments
                Expected_Confirmation_Date__c, // Confirmation Date
                Plan_Expiration__c, // Plan Expiration
                Deposit__c, // Deposit Required
                Deposit_Requested__c, // Deposit
                rep_profile__r.id,  // REP Order Id
                REPOrderSubStatus__c, // REP Order Sub Status
                repstatus__c, // REP Status
                Exception__c // Exception

             from Order__c
             //where id = :accountId limit 1];
             where rep_profile__c = :REP[0].Id  and Name = :orderName limit 1 ];

            if(order.size() == 0){
                flag = true;
                res.StatusCode = 200;
                response.order = null;
                response.status = 'No orders';
                response.message = 'Your update failed with the following error: No orders found';
            }

            if(!flag) {
                if(!updateOrder.order_status.equalsIgnoreCase('Confirmed') && !updateOrder.order_status.equalsIgnoreCase('Rejected')) {
                  flag = true;
                  res.StatusCode = 403;
                  response.order = null;
                  response.status = 'Not Authorized';
                  response.message = 'Your update failed with the following error: Status update must be Confirmed or Rejected';
                }
            }

            if(!flag) {

                if(updateOrder.order_status.equalsIgnoreCase('Confirmed') && updateOrder.Plan_Expiration == null) {

                    flag = true;
                    res.StatusCode = 403;
                    response.order = null;
                    response.status = 'Not Authorized';
                    response.message = 'Your update failed with the following error: If order is Confirmed a Plan Expiration must be provided';

                }
                // if status is rejected a reason is required
                else if(updateOrder.order_status.equalsIgnoreCase('Rejected') && String.isBlank(updateOrder.Rejection_Reason)) {
                  // flag and send error rejection_reson must be given
                  flag = true;
                  res.StatusCode = 403;
                  response.order = null;
                  response.status = 'Not Authorized';
                  response.message = 'Your update failed with the following error: If order is Rejected must privide a reason';

                } else if( updateOrder.order_status.equalsIgnoreCase('Rejected') && !String.isBlank(updateOrder.Rejection_Reason)) {

                    if(updateOrder.Rejection_Reason.equalsIgnoreCase('Other') && String.isBlank(updateOrder.Order_Rejection_Comments)){

                        flag = true;
                        res.StatusCode = 403;
                        response.order = null;
                        response.status = 'Not Authorized';
                        response.message = 'Your update failed with the following error: If Rejected Reason is Other must provide comments';

                    }// if rejected and a reason is given the reason must match one of the following
                    else if(
                        updateOrder.Rejection_Reason.equalsIgnoreCase('Credit Quality') ||
                        updateOrder.Rejection_Reason.equalsIgnoreCase('Customer Rescinded') ||
                        updateOrder.Rejection_Reason.equalsIgnoreCase('Inaccurate Address') ||
                        updateOrder.Rejection_Reason.equalsIgnoreCase('Admin Rejection') ||
                        updateOrder.Rejection_Reason.equalsIgnoreCase('Deposit Unpaid')) {

                        // continue

                    } else {
                        // flag and send error
                        flag = true;
                        res.StatusCode = 403;
                        response.order = null;
                        response.status = 'Not Authorized';
                        response.message = 'Your update failed with the following error: If order is Rejected order reason must be Admin Rejection, Credit Quality, Customer Rescinded, Inaccurate Address or Deposit Unpaid';
                    }

                }
            }


            if(!flag){
                order[0].order_status__c = updateOrder.order_status;
                order[0].Rejection_Reason__c = updateOrder.Rejection_Reason;
                order[0].Order_Rejection_Comments__c = updateOrder.Order_Rejection_Comments;
                order[0].Plan_Expiration__c = updateOrder.Plan_Expiration;
                order[0].Deposit__c = updateOrder.Deposit;
                order[0].Deposit_Requested__c = updateOrder.Deposit_Requested;
                order[0].REPOrderSubStatus__c = updateOrder.REPOrderSubStatus;
                order[0].repstatus__c = updateOrder.repstatus;
                order[0].Exception__c = updateOrder.Exception_Date;
                update order;
                response.status = 'Success';
                response.message = 'Your Order has been updated successfully';
                response.order = order;
            }


        } catch(Exception exc) {

            res.StatusCode = 500;
            response.order = null;
            response.status = 'Error';
            response.message = 'Your update failed with the following error: ' + exc.getMessage();
        }

        return response;

    }

}