force-app/main/default/objects/Account/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/AccountPremiseAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Accounts with Premises</description>
    <label>AccountPremiseAssociation</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>AccountPremiseAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountPremiseAssociations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>The account that the premise is linked to.</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Associated Premises</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Estimated__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Estimated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Meter Data Estimated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The account has provided permission to retrieve data for this premise</description>
    <inlineHelpText>The account has provided permission to retrieve data for this premise</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Data_Request_Status__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Request_Status__c</fullName>
    <label>Meter Data Request Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
            <value>
                <fullName>Error-Incomplete Data</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Service Address</fullName>
            </value>
            <value>
                <fullName>Error-Invalid Meter/ESID Match</fullName>
            </value>
            <value>
                <fullName>Error-No REP of Record</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>For email templates</description>
    <formula>Premise__r.Meter_Number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>For email templates</inlineHelpText>
    <label>Meter Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountPremiseAssociation__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>This is the premise that the account is related to</description>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Associated Accounts</relationshipLabel>
    <relationshipName>AccountPremiseAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What order is this usage associated with?</description>
    <inlineHelpText>What order is this usage associated with?</inlineHelpText>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Business Account</value>
        </filterItems>
        <infoMessage>Filter required for desired results.  DO NOT REMOVE</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address__c</fullName>
    <description>The address that corresponds with the ERCOT lookup table</description>
    <inlineHelpText>The address that corresponds with the ERCOT lookup table.  Includes Street name and address number, not State or Zip Code.</inlineHelpText>
    <label>Address</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_City__c</fullName>
    <label>City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_State2__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_State2__c</fullName>
    <description>Electric Service Address State</description>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Electric_Service_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Electric_Service_Address_Zip__c</fullName>
    <description>The zip code for the electric service address</description>
    <label>Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <description>Electric Service Identifier</description>
    <externalId>true</externalId>
    <inlineHelpText>22-digit number</inlineHelpText>
    <label>ESID</label>
    <length>23</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Data_Permission__c.field-meta.xml
<CustomField>
    <fullName>Meter_Data_Permission__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Has the customer at this premise authorized us to use its meter data?</description>
    <inlineHelpText>Has the customer at this premise authorized us to use its meter data?</inlineHelpText>
    <label>Meter Data Permission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Meter_Number__c.field-meta.xml
<CustomField>
    <fullName>Meter_Number__c</fullName>
    <description>Meter number can be found on electric bills and on the meter itself</description>
    <inlineHelpText>Meter number can be found on electric bills and on the meter itself</inlineHelpText>
    <label>Meter Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <description>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</description>
    <inlineHelpText>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</inlineHelpText>
    <label>Premise Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/TDSP_Lookup__c.field-meta.xml
<CustomField>
    <fullName>TDSP_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>TDSP__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <infoMessage>only ACTIVE utilities are being returned</infoMessage>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Premises</relationshipLabel>
    <relationshipName>Premises</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UHITRequest__c/UHITRequest__c.object-meta.xml
<CustomObject>
    <label>UHITRequest</label>
    <nameField>
        <label>UHITRequest Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UHITRequest</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UHITRequest__c/fields/ESID__c.field-meta.xml
<CustomField>
    <fullName>ESID__c</fullName>
    <label>ESID</label>
    <length>22</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UHITRest.cls
/*
1/24/2012   Barry Glasco    Created to pull UHIT Data for external requests
*/  

@RestResource(urlMapping='/UHITRest/*') 


global  without sharing class  UHITRest {
	/*private final order__c o;
	public string ssn;
	
	public UHITRest(ApexPages.StandardController stdcontroller){ 
		
	}
	
	public string getSSN(){
		order__c myorder= getTheOrder(); 
		return myorder.ssn__c;

	}
	
	public order__c getTheOrder(){
		
		order__c[] o =[select id, SSN__C from order__C where id =: o.id];
		if (o.size()>0) {
			system.debug('============ the order is ============= ' + o[0] );
			return o[0];
		} 
		else {
			return null;
		}
	}
	@HttpGet

global static String doGet() {

			return 'help';
	*/

} 
/*
@HttpPost  
    global static String doPost(RestRequest req1, RestResponse res) {
    	//return JSON.serialize('{"error" :"Error Description"}');
    	//return test;
		  string esiid = ''; 
		  string meter = '';
		  String requestIdResp = '';
		  List<AccountPremiseAssociation__c> apa;
		  id Account   = '00130000011hadx'; // barry
		  esiid = req1.params.get('esiid'); 
		  meter = req1.params.get('meter');
		   system.debug('esid'+ esiid);
		   system.debug('meter'+ meter); 
		   
		  if (esiid == null || meter == null)
		  //return  '{\n' +    ' "error" :"No ESID or No meter passed"\n' +   '}';
		  return JSON.serialize('{"error" :"No ESID or No meter passed"}');
		  
		   
		  if (esiid == '' || meter == '')
		  return JSON.serialize('{"error" :"No ESID or No meter passed"}');
		 
		  
		
		  // check to see if we have a premise for this esiid
		  premises__c selectedpremise2 = [select id, Electric_Service_Address_City__c,Premise_Type__c, Electric_Service_Address__c, 
		                                                    Electric_Service_Address_State2__c, Electric_Service_Address_Zip__c, tdsp_lookup__r.name,meter_number__c 	                                                    
		                                                    from premises__C where ESID__c =:esiid limit 1];
		                                                    
		   
		  if ( selectedPremise2.id ==  null)
		  return JSON.serialize('{"error" :"No premise available for this ESID"}');
		  
		  // check to see if we already have an apa for this premise/esid
		    apa = [select Account__c, Id, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,lastdaily__c, RequestId__c FROM AccountPremiseAssociation__c 
		              where        premise__c =: selectedPremise2.id and account__c =: account limit 1];
		  
		   if ( apa.size() > 0 )
		   {
		   	system.debug('hava apa'+ apa);
		    List<Daily_Usage__c> daily = [SELECT  Date__c,  Intervals__c,Max_for_the_day__c,   Total_for_the_day__c FROM Daily_Usage__c where Account_Premise_Association__c =: apa[0].id and premise__c =: selectedpremise2.id ];
		     If  ( daily.size() > 0){
		     String JSONString = JSON.serialize(daily);
		     return  JSONString;
		     }
		  }else{
		     	system.debug('no apa');
		     	accountpremiseassociation__c newapa = new accountpremiseassociation__c(); 
		    
		        newapa.account__c=  account;
		        newapa.premise__c=selectedPremise2.id;
		        newapa.selected__c=true;
		        newapa.Meter_Data_Permission__c     = true;
		        newapa.Meter_Data_Request_Status__c = 'Complete';
		        selectedPremise2.meter_number__c = meter;
		        update selectedPremise2;
		        insert newapa;
		        apa = [select Account__c, Id, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,lastdaily__c, RequestId__c FROM AccountPremiseAssociation__c 
		              where        premise__c =: selectedPremise2.id and id =: newapa.id limit 1];
		              calluhit(  esiid,   apa[0].id,   selectedpremise2.id, meter);
		     }

	
		return JSON.serialize('{"successRequest" :"request sent""}');	
		
    }
@future (callout=true)
private static void calluhit(String esid, String apa, String premise,String meter)
{
  List<AccountPremiseAssociation__c> lstApa = new List<AccountPremiseAssociation__c>();
       List<UHITRequest__c> requestList = new List<UHITRequest__c >();
       LIST<UsageRequestInterval.PremiseHistoricalUsageRequest> lst = new  LIST<UsageRequestInterval.PremiseHistoricalUsageRequest>(); 
        UsageRequestInterval.PremiseHistoricalUsageRequestList reqList = new UsageRequestInterval.PremiseHistoricalUsageRequestList();
      
      	  List<accountpremiseassociation__c>      apalst = [select Account__c, Id, Meter_Data_Estimated__c,Meter_Data_Permission__c,Meter_Data_Request_Status__c,Premise__c,lastdaily__c, RequestId__c FROM AccountPremiseAssociation__c 
		              where        premise__c =: premise and id =: apa limit 1];
		              
      
    Premises__c premises = [select id, meter_number__C, meter_data_permission__c, 
                          square_feet__c, Year_of_Construction__c, Year_Built__c, Occupants__c, Heating_System__c, Pool__c,
                          Electric_Service_Address__c, ESID__c, Electric_Service_Address_City__c,  Electric_Service_Address_State2__c,Electric_Service_Address_Zip__c
                        from Premises__c where ESID__c =: esid];
   
  
     UsageRequestInterval.PremiseHistoricalUsageRequest req = new  UsageRequestInterval.PremiseHistoricalUsageRequest() ;
        
        req.AuthorizationType                                       = 'Unlimited';
        req.AuthorizationOnFile                                     = true;
        req.ESIID                                                   = premises.ESID__c;
        req.MeterNumber                                             = meter;
        req.ServiceAddress                                          = premises.Electric_Service_Address__c;
        req.ServiceCity                                             = premises.Electric_Service_Address_City__c;
        req.ServiceState                                            = premises.Electric_Service_Address_State2__c;
        req.ServiceZip                                              = premises.Electric_Service_Address_Zip__c.substring(0,5);
      //  req.TypeOfData                                              = 'Summary Billing Data';
        req.TypeOfData                                              = 'Interval Data';
        req.CustomerNameGrantingAuthorization                       = 'IES';
        req.CustomerTitleGrantingAuthorization                      = 'Owner';
        req.CustomerTelephoneNumberGrantingAuthorization            = '7132073204';
        req.CustomerBillingStreetAddressGrantingAuthorization       = '1111 Louisiana';
        req.CustomerBillingCityGrantingAuthorization                = 'Houston';
        req.CustomerBillingStateGrantingAuthorization               = 'Tx';
        if (premises.Electric_Service_Address_Zip__c != null)
        {
        req.CustomerBillingZipGrantingAuthorization                 = premises.Electric_Service_Address_Zip__c.substring(0,5);
        }else
        {
        req.CustomerBillingZipGrantingAuthorization                 = premises.Electric_Service_Address_Zip__c;
        }
        date mydate = date.today()-1;
       
        req.OriginalAuthorizationDate = mydate;
       
     
       
        
        lst.add(req);

        reqList.PremiseHistoricalUsageRequest = lst;
        
     
        UsageRequestINterval.ExecutePortType prt = new UsageRequestInterval.ExecutePortType();
        TrueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        
        String Party        = 'ThirdParty';
        String ReqId        = '838611739';
        String CallBackURI  = 'https://centerpoint.muleion.com/uhit/HistoricalUsage';
       
        String techEmail    = 'barry.glasco@centerpointenergy.com';
        
     
        
        try{
            
        //This is the real call which is currently disabled till people get there crap together 
        UsageRequestInterval.PremiseHistoricalUsageRequestAckList_element[] rep ;
         system.debug('requestmgr reqList'+reqList);
        system.debug('requestmgr req result'+rep);
        rep = prt.RequestForHistoricalUsage(Party, ReqId, CallBackURI, techEmail, reqList );
       
       
        
        // so we have to take the essid and go get the apa and premise info to handle update
        String requestId = rep[0].PremiseHistoricalUsageAck.RequestID;
        Integer responseCode = rep[0].PremiseHistoricalUsageAck.RequestStatusCode;
        String esiiD1 = rep[0].PremiseHistoricalUsageAck.ESIID;
        system.debug('requestmgr req id'+requestId);
        
       
        UHITRequest__c  request = new UHITRequest__c();
       
        
        
        ///request.APA__c = apa.id;
        request.requestId__c = requestId;
        request.ESID__c = esiiD1;
        //requestIdResp = requestId;
        
        insert request;
        apalst[0].RequestId__c = requestId;
        update apalst;
       
      
        }
         catch (CalloutException e)
        {
         system.debug('callout exception ' +e);
        // return  '{\n' +    ' "error" :"Fatal Callout Exception"\n' +   '}';
          //return JSON.serialize('{"error" :"Fatal Callout Exception"}');
        }
}
*/

/*

	public string getidcheck(){
		id theorder = o.id;
		return theorder;
	}


}
*/