force-app/main/default/objects/Content_BlogEntry__c/Content_BlogEntry__c.object-meta.xml
<CustomObject>
    <label>Content--BlogEntry</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Content--BlogEntry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content--BlogEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_BlogEntry__c/fields/Above_the_Fold__c.field-meta.xml
<CustomField>
    <fullName>Above_the_Fold__c</fullName>
    <description>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</description>
    <inlineHelpText>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</inlineHelpText>
    <label>Above the Fold</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The author that will be shown to the customer</description>
    <inlineHelpText>The author that will be shown to the customer</inlineHelpText>
    <label>Author</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Body for the blog entry</description>
    <inlineHelpText>Body for the blog entry</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/BottomScript__c.field-meta.xml
<CustomField>
    <fullName>BottomScript__c</fullName>
    <label>BottomScript</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <description>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</description>
    <inlineHelpText>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</inlineHelpText>
    <label>Deck</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Friendly_URL__c.field-meta.xml
<CustomField>
    <fullName>Friendly_URL__c</fullName>
    <defaultValue>text(YEAR(today()))&amp;&quot;/&quot;&amp;text(Month(today()))&amp;&quot;/&quot;&amp;text(day(today()))&amp;&quot;/&quot;</defaultValue>
    <description>URL of article title in friendly format</description>
    <inlineHelpText>this-is-a-friednly-URL-title (all lowercase, separated by hyphens, absolutely no punctuation!)</inlineHelpText>
    <label>Friendly URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <inlineHelpText>the blog will not appear until this date.  This date is also shown to the readers on the blog pages</inlineHelpText>
    <label>Publish Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The customer-facing title for this blog entry</description>
    <inlineHelpText>The customer-facing title for this blog entry</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/TopScript__c.field-meta.xml
<CustomField>
    <fullName>TopScript__c</fullName>
    <description>For youTube embeds, please use 640x360.  ex: &lt;iframe width=&quot;640&quot; height=&quot;360&quot; src=&quot;http://www.youtube.com/embed/vmQyEoNep2g&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;</description>
    <inlineHelpText>For youTube embeds, please use 640x360.  ex: &lt;iframe width=&quot;640&quot; height=&quot;360&quot; src=&quot;http://www.youtube.com/embed/vmQyEoNep2g&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;</inlineHelpText>
    <label>TopScript</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ControllerForBlogPost.cls
public class ControllerForBlogPost {
    
    public id SpecifiedPostID {get;set;}
    
    public Content_BlogEntry__c getPost(){
        try{return getPostbyID(ApexPages.currentPage().getParameters().get('id'));} catch(exception e){return null;}
    }
    
    public Content_BlogEntry__c getSpecifiedPost(){         
        return getPostbyID(SpecifiedPostID);
    }
    
    public static Content_BlogEntry__c getPostbyID(id localblogid){     
        list<Content_BlogEntry__c> blog = [select id, 
        topscript__c, bottomscript__c, 
        above_the_fold__c, title__c, body__c, deck__c, friendly_url__c, author__c, publish_date__c 
                                            from Content_BlogEntry__c where id=:localblogid ];
        try{return ContentRewriter.Rewrite(blog)[0];} catch(exception e){return null;}  
    }
    
    
}