force-app/main/default/objects/Content_BlogEntry__c/Content_BlogEntry__c.object-meta.xml
<CustomObject>
    <label>Content--BlogEntry</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Content--BlogEntry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content--BlogEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_BlogEntry__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The author that will be shown to the customer</description>
    <inlineHelpText>The author that will be shown to the customer</inlineHelpText>
    <label>Author</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <description>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</description>
    <inlineHelpText>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</inlineHelpText>
    <label>Deck</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Friendly_URL__c.field-meta.xml
<CustomField>
    <fullName>Friendly_URL__c</fullName>
    <defaultValue>text(YEAR(today()))&amp;&quot;/&quot;&amp;text(Month(today()))&amp;&quot;/&quot;&amp;text(day(today()))&amp;&quot;/&quot;</defaultValue>
    <description>URL of article title in friendly format</description>
    <inlineHelpText>this-is-a-friednly-URL-title (all lowercase, separated by hyphens, absolutely no punctuation!)</inlineHelpText>
    <label>Friendly URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The article has completed the approval process and may appear in public</description>
    <inlineHelpText>The article has completed the approval process and may appear in public</inlineHelpText>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/run_copy_trigger__c.field-meta.xml
<CustomField>
    <fullName>run_copy_trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>run copy trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The customer-facing title for this blog entry</description>
    <inlineHelpText>The customer-facing title for this blog entry</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <description>Template for Glossary, fee, or other content item.</description>
    <label>Content Item</label>
    <nameField>
        <label>Content Item Term/Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_Item__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <description>The deck or subtitle.  Only appears to customers if deck=true on the contentviewer component</description>
    <inlineHelpText>The deck or subtitle.  Only appears to customers if deck=true on the contentviewer component</inlineHelpText>
    <label>Deck</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Draft_Content__c.field-meta.xml
<CustomField>
    <fullName>Draft_Content__c</fullName>
    <description>What content is proposed to replace the published content</description>
    <inlineHelpText>What content is proposed to replace the published content</inlineHelpText>
    <label>Draft Content</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this content available to the TrueCost website?</description>
    <inlineHelpText>Is this content available to the TrueCost website?</inlineHelpText>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/run_copy_trigger__c.field-meta.xml
<CustomField>
    <fullName>run_copy_trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Tells the system to copy the rich text field from draft to production.  It&#39;s a system-only thing.  The workflow should set this as a final action.</description>
    <inlineHelpText>Tells the system to copy the rich text field from draft to production.  It&#39;s a system-only thing.  The workflow should set this as a final action.</inlineHelpText>
    <label>run copy trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title for the content item.  May be used by the content viewer component and visible to the users only if the page declaration says to show the title.</description>
    <inlineHelpText>Title for the content item.  May be used by the content viewer component and visible to the users only if the page declaration says to show the title.</inlineHelpText>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/FAQ__c/FAQ__c.object-meta.xml
<CustomObject>
    <description>Frequently Asked Questions</description>
    <label>FAQ</label>
    <nameField>
        <label>FAQ Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAQ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__c/fields/Draft_Answer__c.field-meta.xml
<CustomField>
    <fullName>Draft_Answer__c</fullName>
    <description>Proposed change to the Answer to the Question.  This stays hidden until the approval process completes.</description>
    <inlineHelpText>Proposed change to the Answer to the Question.  This stays hidden until the approval process completes.</inlineHelpText>
    <label>Draft Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Draft_Question__c.field-meta.xml
<CustomField>
    <fullName>Draft_Question__c</fullName>
    <description>If you&#39;d like to rewrite the question for this FAQ, use this field.  The actual question field for a published FAQ cannot be edited without legal review.</description>
    <inlineHelpText>If you&#39;d like to rewrite the question for this FAQ, use this field.  The actual question field for a published FAQ cannot be edited without legal review.</inlineHelpText>
    <label>Draft Question</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this FAQ allowed on the TrueCost website?</description>
    <inlineHelpText>Is this FAQ allowed on the TrueCost website?</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/run_copy_trigger__c.field-meta.xml
<CustomField>
    <fullName>run_copy_trigger__c</fullName>
    <defaultValue>false</defaultValue>
    <description>System only field that tells trigger to copy draft content to production.</description>
    <inlineHelpText>System only field that tells trigger to copy draft content to production.</inlineHelpText>
    <label>run copy trigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestRichTextFieldCopies.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestRichTextFieldCopies {

    static testMethod void TestContentItem() {
        //Make Data
        Content_Item__c item = new Content_Item__c();
        item.published__c=true;
        item.draft_content__c='My draft content';
        //Insert
        insert item;
        //Flip flag that starts trigger
        item.run_copy_trigger__c=true;
        update item;
    }
    
    static testMethod void TestFAQ() {
        //Make Data
        FAQ__c item = new FAQ__c();
        item.public__c=true;
        item.draft_question__c='My draft content';
        item.draft_answer__c='My draft content';
        //Insert
        insert item;
        //Flip flag that starts trigger
        item.run_copy_trigger__c=true;
        update item;
    }
    
    static testMethod void TestBlog() {
        //Make Data
        Content_BlogEntry__c item = new Content_BlogEntry__c();
        item.published__c=true;
        item.deck__c='Deck Deck Deck';
        item.author__c='Shane McLaughlin';
        item.title__c='Hamlet';
        item.friendly_url__c='i-welcome-our-new-google-overlords';
        //Insert
        insert item;
        //Flip flag that starts trigger
        item.run_copy_trigger__c=true;
        update item;
    }
}