force-app/main/default/objects/Content_BlogEntry__c/Content_BlogEntry__c.object-meta.xml
<CustomObject>
    <label>Content--BlogEntry</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Content--BlogEntry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content--BlogEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_BlogEntry__c/fields/Above_the_Fold__c.field-meta.xml
<CustomField>
    <fullName>Above_the_Fold__c</fullName>
    <description>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</description>
    <inlineHelpText>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</inlineHelpText>
    <label>Above the Fold</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Body for the blog entry</description>
    <inlineHelpText>Body for the blog entry</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <description>Template for Glossary, fee, or other content item.</description>
    <label>Content Item</label>
    <nameField>
        <label>Content Item Term/Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_Item__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <label>Definition</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/FAQ__c/FAQ__c.object-meta.xml
<CustomObject>
    <description>Frequently Asked Questions</description>
    <label>FAQ</label>
    <nameField>
        <label>FAQ Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAQ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__c/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <description>Proposed Answer</description>
    <inlineHelpText>Proposed Answer</inlineHelpText>
    <label>Answer</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ContentRewriter.cls
public with sharing class ContentRewriter {

	public static list<Content_BlogEntry__c> Rewrite (list<Content_BlogEntry__c> incoming){
		for (Content_BlogEntry__c b:incoming){
			try{ 
		        b.body__c = b.body__c.replace('http://www.mytruecost.com/', '/');
		        b.body__c = b.body__c.replace('http://www.myTrueCost.com/', '/');
		        b.body__c = b.body__c.replace('http://myTrueCost.com/', '/');
		        b.body__c = b.body__c.replace('http://mytruecost.com/', '/');
		        b.body__c = b.body__c.replace('http://centerpointenergy.force.com/', '/');
		        b.body__c = b.body__c.replace('https://centerpointenergy.secure.force.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('http://www.mytruecost.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('http://www.myTrueCost.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('http://myTrueCost.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('http://mytruecost.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('http://centerpointenergy.force.com/', '/');
		        b.above_the_fold__c = b.above_the_fold__c.replace('https://centerpointenergy.secure.force.com/', '/');
	        } catch (exception e){}
        
		}
		return incoming;
	}
	
	public static list<FAQ__c> Rewrite (list<FAQ__c> incoming){
		for (FAQ__c b:incoming){
			try{
		        b.answer__c = b.answer__c.replace('http://www.mytruecost.com/', '/');
		        b.answer__c = b.answer__c.replace('http://www.myTrueCost.com/', '/');
		        b.answer__c = b.answer__c.replace('http://myTrueCost.com/', '/');
		        b.answer__c = b.answer__c.replace('http://mytruecost.com/', '/');
		        b.answer__c = b.answer__c.replace('http://centerpointenergy.force.com/', '/');
		        b.answer__c = b.answer__c.replace('https://centerpointenergy.secure.force.com/', '/');
	        } catch (exception e){}
        
		}
		return incoming;
	}
	
	public static list<content_item__c> Rewrite (list<content_item__c> incoming){
		for (content_item__c b:incoming){
			try{
		        b.Definition__c = b.Definition__c.replace('http://www.mytruecost.com/', '/');
		        b.Definition__c = b.Definition__c.replace('http://www.myTrueCost.com/', '/');
		        b.Definition__c = b.Definition__c.replace('http://myTrueCost.com/', '/');
		        b.Definition__c = b.Definition__c.replace('http://mytruecost.com/', '/');
		        b.Definition__c = b.Definition__c.replace('http://centerpointenergy.force.com/', '/');
		        b.Definition__c = b.Definition__c.replace('https://centerpointenergy.secure.force.com/', '/');
	        } catch (exception e){}
        
		}
		return incoming;
	}
	
}