force-app/main/default/objects/Content_BlogEntry__c/Content_BlogEntry__c.object-meta.xml
<CustomObject>
    <label>Content--BlogEntry</label>
    <nameField>
        <displayFormat>{YYYY}-{MM}-{DD}-{0}</displayFormat>
        <label>Content--BlogEntry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content--BlogEntries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_BlogEntry__c/fields/Above_the_Fold__c.field-meta.xml
<CustomField>
    <fullName>Above_the_Fold__c</fullName>
    <description>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</description>
    <inlineHelpText>&quot;above the fold&quot; appears on the main blog page so that readers can see the beginning of the post and click a link to the full post.</inlineHelpText>
    <label>Above the Fold</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <description>The author that will be shown to the customer</description>
    <inlineHelpText>The author that will be shown to the customer</inlineHelpText>
    <label>Author</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <description>Body for the blog entry</description>
    <inlineHelpText>Body for the blog entry</inlineHelpText>
    <label>Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <description>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</description>
    <inlineHelpText>The deck is the blurb or subheadline displayed on the main blog and beside the title on the links component</inlineHelpText>
    <label>Deck</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Friendly_URL__c.field-meta.xml
<CustomField>
    <fullName>Friendly_URL__c</fullName>
    <defaultValue>text(YEAR(today()))&amp;&quot;/&quot;&amp;text(Month(today()))&amp;&quot;/&quot;&amp;text(day(today()))&amp;&quot;/&quot;</defaultValue>
    <description>URL of article title in friendly format</description>
    <inlineHelpText>this-is-a-friednly-URL-title (all lowercase, separated by hyphens, absolutely no punctuation!)</inlineHelpText>
    <label>Friendly URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Publish_Date__c.field-meta.xml
<CustomField>
    <fullName>Publish_Date__c</fullName>
    <inlineHelpText>the blog will not appear until this date.  This date is also shown to the readers on the blog pages</inlineHelpText>
    <label>Publish Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The article has completed the approval process and may appear in public</description>
    <inlineHelpText>The article has completed the approval process and may appear in public</inlineHelpText>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_BlogEntry__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>The customer-facing title for this blog entry</description>
    <inlineHelpText>The customer-facing title for this blog entry</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RecentBlogPostsController.cls
/*
1/24/2012   Shane McLaughlin        Added if statements to show only published blog depending on a Custom Setting field
2/22/2012   Shane McLaughlin        Changed query to allow registered users to see FULL blog content but guests can only see published content.
3/28/2012   Shane McLaughlin        Added variable to allow page to specify how many posts it wants
6/8/2012    Shane McLaughlin        Added SOQL offset to reduce code length
*/

public class RecentBlogPostsController{
      
    public list<Content_BlogEntry__c> blogposts {get;set;}
    public integer TheLimit{get;set;}      
    public Profile p{get;set;}
    public integer showblocks{get;set;}
    public integer totalblogcount{get;set;}
    
    public RecentBlogPostsController(){     
        p = [select name from Profile where id =:UserInfo.getProfileId()]; 
        showblocks=1;       
        totalblogcount=counttheblogs();
    }   
    
    public integer counttheblogs(){
        integer x = [select count()
                            from content_blogentry__c
                            where publish_date__c <:system.now() and published__c = true
                            ];
        return x;
    
    }
    
    public list<Content_BlogEntry__c> getAllPosts(){
        blogposts = [select ID, Title__c, body__c, above_the_fold__c, author__c, friendly_url__c, publish_date__c, deck__c, lastmodifieddate
            from content_blogentry__c
            where publish_date__c <:system.now() and published__c = true
            order by publish_date__c DESC];         
        return ContentRewriter.Rewrite(blogposts);    
    }
    
    public list<Content_BlogEntry__c> getMyPosts(){
        
        integer offsetamt = (showblocks-1)*10;        
        if(totalblogcount<(showblocks-1)*10) return null;        
        if (TheLimit==null) TheLimit=10;
        
        blogposts = [select ID, Title__c, body__c, above_the_fold__c, author__c, publish_date__c, deck__c
            from content_blogentry__c
            where publish_date__c <:system.now() and published__c = true
            order by publish_date__c DESC limit: TheLimit offset: offsetamt];         
        return ContentRewriter.Rewrite(blogposts);    
    }
    
    public pageReference ViewMore(){
        showblocks=showblocks+1;
        return null;
    }
    
    public pageReference nada(){return null;}
    
    
}