force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/About_Us__c.field-meta.xml
<CustomField>
    <fullName>About_Us__c</fullName>
    <description>This information will be shown to customers who want to know more about your REP</description>
    <inlineHelpText>This information will be shown to customers who want to know more about your REP</inlineHelpText>
    <label>About Us</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this REP profile active?</description>
    <inlineHelpText>Is this REP profile active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Friendly_URL__c.field-meta.xml
<CustomField>
    <fullName>Friendly_URL__c</fullName>
    <description>Used internally for TrueCost URLrewriter class.  Put in all lowercase with hyphens for spaces.  For example: friendly-name or reliant-energy etc.</description>
    <inlineHelpText>Used internally for TrueCost URLrewriter class.  Put in all lowercase with hyphens for spaces.  For example: friendly-name or reliant-energy etc.</inlineHelpText>
    <label>Friendly URL</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>Where the REPs logo is located.  Optimal logo size is 150 X 75 pixels.</description>
    <inlineHelpText>Where the REPs logo is located.  Optimal logo size is 150 X 75 pixels.</inlineHelpText>
    <label>Logo URL (Size 150 X 75px)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Publish_Reviews_while_Inactive__c.field-meta.xml
<CustomField>
    <fullName>Publish_Reviews_while_Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Publish Reviews while Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Random_Number_for_Sorting__c.field-meta.xml
<CustomField>
    <fullName>Random_Number_for_Sorting__c</fullName>
    <label>Random Number for Sorting</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Star_Rating_Avg__c.field-meta.xml
<CustomField>
    <fullName>Star_Rating_Avg__c</fullName>
    <description>What is your average customer approval?  A higher percentage means a higher customer approval.</description>
    <inlineHelpText>What is your average customer approval?  A higher percentage means a higher customer approval.</inlineHelpText>
    <label>Star Rating Avg</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/total_reviews__c.field-meta.xml
<CustomField>
    <fullName>total_reviews__c</fullName>
    <description>how many reviews this REP has</description>
    <inlineHelpText>how many reviews this REP has</inlineHelpText>
    <label>total reviews</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControllerForElectricCompanies.cls
public class ControllerForElectricCompanies {

    public static list<rep_profile__c> getreplist() {              
        return [select id, name, Logo_URL__c, Friendly_Url__c, Star_Rating_Avg__c, total_reviews__c, About_Us__c from rep_profile__c where active__c=true order by random_number_for_sorting__c, lastmodifieddate DESC];
        
    }

    public static list<rep_profile__c> getInactiveReplist() {              
        return [select id, name, Star_Rating_Avg__c, total_reviews__c from rep_profile__c where active__c=false 
        	and Publish_Reviews_while_Inactive__c = true
        order by random_number_for_sorting__c, lastmodifieddate DESC];
        
    }
}