force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/AEPC_Variable_Rate_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>AEPC_Variable_Rate_Last_Updated__c</fullName>
    <label>AEPC Variable Rate Last Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/AEPN_Variable_Rate_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>AEPN_Variable_Rate_Last_Updated__c</fullName>
    <label>AEPN Variable Rate Last Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/CEHE_Variable_Rate_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>CEHE_Variable_Rate_Last_Updated__c</fullName>
    <label>CEHE Variable Rate Last Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Curent_CEHE__c.field-meta.xml
<CustomField>
    <fullName>Curent_CEHE__c</fullName>
    <label>Current CEHE Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Current_AEPC_Variable_Rate_cents__c.field-meta.xml
<CustomField>
    <fullName>Current_AEPC_Variable_Rate_cents__c</fullName>
    <label>Current AEPC Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Current_AEPN_Variable_Rate_cents__c.field-meta.xml
<CustomField>
    <fullName>Current_AEPN_Variable_Rate_cents__c</fullName>
    <label>Current AEPN Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Current_Oncor_Variable_Rate_cents__c.field-meta.xml
<CustomField>
    <fullName>Current_Oncor_Variable_Rate_cents__c</fullName>
    <label>Current Oncor Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Current_TNMP_Variable_Rate_cents__c.field-meta.xml
<CustomField>
    <fullName>Current_TNMP_Variable_Rate_cents__c</fullName>
    <label>Current TNMP Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Oncor_Variable_Rate_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>Oncor_Variable_Rate_Last_Updated__c</fullName>
    <label>Oncor Variable Rate Last Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/TNMP_Variable_Rate_Last_Updated__c.field-meta.xml
<CustomField>
    <fullName>TNMP_Variable_Rate_Last_Updated__c</fullName>
    <label>TNMP Variable Rate Last Updated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/VariableRatesController.cls
public class VariableRatesController {
	
	public static list<REP_Profile__c> getREPs(){
        return [select id, name, 
        	Curent_CEHE__c, CEHE_Variable_Rate_Last_Updated__c,
			Current_Oncor_Variable_Rate_cents__c, Oncor_Variable_Rate_Last_Updated__c,
			Current_TNMP_Variable_Rate_cents__c, TNMP_Variable_Rate_Last_Updated__c,
			Current_AEPC_Variable_Rate_cents__c, AEPC_Variable_Rate_Last_Updated__c,
			Current_AEPN_Variable_Rate_cents__c, AEPN_Variable_Rate_Last_Updated__c			
			
        	from REP_Profile__c where Curent_CEHE__c!=null and CEHE_Variable_Rate_Last_Updated__c!=null order by Curent_CEHE__c DESC];
    }

}