force-app/main/default/objects/Fixed_Quote__c/Fixed_Quote__c.object-meta.xml
<CustomObject>
    <label>Fixed Quote</label>
    <nameField>
        <displayFormat>FPQ-{0}</displayFormat>
        <label>FPQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Fixed Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fixed_Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Fixed Quotes</relationshipLabel>
    <relationshipName>Fixed_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Index__c.field-meta.xml
<CustomField>
    <fullName>Index__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Index</label>
    <referenceTo>Index__c</referenceTo>
    <relationshipLabel>Fixed Quotes</relationshipLabel>
    <relationshipName>Fixed_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Last_Notification_Price_Check__c.field-meta.xml
<CustomField>
    <fullName>Last_Notification_Price_Check__c</fullName>
    <label>Last Notification Price Check</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Lock_Type__c.field-meta.xml
<CustomField>
    <fullName>Lock_Type__c</fullName>
    <label>Lock Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lock Citygate</fullName>
            </value>
            <value>
                <fullName>Lock Basis</fullName>
            </value>
            <value>
                <fullName>Lock NYMEX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Notifications_On__c.field-meta.xml
<CustomField>
    <fullName>Notifications_On__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notifications On</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Notify_above__c.field-meta.xml
<CustomField>
    <fullName>Notify_above__c</fullName>
    <label>Notify above</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Notify_below__c.field-meta.xml
<CustomField>
    <fullName>Notify_below__c</fullName>
    <label>Notify below</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Fixed Quotes</relationshipLabel>
    <relationshipName>Fixed_Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Position_List_JSON__c.field-meta.xml
<CustomField>
    <fullName>Position_List_JSON__c</fullName>
    <label>Position List JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>7</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Price_at_Last_Check__c.field-meta.xml
<CustomField>
    <fullName>Price_at_Last_Check__c</fullName>
    <label>Price at Last Check</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <formula>Opportunity__r.Opportunity_Owner_Name__c</formula>
    <label>Sales Rep</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Waiting for Pricing Approval</fullName>
            </value>
            <value>
                <fullName>Executed</fullName>
            </value>
            <value>
                <fullName>TC Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <formula>Opportunity__r.LDC2__r.Name</formula>
    <label>Utility</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/Volume__c.field-meta.xml
<CustomField>
    <fullName>Volume__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Fixed_Quote__c/fields/WACOG_Position_JSON__c.field-meta.xml
<CustomField>
    <fullName>WACOG_Position_JSON__c</fullName>
    <label>WACOG Position JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Index__c/Index__c.object-meta.xml
<CustomObject>
    <label>Index</label>
    <nameField>
        <label>Index Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Index__c/fields/Entegrate_Index_Key__c.field-meta.xml
<CustomField>
    <fullName>Entegrate_Index_Key__c</fullName>
    <externalId>true</externalId>
    <label>Entegrate Index Key</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Index__c/fields/Prompt_Month_Last_Trading_Day__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Month_Last_Trading_Day__c</fullName>
    <label>Prompt Month Last Trading Day</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <defaultValue>if (
   month(today())==12,
   date(year(today())+1, 1, 1), 
   date(year(today()), month(today())+1, 1)
)</defaultValue>
    <description>The start date of the contract/TC (must be the first of the month).</description>
    <inlineHelpText>The start date of the contract/TC (must be the first of the month).</inlineHelpText>
    <label>Contract Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Sales_Rep__c.field-meta.xml
<CustomField>
    <fullName>Sales_Rep__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Rep</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Quotes2User</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote/fields/Utility__c.field-meta.xml
<CustomField>
    <fullName>Utility__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Utility</label>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote/recordTypes/Quote.recordType-meta.xml
<RecordType>
    <fullName>Quote</fullName>
    <active>true</active>
    <label>Quote</label>
</RecordType>

force-app/main/default/classes/fpqAlerts.cls
public class fpqAlerts {
	
	public static void CheckQuote(id quoteId){

		Fixed_Quote__c fpq = sharedQuery(quoteId);		
		//did a contract rollOff?

		list<FQPosition> positions = FixedQuoteToContract.quoteJSON2Positions(fpq.Position_List_JSON__c);

		//to handle expiring quotes!!

		date PromptMonthLastTrading = [select id, Prompt_Month_Last_Trading_Day__c from Index__c where Entegrate_Index_Key__c = 'NYMEX Master'].Prompt_Month_Last_Trading_Day__c;

		if (fpq.Start_Date__c < PromptMonthLastTrading){
			string ChatterText = 'Pricing Alert: Quote for ' +fpq.Opportunity__r.Name + 'has expired.  To reactivate your alert, change the start date and update the alert prices.';
			ChatterUtils.mentionOnRecord(fpq.Opportunity__c, fpq.Opportunity__r.OwnerId, ChatterText);
			fpq.Notifications_On__c = false;
			update fpq;
			return;
		}

		//OK, if you got this far, then the quote isn't expiring.

		map<date, decimal> NYMEX = new map<date, decimal>();
		map<date, decimal> Basis = new map<date, decimal>();


		if (fpq.Lock_Type__c == 'Lock Citygate' || fpq.Lock_Type__c == 'Lock NYMEX'){			
			//get the nymex
			NYMEX = GasChoiceUtilities.getStrips(new String[]{'NYMEX'}, true).get('NYMEX');

			//update the positions		
			for (FQPosition p:positions){
				decimal NewNymex = NYMEX.get(dateTimeToDate(p.Contract_Month));
				p.Customer_Price = p.Customer_Price + NewNymex-p.DT_NYMEX ;
				p.DT_NYMEX = NewNymex;
			}
		
		}
		if (fpq.Lock_Type__c == 'Lock Citygate' || fpq.Lock_Type__c == 'Lock Basis'){
			//get the basis
			Basis = GasChoiceUtilities.getStrips(new String[]{fpq.Index__r.Name}, true).get(fpq.Index__r.Name);

			//update the positions
			for (FQPosition p:positions){
				decimal NewBasis = Basis.get(dateTimeToDate(p.Contract_Month));
				p.Customer_Price = p.Customer_Price + NewBasis-p.DT_Basis ;
				p.DT_Basis = NewBasis;
			}		
		}
		//re-wacog and save price
		fpq.Price_at_Last_Check__c = wacog(positions);
		fpq.Last_Notification_Price_Check__c = system.now();

		string ChatterText;

		//price checks and chatter calls
		if (fpq.Price_at_Last_Check__c >= fpq.Notify_above__c){
			ChatterText = ' The price for ' +fpq.Opportunity__r.Name+'exceeded your threshold of '+fpq.Notify_above__c+'. It is now ' + fpq.Price_at_Last_Check__c+ '.  See '+fpq.Name+' below. #FixedPriceAlert';

		} else if (fpq.Price_at_Last_Check__c <= fpq.Notify_below__c){
			ChatterText = ' The price for ' +fpq.Opportunity__r.Name+' went below your threshold of '+fpq.Notify_below__c+'. It is now ' + fpq.Price_at_Last_Check__c + '.  See '+fpq.Name+' below. #FixedPriceAlert';
		}

		//if there was anything to say, say it:
		if (ChatterText!=null){
			ChatterUtils.mentionOnRecord(fpq.Opportunity__c, fpq.Opportunity__r.OwnerId, ChatterText);
			fpq.Notifications_On__c = false;
		}

		update fpq;


	}

	public static Fixed_Quote__c sharedQuery(id quoteId){
		return [select Id, Name, Index__r.Name, Notifications_On__c, Notify_above__c, Notify_below__c, Opportunity__c, Opportunity__r.OwnerId, Opportunity__r.Name, Position_List_JSON__c, Price__c, Price_at_Last_Check__c, Sales_Rep__c,Start_Date__c, Status__c, Term__c, Utility__c, Volume__c, WACOG_Position_JSON__c,  Margin__c, Lock_Type__c, Cost__c, Account__c, Account__r.Name from Fixed_Quote__c where id =: quoteId];
	} 

	public static date dateTimeToDate(datetime dt){
		return date.newinstance(dT.year(), dT.month(), dT.day());
	}

	public static decimal Wacog(list<FQPosition> positions){
		//get the total
		decimal runningTotal = 0;
		for (FQPosition p:positions){
			runningTotal = runningTotal + p.Volume;
		}		

		decimal output = 0;

		for (FQPosition p:positions){
			output = output + p.Customer_Price*(p.Volume/runningTotal);
		}	

		return output.setScale(4);
	}

}