force-app/main/default/objects/User/fields/Make_Profile_Public__c.field-meta.xml
<CustomField>
    <fullName>Make_Profile_Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show this user on the TrueCost people page</description>
    <inlineHelpText>Show this user on the TrueCost people page</inlineHelpText>
    <label>Make Profile Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Public_Picture_URL__c.field-meta.xml
<CustomField>
    <fullName>Public_Picture_URL__c</fullName>
    <description>shows on the TrueCost people page.  Link this to a static resource (similar to REP logos)</description>
    <inlineHelpText>shows on the TrueCost people page.  Link this to a static resource (similar to REP logos)</inlineHelpText>
    <label>Public Picture URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/User/fields/Public_Profile_Description__c.field-meta.xml
<CustomField>
    <fullName>Public_Profile_Description__c</fullName>
    <description>Shown on the TrueCost people page</description>
    <inlineHelpText>Shown on the TrueCost people page</inlineHelpText>
    <label>Public Profile Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/ControllerForTrueCostPeople.cls
public class ControllerForTrueCostPeople {
    
    public list<UserWrapper> getPeople(){
        list<user> users = [select id, name, title, Public_Profile_Description__c, Public_Picture_URL__c from user where Make_Profile_Public__c=true];
        list<UserWrapper> output = new list<UserWrapper>();
        for (user u:users){
            UserWrapper UW = new UserWrapper();
            UW.name = u.name;
            UW.title = u.title;
            UW.image = u.Public_Picture_URL__c;
            UW.description = u.Public_Profile_Description__c;
            output.add(UW);
        }
        return output;
    }
    
    public class UserWrapper {
        public string name {get;set;}
        public string title{get;set;}
        public string image {get;set;}
        public string description {get;set;}
    }
}