force-app/main/default/objects/Daily_Usage__c/Daily_Usage__c.object-meta.xml
<CustomObject>
    <description>Interval data with a summary value for the date</description>
    <label>Daily Usage</label>
    <nameField>
        <label>Daily Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Usages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Usage__c/fields/Account_Premise_Association__c.field-meta.xml
<CustomField>
    <fullName>Account_Premise_Association__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Premise Association</label>
    <referenceTo>AccountPremiseAssociation__c</referenceTo>
    <relationshipLabel>Daily Usages</relationshipLabel>
    <relationshipName>Daily_Usages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Which date this usage occurred on</description>
    <inlineHelpText>Which date this usage occurred on</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Day_of_Week__c</fullName>
    <description>what day of the week the usage happened on</description>
    <formula>CASE( MOD(  Date__c - DATE(1900, 1, 7), 7), 0, &quot;Sunday&quot;, 1, &quot;Monday&quot;, 2, &quot;Tuesday&quot;, 3, &quot;Wednesday&quot;, 4, &quot;Thursday&quot;, 5, &quot;Friday&quot;, 6, &quot;Saturday&quot;,&quot;Error&quot;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>what day of the week the usage happened on</inlineHelpText>
    <label>Day of Week</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Intervals__c.field-meta.xml
<CustomField>
    <fullName>Intervals__c</fullName>
    <description>Stores interval data, matches UHIT spec</description>
    <label>Intervals</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Max_for_the_day__c.field-meta.xml
<CustomField>
    <fullName>Max_for_the_day__c</fullName>
    <label>Max for the day</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Daily_Usage__c/fields/Total_for_the_day__c.field-meta.xml
<CustomField>
    <fullName>Total_for_the_day__c</fullName>
    <label>Total for the day</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/WeeklyTCEmailController.cls
public with sharing class WeeklyTCEmailController {


	public string APAid {get;set;}
	private list<daily_usage__c> Last7;

	public WeeklyTCEmailController() {
		
	}

	public string GetDays(){
		if (Last7 == null) SetAllData();

		string output = '';
		
		for (integer x=6; x>=0; x--){ //for each day
			output=output+(string.valueof(last7[x].total_for_the_day__c))+',';			
		}
		output = output.substringBeforeLast(',');
		return output;
	}	

	public void SetAllData(){
		system.debug('The APA is ' + apaid);
		if (Last7==null){
			Last7 = [select id, date__c, Intervals__c, Max_for_the_day__c, Day_of_Week__c, total_for_the_day__c from daily_usage__c where Account_Premise_Association__c =: APAid and Account_Premise_Association__c!=null order by date__c DESC limit 7];
			
		}
	}

	public list<daily_usage__c> GetLast7(){
		if (Last7 == null) SetAllData();
		return last7;
	}

	public date GetEnddate(){
		if (Last7 == null) SetAllData();
		return Last7[0].date__c;
	}

	public date GetStartdate(){
		if (Last7 == null) SetAllData();
		return Last7[6].date__c;
	}

	public decimal GetWeekMax(){
		if (Last7 == null) SetAllData();
		
		decimal output =0;
		for (daily_usage__c du:Last7){
			output = math.max(output, du.Max_for_the_day__c);
		}
		return output;
	}

}