force-app/main/default/objects/Lead/fields/Current_REP__c.field-meta.xml
<CustomField>
    <fullName>Current_REP__c</fullName>
    <label>Current REP</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Abacus</fullName>
            </value>
            <value>
                <fullName>Ambit</fullName>
            </value>
            <value>
                <fullName>Amigo</fullName>
            </value>
            <value>
                <fullName>Bounce</fullName>
            </value>
            <value>
                <fullName>Brilliant</fullName>
            </value>
            <value>
                <fullName>Champion</fullName>
            </value>
            <value>
                <fullName>Cirro</fullName>
            </value>
            <value>
                <fullName>Direct</fullName>
            </value>
            <value>
                <fullName>Dynowatt</fullName>
            </value>
            <value>
                <fullName>Energy Plus</fullName>
            </value>
            <value>
                <fullName>EPCOT</fullName>
            </value>
            <value>
                <fullName>Gexa</fullName>
            </value>
            <value>
                <fullName>Green Mountain</fullName>
            </value>
            <value>
                <fullName>Just Energy</fullName>
            </value>
            <value>
                <fullName>Kinetic</fullName>
            </value>
            <value>
                <fullName>Mega</fullName>
            </value>
            <value>
                <fullName>MX</fullName>
            </value>
            <value>
                <fullName>Payless</fullName>
            </value>
            <value>
                <fullName>Potentia</fullName>
            </value>
            <value>
                <fullName>Reliant</fullName>
            </value>
            <value>
                <fullName>Simple</fullName>
            </value>
            <value>
                <fullName>Southwest Power &amp; Light</fullName>
            </value>
            <value>
                <fullName>Spark</fullName>
            </value>
            <value>
                <fullName>StarTex</fullName>
            </value>
            <value>
                <fullName>Stream</fullName>
            </value>
            <value>
                <fullName>Tara</fullName>
            </value>
            <value>
                <fullName>TXU</fullName>
            </value>
            <value>
                <fullName>YEP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/TrueCost_Case__c.object-meta.xml
<CustomObject>
    <description>Like a case, only free</description>
    <label>TC Case</label>
    <nameField>
        <displayFormat>Case-{0000000}</displayFormat>
        <label>Case Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TC Cases</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/TrueCost_Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this case.</description>
    <inlineHelpText>TrueCost account for this case.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>TC Cases</relationshipLabel>
    <relationshipName>TrueCost_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Caller_Name__c.field-meta.xml
<CustomField>
    <fullName>Caller_Name__c</fullName>
    <description>Put the name of the person calling</description>
    <inlineHelpText>Put the name of the person calling</inlineHelpText>
    <label>Caller&#39;s Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Current_REP__c.field-meta.xml
<CustomField>
    <fullName>Current_REP__c</fullName>
    <label>Current REP</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Entity_Type__c.field-meta.xml
<CustomField>
    <fullName>Entity_Type__c</fullName>
    <description>What type of entity originated this case?</description>
    <inlineHelpText>What type of entity originated this case?</inlineHelpText>
    <label>Entity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>REP</fullName>
            </value>
            <value>
                <fullName>TDSP</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What lead is this case associated with?</description>
    <inlineHelpText>What lead is this case associated with?</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>TrueCost_Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Non_Account_Email__c.field-meta.xml
<CustomField>
    <fullName>Non_Account_Email__c</fullName>
    <inlineHelpText>Email of people who don&#39;t have an account already</inlineHelpText>
    <label>Non-Account Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Non_Account_Phone__c.field-meta.xml
<CustomField>
    <fullName>Non_Account_Phone__c</fullName>
    <inlineHelpText>Phone of the person who doesn&#39;t have an account already</inlineHelpText>
    <label>Non-Account Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Order_Failure_Reason__c.field-meta.xml
<CustomField>
    <fullName>Order_Failure_Reason__c</fullName>
    <description>Why did the switch order fail?</description>
    <inlineHelpText>Why did the switch order fail?</inlineHelpText>
    <label>Order Failure Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <label>Order Number</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <inlineHelpText>Where did the case come from (phone, email, web?)</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Phone</fullName>
                <default>true</default>
                <label>Phone</label>
            </value>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Web</fullName>
            </value>
            <value>
                <fullName>Outbound Call</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Permission_to_use_comments_in_marketing__c.field-meta.xml
<CustomField>
    <fullName>Permission_to_use_comments_in_marketing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The customer has given us permission to use their comments</description>
    <inlineHelpText>The customer has given us permission to use their comments</inlineHelpText>
    <label>Permission to use comments in marketing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Reason__c.field-meta.xml
<CustomField>
    <fullName>Reason__c</fullName>
    <inlineHelpText>Given the type of case, what reason is the case?</inlineHelpText>
    <label>Reason</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Address Not Found</fullName>
            </value>
            <value>
                <fullName>Comments/Feedback</fullName>
            </value>
            <value>
                <fullName>Commercial Service</fullName>
            </value>
            <value>
                <fullName>Complex functionality</fullName>
            </value>
            <value>
                <fullName>ERCOT alert</fullName>
            </value>
            <value>
                <fullName>ESID lookup</fullName>
            </value>
            <value>
                <fullName>Existing problem</fullName>
            </value>
            <value>
                <fullName>Format</fullName>
            </value>
            <value>
                <fullName>Instructions not clear</fullName>
            </value>
            <value>
                <fullName>Market question</fullName>
            </value>
            <value>
                <fullName>New problem</fullName>
            </value>
            <value>
                <fullName>No Meter</fullName>
            </value>
            <value>
                <fullName>Order Failure</fullName>
            </value>
            <value>
                <fullName>Order status</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Questions about an REP</fullName>
            </value>
            <value>
                <fullName>Questions about a Plan</fullName>
            </value>
            <value>
                <fullName>Suggestion</fullName>
            </value>
            <value>
                <fullName>Technical - Browser assistance</fullName>
            </value>
            <value>
                <fullName>Technical - Complex functionality</fullName>
            </value>
            <value>
                <fullName>Technical - Navigation</fullName>
            </value>
            <value>
                <fullName>Technical - Password reset</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>User didn&#39;t attend training</fullName>
            </value>
            <value>
                <fullName>TDSP Fees</fullName>
            </value>
            <value>
                <fullName>Account termination</fullName>
            </value>
            <value>
                <fullName>Meter number</fullName>
            </value>
            <value>
                <fullName>REP order performance</fullName>
            </value>
            <value>
                <fullName>Page errors</fullName>
            </value>
            <value>
                <fullName>Survey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/REP_for_Switch__c.field-meta.xml
<CustomField>
    <fullName>REP_for_Switch__c</fullName>
    <description>What REP is the customer placing an order with?</description>
    <inlineHelpText>What REP is the customer placing an order with?</inlineHelpText>
    <label>REP for Switch</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <description>Quick subject for the case</description>
    <inlineHelpText>If this case is from web or email, then this is the subject line</inlineHelpText>
    <label>Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>What general category of case is this?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Problem</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Testing</fullName>
            </value>
            <value>
                <fullName>Complaint</fullName>
            </value>
            <value>
                <fullName>Comments/Feedback</fullName>
            </value>
            <value>
                <fullName>Out of Office Reply</fullName>
            </value>
            <value>
                <fullName>Outside of Service Territory (TNMP)</fullName>
            </value>
            <value>
                <fullName>Password Related</fullName>
            </value>
            <value>
                <fullName>Address Matching</fullName>
            </value>
            <value>
                <fullName>Not Actionable (No Survey)</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Outside of Service Territory (Entergy)</fullName>
            </value>
            <value>
                <fullName>Outside of Service Territory (AEP)</fullName>
            </value>
            <value>
                <fullName>Outside of Service Territory (Oncor)</fullName>
            </value>
            <value>
                <fullName>Clawback</fullName>
            </value>
            <value>
                <fullName>Inadvertent Switch</fullName>
            </value>
            <value>
                <fullName>Cancellation</fullName>
            </value>
            <value>
                <fullName>TrueCost Invoice</fullName>
            </value>
            <value>
                <fullName>Order API Error</fullName>
            </value>
            <value>
                <fullName>Gas Choice File</fullName>
            </value>
            <value>
                <fullName>Utility</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
            <value>
                <fullName>Data</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
            <value>
                <fullName>Enhancement</fullName>
            </value>
            <value>
                <fullName>Bug/Fix</fullName>
            </value>
            <value>
                <fullName>CMS/CCOM Request</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TrueCost_Case__c/fields/Wants_Contact__c.field-meta.xml
<CustomField>
    <fullName>Wants_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The customer wants us to contact him/her about this case</description>
    <inlineHelpText>Only applies to cases from the web form.</inlineHelpText>
    <label>Wants Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestCreateTrueCostCaseFromRegularCase.cls
/*
2/10/2012	Shane McLaughlin	Deprecated (now use EmailToTrueCostCaes Service)
*/
@isTest
private class TestCreateTrueCostCaseFromRegularCase {
/*
    static testMethod void myUnitTest() {
        Case C = new Case(); //declare a case variable that we'll insert
        TrueCost_Case__c TCC = new TrueCost_Case__c(); //declare the one we hope the trigger will create
        system.debug('Entering Data in Test Case');
          C.Entity_Type__c = 'Customer';
          C.Subject = 'Dummy Subject';
          C.Current_REP__c = 'Dummy REP1';
          C.Description = 'Blah Blah Blah Blah';
          C.SuppliedEmail = 'testemail@testemaildomain.com';
          C.SuppliedPhone = '7132076453';
          C.SuppliedName = 'Dummy Testname';
          C.Permission_to_use_comments_in_marketing__c=True;
          C.Wants_Contact__c=True;
          C.Order_Number__c = 123456789;
          C.Order_Failure_Reason__c = 'Fraud';
          C.Origin = 'Email';
          C.Priority = 'Low';
          C.Reason = 'Dummy Reason';
          C.REP_for_Switch__c = 'Reliant';
          C.Type = 'Problem';
          C.Status ='New';
             system.debug('Test case data entered');
             system.debug('Creating Test Account');
          Account TestAccount = New Account();
          //TestAccount.Personemail = 'mclaughlin_shane@hotmail.com';
          TestAccount.email__c = 'testemail@testemaildomain.com';
          //TestAccount.Personemail = 'testemail@testemaildomain.com';
          TestAccount.Name = 'Shane McLaughlin';   
          TestAccount.RecordTypeId = '01230000000njET';
          insert TestAccount;
             system.debug('Test account created');   
             system.debug('Creating test lead');   
          Lead TestLead= New Lead();
          TestLead.email = 'testemail@testemaildomain.com';
          TestLead.LastName = 'McLaughlin';
          insert TestLead;    
             system.debug('Test lead created');
                       
       test.startTest();  
          system.debug('Starting Test');
          //next, let's create the case  
          upsert C;  //the trigger should have fired by now
          test.stopTest();
          system.debug('Test complete');
          //Get the new TrueCost Case we just created
          TCC = [select id, Account__c, Lead__c, Entity_Type__c, Subject__c, Current_REP__c, Non_Account_Email__c, 
          Non_Account_Phone__c, Caller_Name__c, Order_Number__c, Order_Failure_Reason__c, Origin__c, Priority__c, Reason__c,
          REP_for_Switch__c, Type__c, Status__c, Wants_Contact__c, Permission_to_use_comments_in_marketing__c
          from TrueCost_Case__c where Order_Number__c = 123456789];
          system.debug('Ran query for New TrueCost Case, starting assertions');
//verify that all the fields got copied
          System.assertEquals(TCC.Entity_Type__c, C.Entity_Type__c);
          System.assertEquals(TCC.Subject__c, C.Subject);
          System.assertEquals(TCC.Current_REP__c, C.Current_REP__c);
          //System.assertEquals(TCC.Description__c = C.Description);
          System.assertEquals(TCC.Non_Account_Email__c, C.SuppliedEmail);
          System.assertEquals(TCC.Non_Account_Phone__c, C.SuppliedPhone);
          System.assertEquals(TCC.Caller_Name__c , C.SuppliedName);
          System.assertEquals(TCC.Order_Number__c ,C.Order_Number__c);
          System.assertEquals(TCC.Order_Failure_Reason__c, C.Order_Failure_Reason__c);
          System.assertEquals(TCC.Origin__c, C.Origin);
          System.assertEquals(TCC.Priority__c , C.Priority);
          System.assertEquals(TCC.Reason__c ,C.Reason);
          System.assertEquals(TCC.REP_for_Switch__c ,C.REP_for_Switch__c);
          System.assertEquals(TCC.Type__c, C.Type);
          System.assertEquals(TCC.Status__c, C.Status);
          System.assertEquals(TCC.Permission_to_use_comments_in_marketing__c, C.Permission_to_use_comments_in_marketing__c);
          System.assertEquals(TCC.Wants_Contact__c, C.Wants_Contact__c);
          system.debug('Assertions complete on data');
//test the account append
          List<Account> TestAccount2 = New List <Account> ();
          TestAccount2 = [select id from Account where email__c = 'testemail@testemaildomain.com' or personEmail = 'testemail@testemaildomain.com'];
          system.assertEquals(TCC.Account__c, TestAccount2[0].id);
          system.debug('Asserted Account');
//test the lead append
          List<Lead> TestLead2 = New List<Lead>();
          TestLead2 = [select id from Lead where email = 'testemail@testemaildomain.com'];
          system.assertEquals(TCC.Lead__c, TestLead2[0].id);
          system.debug('Asserted Lead');
                
}*/
}