force-app/main/default/objects/CSR_Transaction__c/CSR_Transaction__c.object-meta.xml
<CustomObject>
    <label>CSR Transaction</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>CSR Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CSR Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CSR_Transaction__c/fields/CSR__c.field-meta.xml
<CustomField>
    <fullName>CSR__c</fullName>
    <label>CSR</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CSR_Transaction__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <description>How did the interaction end?</description>
    <inlineHelpText>How did the interaction end?</inlineHelpText>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone Transfer</fullName>
            </value>
            <value>
                <fullName>Decline</fullName>
            </value>
            <value>
                <fullName>Invalid Zip Code</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CSR_Transaction__c/fields/Start__c.field-meta.xml
<CustomField>
    <fullName>Start__c</fullName>
    <description>When did the CSR begin talking to customer about TrueCost</description>
    <inlineHelpText>When did the CSR begin talking to customer about TrueCost</inlineHelpText>
    <label>Start</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/CSR_Transaction__c/fields/Stop__c.field-meta.xml
<CustomField>
    <fullName>Stop__c</fullName>
    <description>When did the CSR finish talking about TrueCost</description>
    <inlineHelpText>When did the CSR finish talking about TrueCost</inlineHelpText>
    <label>Stop</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/CSW2Lead.cls
public with sharing class CSW2Lead {
    public CSR_Transaction__c CSRT;
    
    public void setStart(){
       CSRT=new CSR_Transaction__c();
       CSRT.Start__c=System.Now();
       }
     
    public lead l {get; set;}
    public CSW2Lead(){
        l=new Lead();
        }
    public list<Lead> Existing = new list<lead>();
    public PageReference email() {
            CSRT.Stop__c=System.Now();
            CSRT.Outcome__c='Email';
           //CSRT.CSR__c=l.CSR_Name__c;
            l.LastName='None';
            //l.SFGA__Web_Source__c='Customer Service W2L';
            insert l;
            insert CSRT;
            PageReference acctPage = Page.CustomerServiceZipCodeCheck;
            acctPage.setRedirect(true);
            return acctPage;
        }
     public PageReference call() {
            CSRT.Stop__c=System.Now();
            CSRT.Outcome__c='Phone Transfer';
            //CSRT.CSR__c=l.CSR_Name__c;
            l.LastName='None';
            //l.SFGA__Web_Source__c='Customer Service W2L';
            insert l;
            insert CSRT;
            PageReference acctPage = Page.CustomerServiceZipCodeCheck;
            acctPage.setRedirect(true);
            return acctPage;
        }
     public PageReference decline() {
            CSRT.Stop__c=System.Now();
            CSRT.Outcome__c='Decline';
            //CSRT.CSR__c=l.CSR_Name__c;
            insert CSRT;
            PageReference acctPage = Page.CustomerServiceZipCodeCheck;
            acctPage.setRedirect(true);
            return acctPage;
     }
}