force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Cancellation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee__c</fullName>
    <description>What is the fee if the customer cancels the plan before the contract expires?</description>
    <inlineHelpText>What is the fee if the customer cancels the plan before the contract expires?</inlineHelpText>
    <label>Cancellation Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Cancellation_Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee_Type__c</fullName>
    <label>Cancellation Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Prorated by remaining months</fullName>
            </value>
            <value>
                <fullName>Per remaining month</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Alternate_Payment_Surcharge__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Payment_Surcharge__c</fullName>
    <description>Fee for Corporate/Business credit card payment.</description>
    <inlineHelpText>Fee for Corporate/Business credit card payment.</inlineHelpText>
    <label>Alternate Payment Surcharge</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Cancellation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee__c</fullName>
    <label>Cancellation Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Cancellation_Fee_Description__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee_Description__c</fullName>
    <description>How is the cancellation fee calculated?</description>
    <inlineHelpText>How is the cancellation fee calculated?</inlineHelpText>
    <label>Cancellation Fee Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Cancellation_Fee_Type__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee_Type__c</fullName>
    <label>Cancellation Fee Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fixed</fullName>
                <default>true</default>
                <label>Fixed</label>
            </value>
            <value>
                <fullName>Flat Fee X Remaining Months</fullName>
            </value>
            <value>
                <fullName>Calculated Estimate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Changed_Start_Date_Fee__c.field-meta.xml
<CustomField>
    <fullName>Changed_Start_Date_Fee__c</fullName>
    <description>Fee for each start date change.</description>
    <inlineHelpText>Fee for each start date change.</inlineHelpText>
    <label>Changed Start Date Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Disconnect_Fee__c.field-meta.xml
<CustomField>
    <fullName>Disconnect_Fee__c</fullName>
    <description>REP assessed standard disconnection processing fee</description>
    <inlineHelpText>REP assessed standard disconnection processing fee</inlineHelpText>
    <label>Disconnect Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Excessive_Payments_Fee__c.field-meta.xml
<CustomField>
    <fullName>Excessive_Payments_Fee__c</fullName>
    <description>Fee for more than 5 bill payments per month.</description>
    <inlineHelpText>Fee for more than 5 bill payments per month.</inlineHelpText>
    <label>Excessive Payments Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Insufficient_Funds_Cancelled_Checks__c.field-meta.xml
<CustomField>
    <fullName>Insufficient_Funds_Cancelled_Checks__c</fullName>
    <description>Fee for returned or cancelled checks due to unsuccessful payment</description>
    <inlineHelpText>Fee for returned or cancelled checks due to unsuccessful payment</inlineHelpText>
    <label>Insufficient Funds/Cancelled Checks</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Late_Payment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Late_Payment_Fee__c</fullName>
    <defaultValue>&quot;5%&quot;</defaultValue>
    <description>Fee for late bill payment, charged as a % of past due amounts.</description>
    <inlineHelpText>Fee for late bill payment, charged as a % of past due amounts.</inlineHelpText>
    <label>Late Payment Fee</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Manual_Assistance_Fee__c.field-meta.xml
<CustomField>
    <fullName>Manual_Assistance_Fee__c</fullName>
    <description>Fee for live billing/payment assistance</description>
    <inlineHelpText>Fee for live billing/payment assistance</inlineHelpText>
    <label>Manual Assistance Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge2__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge2__c</fullName>
    <label>Minimum Usage Charge 2</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge3__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge3__c</fullName>
    <label>Minimum Usage Charge 3</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge__c</fullName>
    <description>Minimum usage customer charge</description>
    <inlineHelpText>Minimum usage customer charge</inlineHelpText>
    <label>Minimum Usage Charge</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge_Threshold2__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge_Threshold2__c</fullName>
    <label>Minimum Usage Charge Threshold 2 (kWh)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge_Threshold3__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge_Threshold3__c</fullName>
    <label>Minimum Usage Charge Threshold 3 (kWh)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Usage_Charge_Threshold_kWh__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Usage_Charge_Threshold_kWh__c</fullName>
    <description>How many kWh does a customer need to use to avoid the Minimum Usage Charge?</description>
    <inlineHelpText>How many kWh does a customer need to use to avoid the Minimum Usage Charge?</inlineHelpText>
    <label>Minimum Usage Charge Threshold (kWh)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Monthly_Base_Charge__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Base_Charge__c</fullName>
    <description>Monthly fixed base customer charge (charged regardless of kWh usage)</description>
    <inlineHelpText>Monthly fixed base customer charge (charged regardless of kWh usage)</inlineHelpText>
    <label>Monthly Base Charge</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Move_in_Fee__c.field-meta.xml
<CustomField>
    <fullName>Move_in_Fee__c</fullName>
    <description>Standard (not priority) move in fee</description>
    <inlineHelpText>Standard (not priority) move in fee</inlineHelpText>
    <label>Move-in Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Paper_Bill_Request_Fee__c.field-meta.xml
<CustomField>
    <fullName>Paper_Bill_Request_Fee__c</fullName>
    <description>Fee for physical paper bill issuance</description>
    <inlineHelpText>Fee for physical paper bill issuance</inlineHelpText>
    <label>Paper Bill Request Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Reconnect_Fee__c.field-meta.xml
<CustomField>
    <fullName>Reconnect_Fee__c</fullName>
    <description>REP processing Fee to reconnect a customer who had been previously disconnected by the REP</description>
    <inlineHelpText>REP processing Fee to reconnect a customer who had been previously disconnected by the REP</inlineHelpText>
    <label>Reconnect Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Reminder_Fee__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Fee__c</fullName>
    <description>Fee for reminder of past-due bill</description>
    <inlineHelpText>Fee for reminder of past-due bill</inlineHelpText>
    <label>Reminder Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Same_Day_Move_In_Fee__c.field-meta.xml
<CustomField>
    <fullName>Same_Day_Move_In_Fee__c</fullName>
    <description>Fee for same day move-ins.</description>
    <inlineHelpText>Fee for same day move-ins.</inlineHelpText>
    <label>Same-Day Move-In Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Self_Selected_Switch_Fee__c.field-meta.xml
<CustomField>
    <fullName>Self_Selected_Switch_Fee__c</fullName>
    <description>Fee for customers selecting a specific date for their switch.</description>
    <inlineHelpText>Fee for customers selecting a specific date for their switch.</inlineHelpText>
    <label>Self-Selected Switch Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Standard_Move_In_for_New_Meters__c.field-meta.xml
<CustomField>
    <fullName>Standard_Move_In_for_New_Meters__c</fullName>
    <description>Move-in fee if a new meter is installed</description>
    <inlineHelpText>Move-in fee if a new meter is installed</inlineHelpText>
    <label>Standard Move-In for New Meters</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Third_Party_Payment_Fee__c.field-meta.xml
<CustomField>
    <fullName>Third_Party_Payment_Fee__c</fullName>
    <description>Fee for bill payment issued through a third-party/pay station</description>
    <inlineHelpText>Fee for bill payment issued through a third-party/pay station</inlineHelpText>
    <label>Third-Party Payment Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Usage_Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Usage_Discount_Amount__c</fullName>
    <label>Usage Discount Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Usage_Discount_Minimum__c.field-meta.xml
<CustomField>
    <fullName>Usage_Discount_Minimum__c</fullName>
    <label>Usage Discount Minimum</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Zero_Usage_Fee__c.field-meta.xml
<CustomField>
    <fullName>Zero_Usage_Fee__c</fullName>
    <description>Fee for zero usage per month per meter.</description>
    <inlineHelpText>Fee for zero usage per month per meter.</inlineHelpText>
    <label>Zero Usage Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ControllerForFeeDisplay.cls
public class ControllerForFeeDisplay {
    public id therateid {get;set;}
    
    public rate__c getthefees(){
        list<rate__c> theratelist = new list<rate__C>();
        theratelist = [select id, plan__r.REP_Profile__r.name, 
                            cancellation_fee__c, Cancellation_Fee_Type__c, Cancellation_Fee_Description__c,
                       		
                            Alternate_Payment_Surcharge__c, 
                            Changed_Start_Date_Fee__c, Same_Day_Move_In_Fee__c, Move_in_Fee__c,
                            Disconnect_Fee__c, Reconnect_Fee__c, Excessive_Payments_Fee__c, 
                            Late_Payment_Fee__c, 
                            Standard_Move_In_for_New_Meters__c, 
                            Insufficient_Funds_Cancelled_Checks__c,  Reminder_Fee__c,
                            Manual_Assistance_Fee__c, Paper_Bill_Request_Fee__c, Third_Party_Payment_Fee__c, Self_Selected_Switch_Fee__c,
                       		Minimum_Usage_Charge__c, Minimum_Usage_Charge_Threshold_kWh__c,
                            Minimum_Usage_Charge2__c, Minimum_Usage_Charge_Threshold2__c,
                            Minimum_Usage_Charge3__c, Minimum_Usage_Charge_Threshold3__c,
                            Usage_Discount_Amount__c, Usage_Discount_Minimum__c,
                       	    Monthly_Base_Charge__c, Zero_Usage_Fee__c
                            from rate__c where id =: therateid];
        return theratelist[0];
    }
    
    
    
}