force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the plan currently active?</description>
    <inlineHelpText>Is the plan currently active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_End_Date__c</fullName>
    <description>When should the plan not be displayed or available to customers?</description>
    <inlineHelpText>When should the plan not be displayed or available to customers?</inlineHelpText>
    <label>Plan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>When should the plan be displayed and available to customers?</description>
    <inlineHelpText>When should the plan be displayed and available to customers?</inlineHelpText>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Rate_Class_del__c.field-meta.xml
<CustomField>
    <fullName>Rate_Class_del__c</fullName>
    <description>What rate class is this plan available for?</description>
    <inlineHelpText>What rate class is this plan available for?</inlineHelpText>
    <label>Rate Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
                <default>true</default>
                <label>Residential</label>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Suspended__c.field-meta.xml
<CustomField>
    <fullName>Suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this rate currently active?</description>
    <inlineHelpText>Is this rate currently active?</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Suspended__c.field-meta.xml
<CustomField>
    <fullName>Suspended__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this plan is not visible due to incorrect information, or it has not yet been approved by an administrator since its creation.</description>
    <inlineHelpText>If checked, this plan is not visible due to incorrect information, or it has not yet been approved by an administrator since its creation.</inlineHelpText>
    <label>Suspended</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <description>Shows the fields relevant to residential rates.</description>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/About_Us__c.field-meta.xml
<CustomField>
    <fullName>About_Us__c</fullName>
    <description>This information will be shown to customers who want to know more about your REP</description>
    <inlineHelpText>This information will be shown to customers who want to know more about your REP</inlineHelpText>
    <label>About Us</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this REP profile active?</description>
    <inlineHelpText>Is this REP profile active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Customer_Service_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone_Number__c</fullName>
    <description>What number should TrueCost customers use to contact you about their account?</description>
    <inlineHelpText>What number should TrueCost customers use to contact you about their account?</inlineHelpText>
    <label>Customer Service Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Friendly_URL__c.field-meta.xml
<CustomField>
    <fullName>Friendly_URL__c</fullName>
    <description>Used internally for TrueCost URLrewriter class.  Put in all lowercase with hyphens for spaces.  For example: friendly-name or reliant-energy etc.</description>
    <inlineHelpText>Used internally for TrueCost URLrewriter class.  Put in all lowercase with hyphens for spaces.  For example: friendly-name or reliant-energy etc.</inlineHelpText>
    <label>Friendly URL</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Full legal name of REP</description>
    <inlineHelpText>Full legal name of REP</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Logo_URL__c.field-meta.xml
<CustomField>
    <fullName>Logo_URL__c</fullName>
    <description>Where the REPs logo is located.  Optimal logo size is 150 X 75 pixels.</description>
    <inlineHelpText>Where the REPs logo is located.  Optimal logo size is 150 X 75 pixels.</inlineHelpText>
    <label>Logo URL (Size 150 X 75px)</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TX</fullName>
                <default>true</default>
                <label>TX</label>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/PUCT_License_Number__c.field-meta.xml
<CustomField>
    <fullName>PUCT_License_Number__c</fullName>
    <description>PUCT License Number</description>
    <inlineHelpText>PUCT License Number (5 digits with no # sign)</inlineHelpText>
    <label>PUCT License Number</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Snapshot_ID__c.field-meta.xml
<CustomField>
    <fullName>Snapshot_ID__c</fullName>
    <description>Salesforce ID for the blog post that is the retailer snapshot for this REP profile.</description>
    <inlineHelpText>Salesforce ID for the blog post that is the retailer snapshot for this REP profile.</inlineHelpText>
    <label>Snapshot ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Star_Rating_Avg__c.field-meta.xml
<CustomField>
    <fullName>Star_Rating_Avg__c</fullName>
    <description>What is your average customer approval?  A higher percentage means a higher customer approval.</description>
    <inlineHelpText>What is your average customer approval?  A higher percentage means a higher customer approval.</inlineHelpText>
    <label>Star Rating Avg</label>
    <precision>4</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/total_reviews__c.field-meta.xml
<CustomField>
    <fullName>total_reviews__c</fullName>
    <description>how many reviews this REP has</description>
    <inlineHelpText>how many reviews this REP has</inlineHelpText>
    <label>total reviews</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>5</defaultValue>
    <inlineHelpText>Customer rating (1=low, 5=high)</inlineHelpText>
    <label>Rating</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Which REP is this review about?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Review__c.field-meta.xml
<CustomField>
    <fullName>Review__c</fullName>
    <label>Review</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ControllerforReadReviews.cls
public with sharing class ControllerforReadReviews {
        
    public rep_profile__c therep{get;set;}
    public list<TrueCostUtilities.ratingwrapper> thelist{get;set;}
    
    public list<TrueCostUtilities.ratingwrapper> getratings(){        
        thelist=TrueCostUtilities.getRatingWrapperForREP(ApexPages.currentPage().getParameters().get('Id'));
        if (ApexPages.currentPage().getParameters().get('Id')==null) thelist=TrueCostUtilities.getRatingWrapperForREP();
        return thelist;
    }
    
    public list<rep_profile__c> getRepList(){
        return ControllerForElectricCompanies.getreplist();
    }
    
    public integer getRepPlanCount(){
        return [select id from rate__c where
                active__c = true AND plan__r.active__c = true AND suspended__c = false AND plan__r.suspended__c = false and plan__r.rep_profile__r.active__c =: true
                           AND plan__r.plan_start_date__c <= today AND plan__r.plan_end_date__c >today 
                           and plan__r.rate_class_del__c =: 'Residential'  //and the rate class matches                
                and plan__r.rep_profile__r.id =:ApexPages.currentPage().getParameters().get('Id')].size();
    }
        
    public rep_profile__c getrep(){
        therep=[select id, createdby.firstname, name, about_us__c, star_rating_avg__c, total_reviews__c, logo_url__c, 
        Legal_Name__c, PUCT_License_Number__c, Customer_Service_Phone_Number__c, Mailing_Street_Address__c,
        snapshot_id__c, Friendly_URL__c, Mailing_City__c, Mailing_State__c, Mailing_Zip__c
                from rep_profile__c where id =: ApexPages.currentPage().getParameters().get('Id') limit 1];
        return therep;
    }
    
    public list<rate__c> getRates(){
        list<rate__C> theRates = [select id, plan__r.name from rate__c 
                                  where plan__r.rep_profile__r.id =: ApexPages.currentPage().getParameters().get('Id') 
                                  and active__c = true AND plan__r.active__c = true AND suspended__c = false 
                                  AND plan__r.suspended__c = false AND plan__r.plan_start_date__c <= today AND plan__r.plan_end_date__c >today ];
        return theRates;
    }

    //pass it a rep id
    public static rep_rating__c getRandomReview(string repid){

        if (repid==null) {return getRandomReview();}
        
        list<rep_rating__c> repratinglist =[select id, rating__c, REP_Profile__r.name, Review__c, REP_Profile__r.logo_url__c, createddate, 
        author__r.firstname, Plan__r.name, Site_Comments__c ,REP_Profile__c
        from rep_rating__c where rep_profile__r.id =:repid and published__c=true];   
        
        return PickOneAtRandom(repratinglist);
    }

    //has no rep id
    public static rep_rating__c getRandomReview(){
        list<rep_rating__c> repratinglist =[select id, rating__c, REP_Profile__r.name, Review__c, REP_Profile__r.logo_url__c, createddate, 
        author__r.firstname, Plan__r.name, Site_Comments__c,REP_Profile__c
        from rep_rating__c where published__c=true and REP_Profile__r.active__c=true];   

        return PickOneAtRandom(repratinglist);
    }

    public static rep_rating__c PickOneAtRandom(list<rep_rating__c> incoming){
        integer itemcount = incoming.size();
        system.debug(itemcount);  
        integer whichOne;

        do {             
            whichOne = math.min(itemcount-1, math.round((math.random()*itemcount)));
        } while (incoming[whichOne].Review__c==null);       

        return incoming[whichOne];
    }

 }