force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>In months, how long is the contract?</description>
    <inlineHelpText>In months, how long is the contract?</inlineHelpText>
    <label>Contract Length (# of months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_End_Date__c</fullName>
    <description>When should the plan not be displayed or available to customers?</description>
    <inlineHelpText>When should the plan not be displayed or available to customers?</inlineHelpText>
    <label>Plan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <description>Code used by the REP to refer to this plan</description>
    <inlineHelpText>Code used by the REP to refer to this plan</inlineHelpText>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>When should the plan be displayed and available to customers?</description>
    <inlineHelpText>When should the plan be displayed and available to customers?</inlineHelpText>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Renewable_Content__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Content__c</fullName>
    <description>What percent of the electricity comes from renewable sources?</description>
    <inlineHelpText>What percent of the electricity comes from renewable sources?</inlineHelpText>
    <label>Renewable Content (in %)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Business_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Start_Date__c</fullName>
    <description>When did you start serving the Texas retail electric market?</description>
    <inlineHelpText>When did you start serving the Texas retail electric market?</inlineHelpText>
    <label>Business Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Customer_Service_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone_Number__c</fullName>
    <description>What number should TrueCost customers use to contact you about their account?</description>
    <inlineHelpText>What number should TrueCost customers use to contact you about their account?</inlineHelpText>
    <label>Customer Service Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>Fax_Number__c</fullName>
    <description>REP primary fax number</description>
    <label>Fax Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Home_Page__c.field-meta.xml
<CustomField>
    <fullName>Home_Page__c</fullName>
    <description>Enter in the url for your home page.</description>
    <inlineHelpText>Enter in the url for your home page.</inlineHelpText>
    <label>Home Page</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Full legal name of REP</description>
    <inlineHelpText>Full legal name of REP</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Author__c.field-meta.xml
<CustomField>
    <fullName>Author__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who wrote this review</description>
    <inlineHelpText>Who wrote this review</inlineHelpText>
    <label>Author</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This review can be shown on the site</description>
    <inlineHelpText>This review can be shown on the site</inlineHelpText>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Which REP is this review about?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestCreateTrueCostLogoUpdate.cls
@isTest(seeAllData=true)

public class TestCreateTrueCostLogoUpdate {

static testMethod void myUnitTest() {
makeREP();


 


list<REP_Profile__c> ids=new list<REP_Profile__c> ();
        ids= [select id from rep_profile__C where Name=:'Atom Energy' limit 1];

rep_rating__C reprating = new rep_rating__C();
reprating.REP_Profile__c=ids[0].id;


account acct= new account();
acct.lastname='Benavidez';
insert acct;
list<account> acctlist=new list<account> ();
acctlist=[select id from account where lastname='Benavidez' limit 1];
reprating.author__C= acctlist[0].id;
reprating.published__c=true;
insert reprating;

makePlan();
}

//test helper classes
    static void makeREP(){
        rep_profile__C rp= new rep_profile__C();
        rp.Name='Atom Energy';
        rp.Legal_Name__c='Acme Company DBA Atom Energy';
         rp.Business_Start_Date__c=system.today();
        rp.Mailing_Street_Address__c='1234 Anywhere Ave';
        rp.Mailing_City__c='Anytown';
        rp.Mailing_Zip__c='77123';
        rp.Customer_Service_Phone_Number__c='(832) 594-0111';
        rp.Fax_Number__c='(832) 594-0123';
        rp.Home_Page__c='http://www.centerpointenergy.com';
        insert rp;
        
        attachment A= new attachment ();  //test the logo attachment trigger
        list<REP_Profile__c> ids=new list<REP_Profile__c> ();
        ids= [select id from rep_profile__C where Name=:'Atom Energy' limit 1];
        a.parentid=ids[0].id;
        a.name='testlogo';
        a.body=blob.valueof('x');
        insert a;
    }
    
    static void makePlan(){
        list<REP_Profile__c> ids=new list<REP_Profile__c> ();
        ids= [select id from rep_profile__C where Name=:'Atom Energy' limit 1];
        plan__c p = new plan__c();
        p.name='stupid plan name';
        p.recordtypeid=[select id from recordtype where name='Electric Plan'].id;
        p.renewable_content__c=100;
        p.Contract_Length__c=12;
        p.Plan_ID__c='x';
        p.REP_Profile__c=ids[0].id;
        p.Plan_Start_Date__c=System.today();
        p.Plan_End_Date__c=System.today()+365;
    insert p;
    }

}