force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <description>The three programs in NE/WY Choice</description>
    <inlineHelpText>The three programs in NE/WY Choice</inlineHelpText>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ag</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Wyoming</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RateRewardAssociation__c/RateRewardAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Rate and Rewards.</description>
    <label>Reward For This Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RateRewardAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateRewardAssociation__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The rate that the reward is linked to.</description>
    <inlineHelpText>The rate that the reward is linked to.</inlineHelpText>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipName>RateRewardAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/RateRewardAssociation__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The reward that is linked to the rate.</description>
    <inlineHelpText>The reward that is linked to the rate.</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Rewards__c</referenceTo>
    <relationshipName>RateRewardAssociations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rewards__c/Rewards__c.object-meta.xml
<CustomObject>
    <description>Customer incentives and rewards.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rewards__c/fields/Applies_to_All_Plans__c.field-meta.xml
<CustomField>
    <fullName>Applies_to_All_Plans__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This reward/program applies to every plan/rate listed by this REP Profile on TrueCost</description>
    <inlineHelpText>This reward/program applies to every plan/rate listed by this REP Profile on TrueCost</inlineHelpText>
    <label>Applies to All Plans</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Choice__c.field-meta.xml
<CustomField>
    <fullName>Choice__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this reward is a customer choice, and is part of a larger program.</description>
    <inlineHelpText>Check this box if this reward is a customer choice, and is part of a larger program.</inlineHelpText>
    <label>Choice</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/New_Customer_Only__c.field-meta.xml
<CustomField>
    <fullName>New_Customer_Only__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if the reward/incentive is only available for NEW customers.</description>
    <inlineHelpText>Check this box if the reward/incentive is only available for NEW customers.</inlineHelpText>
    <label>New Customer Only</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Percentage_Value__c.field-meta.xml
<CustomField>
    <fullName>Percentage_Value__c</fullName>
    <description>What percentage cash-back is offered by this reward?  Only required for % Cash Back reward type.</description>
    <inlineHelpText>What percentage cash-back is offered by this reward?  Only required for % Cash Back reward type.</inlineHelpText>
    <label>% Value</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this reward is a Program type offer where you will assign multiple choices that a customer will have for selecting rewards or incentives.</description>
    <inlineHelpText>Check this box if this reward is a Program type offer where you will assign multiple choices that a customer will have for selecting rewards or incentives.</inlineHelpText>
    <label>Program</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <description>The REP that offers this reward or incentive.</description>
    <inlineHelpText>The REP that offers this reward or incentive.</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Description__c.field-meta.xml
<CustomField>
    <fullName>Reward_Description__c</fullName>
    <description>List any details for the reward or incentive here.</description>
    <inlineHelpText>List any details for the reward or incentive here.</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_End_Date__c</fullName>
    <description>When does this offer become unavailable?</description>
    <inlineHelpText>When does this offer become unavailable?</inlineHelpText>
    <label>Reward End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Program__c.field-meta.xml
<CustomField>
    <fullName>Reward_Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What program is this reward choice a part of?  Please create reward programs before creating choices.</description>
    <inlineHelpText>What program is this reward choice a part of?  Please create reward programs before creating choices.</inlineHelpText>
    <label>Reward Program</label>
    <referenceTo>Rewards__c</referenceTo>
    <relationshipLabel>Reward Program Choices</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_Start_Date__c</fullName>
    <description>What is the soonest date that this offer is available?</description>
    <inlineHelpText>What is the soonest date that this offer is available?</inlineHelpText>
    <label>Reward Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Value__c.field-meta.xml
<CustomField>
    <fullName>Reward_Value__c</fullName>
    <description>What is the $ value of this reward or incentive?  This does not apply to Airline Miles or Hotel Points.</description>
    <inlineHelpText>What is the $ value of this reward or incentive?  This does not apply to Airline Miles or Hotel Points.</inlineHelpText>
    <label>$ Value</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Time_from_start_of_contract_in_months__c.field-meta.xml
<CustomField>
    <fullName>Time_from_start_of_contract_in_months__c</fullName>
    <description>How many months from when the contract starts is the customer able to receive this reward or incentive?</description>
    <inlineHelpText>How many months from when the contract starts is the customer able to receive this reward or incentive?</inlineHelpText>
    <label>Time from start of contract (in months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ControllerForCustomerRewardsView.cls
public with sharing class ControllerForCustomerRewardsView {
	public id therateid {get;set;}
	public Rate__c rate {get;set;}
	public id program {get;set;}
	
	public 	ControllerForCustomerRewardsView(){
	}
	
	public list<rewards__c> getTheRewards(){
		//first get the REP offering the rate in the URL parameter.  We'll check for universal plans
		list<rewards__c> rewardlist = new list<rewards__c>();
		try{
			rate = [select id, plan__r.REP_Profile__r.id from Rate__c where id=:therateid]; //match the rate with an REP and get its ID
		} catch(exception e){return rewardlist;}
				
		list<RateRewardAssociation__c> RRAlist = [select id, reward__r.program__c, rate__r.plan__r.REP_Profile__r.id, reward__r.id from RateRewardAssociation__c 
			where rate__r.id=:therateid];
		list<id> rewardIDlist = new list<id>();
		for (RateRewardAssociation__c RRA:RRAlist){
			rewardIDlist.add(RRA.reward__r.id);
		}
				
		rewardlist=[select id, Choice__c, Program__c, name, Percentage_Value__c, Reward_Value__c, Reward_Program__c,reward_program__r.id,  Reward_Description__c, 
							Time_from_start_of_contract_in_months__c, New_Customer_Only__c 
							from rewards__c 
							where ((id in: rewardIDlist or reward_program__r.id in:rewardIDlist) or (Applies_to_all_plans__c=:true and rep_profile__r.id =: rate.plan__r.rep_profile__r.id)) and ((Reward_Start_Date__c<=:System.today() and Reward_End_Date__c>=:System.today()) or (Reward_Start_Date__c=:null and Reward_End_Date__c=:null))
							order by Program__c, Reward_Program__c, Time_from_start_of_contract_in_months__c ASC, choice__c
					];
		system.debug('==================rewardslist contains' + rewardlist);
		list<rewards__c> rewardlist2 = new list<rewards__c>();
		for (Rewards__c reward :rewardlist){
			if (reward.program__c){ //if it's a program
				rewardlist2.add(reward);//gather each program into your list	
				system.debug('==================added program' + reward.name);
				for (Rewards__c subreward :rewardlist){ //look through all the rewards again
					system.debug('====================checking reward + subreward' + subreward.name);
					if (subreward.Reward_Program__r.id == reward.id){ //find all the rewards that are part of that program
						rewardlist2.add(subreward); // add them so that the display order to the customer makes sense
						system.debug('==================added subreward + subreward.name');
					} 	else {system.debug('==================did not add subreward + subreward.name');}
				}
			}		  
		}
		for (Rewards__c reward:rewardlist){ //now grab the rewars taht are not part of a program and list them.
                    if (!reward.program__c && reward.reward_Program__c ==null){
                        rewardlist2.add(reward);
                    }
                        
                }
		
		return rewardlist2;
	}
	
	
}