force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is the plan currently active?</description>
    <inlineHelpText>Is the plan currently active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Cancellation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee__c</fullName>
    <description>What is the fee if the customer cancels the plan before the contract expires?</description>
    <inlineHelpText>What is the fee if the customer cancels the plan before the contract expires?</inlineHelpText>
    <label>Cancellation Fee</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>In months, how long is the contract?</description>
    <inlineHelpText>In months, how long is the contract?</inlineHelpText>
    <label>Contract Length (# of months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_End_Date__c</fullName>
    <description>When should the plan not be displayed or available to customers?</description>
    <inlineHelpText>When should the plan not be displayed or available to customers?</inlineHelpText>
    <label>Plan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <description>Code used by the REP to refer to this plan</description>
    <inlineHelpText>Code used by the REP to refer to this plan</inlineHelpText>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Start_Date__c</fullName>
    <description>When should the plan be displayed and available to customers?</description>
    <inlineHelpText>When should the plan be displayed and available to customers?</inlineHelpText>
    <label>Plan Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Renewable_Content__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Content__c</fullName>
    <description>What percent of the electricity comes from renewable sources?</description>
    <inlineHelpText>What percent of the electricity comes from renewable sources?</inlineHelpText>
    <label>Renewable Content (in %)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this rate currently active?</description>
    <inlineHelpText>Is this rate currently active?</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Cancellation_Fee__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Fee__c</fullName>
    <label>Cancellation Fee</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/EFL_Url__c.field-meta.xml
<CustomField>
    <fullName>EFL_Url__c</fullName>
    <description>Links to the EFL related to the Rate listed.</description>
    <inlineHelpText>Links to the EFL related to the Rate listed.</inlineHelpText>
    <label>EFL Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Energy_Base_Rate_cents__c.field-meta.xml
<CustomField>
    <fullName>Energy_Base_Rate_cents__c</fullName>
    <description>REP Base energy delivery price</description>
    <inlineHelpText>REP Base energy delivery price</inlineHelpText>
    <label>Energy Base Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/TOS_Url__c.field-meta.xml
<CustomField>
    <fullName>TOS_Url__c</fullName>
    <description>Links to the TOS related to the Rate listed.</description>
    <inlineHelpText>Links to the TOS related to the Rate listed.</inlineHelpText>
    <label>TOS Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/X1000_kWh_rate__c.field-meta.xml
<CustomField>
    <fullName>X1000_kWh_rate__c</fullName>
    <description>Average pricing in cents based on monthly usage of 1000 kWh</description>
    <inlineHelpText>Average pricing in cents based on monthly usage of 1000 kWh</inlineHelpText>
    <label>1000 kWh rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/X2000_kWh_rate_cents__c.field-meta.xml
<CustomField>
    <fullName>X2000_kWh_rate_cents__c</fullName>
    <description>Average pricing in cents based on monthly usage of 2000 kWh</description>
    <inlineHelpText>Average pricing in cents based on monthly usage of 2000 kWh</inlineHelpText>
    <label>2000 kWh rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/X500_kWh_rate_cents__c.field-meta.xml
<CustomField>
    <fullName>X500_kWh_rate_cents__c</fullName>
    <description>Average pricing in cents based on monthly usage of 500 kWh</description>
    <inlineHelpText>Average pricing in cents based on monthly usage of 500 kWh</inlineHelpText>
    <label>500 kWh rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/YRAC_Url__c.field-meta.xml
<CustomField>
    <fullName>YRAC_Url__c</fullName>
    <description>Links to the YRAC related to the Rate listed.</description>
    <inlineHelpText>Links to the YRAC related to the Rate listed.</inlineHelpText>
    <label>YRAC Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/RateRewardAssociation__c/RateRewardAssociation__c.object-meta.xml
<CustomObject>
    <description>This is a junction object to link Rate and Rewards.</description>
    <label>Reward For This Rate</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>RateRewardAssociation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RateRewardAssociation__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The rate that the reward is linked to.</description>
    <inlineHelpText>The rate that the reward is linked to.</inlineHelpText>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipName>RateRewardAssociations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this REP profile active?</description>
    <inlineHelpText>Is this REP profile active?</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Business_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Start_Date__c</fullName>
    <description>When did you start serving the Texas retail electric market?</description>
    <inlineHelpText>When did you start serving the Texas retail electric market?</inlineHelpText>
    <label>Business Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Customer_Service_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone_Number__c</fullName>
    <description>What number should TrueCost customers use to contact you about their account?</description>
    <inlineHelpText>What number should TrueCost customers use to contact you about their account?</inlineHelpText>
    <label>Customer Service Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Fax_Number__c.field-meta.xml
<CustomField>
    <fullName>Fax_Number__c</fullName>
    <description>REP primary fax number</description>
    <label>Fax Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Home_Page__c.field-meta.xml
<CustomField>
    <fullName>Home_Page__c</fullName>
    <description>Enter in the url for your home page.</description>
    <inlineHelpText>Enter in the url for your home page.</inlineHelpText>
    <label>Home Page</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Full legal name of REP</description>
    <inlineHelpText>Full legal name of REP</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/REP_Rating__c.object-meta.xml
<CustomObject>
    <label>REP Rating</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>REP Rating Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>REP Ratings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Rating__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/REP_Rating__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Which REP is this review about?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>REP Ratings</relationshipLabel>
    <relationshipName>REP_Ratings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rewards__c/Rewards__c.object-meta.xml
<CustomObject>
    <description>Customer incentives and rewards.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rewards__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <description>The REP that offers this reward or incentive.</description>
    <inlineHelpText>The REP that offers this reward or incentive.</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Rewards</relationshipLabel>
    <relationshipName>Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rewards__c/fields/Reward_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Reward_Start_Date__c</fullName>
    <description>What is the soonest date that this offer is available?</description>
    <inlineHelpText>What is the soonest date that this offer is available?</inlineHelpText>
    <label>Reward Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RewardList_Test.cls
@isTest
private class RewardList_Test{

    static testMethod void test(){
  
    //First create REP Profile
    REP_Profile__c prflObj=new REP_Profile__c();
    prflObj.Customer_Service_Phone_Number__c='123456789';
    prflObj.Business_Start_Date__c=System.today();
    prflObj.Fax_Number__c='123456';
    prflObj.Home_Page__c='www.google.com';
    prflObj.Legal_Name__c='Test REP Profile';
    prflObj.Mailing_City__c='NewYork';
    prflObj.Mailing_Street_Address__c='ABCDEF';
    prflObj.Mailing_Zip__c='78992';
    insert prflObj;
    
    //Create a Plan
    Plan__c planObj=new Plan__c();
    planObj.recordtypeid = [select id from recordtype where name='Electric Plan'].id;
    planObj.REP_Profile__c=prflObj.Id;
    planObj.Plan_ID__c='testplan';
    planObj.Plan_Start_Date__c=System.today();
    planObj.Plan_End_Date__c=System.today()+365;
    planObj.Contract_Length__c=3.3;
    planObj.Renewable_Content__c=25;
    insert planObj;
    
    
    //Create a Rate record
    Rate__c rtObj=new Rate__c();
    rtObj.Plan__c=planObj.Id;
    rtObj.Active__c=true;
    rtObj.EFL_Url__c='www.google.com';
    rtObj.Cancellation_Fee__c=35000;
    rtObj.Energy_Base_Rate_cents__c=2.2;
    rtObj.TOS_Url__c='www.google.com';
    rtObj.X1000_kWh_rate__c=10;
    rtObj.X2000_kWh_rate_cents__c=45.40;
    rtObj.X500_kWh_rate_cents__c=50;
    rtObj.YRAC_Url__c='www.google.com';
    insert rtObj;
    
    
    //Create a reward record
    Rewards__c rewardObj=new Rewards__c();
    rewardObj.Reward_Start_Date__c=System.today();
    rewardObj.Reward_End_Date__c=System.today()+365;
    rewardObj.Name='Test Reward';
    rewardObj.Reward_Type__c='Hotel Points';
    rewardObj.Reward_Value__c=100;
    rewardObj.REP_Profile__c=prflObj.Id;
    rewardObj.Reward_Description__c='test comments';
    insert rewardObj;
    
    //Create a rate-reward association record
    RateRewardAssociation__c associateObj=new RateRewardAssociation__c();
    associateObj.Rate__c=rtObj.Id;
    associateObj.Reward__c=rewardObj.Id;
    insert associateObj;
    
    
    PageReference pageRef=Page.REPRewardList;
    pageRef.getParameters().put('id',rtObj.Id);
    test.setCurrentPage(pageRef);
    
    RewardList rwListCls=new RewardList(new ApexPages.Standardcontroller(rtObj));
    rwListCls.GetRewards();
    rwListCls.selectedreward=rewardObj.Id;
    rwListCls.addReward();
    
    ControllerForCustomerRewardsView rewardViewCls=new ControllerForCustomerRewardsView();
    rewardViewCls.getTheRewards();
    /*REP_Rating__c repRtObj=new REP_Rating__c();
    repRtObj.REP_Profile__c=prflObj.Id;
    repRtObj.Review__c='test comments';
    insert repRtObj;
        
        //Insert a record for rate__c
        //rate__c rtObj=new rate__c();*/
        //hi
  
    }
}