force-app/main/default/objects/Annual_Usage__c/Annual_Usage__c.object-meta.xml
<CustomObject>
    <label>Annual Usage</label>
    <nameField>
        <displayFormat>Annual Usage-{0}</displayFormat>
        <label>Annual Usage Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Annual Usage</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Annual_Usage__c/fields/April__c.field-meta.xml
<CustomField>
    <fullName>April__c</fullName>
    <description>Monthly usage for April.</description>
    <inlineHelpText>Monthly usage for April.</inlineHelpText>
    <label>April</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/August__c.field-meta.xml
<CustomField>
    <fullName>August__c</fullName>
    <description>Monthly usage for August.</description>
    <inlineHelpText>Monthly usage for August.</inlineHelpText>
    <label>August</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/December__c.field-meta.xml
<CustomField>
    <fullName>December__c</fullName>
    <description>Monthly usage for December.</description>
    <inlineHelpText>Monthly usage for December.</inlineHelpText>
    <label>December</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/Estimated__c.field-meta.xml
<CustomField>
    <fullName>Estimated__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this usage an estimation?</description>
    <inlineHelpText>Is this usage an estimation?</inlineHelpText>
    <label>Estimated?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/February__c.field-meta.xml
<CustomField>
    <fullName>February__c</fullName>
    <description>Monthly usage for February.</description>
    <inlineHelpText>Monthly usage for February.</inlineHelpText>
    <label>February</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/Ignore__c.field-meta.xml
<CustomField>
    <fullName>Ignore__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do not consider this annual usage when calculating costs for the customer</description>
    <inlineHelpText>Do not consider this annual usage when calculating costs for the customer</inlineHelpText>
    <label>Ignore</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/January__c.field-meta.xml
<CustomField>
    <fullName>January__c</fullName>
    <description>Monthly usage for January.</description>
    <inlineHelpText>Monthly usage for January.</inlineHelpText>
    <label>January</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/July__c.field-meta.xml
<CustomField>
    <fullName>July__c</fullName>
    <description>Monthly usage for July.</description>
    <inlineHelpText>Monthly usage for July.</inlineHelpText>
    <label>July</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/June__c.field-meta.xml
<CustomField>
    <fullName>June__c</fullName>
    <description>Monthly usage for June.</description>
    <inlineHelpText>Monthly usage for June.</inlineHelpText>
    <label>June</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/March__c.field-meta.xml
<CustomField>
    <fullName>March__c</fullName>
    <description>Monthly usage for March.</description>
    <inlineHelpText>Monthly usage for March.</inlineHelpText>
    <label>March</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/May__c.field-meta.xml
<CustomField>
    <fullName>May__c</fullName>
    <description>Monthly usage for May.</description>
    <inlineHelpText>Monthly usage for May.</inlineHelpText>
    <label>May</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/November__c.field-meta.xml
<CustomField>
    <fullName>November__c</fullName>
    <description>Monthly usage for November.</description>
    <inlineHelpText>Monthly usage for November.</inlineHelpText>
    <label>November</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/October__c.field-meta.xml
<CustomField>
    <fullName>October__c</fullName>
    <description>Monthly usage for October.</description>
    <inlineHelpText>Monthly usage for October.</inlineHelpText>
    <label>October</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/Premise__c.field-meta.xml
<CustomField>
    <fullName>Premise__c</fullName>
    <description>The premise that this usage is tied to.</description>
    <inlineHelpText>The premise that this usage is tied to.</inlineHelpText>
    <label>Premise</label>
    <referenceTo>Premises__c</referenceTo>
    <relationshipLabel>Annual Usage</relationshipLabel>
    <relationshipName>Annual_Usage</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/Premise_Usage_Sum__c.field-meta.xml
<CustomField>
    <fullName>Premise_Usage_Sum__c</fullName>
    <description>This premise&#39;s total usage for the year.</description>
    <formula>January__c + February__c + March__c  +April__c + May__c + June__c  +July__c  +August__c  +September__c  +October__c + November__c  +December__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This premise&#39;s total usage for the year.</inlineHelpText>
    <label>Premise Usage (sum of all months)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/September__c.field-meta.xml
<CustomField>
    <fullName>September__c</fullName>
    <description>Monthly usage for September.</description>
    <inlineHelpText>Monthly usage for September.</inlineHelpText>
    <label>September</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Annual_Usage__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <description>The year of this usage.</description>
    <inlineHelpText>The year of this usage.</inlineHelpText>
    <label>Program Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GasChoiceCalcInputs__c/GasChoiceCalcInputs__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Gas Choice Calculation Inputs</label>
</CustomObject>

force-app/main/default/objects/GasChoiceCalcInputs__c/fields/Current_Program_Year__c.field-meta.xml
<CustomField>
    <fullName>Current_Program_Year__c</fullName>
    <description>What year is it in Gas Choice?</description>
    <inlineHelpText>What year is it in Gas Choice?</inlineHelpText>
    <label>Current Program Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GasChoiceCalcInputs__c/fields/Maximum_Annual_Dth_SmartBill__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Annual_Dth_SmartBill__c</fullName>
    <defaultValue>500</defaultValue>
    <description>In Dth, how much can the customer use and still qualify for a smartbill?</description>
    <inlineHelpText>In Dth, how much can the customer use and still qualify for a smartbill?</inlineHelpText>
    <label>Maximum Annual Dth SmartBill</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Maximum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Annual_Usage__c</fullName>
    <defaultValue>99999999999999</defaultValue>
    <description>What is the maximum kWh that a customer could use last year and be able to see this plan?</description>
    <inlineHelpText>What is the maximum kWh that a customer could use last year and be able to see this plan?  Use this feature to create &quot;bands&quot; of pricing based on usage</inlineHelpText>
    <label>Maximum Annual Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Minimum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Usage__c</fullName>
    <description>How many kWh per year must a customer have used in the last 12 months in order to qualify for this plan?</description>
    <inlineHelpText>How many kWh per year must a customer have used in the last 12 months in order to qualify for this plan?</inlineHelpText>
    <label>Minimum Annual Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/Premises__c.object-meta.xml
<CustomObject>
    <description>These are homes and business that can be associated with one or more accounts (person accounts)</description>
    <label>Premise</label>
    <nameField>
        <displayFormat>Premise-{0}</displayFormat>
        <label>Premise Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Premises</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Premises__c/fields/Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Annual_Usage__c</fullName>
    <description>what was the usage for the last 12 months?</description>
    <inlineHelpText>what was the usage for the last 12 months?</inlineHelpText>
    <label>Annual Usage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Premises__c/fields/Premise_Type__c.field-meta.xml
<CustomField>
    <fullName>Premise_Type__c</fullName>
    <description>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</description>
    <inlineHelpText>Denotes the type of premise as either Residential, Small Non-Residential, or Large Non-Residential.</inlineHelpText>
    <label>Premise Type</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Maximum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Annual_Usage__c</fullName>
    <description>How much yearly kWh usage is allowed for a customer to have this rate.</description>
    <inlineHelpText>How much yearly kWh usage is allowed for a customer to have this rate.</inlineHelpText>
    <label>Maximum Annual Usage (kWh)</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rate__c/fields/Minimum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Usage__c</fullName>
    <description>How much yearly kWh usage is required for a customer to have this rate?</description>
    <inlineHelpText>How much yearly kWh usage is required for a customer to have this rate?</inlineHelpText>
    <label>Minimum Annual Usage (kWh)</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SmartBill_Index__c/SmartBill_Index__c.object-meta.xml
<CustomObject>
    <description>Tracks SmartBill Index pricing</description>
    <label>SmartBill Index</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>SmartBill Index Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SmartBill Indexes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SmartBill_Index__c/fields/Above_threshold_cost__c.field-meta.xml
<CustomField>
    <fullName>Above_threshold_cost__c</fullName>
    <description>Distribution costs for usage above the monthly threshold</description>
    <inlineHelpText>Distribution costs for usage above the monthly threshold</inlineHelpText>
    <label>Above threshold cost</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SmartBill_Index__c/fields/Maximum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Annual_Usage__c</fullName>
    <description>At what usage would we not want to offer a smart bill?</description>
    <inlineHelpText>At what usage would we not want to offer a smart bill?</inlineHelpText>
    <label>Maximum Annual Usage</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SmartBill_Index__c/fields/Minimum_Annual_Usage__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Usage__c</fullName>
    <description>How many therms/year is the minimum required to get a smart bill offer?</description>
    <inlineHelpText>How many therms/year is the minimum required to get a smart bill offer?</inlineHelpText>
    <label>Minimum Annual Usage</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SmartBill_Index__c/fields/Nebraska_Distribution_Threshhold__c.field-meta.xml
<CustomField>
    <fullName>Nebraska_Distribution_Threshhold__c</fullName>
    <defaultValue>40</defaultValue>
    <description>Monthly volume subject to the STEP 1 cost...Currently 40 therms</description>
    <inlineHelpText>Monthly volume subject to the STEP 1 cost...Currently 40 therms</inlineHelpText>
    <label>Resi Distribution Threshhold</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/SmartBillUtilities.cls
public class SmartBillUtilities{
    
    public static boolean SmartBillTests3(map<integer, decimal> usage, premises__c thepremise){        
        //is the usage real or estimated?
        list<annual_usage__c> AUs = [select id, year__c, estimated__c, Premise_Usage_Sum__c from annual_usage__c where ignore__c != true and premise__r.id=:thepremise.id];
        if (AUs.isempty()) {system.debug('Estimated Usage Only'); return false;}
        boolean ok=false;
        GasChoiceCalcInputs__c GCCI = GasChoiceCalcInputs__c.getinstance();
        for (annual_usage__C AU:AUS){
            if (integer.valueof(au.Year__c)>=integer.valueof(GCCI.Current_Program_Year__c)-1 && au.Premise_Usage_Sum__c/10 < (GCCI.Maximum_Annual_Dth_SmartBill__c) && au.estimated__c == false) ok=true;
        }
        if (!ok) return false;
        //Verify usage via tests 1-7.
        decimal totalusage = 0;
        for (decimal d:usage.values()){
            totalusage=totalusage+d;
        }
    //Test 2--below maximum annual usage
        if (totalusage > GCCI.Maximum_Annual_Dth_SmartBill__c) {system.debug('Test 2 Failed'); return false;}
    //Test 3--maximum "zero usage" months allowed is 4
        decimal zerocounter=0;
        for (decimal d:usage.values()){
            if (d==0) zerocounter++;
        }        
        if (zerocounter>4) {system.debug('Test 3 Failed'); return false;}       
        return true;
    }
    
    public static boolean SmartBillTests2(map<integer, decimal> usage, premises__c thepremise, SmartBill_Index__c SBI){        
        //is the usage real or estimated?
        list<annual_usage__c> AUs = [select id, year__c, estimated__c, Premise_Usage_Sum__c from annual_usage__c where ignore__c != true and premise__r.id=:thepremise.id];
        if (AUs.isempty()) {system.debug('Estimated Usage Only'); return false;}
        boolean ok=false;
        GasChoiceCalcInputs__c GCCI = GasChoiceCalcInputs__c.getinstance();
        for (annual_usage__C AU:AUS){
            if (integer.valueof(au.Year__c)>=integer.valueof(GCCI.Current_Program_Year__c)-1 && au.Premise_Usage_Sum__c < (SBI.Maximum_Annual_Usage__c) && au.estimated__c == false) ok=true;
        }
        if (!ok) return false;
        //Verify usage via tests 1-7.
        decimal totalusage = 0;
        
        for (decimal d:usage.values()){
            totalusage=totalusage+d;
        }
        
    //Test 1--meets minimum annual usage    
       // why have a minimum?	 if (totalusage < SBI.Minimum_Annual_Usage__c/10) {system.debug('Test 1 Failed'); return false;}
    //Test 2--below maximum annual usage
        if (totalusage > GCCI.Maximum_Annual_Dth_SmartBill__c/10) {system.debug('Test 2 Failed'); return false;}
    //Test 3--maximum "zero usage" months allowed is 4
        
        decimal zerocounter=0;
        for (decimal d:usage.values()){
            if (d==0) zerocounter++;
        }        
        if (zerocounter>4) {system.debug('Test 3 Failed'); return false;}       
    /*
//Test 4--Oct to Mar must be greater than sum of the other months
        decimal OctToMar = usage.get(10)+usage.get(11)+usage.get(12)+usage.get(1)+usage.get(2)+usage.get(3);
        decimal AprSept = totalusage - OctToMar;
        if (AprSept > OctToMar) {system.debug('Test 4 Failed'); return false;}
        
    //Test 5--Average of Dec-Feb must be greater than average of Oct to Mar
        decimal DecFeb = usage.get(12)+usage.get(1)+usage.get(2);
        if (DecFeb/3 < OctToMar/6) {system.debug('Test 5 Failed'); return false;}
    //Test 6--Jan to April must be greater than May to August
        decimal MayAug = usage.get(5)+usage.get(6)+usage.get(7)+usage.get(8);
        if (usage.get(1) + usage.get(2) + usage.get(3) + usage.get(4) < MayAug) {system.debug('Test 6 Failed'); return false;}
    //Test 7 --SeptDec must be greater than May-Aug 
        if (MayAug > usage.get(9)+usage.get(10)+usage.get(11)+usage.get(12) ) {system.debug('Test 7 Failed'); return false;}
    //if you made it this far, you must be quotable
        */
        return true;
    }
    
    public static boolean SmartBillTests(annual_usage__c AU, premises__c thepremise, SmartBill_Index__c SBI){        
    //Verify usage via tests 1-7.
    
    //Test 1--meets minimum annual usage    
        if (AU.Premise_Usage_Sum__c < SBI.Minimum_Annual_Usage__c) {system.debug('Test 1 Failed'); return false;}
    //Test 2--below maximum annual usage
        if (AU.Premise_Usage_Sum__c > SBI.Maximum_Annual_Usage__c) {system.debug('Test 2 Failed'); return false;}
    //Test 3--maximum "zero usage" months allowed is 4
        decimal zerocounter=0;
        if (AU.January__c == 0) zerocounter ++;
        if (AU.February__c == 0) zerocounter ++;
        if (AU.March__c == 0) zerocounter ++;
        if (AU.April__c == 0) zerocounter ++;
        if (AU.May__c == 0) zerocounter ++;
        if (AU.June__c == 0) zerocounter ++;
        if (AU.July__c == 0) zerocounter ++;
        if (AU.August__c == 0) zerocounter ++;
        if (AU.September__c == 0) zerocounter ++;
        if (AU.October__c == 0) zerocounter ++;
        if (AU.November__c == 0) zerocounter ++;
        if (AU.December__c == 0) zerocounter ++;
        if (zerocounter>4) {system.debug('Test 3 Failed'); return false;}       
    //Test 4--Oct to Mar must be greater than sum of the other months
        decimal OctToMar = AU.October__c+AU.November__c+AU.December__c+AU.January__c+AU.February__c+AU.March__c;
        decimal AprSept = AU.Premise_Usage_Sum__c - OctToMar;
        if (AprSept > OctToMar) {system.debug('Test 4 Failed'); return false;}
    //Test 5--Average of Dec-Feb must be greater than average of Oct to Mar
        decimal DecFeb = AU.December__c+AU.January__c+AU.February__c;
        if (DecFeb/3 < OctToMar/6) {system.debug('Test 5 Failed'); return false;}
    //Test 6--Jan to April must be greater than May to August
        decimal MayAug = AU.May__c+AU.June__c+AU.July__c+AU.August__c;
        if (AU.January__c +AU.February__c+AU.March__c+AU.April__c < MayAug) {system.debug('Test 6 Failed'); return false;}
    //Test 7 --SeptDec must be greater than May-Aug 
        if (MayAug > AU.October__c+AU.November__c+AU.December__c+AU.September__c) {system.debug('Test 7 Failed'); return false;}
    //if you made it this far, you must be quotable
        return true;
    }
    
    public static decimal getNormalizedUsage(annual_usage__c AU, premises__c thepremise, SmartBill_Index__c SBI){
        decimal weatherFactor = 1; ////////////////////////////////////////////////////////////temporary stub.
        decimal baseload = (AU.July__c+AU.August__c)/2;
        decimal weatherAffectedUsage = AU.Premise_Usage_Sum__c - baseload*12;
        decimal normalizedWeatherAffectedUsage= weatherAffectedUsage * weatherFactor;
        system.debug('================================================Usage for the year is ' + normalizedWeatherAffectedUsage + baseload*12);        
        return normalizedWeatherAffectedUsage + baseload*12;        
    }
    
    public static decimal getDistributionCosts(premises__c premise, annual_usage__c usage, SmartBill_Index__c SBI){
        decimal VariableCost =0; 
        decimal FixedCost =0; 
        
        if (premise.premise_type__c == 'RES'){
            map<integer, decimal>usagemap = GasChoiceUtilities.NormalizeUsage(premise);            
            for (integer i:usagemap.keyset()){
                system.debug('===================RES: month is ' + i + ' and usage for that month is ' + usagemap.get(i));
                VariableCost = VariableCost + math.max(0, usagemap.get(i)*10-SBI.Nebraska_Distribution_Threshhold__c)*SBI.Above_threshold_cost__c;
                VariableCost = VariableCost + math.min(SBI.Nebraska_Distribution_Threshhold__c, usagemap.get(i)*10)*SBI.Below_threshold_distribution_cost__c;
            }
            system.debug('============================Variable distribution cost for the year is ' + VariableCost);
            FixedCost = 12*SBI.Nebraska_Dist_Fixed__c;  
            system.debug('Fixed cost for the year is '+     FixedCost );     
        }
        if (premise.premise_type__c == 'COM'){
            map<integer, decimal>usagemap = GasChoiceUtilities.NormalizeUsage(premise);
            for (integer i:usagemap.keyset()){
                system.debug('===================COM: month is ' + i + ' and usage for that month is ' + usagemap.get(i));
                VariableCost = VariableCost + math.max(0, usagemap.get(i)*10-SBI.Nebraska_COM_Distribution_Threshhold__c)*SBI.Above_threshold_cost_COM__c;
                system.debug('===================COM: Variable cost is now ' + VariableCost);
                VariableCost = VariableCost + math.min(SBI.Nebraska_COM_Distribution_Threshhold__c, usagemap.get(i)*10)*SBI.Below_threshold_distribution_cost_COM__c;
                system.debug('===================COM: Variable cost is now ' + VariableCost);
            }
            system.debug('============================Variable distribution cost for the year is ' + VariableCost);
            FixedCost = 12*SBI.Nebraska_COM_Dist_Fixed__c;       
            system.debug('Fixed cost for the year is '+     FixedCost );  
        }
        system.debug('Fixed cost for the year is '+     FixedCost );   
        system.debug('VariableCost for the year is '+     VariableCost);   
        return FixedCost+VariableCost;
    }
    
    public static decimal getCommodity(decimal TotalUsage, SmartBill_Index__c SBI, integer YearNumber){        
        if(YearNumber ==1) {
            system.debug('Year1 Commodity is  ' +     SBI.year_1_cost__c*TotalUsage + math.max(SBI.Margin_year_1__c*TotalUsage, SBI.Minimum_Aggregate_Margin_Year_1__c));
            return SBI.year_1_cost__c*TotalUsage + math.max(SBI.Margin_year_1__c*TotalUsage, SBI.Minimum_Aggregate_Margin_Year_1__c);
        }else{
            system.debug('Year2 Commodity is  ' +     SBI.year_2_cost__c*TotalUsage + math.max(SBI.Margin_Year_2_per_therm__c*TotalUsage, SBI.Minimum_Aggregate_Margin_Year_2__c));

            return SBI.year_2_cost__c*TotalUsage + math.max(SBI.Margin_Year_2_per_therm__c*TotalUsage, SBI.Minimum_Aggregate_Margin_Year_2__c);
        }
        return null;    
    }
    
    public static decimal getSmartBill(premises__c premise, rate__c Rate){
        try{
            decimal SmartBill;
            //get the SmartBillIndex information
            SmartBill_Index__c SBI = [select id,
                                      Dist_Fixed_Monthly_30000__c, Dist_Fixed_Monthly_5000_or_less__c, Dist_Fixed_Monthly_5001_to_30000__c,
                                      Dist_per_Therm_30000__c, Dist_per_Therm_5000_or_less__c, Dist_per_Therm_5001_to_30000__c,
                                      Margin_year_1__c, Margin_Year_2_per_therm__c, Maximum_Annual_Usage__c, Minimum_Annual_Usage__c,
                                      Minimum_Aggregate_Margin_Year_1__c, Minimum_Aggregate_Margin_Year_2__c, Tax_Factor__c, 
                                      year_1_cost__c, year_2_cost__c,       
                                      Above_threshold_cost__c, Below_threshold_distribution_cost__c, Nebraska_Dist_Fixed__c, Nebraska_Distribution_Threshhold__c, 
                                      Above_threshold_cost_COM__c, Below_threshold_distribution_cost_COM__c, Nebraska_COM_Dist_Fixed__c, Nebraska_COM_Distribution_Threshhold__c,
                                      Program__c
                                                                 
                                      from SmartBill_Index__c where Division__c =: premise.division__c and program__c =:premise.program__c];
            //get usage history (the most recent one)        
            annual_usage__c usage = [select id, Account__c,April__c, August__c, December__c, Estimated__c, February__c, 
                                     January__c,July__c,  June__c, March__c,May__c,November__c,   October__c, Premise_Usage_Sum__c ,September__c, Year__c
                                     from annual_usage__c where Premise__r.id =: premise.id order by year__c desc limit 1];
            //Run the Tests to see if it's quotable
            if (!SmartBillUtilities.SmartBillTests(usage, premise, SBI)){return null;}
            //weather normalize--need HDD/CDD tables?
            decimal TotalUsage = getNormalizedUsage(usage, premise, SBI);
            decimal DistributionCosts = SmartBillUtilities.getDistributionCosts(premise, usage, SBI);
            system.debug('================================DistributionCosts per year are ' + DistributionCosts);
            decimal Year1Commodity = SmartBillUtilities.getCommodity(TotalUsage, SBI, 1);
            decimal Year2Commodity = SmartBillUtilities.getCommodity(TotalUsage, SBI, 2);
            decimal Year1Quote = ((Year1Commodity + DistributionCosts)/12)*SBI.tax_factor__c;
            decimal Year2Quote = ((Year2Commodity + DistributionCosts)/12)*SBI.tax_factor__c;
            decimal CombinedQuote = (Year1Quote + Year2Quote)/2;        
            //now which one were you looking for?
            if (Rate.plan__r.contract_length__c == 12){return Year1Quote.setscale(2);}
            if (Rate.plan__r.contract_length__c == 24){return CombinedQuote.setscale(2);}
        } catch(exception e){return null;}
        return null;
    }
    
    
    public static decimal getDistributionCosts2(premises__c premise, decimal usage, SmartBill_Index__c SBI){        
        decimal VariableCost =0; 
        decimal FixedCost =0; 
        
        if (premise.premise_type__c == 'RES'){
                VariableCost = VariableCost + math.max(0, usage*10-SBI.Nebraska_Distribution_Threshhold__c)*SBI.Above_threshold_cost__c;
                VariableCost = VariableCost + math.min(SBI.Nebraska_Distribution_Threshhold__c, usage*10)*SBI.Below_threshold_distribution_cost__c;
            system.debug('============================Variable distribution cost is ' + VariableCost);
            FixedCost = SBI.Nebraska_Dist_Fixed__c;  
        }
        if (premise.premise_type__c == 'COM'){
                VariableCost = VariableCost + math.max(0, usage*10-SBI.Nebraska_COM_Distribution_Threshhold__c)*SBI.Above_threshold_cost_COM__c;
                VariableCost = VariableCost + math.min(SBI.Nebraska_COM_Distribution_Threshhold__c, usage*10)*SBI.Below_threshold_distribution_cost_COM__c;
            system.debug('============================Variable distribution cost is ' + VariableCost);
            FixedCost = SBI.Nebraska_COM_Dist_Fixed__c; 
        }
        system.debug('distribution cost is ' + (FixedCost+VariableCost));
        return FixedCost+VariableCost;
    }
    
    public static list<plan__c> RemoveSmartBills(list<plan__c> incoming){
        list<plan__c> output = new list<plan__c>();
        for (plan__c p:incoming){
            if (p.rate_type__c != 'SmartBill'){
                output.add(p);
            }        
        }
        return output;
    }
    
    public static decimal getSmartBillImpliedCustomerCost(SmartBill_Index__c SBI, date startdate, date enddate, map<string, map<date, decimal>> Costs, map<integer, decimal> usage, decimal margin, decimal Discount){
        date datecounter=startdate;
        decimal totalCost =0;
        decimal totalUsage = 0;
        
        while (datecounter<=enddate){
            totalCost = totalCost + SBI.Monthly_Supplier_Fee__c + (Costs.get('Fixed Supply').get(datecounter)+ margin + discount)*usage.get(datecounter.month());
            totalUsage = totalUsage + usage.get(datecounter.month());
            datecounter=datecounter.addmonths(1);
        }
        
        if (TotalUsage>0)        return TotalCost/TotalUsage ;
        else return TotalCost;
    }  
        
    
    
}