force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <description>Fees are maintained by the TrueCost administrators</description>
    <label>TDSP Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDSP Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Fee__c/fields/Basis__c.field-meta.xml
<CustomField>
    <fullName>Basis__c</fullName>
    <description>How often does this fee occur, is it based on kWh usage (volumetric), or is it determined by the customer&#39;s actions (potential)?</description>
    <inlineHelpText>How often does this fee occur, is it based on kWh usage (volumetric), or is it determined by the customer&#39;s actions (potential)?</inlineHelpText>
    <label>Basis</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>Daily</fullName>
            </value>
            <value>
                <fullName>Volumetric</fullName>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Rate_Class__c.field-meta.xml
<CustomField>
    <fullName>Rate_Class__c</fullName>
    <description>Is this fee charged to residential or commercial customers?</description>
    <inlineHelpText>Is this fee charged to residential or commercial customers?</inlineHelpText>
    <label>Fee Class/Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Residential</fullName>
            </value>
            <value>
                <fullName>Secondary Service &lt;= 10 kVa</fullName>
            </value>
            <value>
                <fullName>Secondary Service &gt; 10 kVa</fullName>
            </value>
            <value>
                <fullName>Residential Gas</fullName>
            </value>
            <value>
                <fullName>Commercial Gas</fullName>
            </value>
            <value>
                <fullName>Agriculture Gas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Fee__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What service provider/territory does this fee apply to?</description>
    <inlineHelpText>What service provider/territory does this fee apply to?</inlineHelpText>
    <label>TDSP</label>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipName>Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Fee__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value (in $)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Maintained_Fees__c/Maintained_Fees__c.object-meta.xml
<CustomObject>
    <description>These fees are selected by the REPs from options provided by the CNP admins</description>
    <label>TDSP-Maintained Fee</label>
    <nameField>
        <displayFormat>TDU Fee-{0}</displayFormat>
        <label>Maintained Fee ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TDSP-Maintained Fees</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintained_Fees__c/fields/Additional_Charge__c.field-meta.xml
<CustomField>
    <fullName>Additional_Charge__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Is this fee in addition to the base energy charge AND any other fees listed?</description>
    <inlineHelpText>Is this fee in addition to the base energy charge AND any other fees listed?</inlineHelpText>
    <label>Additional Charge?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Maintained_Fees__c/fields/Basis__c.field-meta.xml
<CustomField>
    <fullName>Basis__c</fullName>
    <formula>TEXT( Fee__r.Basis__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>How the fee is charged.  This is set by the CNP admin and can&#39;t be edited by REPs</inlineHelpText>
    <label>Basis</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Maintained_Fees__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which of the CNP admin-maintained fees do you want to include?</description>
    <inlineHelpText>Which of the CNP admin-maintained fees do you want to include?</inlineHelpText>
    <label>Fee</label>
    <referenceTo>Fee__c</referenceTo>
    <relationshipName>Maintained_Fees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Maintained_Fees__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <description>The parent  rate that has this fee</description>
    <inlineHelpText>The parent  rate that has this fee</inlineHelpText>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipName>Maintained_Fees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Maintained_Fees__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <formula>Fee__r.Value__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>This fee is maintained by the TrueCost admins.  You can&#39;t edit it.</inlineHelpText>
    <label>Value</label>
    <precision>18</precision>
    <scale>5</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which TDSP has this rate available?</description>
    <inlineHelpText>Which TDSP has this rate available?</inlineHelpText>
    <label>TDSP</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>equals</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <filterItems>
            <field>TDSP__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>TDSP</value>
        </filterItems>
        <filterItems>
            <field>$Profile.Name</field>
            <operation>notEqual</operation>
            <value>REP Lite, REP Portal User, REPs Profile, TrueCost REPs Profile</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>TDSP__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rate__c/recordTypes/Residential.recordType-meta.xml
<RecordType>
    <fullName>Residential</fullName>
    <active>true</active>
    <description>Shows the fields relevant to residential rates.</description>
    <label>Residential</label>
</RecordType>

force-app/main/default/objects/TDSP__c/TDSP__c.object-meta.xml
<CustomObject>
    <description>Transmission and distribution service providers</description>
    <label>Utility</label>
    <nameField>
        <label>Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Utilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/FeeList.cls
public class FeeList {
	
	public Rate__c TheRate;
	list<rate__c> theRates = new list<rate__c>();
	
	public FeeList(ApexPages.StandardController stdController){
		theRates = [select id, tdsp__c from Rate__c where id =:ApexPages.currentPage().getParameters().get('Id') ];	
		if ( theRates.size()>0 )theRate = theRates[0];
	}
	public id selectedfee {get;set;}
	public boolean refreshpage {get;set;}
	
	public list<fee__c> GetFees(){ 
		if ( theRates.size()>0 ) {
			set<id> blacklist = new set<id>();
			
			list<Maintained_Fees__c> existing = [select id, fee__r.id from Maintained_Fees__c where rate__r.id =: therate.id]; //don't show ones already used
			if (existing.size()>0 ) {			
				
				for (Maintained_Fees__c mf:existing){
					blacklist.add(mf.fee__r.id);
				
				}
			}
			list<fee__c> feelist = [select name, value__c, basis__c, tdsp__c from fee__c where tdsp__c =: theRate.tdsp__c and rate_class__c = 'Residential' and id not IN:blacklist order by name];
			blacklist.clear();
			return feelist;
		} else {return null;}
	}

	public pagereference addFee(){
		Maintained_Fees__c theNewMaintainedFee = new Maintained_Fees__c ();
		theNewMaintainedFee.Rate__c = therate.id;
		theNewMaintainedFee.Fee__c = selectedfee;
		theNewMaintainedFee.Additional_Charge__c = true;
		insert theNewMaintainedFee;
		refreshpage = true;
		return null;
	}
}