force-app/main/default/objects/logger__c/logger__c.object-meta.xml
<CustomObject>
    <label>logger</label>
    <nameField>
        <label>logger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>loger</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/logger__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>loger</relationshipLabel>
    <relationshipName>loger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/logger__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>loger</relationshipLabel>
    <relationshipName>loger</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Authorized_Representative__c.field-meta.xml
<CustomField>
    <fullName>Authorized_Representative__c</fullName>
    <description>The customer has selected someone who can speak to their REP on their behalf</description>
    <inlineHelpText>The customer has selected someone who can speak to their REP on their behalf</inlineHelpText>
    <label>Authorized Representative</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Critical_Care__c.field-meta.xml
<CustomField>
    <fullName>Critical_Care__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the customer a critical care customer?</description>
    <inlineHelpText>Is the customer a critical care customer?</inlineHelpText>
    <label>Critical Care</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Customer_Date_of_Birth__c</fullName>
    <label>Customer Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Email__c.field-meta.xml
<CustomField>
    <fullName>Customer_Email__c</fullName>
    <label>Customer Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Customer_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Phone_Number__c</fullName>
    <inlineHelpText>The customer&#39;s primary phone number</inlineHelpText>
    <label>Customer Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ESIID_Number__c.field-meta.xml
<CustomField>
    <fullName>ESIID_Number__c</fullName>
    <description>The ESIID number of the meter to be switched to a plan</description>
    <inlineHelpText>The Electric Service Identifier ID number of the meter to be switched on for a plan.</inlineHelpText>
    <label>ESIID Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/InitialDateofService__c.field-meta.xml
<CustomField>
    <fullName>InitialDateofService__c</fullName>
    <description>Initial date of service.</description>
    <inlineHelpText>Date the change to new REP will occur.</inlineHelpText>
    <label>Date Requested</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Texas</fullName>
                <default>true</default>
                <label>Texas</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip_Code__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this order.</description>
    <inlineHelpText>TrueCost account for this order.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Parent Account)</relationshipLabel>
    <relationshipName>OrdersPlaced</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PMVI_Flag__c.field-meta.xml
<CustomField>
    <fullName>PMVI_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a priority move in order?</description>
    <label>Move?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REPOrderId__c.field-meta.xml
<CustomField>
    <fullName>REPOrderId__c</fullName>
    <label>REPOrderId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REPStatus__c.field-meta.xml
<CustomField>
    <fullName>REPStatus__c</fullName>
    <label>REPStatus</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_Address__c.field-meta.xml
<CustomField>
    <fullName>Service_Address__c</fullName>
    <label>Service Address</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_City__c.field-meta.xml
<CustomField>
    <fullName>Service_City__c</fullName>
    <label>Service City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_State__c.field-meta.xml
<CustomField>
    <fullName>Service_State__c</fullName>
    <label>Service State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TX</fullName>
                <default>true</default>
                <label>TX</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Service_Zip__c.field-meta.xml
<CustomField>
    <fullName>Service_Zip__c</fullName>
    <label>Service Zip</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_State__c.field-meta.xml
<CustomField>
    <fullName>Mailing_State__c</fullName>
    <label>Mailing State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>TX</fullName>
                <default>true</default>
                <label>TX</label>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>DC</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TrueCostSystemVariables__c/TrueCostSystemVariables__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Variables to control the TrueCost site without touching code.  These can differ from one environment to another.</description>
    <label>TrueCostSystemVariables</label>
</CustomObject>

force-app/main/default/objects/TrueCostSystemVariables__c/fields/bounce__c.field-meta.xml
<CustomField>
    <fullName>bounce__c</fullName>
    <label>bounce</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BounceAPImgr.cls
public class BounceAPImgr {
    
    public List<String> XMLData{get;set;}
    public order__c[] orderlist;
    
    public void placeOrder(order__c[] orderlist)
    {
        String enrollmenttype = '';
        if  (orderlist[0].PMVI_Flag__c)     
        {
            enrollmenttype = 'MI';
        }else
        {
            enrollmenttype = 'NB';
        }
        //String token = getToken();    
        system.debug('place order'+ orderlist[0]);
        neworder(orderlist[0].name);
        // order(orderlist[0].ssn__c,orderlist[0].Critical_Care__c, orderlist[0].name, orderlist[0].id, orderlist[0].First_Name__c,orderlist[0].Last_Name__c,orderlist[0].Customer_Date_of_Birth__c,orderlist[0].Mailing_City__c,orderlist[0].Mailing_State__c,orderlist[0].Mailing_Street_Address__c,orderlist[0].Mailing_Zip_Code__c,orderlist[0].Service_Address__c,orderlist[0].Service_City__c,orderlist[0].Service_State__c,orderlist[0].Service_Zip__c,orderlist[0].InitialDateofService__c,enrollmenttype, orderlist[0].Plan_ID__c,orderlist[0].ESIID_Number__c,orderlist[0].Customer_Email__c, orderlist[0].Customer_Phone_Number__c,orderlist[0].rate__c);
        
    }
    
    
    
    
    public String gettoken(){
        if(!Test.isRunningTest()){
            //RC Added to prevent web callouts from test class
            system.debug('Inside');
            HttpRequest req = new HttpRequest();
            String token = '';
            
            trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
            
            req.setEndPoint(tcsv.bounce__c);
            
            req.setMethod('POST');
            String username = 'centerpoint';
            String password = '7kbzlhSw';
            Blob headerValue = Blob.valueOf(username + ':' + password);
            String authorizationHeader = 'BASIC ' +
                EncodingUtil.base64Encode(headerValue);
            req.setHeader('Authorization', authorizationHeader);
            String body ='bounce_xml='+
                +'<?xml version=\"1.0\"?>'
                +'<bounce_api>' 
                +'<request>'
                +'<type>login</type>'
                +'<username>centerpoint</username>' 
                +'<password>7kbzlhSw</password> '
                +'</request> '
                +'</bounce_api> ';
            
            
            
            req.setbody(body);
            
            
            Http http = new Http();
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
            
            
            List<String> orgInfo=new List<String>();
            
            Dom.Document doc = new Dom.Document();
            
            doc.load(res.getBody());
            
            //Retrieve the root element for this document.
            
            Dom.XMLNode Envelope = doc.getRootElement();
            
            Dom.XMLNode Body1= Envelope.getChildElements()[0];
            
            string user_createResult = '';
            
            
            
            for(Dom.XMLNode child : Body1.getChildElements()) {
                
                orgInfo.add(child .getText());
            }
            system.debug(orginfo);
            
            return orginfo[2];
            
        }
        else{
            String Token = 'Token';
            return Token;
        }
    }
    
    
    @Future(callout=true)
    private static void neworder(String name)
    {
        if(!Test.isRunningTest()){
        order__c order = [select id,   exception__c, repstatus__c, ownerid,Authorized_Representative__c,Parent_Account__c,reporderid__c,record_type_name__c, rate__c,SSN__c,rep_profile__r.name,order_status__c, premise__r.id, premise__c,Plan_ID__c,  order_expiration_date__c, createddate, name,First_Name__c,Last_Name__c,Customer_date_of_birth__c,Critical_Care__c,Mailing_Street_Address__c,Mailing_City__c,Mailing_State__c,Mailing_Zip_Code__c,Service_Address__c,Service_State__c,Service_City__c,Service_Zip__c,InitialDateofService__c,Enrollment_Type__c,PMVI_Flag__c,ESIID_Number__c,Customer_Email__c, Customer_Phone_Number__c ,REP_email__c ,Fixed_Energy_Rate__c from Order__c where name =: name limit 1 ];
        List<logger__c> log = new List<logger__c>(); 
        ProcessorControl.inFutureContext = true;
        system.debug('order:' + order);
        String phone = '';
        phone = order.Customer_Phone_Number__c;
        phone = phone.replace(' ','');
        phone = phone.replace('(','');
        phone = phone.replace(')','');
        phone = phone.replace('-','');
        String ssn   = order.ssn__c.replace('-','');
        
        //
        
        //get rateid__c for rate id passed
        
        Rate__c rateRes = [ select name from rate__c where id =: order.rate__c limit 1];
        system.debug('rateId.........................'+ rateRes.name);
        if (order.InitialDateofService__c == null)
        {
            order.InitialDateofService__c = system.today()+3;
        }
        logger__c logs = new logger__c(); 
        logs.Order__c = order.id;
        logs.message__c = 'inital date of service:'+order.InitialDateofService__c;
        log.add(logs); 
        list<BusinessHours> REPhours = [select id from BusinessHours where name = 'REP SLA']; //Finds the REP business hours 
        system.debug('=============initial date of service =========  ' + order.InitialDateofService__c);
        //Datetime newdate = BusinessHours.add(REPhours[0].id, order.InitialDateofService__c, 18*60*60*1000L); 
        //1 * 24 * 60 * 60 * 1000L
        Datetime newdate = BusinessHours.add(REPhours[0].id, order.InitialDateofService__c, 1*24*60*1000L); 
        logger__c logs1 = new logger__c(); 
        logs1.Order__c = order.id;
        logs1.message__c = 'business  date of service:'+newdate;
        log.add(logs1); 
        
        
        system.debug('=============created=========  ' + newdate);
        integer month1                       = newdate.month();
        integer day1                         = newdate.day();
        String dayS1                          = string.valueof(newdate.day());
        String monthS1                        = string.valueof(newdate.month());
        if (order.InitialDateofService__c != null)
        {
            
            system.debug('service start date' + newdate);
            
            
            String zero1                         = '0';
            if (string.valueof(month1).length() == 1){
                
                monthS1 = zero1 + string.valueof(month1);
            }
            
            if (string.valueof(day1).length() == 1){
                
                dayS1 = zero1 + string.valueof(day1);
                
            }
            
            system.debug('initdateofservice' +monthS1+dayS1+newdate.year());
        }
        
        string typeSwitch = 'switch';
        date now = System.today();
        date bet =  date.newInstance(newdate.year(),  newdate.month(),newdate.day());
        date start = date.newInstance(now.year(),  now.month(),now.day());
        System.debug('start date:'+ start);
        system.debug('end date:'+ bet);
        
        integer numberDaysDue =     start.daysBetween(bet);
        integer test =     start.daysBetween(date.valueof(newdate));
        system.debug('days due:'+numberDaysDue);
        system.debug('test'+test);
        if ( numberDaysDue > 6)
        {
            
            typeSwitch = 'forward_switch';
            
        }
        logger__c logs2 = new logger__c(); 
        logs2.Order__c = order.id;
        logs2.message__c = 'switch type:'+typeSwitch;
        log.add(logs2);
        logger__c logs3 = new logger__c(); 
        logs3.Order__c = order.id;
        logs3.message__c = 'days between: '+numberDaysDue;
        log.add(logs3);
        
        HttpRequest req = new HttpRequest();
        String token = '';
        //req.setEndpoint('http://174.36.54.131/test-api/api-ng/place-order.php');
        //req.setEndpoint('http://199.168.175.28/test-api/api-ng/place-order.php');
        //req.setEndpoint('https://www.bounceenergy.com/api-ng/place-order.php');
        //req.setEndpoint('https://www.bounceenergy.com/test-api/api-ng/place-order.php');
        TrueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        
        System.debug(tcsv);
        req.setEndPoint(tcsv.bounce__c);
        req.setMethod('POST');
        String username = 'testuser';
        String password = '@p1T3st';
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'BASIC ' +
            EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        String body ='bounce_xml='+
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>login</type>'
            +'<username>centerpoint</username>' 
            +'<password>7kbzlhSw</password> '
            +'</request> '
            +'</bounce_api> ';
        
        
        
        req.setbody(body);
        
        
        Http http = new Http();
        
        HTTPResponse res = http.send(req);
        
        System.debug(res.getBody());
        
        
        List<String> orgInfo=new List<String>();
        
        Dom.Document doc = new Dom.Document();
        
        doc.load(res.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode Envelope = doc.getRootElement();
        
        Dom.XMLNode Body1= Envelope.getChildElements()[0];
        
        string user_createResult = '';
        
        
        
        for(Dom.XMLNode child : Body1.getChildElements()) {
            
            orgInfo.add(child .getText());
        }
        system.debug(orginfo);
        
        token = orginfo[2];
        
        System.debug('Token' + token);
        //End get token call
        if ((order.Mailing_Street_Address__c == '') || (order.Mailing_Street_Address__c == null))
        {
            order.Mailing_Street_Address__c = order.Service_Address__c;
            order.Mailing_City__c           = order.Service_City__c;
            order.Mailing_State__c          = order.Service_State__c;
            order.Mailing_Zip_Code__c       = order.Service_Zip__c;
            
            
        }
        
        body ='bounce_xml='+  
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>create_order</type>'
            +'<token>'+token+'</token>'
            +'</request>'
            +'<order>'
            +'<esiid>'+order.ESIID_Number__c+'</esiid>'
            +'<service_addr1>'+order.Service_Address__c+'</service_addr1>'
            +'<service_addr2></service_addr2>'
            +'<service_city>'+order.Service_City__c+'</service_city>'
            +'<service_state>'+order.Service_State__c+'</service_state>'
            +'<service_zip>'+order.Service_Zip__c+'</service_zip>'
            +'<previous_addr1></previous_addr1>'
            +'<previous_addr2></previous_addr2>'
            +'<previous_city></previous_city>'
            +'<previous_state></previous_state>'
            +'<previous_zip></previous_zip>'
            +'<service_start_day>'+newdate.day()+'</service_start_day>'
            +'<service_start_month>'+newdate.month()+'</service_start_month>'
            +'<service_start_year>'+newdate.year()+'</service_start_year>'
            +'<customer_type>'+typeswitch+'</customer_type>'
            +'<plan_id>'+order.Plan_ID__c+'</plan_id>'
            +'<products>'
            +'<product>'
            +'<product_id>'+rateRes.name+'</product_id>'
            +'</product>'
            +'</products>'
            +'<language>english</language>'
            +'<f_name>'+order.First_Name__c+'</f_name>'
            +'<l_name>'+order.Last_Name__c+'</l_name>'
            +'<email>'+order.Customer_Email__c+'</email>'
            +'<day_phone>'+phone+'</day_phone>'
            +'<day_phone_ext></day_phone_ext>'
            +'<alt_phone></alt_phone>'
            +'<alt_phone_ext></alt_phone_ext>'
            +'<bill_addr1>'+order.Mailing_Street_Address__c+'</bill_addr1>'
            +'<bill_addr2></bill_addr2>'
            +'<bill_city>'+order.Mailing_City__c+'</bill_city>'
            +'<bill_state>'+order.Mailing_City__c+'</bill_state>'
            +'<bill_zip>'+order.Mailing_Zip_Code__c+'</bill_zip>'
            +'<ssn>'+ssn+'</ssn>'
            +'<market_source_id>448</market_source_id>'
            
            +'</order>'
            +'</bounce_api>';
        
        logger__c logs4 = new logger__c(); 
        logs4.Order__c = order.id;
        logs4.message__c = 'order body sent: '+body;
        log.add(logs4);
        
        req.setbody(body);
        
        Http http1 = new Http();
        res = http1.send(req);
        System.debug(res.getBody());
        /*
<bounce_api>
<response>
<type>order_result</type>
<order_valid>0</order_valid>
<error_msg>Esid is active</error_msg>
<active_order_id>374249</active_order_id>
</response>
</bounce_api>
*/
        //Handle response
        List<String> orderResponse =new List<String>();
        List<String> orderResponse1 =new List<String>();
        Dom.Document docRes = new Dom.Document();
        
        docRes.load(res.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode EnvelopeRes = docRes.getRootElement();
        
        Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
        
        system.debug('raw response' +res.getBody());
        logger__c logs5 = new logger__c(); 
        logs5.Order__c = order.id;
        logs5.message__c = 'response: '+res.getBody();
        log.add(logs5);
        
        system.debug('raw response' +BodyRes);
        String order_result = '';
        string id_validated = '';
        String order_created = '';
        String order_id = '';
        String deposit_required = '';
        String deposit_due = '';
        String payment_required = '';
        String payment_due = '';
        
        for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
            
            if (childres.getName() == 'order_result')
                order_result = childRes .getText();
            if (childres.getName() == 'id_validated')
                id_validated = childRes .getText(); 
            if (childres.getName() == 'order_created')
                order_created = childRes .getText();
            if (childres.getName() == 'order_id')
                order_id = childRes .getText(); 
            if (childres.getName() == 'deposit_required')
                deposit_required = childRes .getText(); 
            if (childres.getName() == 'deposit_due')
                deposit_due = childRes .getText();  
            if (childres.getName() == 'payment_required')
                payment_required = childRes .getText();
            if (childres.getName() == 'payment_due')
                payment_due = childRes .getText();  
            if (childres.getName() == 'active_order_id')
                order_id = childres.getText();        
            
            orderResponse1.add(childres.getName());
            orderResponse.add(childRes .getText());
        }
        system.debug( order_result );
        system.debug(id_validated );
        system.debug(order_created );
        system.debug(order_id );
        system.debug(deposit_required );
        system.debug(deposit_due );
        system.debug(payment_required );
        system.debug(payment_due  );
        
        /*
<type>order_result</type>
<id_validated>validated</id_validated>
<order_created>1</order_created>
<order_id>502920</order_id>
<deposit_required>0</deposit_required>
<deposit_due>0.00</deposit_due>
<payment_required>0</payment_required>
<payment_due>0.00</payment_due>
*/
        if( id_validated == 'nomatch')
        {
            System.debug('order Error ssn not match');
            
            order.failure_reason__c = 'nomatch';
            
            order.order_status__c = 'Pending';
            update order;
            
        }
        
        
        // if (orderResponse[1] == '0' && order_id == '')
        if ( order_id == '')
        {
            System.debug('order Error');
            
            order.failure_reason__c = orderResponse[2];
            
            order.order_status__c = 'Pending';
            update order;
            
            //}else if(orderResponse[1] == '0' && order_id != ''){
        }else if( order_id != ''){	
            
            order.reporderid__c = order_id; 
            
            if( id_validated == 'validated' || order_id != '')
            {
                order.Order_Status__c =  'Approved Pending Confirmation';
                order.REPStatus__c = id_validated;
            }
            if(  deposit_required == '1' && id_validated != 'nomatch')
            {
                order.Order_status__c =  'Approved Pending Deposit';
                order.Deposit_Requested__c = true;
                order.Deposit__c = Decimal.valueof(deposit_due);
            }
            list<BusinessHours> REPhours2 = [select id from BusinessHours where name = 'REP SLA']; //Finds the REP business hours 
            if (REPhours2.size() == 0) REPhours2 = [select id from BusinessHours where isDefault = true];  //just in case, uses our org's default hours.
            order.Order_Expiration_Date__c = BusinessHours.add(REPhours2[0].id, system.today(), 18*60*60*1000L); 
            
            update order;
        }
        
        upsert log;
        }
    }
    
    public void manualOrder(String name)
    {
        order__c order = [select id,   exception__c, repstatus__c, ownerid,Authorized_Representative__c,Parent_Account__c,reporderid__c,record_type_name__c, rate__c,SSN__c,rep_profile__r.name,order_status__c, premise__r.id, premise__c,Plan_ID__c,  order_expiration_date__c, createddate, name,First_Name__c,Last_Name__c,Customer_date_of_birth__c,Critical_Care__c,Mailing_Street_Address__c,Mailing_City__c,Mailing_State__c,Mailing_Zip_Code__c,Service_Address__c,Service_State__c,Service_City__c,Service_Zip__c,InitialDateofService__c,Enrollment_Type__c,PMVI_Flag__c,ESIID_Number__c,Customer_Email__c, Customer_Phone_Number__c ,REP_email__c ,Fixed_Energy_Rate__c from Order__c where name =: name limit 1 ];
        List<logger__c> log = new List<logger__c>(); 
        ProcessorControl.inFutureContext = true;
        system.debug('order:' + order);
        String phone = '';
        phone = order.Customer_Phone_Number__c;
        phone = phone.replace(' ','');
        phone = phone.replace('(','');
        phone = phone.replace(')','');
        phone = phone.replace('-','');
        String ssn   = order.ssn__c.replace('-','');
        
        //
        
        //get rateid__c for rate id passed
        
        Rate__c rateRes = [ select name from rate__c where id =: order.rate__c limit 1];
        system.debug('rateId.........................'+ rateRes.name);
        if (order.InitialDateofService__c == null)
        {
            order.InitialDateofService__c = system.today()+3;
        }
        logger__c logs = new logger__c(); 
        logs.Order__c = order.id;
        logs.message__c = 'inital date of service:'+order.InitialDateofService__c;
        log.add(logs); 
        list<BusinessHours> REPhours = [select id from BusinessHours where name = 'REP SLA']; //Finds the REP business hours 
        system.debug('=============initial date of service =========  ' + order.InitialDateofService__c);
        //Datetime newdate = BusinessHours.add(REPhours[0].id, order.InitialDateofService__c, 18*60*60*1000L); 
        //1 * 24 * 60 * 60 * 1000L
        Datetime newdate = BusinessHours.add(REPhours[0].id, order.InitialDateofService__c, 1*24*60*1000L); 
        logger__c logs1 = new logger__c(); 
        logs1.Order__c = order.id;
        logs1.message__c = 'business  date of service:'+newdate;
        log.add(logs1); 
        
        
        system.debug('=============created=========  ' + newdate);
        integer month1                       = newdate.month();
        integer day1                         = newdate.day();
        String dayS1                          = string.valueof(newdate.day());
        String monthS1                        = string.valueof(newdate.month());
        if (order.InitialDateofService__c != null)
        {
            
            system.debug('service start date' + newdate);
            
            
            String zero1                         = '0';
            if (string.valueof(month1).length() == 1){
                
                monthS1 = zero1 + string.valueof(month1);
            }
            
            if (string.valueof(day1).length() == 1){
                
                dayS1 = zero1 + string.valueof(day1);
                
            }
            
            system.debug('initdateofservice' +monthS1+dayS1+newdate.year());
        }
        
        string typeSwitch = 'switch';
        date now = System.today();
        date bet =  date.newInstance(newdate.year(),  newdate.month(),newdate.day());
        date start = date.newInstance(now.year(),  now.month(),now.day());
        System.debug('start date:'+ start);
        system.debug('end date:'+ bet);
        
        integer numberDaysDue =     start.daysBetween(bet);
        integer test =     start.daysBetween(date.valueof(newdate));
        system.debug('days due:'+numberDaysDue);
        system.debug('test'+test);
        if ( numberDaysDue > 6)
        {
            
            typeSwitch = 'forward_switch';
            
        }
        logger__c logs2 = new logger__c(); 
        logs2.Order__c = order.id;
        logs2.message__c = 'switch type:'+typeSwitch;
        log.add(logs2);
        logger__c logs3 = new logger__c(); 
        logs3.Order__c = order.id;
        logs3.message__c = 'days between: '+numberDaysDue;
        log.add(logs3);
        
        HttpRequest req = new HttpRequest();
        String token = '';
        //req.setEndpoint('http://174.36.54.131/test-api/api-ng/place-order.php');
        //req.setEndpoint('http://199.168.175.28/test-api/api-ng/place-order.php');
        //req.setEndpoint('https://www.bounceenergy.com/api-ng/place-order.php');
        //req.setEndpoint('https://www.bounceenergy.com/test-api/api-ng/place-order.php');
        trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        
        req.setEndPoint(tcsv.bounce__c);
        req.setMethod('POST');
        String username = 'testuser';
        String password = '@p1T3st';
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'BASIC ' +
            EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        String body ='bounce_xml='+
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>login</type>'
            +'<username>centerpoint</username>' 
            +'<password>7kbzlhSw</password> '
            +'</request> '
            +'</bounce_api> ';
        
        
        
        req.setbody(body);
        
        
        Http http = new Http();
        HTTPResponse res = http.send(req);
        System.debug(res.getBody());
        
        
        List<String> orgInfo=new List<String>();
        
        Dom.Document doc = new Dom.Document();
        
        doc.load(res.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode Envelope = doc.getRootElement();
        
        Dom.XMLNode Body1= Envelope.getChildElements()[0];
        
        string user_createResult = '';
        
        
        
        for(Dom.XMLNode child : Body1.getChildElements()) {
            
            orgInfo.add(child .getText());
        }
        system.debug(orginfo);
        
        token = orginfo[2];
        
        System.debug('Token' + token);
        //End get token call
        if ((order.Mailing_Street_Address__c == '') || (order.Mailing_Street_Address__c == null))
        {
            order.Mailing_Street_Address__c = order.Service_Address__c;
            order.Mailing_City__c           = order.Service_City__c;
            order.Mailing_State__c          = order.Service_State__c;
            order.Mailing_Zip_Code__c       = order.Service_Zip__c;
            
            
        }
        
        body ='bounce_xml='+  
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>create_order</type>'
            +'<token>'+token+'</token>'
            +'</request>'
            +'<order>'
            +'<esiid>'+order.ESIID_Number__c+'</esiid>'
            +'<service_addr1>'+order.Service_Address__c+'</service_addr1>'
            +'<service_addr2></service_addr2>'
            +'<service_city>'+order.Service_City__c+'</service_city>'
            +'<service_state>'+order.Service_State__c+'</service_state>'
            +'<service_zip>'+order.Service_Zip__c+'</service_zip>'
            +'<previous_addr1></previous_addr1>'
            +'<previous_addr2></previous_addr2>'
            +'<previous_city></previous_city>'
            +'<previous_state></previous_state>'
            +'<previous_zip></previous_zip>'
            +'<service_start_day>'+newdate.day()+'</service_start_day>'
            +'<service_start_month>'+newdate.month()+'</service_start_month>'
            +'<service_start_year>'+newdate.year()+'</service_start_year>'
            +'<customer_type>'+typeswitch+'</customer_type>'
            +'<plan_id>'+order.Plan_ID__c+'</plan_id>'
            +'<products>'
            +'<product>'
            +'<product_id>'+rateRes.name+'</product_id>'
            +'</product>'
            +'</products>'
            +'<language>english</language>'
            +'<f_name>'+order.First_Name__c+'</f_name>'
            +'<l_name>'+order.Last_Name__c+'</l_name>'
            +'<email>'+order.Customer_Email__c+'</email>'
            +'<day_phone>'+phone+'</day_phone>'
            +'<day_phone_ext></day_phone_ext>'
            +'<alt_phone></alt_phone>'
            +'<alt_phone_ext></alt_phone_ext>'
            +'<bill_addr1>'+order.Mailing_Street_Address__c+'</bill_addr1>'
            +'<bill_addr2></bill_addr2>'
            +'<bill_city>'+order.Mailing_City__c+'</bill_city>'
            +'<bill_state>'+order.Mailing_City__c+'</bill_state>'
            +'<bill_zip>'+order.Mailing_Zip_Code__c+'</bill_zip>'
            +'<ssn>'+ssn+'</ssn>'
            +'<market_source_id>448</market_source_id>'
            
            +'</order>'
            +'</bounce_api>';
        
        logger__c logs4 = new logger__c(); 
        logs4.Order__c = order.id;
        logs4.message__c = 'order body sent: '+body;
        log.add(logs4);
        
        req.setbody(body);
        
        Http http1 = new Http();
        res = http1.send(req);
        System.debug(res.getBody());
        /*
<bounce_api>
<response>
<type>order_result</type>
<order_valid>0</order_valid>
<error_msg>Esid is active</error_msg>
<active_order_id>374249</active_order_id>
</response>
</bounce_api>
*/
        //Handle response
        List<String> orderResponse =new List<String>();
        List<String> orderResponse1 =new List<String>();
        Dom.Document docRes = new Dom.Document();
        
        docRes.load(res.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode EnvelopeRes = docRes.getRootElement();
        
        Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
        
        system.debug('raw response' +res.getBody());
        logger__c logs5 = new logger__c(); 
        logs5.Order__c = order.id;
        logs5.message__c = 'response: '+res.getBody();
        log.add(logs5);
        
        system.debug('raw response' +BodyRes);
        String order_result = '';
        string id_validated = '';
        String order_created = '';
        String order_id = '';
        String deposit_required = '';
        String deposit_due = '';
        String payment_required = '';
        String payment_due = '';
        
        for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
            
            if (childres.getName() == 'order_result')
                order_result = childRes .getText();
            if (childres.getName() == 'id_validated')
                id_validated = childRes .getText(); 
            if (childres.getName() == 'order_created')
                order_created = childRes .getText();
            if (childres.getName() == 'order_id')
                order_id = childRes .getText(); 
            if (childres.getName() == 'deposit_required')
                deposit_required = childRes .getText(); 
            if (childres.getName() == 'deposit_due')
                deposit_due = childRes .getText();  
            if (childres.getName() == 'payment_required')
                payment_required = childRes .getText();
            if (childres.getName() == 'payment_due')
                payment_due = childRes .getText();  
            if (childres.getName() == 'active_order_id')
                order_id = childres.getText();        
            
            orderResponse1.add(childres.getName());
            orderResponse.add(childRes .getText());
        }
        system.debug( order_result );
        system.debug(id_validated );
        system.debug(order_created );
        system.debug(order_id );
        system.debug(deposit_required );
        system.debug(deposit_due );
        system.debug(payment_required );
        system.debug(payment_due  );
        
        /*
<type>order_result</type>
<id_validated>validated</id_validated>
<order_created>1</order_created>
<order_id>502920</order_id>
<deposit_required>0</deposit_required>
<deposit_due>0.00</deposit_due>
<payment_required>0</payment_required>
<payment_due>0.00</payment_due>
*/
        if( id_validated == 'nomatch')
        {
            System.debug('order Error ssn not match');
            
            order.failure_reason__c = 'nomatch';
            
            order.order_status__c = 'Pending';
            update order;
            
        }
        
        
        // if (orderResponse[1] == '0' && order_id == '')
        if ( order_id == '')
        {
            System.debug('order Error');
            
            order.failure_reason__c = orderResponse[2];
            
            order.order_status__c = 'Pending';
            update order;
            
            //}else if(orderResponse[1] == '0' && order_id != ''){
        }else if( order_id != ''){	
            
            order.reporderid__c = order_id; 
            
            if( id_validated == 'validated' || order_id != '')
            {
                order.Order_Status__c =  'Approved Pending Confirmation';
                order.REPStatus__c = id_validated;
            }
            if(  deposit_required == '1' && id_validated != 'nomatch')
            {
                order.Order_status__c =  'Approved Pending Deposit';
                order.Deposit_Requested__c = true;
                order.Deposit__c = Decimal.valueof(deposit_due);
            }
            list<BusinessHours> REPhours2 = [select id from BusinessHours where name = 'REP SLA']; //Finds the REP business hours 
            if (REPhours2.size() == 0) REPhours2 = [select id from BusinessHours where isDefault = true];  //just in case, uses our org's default hours.
            order.Order_Expiration_Date__c = BusinessHours.add(REPhours2[0].id, system.today(), 18*60*60*1000L); 
            
            update order;
        }
        
        upsert log;
        
    }
    
    
    public String makePayment(Order__c order)
    {
        
        
        Order__c orderId = [select reporderid__c,Deposit__c from order__c where Id = :order.id limit 1];
        
        HttpRequest req = new HttpRequest();
        String token;
        if(!Test.isRunningTest()){
            //RC Added to prevent web callouts from test class
            system.debug('Inside');
            token = gettoken();
        }
        
        //req.setEndpoint('http://174.36.54.131/test-api/api-ng/place-order.php');
        //req.setEndpoint('http://199.168.175.28/test-api/api-ng/place-order.php');
        // req.setEndpoint('https://www.bounceenergy.com/api-ng/place-order.php');
        trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        
        req.setEndPoint(tcsv.bounce__c);
        req.setMethod('POST');
        String username = 'testuser';
        String password = '@p1T3st';
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'BASIC ' +
            EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        String body ='bounce_xml='+
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>login</type>'
            +'<username>centerpoint</username>' 
            +'<password>7kbzlhSw</password> '
            +'</request> '
            +'</bounce_api> ';
        
        
        
        
        
        
        String body1 ='bounce_xml='+   
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>make_payment</type>'
            +'<token>'+token+'</token>'
            +'</request>'
            +'<payment>'
            +'<order_id>'+orderId.reporderid__c+'</order_id>'
            +'<auto_pay>0</auto_pay>'
            +'<payment_type>creditcard</payment_type>'
            +'<cc_num>'+order.Payment_Card_Number__c+'</cc_num>'
            +'<cc_type>'+order.Payment_Card_Type__c+'</cc_type>'
            +'<cc_exp_month>'+order.Payment_Card_Month__c+'</cc_exp_month>'
            +'<cc_exp_year>'+order.Payment_Card_Year__c+'</cc_exp_year>'
            +'<cc_sec_code>'+order.Payment_Card_3_digit_code__c+'</cc_sec_code>'
            +'<cc_holder_name>'+order.Name_as_it_appears_on_Payment_Card__c+'</cc_holder_name>'
            +'<payment_addr1>'+order.Payment_Card_Address_Line_1__c+'</payment_addr1>'
            +'<payment_addr2></payment_addr2>'
            +'<payment_city>'+order.Payment_Card_Address_City__c+'</payment_city>'
            +'<payment_state>'+order.Payment_Card_Address_State__c+'</payment_state>'
            +'<payment_zip>'+order.Payment_Card_Address_Zip__c+'</payment_zip>'
            +'<deposit_amount>'+orderId.Deposit__c+'</deposit_amount>'
            +'</payment>'
            +'</bounce_api>';
        
        System.debug('req'+body1);
        
        req.setbody(body1);
        
        Http http1 = new Http();
        
        HTTPResponse res1 = http1.send(req);
        System.debug(res1.getBody());
        /*
<bounce_api>
<response>
<type>order_result</type>
<order_valid>0</order_valid>
<error_msg>Esid is active</error_msg>
<active_order_id>374249</active_order_id>
</response>
</bounce_api>
*/
        //Handle response
        List<String> orderResponse =new List<String>();
        List<String> orderResponse1 =new List<String>();
        Dom.Document docRes = new Dom.Document();
        
        docRes.load(res1.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode EnvelopeRes = docRes.getRootElement();
        
        Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
        
        system.debug('raw response' +res1.getBody());
        system.debug('raw response' +BodyRes);
        String order_result = '';
        string id_validated = '';
        String order_created = '';
        String order_id = '';
        String deposit_required = '';
        String deposit_due = '';
        String payment_required = '';
        String payment_due = '';
        String authCode = '';
        String result   = '';
        for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
            
            if (childres.getName() == 'auth_code')
                authcode = childRes .getText();
            if (childres.getName() == 'result')
                result = childRes .getText();   
            
            
            orderResponse1.add(childres.getName());
            orderResponse.add(childRes .getText());
        }
        system.debug('orderresponse'+ orderresponse);
        system.debug( 'authcode'+ authcode );
        system.debug( 'result'+ result );
        
        if ( result == '1')
            order.Order_Status__c = 'Confirmed';
        
        
        update order;
        return 'order';
        
        
        
    }
    @Future(callout=true)
    public static void getOrderStatus()
    {
        //token
        String token = '';
        try{
            HttpRequest req = new HttpRequest();
            
            
            trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
            
            req.setEndPoint(tcsv.bounce__c);
            
            req.setMethod('POST');
            String username = 'centerpoint';
            String password = '7kbzlhSw';
            Blob headerValue = Blob.valueOf(username + ':' + password);
            String authorizationHeader = 'BASIC ' +
                EncodingUtil.base64Encode(headerValue);
            req.setHeader('Authorization', authorizationHeader);
            String body ='bounce_xml='+
                +'<?xml version=\"1.0\"?>'
                +'<bounce_api>' 
                +'<request>'
                +'<type>login</type>'
                +'<username>centerpoint</username>' 
                +'<password>7kbzlhSw</password> '
                +'</request> '
                +'</bounce_api> ';
            
            
            
            req.setbody(body);
            
            
            Http http = new Http();
            HTTPResponse res = http.send(req);
            System.debug(res.getBody());
            
            
            List<String> orgInfo=new List<String>();
            
            Dom.Document doc = new Dom.Document();
            
            doc.load(res.getBody());
            
            //Retrieve the root element for this document.
            
            Dom.XMLNode Envelope = doc.getRootElement();
            
            Dom.XMLNode Body1= Envelope.getChildElements()[0];
            
            string user_createResult = '';
            
            
            
            for(Dom.XMLNode child : Body1.getChildElements()) {
                
                orgInfo.add(child .getText());
            }
            system.debug(orginfo);
            
            token =  orginfo[2];
        }
        catch(exception e)
        {
            system.debug(e);
        }
        //end token
        List<Order__c> order = [select a.id,a.order_status__c,a.reporderid__c from order__c a where a.order_status__c = 'Approved Pending Confirmation' and a.rep_profile__r.name = 'Bounce Energy' limit 4 ];
        system.debug('order'+order);
        List<order__c> updateOrder = new List<order__c>();
        for (Order__c ord : order){
            HttpRequest req = new HttpRequest();
            
            //req.setEndpoint('http://174.36.54.131/test-api/api-ng/place-order.php');
            //req.setEndpoint('http://199.168.175.28/test-api/api-ng/place-order.php');
            //req.setEndpoint('https://www.bounceenergy.com/api-ng/place-order.php');
            trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
            
            req.setEndPoint(tcsv.bounce__c);
            req.setMethod('POST');
            String username = 'testuser';
            String password = '@p1T3st';
            Blob headerValue = Blob.valueOf(username + ':' + password);
            String authorizationHeader = 'BASIC ' +
                EncodingUtil.base64Encode(headerValue);
            req.setHeader('Authorization', authorizationHeader);
            String body ='bounce_xml='+
                +'<?xml version=\"1.0\"?>'
                +'<bounce_api>' 
                +'<request>'
                +'<type>login</type>'
                +'<username>centerpoint</username>' 
                +'<password>7kbzlhSw</password> '
                +'</request> '
                +'</bounce_api> ';
            
            
            
            
            System.debug('Token' + token);
            /*
<bounce_api>
<request>
<type>get_order_status</type>
<token>3409adfjm34rlaedflk34r45</token>
<order_id>123456</order_id>
</request>
</bounce_api>       
*/        
            
            
            
            String body1 ='bounce_xml='+   
                +'<?xml version=\"1.0\"?>'
                +'<bounce_api>' 
                +'<request>'
                +'<type>get_order_status</type>'
                +'<token>'+token+'</token>'
                +'<order_id>'+ord.reporderid__c+'</order_id>'
                +'</request>'
                +'</bounce_api>';
            
            System.debug('req'+body1);
            
            req.setbody(body1);
            
            Http http1 = new Http();
            
            HTTPResponse res1 = http1.send(req);
            System.debug(res1.getBody());
            /*
<bounce_api>
<response>
<type>order_result</type>
<order_valid>0</order_valid>
<error_msg>Esid is active</error_msg>
<active_order_id>374249</active_order_id>
</response>
</bounce_api>
<bounce_api>
<response>
<type>order_status</type>
<order_id>123456</order_id>
<order_status_id>17</order_status_id>
<order_status_description>accepted</order_status_description>
</response>
</bounce_api>
*/
            //Handle response
            List<String> orderResponse =new List<String>();
            List<String> orderResponse1 =new List<String>();
            Dom.Document docRes = new Dom.Document();
            
            docRes.load(res1.getBody());
            
            //Retrieve the root element for this document.
            
            Dom.XMLNode EnvelopeRes = docRes.getRootElement();
            
            Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
            
            system.debug('raw response' +res1.getBody());
            system.debug('raw response' +BodyRes);
            String order_result = '';
            string id_validated = '';
            String order_created = '';
            String order_id = '';
            String deposit_required = '';
            String deposit_due = '';
            String payment_required = '';
            String payment_due = '';
            String authCode = '';
            String result   = '';
            String orderStatus = '';
            String orderStatusDescription = '';
            for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
                
                if (childres.getName() == 'order_status_id')
                    orderStatus = childRes .getText();
                if (childres.getName() == 'order_status_description')
                    orderStatusDescription = childRes .getText();   
                
                
                orderResponse1.add(childres.getName());
                orderResponse.add(childRes .getText());
            }
            system.debug('orderresponse'+ orderresponse);
            system.debug( 'authcode'+ authcode );
            system.debug( 'result'+ result );
            
            if ( orderStatusDescription == 'accepted') 
                ord.Order_Status__c = 'Confirmed';
            
            if ( orderStatusDescription == 'declined') 
                ord.Order_Status__c = 'Rejected';
            
            if ( orderStatusDescription == 'pending') 
                ord.Order_Status__c = 'Pending';  
            
            updateOrder.add(ord);
            //update ord;
            
        }  	
        update updateOrder;
        /*
Get Order Status
Request:
Response:


<bounce_api>
<request>
<type>get_order_status</type>
<token>3409adfjm34rlaedflk34r45</token>
<order_id>123456</order_id>
</request>
</bounce_api>



<bounce_api>
<response>
<type>order_status</type>
<order_id>123456</order_id>
<order_status_id>3</order_status_id>
<order_status_description>pending</order_status_description>
</response>
</bounce_api>



<bounce_api>
<response>
<type>order_status</type>
<order_id>123456</order_id>
<order_status_id>17</order_status_id>
<order_status_description>accepted</order_status_description>
</response>
</bounce_api>



<bounce_api>
<response>
<type>order_status</type>
<order_id>123456</order_id>
<order_status_id>9</order_status_id>
<order_status_description>declined</order_status_description>
</response>
</bounce_api>
*/
        
    }
    
    public  void orderstat(string name){  	
        Order__c order = [select a.id,a.order_status__c,a.reporderid__c from order__c a where a.name =: name and a.rep_profile__r.name = 'Bounce Energy'  limit 1];
        system.debug('order'+order);
        HttpRequest req = new HttpRequest();
        String token;
        if(!Test.isRunningTest()){
            //RC Added to prevent web callouts from test class
            //system.debug('Inside');
            token = gettoken();
        }
        //req.setEndpoint('http://174.36.54.131/test-api/api-ng/place-order.php');
        //req.setEndpoint('http://199.168.175.28/test-api/api-ng/place-order.php');
        //req.setEndpoint('https://www.bounceenergy.com/api-ng/place-order.php');
        trueCostSystemVariables__c tcsv = TrueCostSystemVariables__c.getOrgDefaults();
        
        req.setEndPoint(tcsv.bounce__c);
        req.setMethod('POST');
        String username = 'testuser';
        String password = '@p1T3st';
        Blob headerValue = Blob.valueOf(username + ':' + password);
        String authorizationHeader = 'BASIC ' +
            EncodingUtil.base64Encode(headerValue);
        req.setHeader('Authorization', authorizationHeader);
        String body ='bounce_xml='+
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>login</type>'
            +'<username>centerpoint</username>' 
            +'<password>7kbzlhSw</password> '
            +'</request> '
            +'</bounce_api> ';
        
        
        
        
        System.debug('Token' + token);
        
        
        
        String body1 ='bounce_xml='+   
            +'<?xml version=\"1.0\"?>'
            +'<bounce_api>' 
            +'<request>'
            +'<type>get_order_status</type>'
            +'<token>'+token+'</token>'
            +'<order_id>'+order.reporderid__c+'</order_id>'
            +'</request>'
            +'</bounce_api>';
        
        System.debug('req'+body1);
        
        req.setbody(body1);
        
        Http http1 = new Http();
        
        HTTPResponse res1 = http1.send(req);
        System.debug(res1.getBody());
        
        //Handle response
        List<String> orderResponse =new List<String>();
        List<String> orderResponse1 =new List<String>();
        Dom.Document docRes = new Dom.Document();
        
        docRes.load(res1.getBody());
        
        //Retrieve the root element for this document.
        
        Dom.XMLNode EnvelopeRes = docRes.getRootElement();
        
        Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
        
        system.debug('raw response' +res1.getBody());
        system.debug('raw response' +BodyRes);
        String order_result = '';
        string id_validated = '';
        String order_created = '';
        String order_id = '';
        String deposit_required = '';
        String deposit_due = '';
        String payment_required = '';
        String payment_due = '';
        String authCode = '';
        String result   = '';
        String orderStatus = '';
        String orderStatusDescription = '';
        for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
            
            if (childres.getName() == 'order_status_id')
                orderStatus = childRes .getText();
            if (childres.getName() == 'order_status_description')
                orderStatusDescription = childRes .getText();   
            
            
            orderResponse1.add(childres.getName());
            orderResponse.add(childRes .getText());
        }
        system.debug('orderresponse'+ orderresponse);
        system.debug( 'authcode'+ authcode );
        system.debug( 'result'+ result );
        
        if ( orderStatusDescription == 'accepted') 
            order.Order_Status__c = 'Confirmed';
        
        if ( orderStatusDescription == 'declinded') 
            order.Order_Status__c = 'Rejected';
        
        //  update order;
        
        
        
        
        
        
        
    }
}