force-app/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <description>Template for Glossary, fee, or other content item.</description>
    <label>Content Item</label>
    <nameField>
        <label>Content Item Term/Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_Item__c/fields/Deck__c.field-meta.xml
<CustomField>
    <fullName>Deck__c</fullName>
    <description>The deck or subtitle.  Only appears to customers if deck=true on the contentviewer component</description>
    <inlineHelpText>The deck or subtitle.  Only appears to customers if deck=true on the contentviewer component</inlineHelpText>
    <label>Deck</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Definition__c.field-meta.xml
<CustomField>
    <fullName>Definition__c</fullName>
    <label>Definition</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Published__c.field-meta.xml
<CustomField>
    <fullName>Published__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this content available to the TrueCost website?</description>
    <inlineHelpText>Is this content available to the TrueCost website?</inlineHelpText>
    <label>Published</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title for the content item.  May be used by the content viewer component and visible to the users only if the page declaration says to show the title.</description>
    <inlineHelpText>Title for the content item.  May be used by the content viewer component and visible to the users only if the page declaration says to show the title.</inlineHelpText>
    <label>Title</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ControllerforContentItems.cls
/*
1/24/2012   Shane McLaughlin        Added if statement for control of whether only approved content can be shown
*/

public class ControllerforContentItems {    
    public string whichcontent {get;set;}
    public content_item__c thecontent {get;set;}
    
    public content_item__c getmycontent(){  
        list<content_item__c>thecontentlist = new list<content_item__c>();  
        if(TrueCostUtilities.showOnlyPublished()){
            thecontentlist = [select Definition__c, title__c, deck__c from content_item__c where name =: whichcontent and published__c = true limit 1];
        }   else{
                thecontentlist = [select Definition__c, title__c, deck__c from content_item__c where name =: whichcontent limit 1];
            }
        
        
        if (thecontentlist.size()>0) {thecontent=ContentRewriter.Rewrite(thecontentlist)[0];}        
        return thecontent;
        
    }
    
}