force-app/main/default/objects/Content_Item__c/Content_Item__c.object-meta.xml
<CustomObject>
    <description>Template for Glossary, fee, or other content item.</description>
    <label>Content Item</label>
    <nameField>
        <label>Content Item Term/Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Content Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_Item__c/fields/fee__c.field-meta.xml
<CustomField>
    <fullName>fee__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is the term/item fee-related?</description>
    <inlineHelpText>Is the term/item fee-related?</inlineHelpText>
    <label>Fee?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Content_Item__c/fields/Glossary_Term__c.field-meta.xml
<CustomField>
    <fullName>Glossary_Term__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this a general glossary term/item?</description>
    <inlineHelpText>Is this a general glossary term/item?</inlineHelpText>
    <label>Glossary Term?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FAQ__c/FAQ__c.object-meta.xml
<CustomObject>
    <description>Frequently Asked Questions</description>
    <label>FAQ</label>
    <nameField>
        <label>FAQ Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FAQ</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>What category does this question belong to?</description>
    <inlineHelpText>What category does this question belong to?</inlineHelpText>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Enrollment</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>REPs</fullName>
            </value>
            <value>
                <fullName>About TrueCost</fullName>
            </value>
            <value>
                <fullName>Fees</fullName>
            </value>
            <value>
                <fullName>Glossary</fullName>
            </value>
            <value>
                <fullName>Switching</fullName>
            </value>
            <value>
                <fullName>Plans</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>CenterPoint Energy</fullName>
            </value>
            <value>
                <fullName>Texas Electric Market</fullName>
            </value>
            <value>
                <fullName>Small Business</fullName>
            </value>
            <value>
                <fullName>SourceGas Information</fullName>
            </value>
            <value>
                <fullName>Getting Started</fullName>
            </value>
            <value>
                <fullName>Pricing and Fees</fullName>
            </value>
            <value>
                <fullName>Switching Electric Companies</fullName>
            </value>
            <value>
                <fullName>Technical Support</fullName>
            </value>
            <value>
                <fullName>Natural Gas Basics</fullName>
            </value>
            <value>
                <fullName>Moving</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Public__c.field-meta.xml
<CustomField>
    <fullName>Public__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this FAQ allowed on the TrueCost website?</description>
    <inlineHelpText>Is this FAQ allowed on the TrueCost website?</inlineHelpText>
    <label>Public</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FAQ__c/fields/Top_FAQ__c.field-meta.xml
<CustomField>
    <fullName>Top_FAQ__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Top FAQs display on the home FAQ page instead in addition to being found underneath their category</description>
    <inlineHelpText>Top FAQs display on the home FAQ page instead in addition to being found underneath their category</inlineHelpText>
    <label>Top FAQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Fee__c/Fee__c.object-meta.xml
<CustomObject>
    <description>Fees are maintained by the TrueCost administrators</description>
    <label>TDSP Fee</label>
    <nameField>
        <label>Fee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TDSP Fees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SupportLinks_Test.cls
@isTest
private class SupportLinks_Test{       
    static testMethod void testTheComponent(){
    
        faq__c faq = new faq__c(Public__c = true,category__c = 'test',top_faq__c = true);
        insert faq;
        
        content_item__c item = new content_item__c(glossary_term__c = true, fee__c = true);
        insert item;
        
        PageReference pageRef = page.faq;
        pageRef.getParameters().put('cat','test');
        test.setCurrentPage(PageRef);
        supportlinks controller = new supportlinks();
        controller.getUniqueCategoriesList();
        controller.getTopFaq();
        controller.getTCFaq();
        controller.togglefees();
        controller.toggleFAQ();
        controller.toggleGlossary();
        controller.GetFullAlphabetFee();
        controller.GetFullAlphabetGlossary();
        controller.getAllFaq();
        controller.getAllFee();
        controller.getAllGlossary();
        controller.getresponselist();
        controller.getGlossaryAlpha();
        controller.getglossarylist();
        controller.getThePage();
        controller.getFeeAlpha();
    }
}