force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>Where to send the customer&#39;s bill</description>
    <inlineHelpText>Where to send the customer&#39;s bill</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What plan did the customer sign up for?</description>
    <inlineHelpText>What plan did the customer sign up for?</inlineHelpText>
    <label>Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plan__c.REP_Profile__c</field>
            <operation>equals</operation>
            <valueField>$Source.REP_Profile__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TDSP__c.field-meta.xml
<CustomField>
    <fullName>TDSP__c</fullName>
    <label>TDSP</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Business_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Business_Start_Date__c</fullName>
    <description>When did you start serving the Texas retail electric market?</description>
    <inlineHelpText>When did you start serving the Texas retail electric market?</inlineHelpText>
    <label>Business Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Customer_Service_Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Customer_Service_Phone_Number__c</fullName>
    <description>What number should TrueCost customers use to contact you about their account?</description>
    <inlineHelpText>What number should TrueCost customers use to contact you about their account?</inlineHelpText>
    <label>Customer Service Phone Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Deposit_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Instructions__c</fullName>
    <description>What steps should a customer follow to pay a deposit?  This will be sent to customers via email.</description>
    <inlineHelpText>What steps should a customer follow to pay a deposit?  This will be sent to customers via email.</inlineHelpText>
    <label>Deposit Instructions</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Escalated_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Issues_Email__c</fullName>
    <description>Email for any other issues requiring QUICK response.</description>
    <inlineHelpText>Email for any other issues requiring QUICK response.</inlineHelpText>
    <label>Escalated Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Escalated_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>Escalated_Issues_Phone__c</fullName>
    <description>Phone number for any other issues requiring QUICK response.</description>
    <inlineHelpText>Phone number for any other issues requiring QUICK response.</inlineHelpText>
    <label>Escalated Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/General_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>General_Issues_Email__c</fullName>
    <description>Email for when REP response is needed for bill, plan, or rewards questions.</description>
    <inlineHelpText>Email for when REP response is needed for bill, plan, or rewards questions.</inlineHelpText>
    <label>General Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/General_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>General_Issues_Phone__c</fullName>
    <description>Phone number for when REP response is needed for bill, plan, or rewards questions.</description>
    <inlineHelpText>Phone number for when REP response is needed for bill, plan, or rewards questions.</inlineHelpText>
    <label>General Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Home_Page__c.field-meta.xml
<CustomField>
    <fullName>Home_Page__c</fullName>
    <description>Enter in the url for your home page.</description>
    <inlineHelpText>Enter in the url for your home page.</inlineHelpText>
    <label>Home Page</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Legal_Name__c.field-meta.xml
<CustomField>
    <fullName>Legal_Name__c</fullName>
    <description>Full legal name of REP</description>
    <inlineHelpText>Full legal name of REP</inlineHelpText>
    <label>Legal Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_City__c.field-meta.xml
<CustomField>
    <fullName>Mailing_City__c</fullName>
    <label>Mailing City</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Street_Address__c</fullName>
    <description>mailing address</description>
    <inlineHelpText>presented to customers per PUCT rules</inlineHelpText>
    <label>Mailing Street Address</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Mailing_Zip__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Zip__c</fullName>
    <label>Mailing Zip</label>
    <length>10</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Maximum_Switch_Days__c.field-meta.xml
<CustomField>
    <fullName>Maximum_Switch_Days__c</fullName>
    <defaultValue>90</defaultValue>
    <description>How many days in advance can a customer schedule a switch</description>
    <inlineHelpText>How many days in advance can a customer schedule a switch</inlineHelpText>
    <label>Maximum Switch Days</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Order_Issues_Email__c.field-meta.xml
<CustomField>
    <fullName>Order_Issues_Email__c</fullName>
    <description>Email address for cancellation, date change, order errors, inadvertent switch, or other issues.</description>
    <inlineHelpText>Email address for cancellation, date change, order errors, inadvertent switch, or other issues.</inlineHelpText>
    <label>Order Issues Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Order_Issues_Phone__c.field-meta.xml
<CustomField>
    <fullName>Order_Issues_Phone__c</fullName>
    <description>Phone number for cancellation, date change, order errors, inadvertent switch,or other issues.</description>
    <inlineHelpText>Phone number for cancellation, date change, order errors, inadvertent switch,or other issues.</inlineHelpText>
    <label>Order Issues Phone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/PUC_Scorecard_Ranking__c.field-meta.xml
<CustomField>
    <fullName>PUC_Scorecard_Ranking__c</fullName>
    <description>1-5 ranking from http://www.powertochoose.org/scorecard/Scorecard.pdf</description>
    <inlineHelpText>1-5 ranking from http://www.powertochoose.org/scorecard/Scorecard.pdf</inlineHelpText>
    <label>PUC Scorecard Ranking</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
                <default>true</default>
                <label>3</label>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Soonest_Move_Date__c.field-meta.xml
<CustomField>
    <fullName>Soonest_Move_Date__c</fullName>
    <defaultValue>3</defaultValue>
    <description>How soon can a customer be moved from now (in days)?  0 means today, 1 means tomorrow, etc.</description>
    <inlineHelpText>How soon can a customer be moved from now (in days)?  0 means today, 1 means tomorrow, etc.</inlineHelpText>
    <label>Soonest Move Date Available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Soonest_Switch_Date__c.field-meta.xml
<CustomField>
    <fullName>Soonest_Switch_Date__c</fullName>
    <defaultValue>3</defaultValue>
    <description>How soon can a customer be switched from now (in days)?  0 means today, 1 means tomorrow, etc.</description>
    <inlineHelpText>How soon can a customer be switched from now (in days)?  0 means today, 1 means tomorrow, etc.</inlineHelpText>
    <label>Soonest Switch Date Available</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/fields/Star_ranking__c.field-meta.xml
<CustomField>
    <fullName>Star_ranking__c</fullName>
    <defaultValue>000.50</defaultValue>
    <description>How do your customer-given star ratings compare to other REPs on TrueCost?  The higher the percentage, the higher your approval is versus other REPs.</description>
    <inlineHelpText>How do your customer-given star ratings compare to other REPs on TrueCost?  The higher the percentage, the higher your approval is versus other REPs.</inlineHelpText>
    <label>Star Ranking</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/classes/ChatterUtilsTest.cls
@isTest
public class ChatterUtilsTest {
	
	@isTest(seeAllData=true) static void testsimpleTextPostToRecord() {	
        // mccann fix by staging test data
        REP_Profile__c r = new REP_Profile__c();
        r.Name = 'Test Rep';
        r.Legal_Name__c = 'Test Legal';
        r.Business_Start_Date__c = Date.newInstance(2012, 12, 12);
        r.Star_ranking__c = .01;
        r.PUC_Scorecard_Ranking__c = '3';
        r.Deposit_Instructions__c = 'deposit';
        r.Maximum_Switch_Days__c = 1;
        r.Soonest_Switch_Date__c = 1;
        r.Soonest_Move_Date__c = 1;
        r.Mailing_Street_Address__c = '123 st';
        r.Mailing_City__c = 'Houston';
        r.Mailing_Zip__c = '77042';
        r.Customer_Service_Phone_Number__c = '7135551234';
        r.Home_Page__c = 'www.url.com';
        r.Order_Issues_Email__c = 'email@test.com';
        r.Order_Issues_Phone__c = '2818320884';
        r.General_Issues_Email__c = 'email2@test.com';
        r.General_Issues_Phone__c = '8325551234';
        r.Escalated_Issues_Email__c = 'email3@test.com';
        r.Escalated_Issues_Phone__c = '7135554321';
        insert r;
        
        Id planrType = Schema.SObjectType.Plan__c.getRecordTypeInfosByName().get('C&I Product').getRecordTypeId();
        Id utilrType = Schema.SObjectType.TDSP__c.getRecordTypeInfosByName().get('TDSP').getRecordTypeId();
        
        TDSP__c testUtility = new TDSP__c(Name='Test Util 1');
        insert testUtility;
        
        Plan__c p = new Plan__c();
        p.RecordTypeId = planrType;
        p.Name = 'Test Plan';
        p.REP_Profile__c = r.Id;
        insert p;
        
        Rate__c rt = new Rate__c();
        rt.Plan__c = p.Id;
        rt.Name = 'Test Rate5';
        rt.TDSP__c = testUtility.Id;
        rt.Minimum_Annual_Usage__c = 1;
        rt.Maximum_Annual_Usage__c = 1;
        rt.Energy_Base_Rate_cents__c = 1;
        rt.non_demand_1500_kWh_rate_cents__c = 1;
        rt.non_demand_2500_kWh_rate_cents__c = 1;
        rt.non_demand_3500_kWh_rate_cents__c = 1;
        rt.Cancellation_Fee__c = 10.99;
        rt.Confirmation_Code_Year__c = '2012';
        insert rt;
        
        Order__c o = new Order__c();
        o.Rate__c = rt.Id;
        o.Contract_Length__c = 2;
        o.Confirmation_Code_Year__c = '2012';
        o.REP_Profile__c = r.Id;
        o.Confirmation_Code__c = 'Rate5';
        insert o;
        
		//ChatterUtils.simpleTextPostToRecord([select id from order__c limit 1].id, 'sup record!');
        ChatterUtils.simpleTextPostToRecord(o.id, 'sup record!');
	}
	
	@isTest(seeAllData=true) static void testsimpleTextPost() {
		ChatterUtils.simpleTextPost(TrueCostUtilities.lookuptheAdmin(), 'sup, admin!');
	}

	@isTest(seeAllData=true) static void testsimpleLinkPost() {
		ChatterUtils.simpleLinkPost(UserInfo.getUserId(), 'it a link', 'www.google.com', 'google');
	}

	@isTest(seeAllData=true) static void testmentionTextPost() {
		ChatterUtils.mentionTextPost(TrueCostUtilities.lookuptheAdmin(), TrueCostUtilities.lookuptheAdmin(), 'sup, dawg');
	}
	
	@isTest(seeAllData=true) static void testmentionOnRecord() {
        // mccann fix by staging test data
        REP_Profile__c r = new REP_Profile__c();
        r.Name = 'Test Rep';
        r.Legal_Name__c = 'Test Legal';
        r.Business_Start_Date__c = Date.newInstance(2012, 12, 12);
        r.Star_ranking__c = .01;
        r.PUC_Scorecard_Ranking__c = '3';
        r.Deposit_Instructions__c = 'deposit';
        r.Maximum_Switch_Days__c = 1;
        r.Soonest_Switch_Date__c = 1;
        r.Soonest_Move_Date__c = 1;
        r.Mailing_Street_Address__c = '123 st';
        r.Mailing_City__c = 'Houston';
        r.Mailing_Zip__c = '77042';
        r.Customer_Service_Phone_Number__c = '7135551234';
        r.Home_Page__c = 'www.url.com';
        r.Order_Issues_Email__c = 'email@test.com';
        r.Order_Issues_Phone__c = '2818320884';
        r.General_Issues_Email__c = 'email2@test.com';
        r.General_Issues_Phone__c = '8325551234';
        r.Escalated_Issues_Email__c = 'email3@test.com';
        r.Escalated_Issues_Phone__c = '7135554321';
        insert r;
        
        Id planrType = Schema.SObjectType.Plan__c.getRecordTypeInfosByName().get('C&I Product').getRecordTypeId();
        Id utilrType = Schema.SObjectType.TDSP__c.getRecordTypeInfosByName().get('TDSP').getRecordTypeId();
        
        TDSP__c testUtility = new TDSP__c(Name='Test Util 1');
        insert testUtility;
        
        Plan__c p = new Plan__c();
        p.RecordTypeId = planrType;
        p.Name = 'Test Plan';
        p.REP_Profile__c = r.Id;
        insert p;
        
        Rate__c rt = new Rate__c();
        rt.Plan__c = p.Id;
        rt.Name = 'Test Rate5';
        rt.TDSP__c = testUtility.Id;
        rt.Minimum_Annual_Usage__c = 1;
        rt.Maximum_Annual_Usage__c = 1;
        rt.Energy_Base_Rate_cents__c = 1;
        rt.non_demand_1500_kWh_rate_cents__c = 1;
        rt.non_demand_2500_kWh_rate_cents__c = 1;
        rt.non_demand_3500_kWh_rate_cents__c = 1;
        rt.Cancellation_Fee__c = 10.99;
        rt.Confirmation_Code_Year__c = '2012';
        insert rt;
        
        Order__c o = new Order__c();
        o.Rate__c = rt.Id;
        o.Contract_Length__c = 2;
        o.Confirmation_Code_Year__c = '2012';
        o.REP_Profile__c = r.Id;
        o.Confirmation_Code__c = 'Rate5';
        insert o;
        
		//ChatterUtils.mentionOnRecord([select id from order__c limit 1].id, TrueCostUtilities.lookuptheAdmin(), 'sup, dawg');
		ChatterUtils.mentionOnRecord(o.id, TrueCostUtilities.lookuptheAdmin(), 'sup, dawg');
	}

	@isTest(seeAllData=true) static void testMultiMentionAdmin(){
		ChatterUtils.chatterTheAdmins([select id from account limit 1].id, 'sup admins!');
	}

}