force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REPOrderId__c.field-meta.xml
<CustomField>
    <fullName>REPOrderId__c</fullName>
    <label>REPOrderId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PartnerAPI__c/PartnerAPI__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>PartnerAPI</label>
</CustomObject>

force-app/main/default/objects/PartnerAPI__c/fields/Brand_string__c.field-meta.xml
<CustomField>
    <fullName>Brand_string__c</fullName>
    <description>built for direct energy brands--which namespace does the api use?</description>
    <inlineHelpText>built for direct energy brands--which namespace does the api use?</inlineHelpText>
    <label>Brand string</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/REPAPIChecks.cls
public with sharing class REPAPIChecks {
	
	public static void CheckCirro(){
		orderapimanager vir = new orderapimanager();
		vir.checkcirrostatus();
	}

	public class OrderStatusException extends exception {}

	
	public static void CheckDirectOrder(string orderid){
		order__c o = [select id, order_status__c, reporderid__c, Rep_Profile__r.Name
			from order__c 
			where id=:orderid limit 1];
		system.debug('order'+o);


	//let's get that lovely token
	HttpRequest req = NewLeafAPImrg.BuildTokenRequest(o.Rep_Profile__r.Name);

	String token = '';
	Http http = new Http();
	HTTPResponse res = http.send(req);
	System.debug(res.getBody());
	token = NewLeafAPImrg.parseToken(res);
	System.debug('Token' + token);
	 //End get token call
	

	PartnerAPI__c Papi = PartnerAPI__c.getInstance(o.Rep_Profile__r.Name);
	string repstring = Papi.brand_string__c;

	//req = new HttpRequest();
	String body1 =repstring+'_xml='+
		+'<?xml version=\"1.0\"?>'
			+'<'+repstring+'_api>'
			+'<request>'
			+'<type>get_order_status</type>'
			+'<token>'+token+'</token>'
			+'<order_id>'+o.reporderid__c+'</order_id>'
			+'</request>'
			+'</'+repstring+'_api>';
	
	System.debug('req'+body1);
	
	req.setbody(body1);

	Http http1 = new Http();
	
	HTTPResponse res1 = http1.send(req);
	System.debug(res1.getBody());

	//Handle response
	List<String> orderResponse =new List<String>();
		List<String> orderResponse1 =new List<String>();
	Dom.Document docRes = new Dom.Document();
		
		docRes.load(res1.getBody());
		
		//Retrieve the root element for this document.
		
		Dom.XMLNode EnvelopeRes = docRes.getRootElement();
		
		Dom.XMLNode BodyRes= EnvelopeRes.getChildElements()[0];
		
		system.debug('raw response' +res1.getBody());
		system.debug('raw response' +BodyRes);
		String order_result = '';
		string id_validated = '';
		String order_created = '';
		String order_id = '';
		String deposit_required = '';
		String deposit_due = '';
		String payment_required = '';    
		String payment_due = '';
		String authCode = '';
		String result   = '';
		String orderStatus = '';
		String orderStatusDescription = '';
		for(Dom.XMLNode childRes : BodyRes.getChildElements()) {
			
		if (childres.getName() == 'order_status_id')
			orderStatus = childRes .getText();
		if (childres.getName() == 'order_status_description')
			orderStatusDescription = childRes .getText();   
		
				
		orderResponse1.add(childres.getName());
		orderResponse.add(childRes .getText());
		}
		system.debug('orderresponse'+ orderresponse);
		system.debug( 'authcode'+ authcode );
		system.debug( 'result'+ result );
	
		if ( orderStatusDescription == 'accepted') o.Order_Status__c = 'Confirmed';
		if ( orderStatusDescription == 'declined') o.Order_Status__c = 'Rejected';		  
		
	 update o; //updates that list of orders

	}
}