force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ManageOrders2Controller.cls
public with sharing class ManageOrders2Controller{
    
    list<order__c> orders;
    order__c singleOrder;
    
    public ManageOrders2Controller (ApexPages.StandardSetController stdController){ 
        orders = (list<order__c>)stdController.getSelected();
    }
    
    public ManageOrders2Controller (ApexPages.StandardController stdController){ 
        singleOrder = (order__c)stdController.getRecord();
    }
    
    public PageReference ApproveSingle(){
        singleOrder.order_status__c = 'Approved Pending Confirmation';
        update singleOrder;
        return page.manageOrders2;
    }
    
    public PageReference ConfirmSingle(){
        singleOrder.order_status__c = 'Confirmed';
        update singleOrder;
        return page.manageOrders2;
    }
    
    
    public PageReference Approve(){
        for (order__c o:orders) {
            o.order_status__c = 'Approved Pending Confirmation';
        }	
        update orders;
        return page.manageOrders2;
    }
   
    public PageReference Confirm(){
        for (order__c o:orders) {
            o.order_status__c = 'Confirmed';
        }	
        update orders;
        return page.manageOrders2;
    }
    
    
}