force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Name_as_it_appears_on_Payment_Card__c.field-meta.xml
<CustomField>
    <fullName>Name_as_it_appears_on_Payment_Card__c</fullName>
    <label>Name (as it appears on Payment Card)</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_3_digit_code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_3_digit_code__c</fullName>
    <label>Payment Card 3 digit code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Address_City__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Address_City__c</fullName>
    <label>Payment Card Address City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Address_Line_1__c</fullName>
    <label>Payment Card Address Line 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Address_State__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Address_State__c</fullName>
    <label>Payment Card Address State</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AK</fullName>
            </value>
            <value>
                <fullName>AZ</fullName>
            </value>
            <value>
                <fullName>AR</fullName>
            </value>
            <value>
                <fullName>CA</fullName>
            </value>
            <value>
                <fullName>CO</fullName>
            </value>
            <value>
                <fullName>CT</fullName>
            </value>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FL</fullName>
            </value>
            <value>
                <fullName>GA</fullName>
            </value>
            <value>
                <fullName>HI</fullName>
            </value>
            <value>
                <fullName>ID</fullName>
            </value>
            <value>
                <fullName>IL</fullName>
            </value>
            <value>
                <fullName>IN</fullName>
            </value>
            <value>
                <fullName>IA</fullName>
            </value>
            <value>
                <fullName>KS</fullName>
            </value>
            <value>
                <fullName>KY</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MI</fullName>
            </value>
            <value>
                <fullName>MN</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MO</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>NV</fullName>
            </value>
            <value>
                <fullName>NH</fullName>
            </value>
            <value>
                <fullName>NJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Address_Zip__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Address_Zip__c</fullName>
    <label>Payment Card Address Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Month__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Month__c</fullName>
    <label>Payment Card Expiration Month</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01 - January</fullName>
            </value>
            <value>
                <fullName>02 - February</fullName>
            </value>
            <value>
                <fullName>03 - March</fullName>
            </value>
            <value>
                <fullName>04 - April</fullName>
            </value>
            <value>
                <fullName>05 - May</fullName>
            </value>
            <value>
                <fullName>06 - June</fullName>
            </value>
            <value>
                <fullName>07 - July</fullName>
            </value>
            <value>
                <fullName>08 - August</fullName>
            </value>
            <value>
                <fullName>09 - September</fullName>
            </value>
            <value>
                <fullName>10 - October</fullName>
            </value>
            <value>
                <fullName>11 - November</fullName>
            </value>
            <value>
                <fullName>12 - December</fullName>
            </value>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Number__c</fullName>
    <label>Payment Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Type__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Type__c</fullName>
    <label>Payment Card Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>American Express</fullName>
            </value>
            <value>
                <fullName>Discover</fullName>
            </value>
            <value>
                <fullName>MasterCard</fullName>
            </value>
            <value>
                <fullName>Visa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Year__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Year__c</fullName>
    <label>Payment Card Expiration Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2012</fullName>
            </value>
            <value>
                <fullName>2013</fullName>
            </value>
            <value>
                <fullName>2014</fullName>
            </value>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/PIIViewController.cls
global class PIIViewController{
	
    @RemoteAction
        global static order__c getRemoteREPOrder(string orderid, string flavor){
            if (flavor=='cc'){
            return [SELECT id,
                Payment_Card_3_digit_code__c, Payment_Card_Address_City__c, Payment_Card_Address_Line_1__c,
                Payment_Card_Address_State__c, Payment_Card_Address_Zip__c,  Payment_Card_Month__c, Payment_Card_Year__c, 
                Payment_Card_Number__c, Payment_Card_Type__c, Name_as_it_appears_on_Payment_Card__c 
                from order__c where id =: orderid];
            }
            
            if (flavor=='ssn'){
            	return [SELECT id, ssn__c from order__c where id =: orderid];
            }
            
            return null; //just in case
        }
    
       
    
    
    
}