force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <description>What is the order status</description>
    <inlineHelpText>What is this order&#39;s current status?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Ready To Submit</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Started</fullName>
            </value>
            <value>
                <fullName>Enroll Page - Complete</fullName>
            </value>
            <value>
                <fullName>Plan Disclosures Page - Complete</fullName>
            </value>
            <value>
                <fullName>Default Submitted</fullName>
            </value>
            <value>
                <fullName>Pending Confirmation Code Change</fullName>
            </value>
            <value>
                <fullName>Pending DA</fullName>
            </value>
            <value>
                <fullName>DA Received From Customer</fullName>
            </value>
            <value>
                <fullName>DA Submitted To Utility</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>DA Receipt Acknowledged</fullName>
            </value>
            <value>
                <fullName>New/Successfully Submitted</fullName>
            </value>
            <value>
                <fullName>New Gas Choice Order</fullName>
            </value>
            <value>
                <fullName>Pending Information</fullName>
            </value>
            <value>
                <fullName>Pending Switch Hold</fullName>
            </value>
            <value>
                <fullName>Approved Pending Deposit</fullName>
            </value>
            <value>
                <fullName>Approved Pending Confirmation</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Reversed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Gas Choice Temporary</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
            <value>
                <fullName>Abandoned</fullName>
            </value>
            <value>
                <fullName>Pending API Response</fullName>
            </value>
            <value>
                <fullName>Released</fullName>
            </value>
            <value>
                <fullName>Terminated Early</fullName>
            </value>
            <value>
                <fullName>API Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What plan did the customer sign up for?</description>
    <inlineHelpText>What plan did the customer sign up for?</inlineHelpText>
    <label>Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plan__c.REP_Profile__c</field>
            <operation>equals</operation>
            <valueField>$Source.REP_Profile__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Rate__c.field-meta.xml
<CustomField>
    <fullName>Rate__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Rate</label>
    <referenceTo>Rate__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Plan_ID__c.field-meta.xml
<CustomField>
    <fullName>Plan_ID__c</fullName>
    <description>Code used by the REP to refer to this plan</description>
    <inlineHelpText>Code used by the REP to refer to this plan</inlineHelpText>
    <label>Plan ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Rate__c/Rate__c.object-meta.xml
<CustomObject>
    <description>Pricing within a plan specific to a TDSP</description>
    <label>Rate</label>
    <nameField>
        <label>Rate ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rate__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <description>Which plan is this rate part of?</description>
    <inlineHelpText>Which plan is this rate part of?</inlineHelpText>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Rates</relationshipLabel>
    <relationshipName>Rates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderStatus.cls
@RestResource(urlMapping='/OrderStatus/*')

global  without sharing class  OrderStatus {
    private final order__c o;
    public string ssn;
    
    public OrderStatus(ApexPages.StandardController stdcontroller){ 
        
    }
    
    public string getSSN(){
        order__c myorder= getTheOrder(); 
        return myorder.ssn__c;

    }
    
    public order__c getTheOrder(){
        
        order__c[] o =[select id, SSN__C from order__C where id =: o.id];
        if (o.size()>0) {
            system.debug('============ the order is ============= ' + o[0] );
            return o[0];
        } 
        else {
            return null;
        }
    }
    @HttpGet
global static String doGet() {

            return null;
    

}

@HttpPost
    global static String doPost(RestRequest req, RestResponse res) {
       string repid     = req.params.get('id');
       string orderid   = req.params.get('order');
       string status    = req.params.get('status');
      system.debug('============ the repid is ============= ' + repid  );
        //List<Order__c>  o =[select id, SSN__C from order__c where REP_Profile__c = :order];
        List<Order__c>  back  = new List<Order__c>();
        
        //Plan__r.Plan_ID__c,Rate__r.Name
       Order__c  o  = [SELECT id, Order_Status__c  FROM Order__c where name = :orderid  limit 1 ];
       o.Order_Status__c   = status;
       update o;   
    return JSON.serialize('{"successRequest" :"status changed""}');
        }

    public string getidcheck(){
        id theorder = o.id;
        return theorder;
    }
}