force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>How long is the contract (in months)</description>
    <inlineHelpText>12 for a 12 month contract, 0 for a month to month contract</inlineHelpText>
    <label>Contract Length</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Green_Order__c.field-meta.xml
<CustomField>
    <fullName>Green_Order__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This customer purchased a 100% renewable/green plan.</description>
    <inlineHelpText>This customer purchased a 100% renewable/green plan.</inlineHelpText>
    <label>Green Order?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/kWh_rate_1000__c.field-meta.xml
<CustomField>
    <fullName>kWh_rate_1000__c</fullName>
    <description>For the rate the customer signed up for, what was the PUC 1000 kWh/month rate?</description>
    <inlineHelpText>For the rate the customer signed up for, what was the PUC 1000 kWh/month rate?</inlineHelpText>
    <label>kWh rate 1000</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>What plan did the customer sign up for?</description>
    <inlineHelpText>What plan did the customer sign up for?</inlineHelpText>
    <label>Plan</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Plan__c.REP_Profile__c</field>
            <operation>equals</operation>
            <valueField>$Source.REP_Profile__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Plan_Expiration__c.field-meta.xml
<CustomField>
    <fullName>Plan_Expiration__c</fullName>
    <description>When does the plan from this order expire?</description>
    <inlineHelpText>When does the plan from this order expire?</inlineHelpText>
    <label>Plan Expiration</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which REP was this order placed with?</description>
    <inlineHelpText>Which REP was this order placed with?</inlineHelpText>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plan__c/Plan__c.object-meta.xml
<CustomObject>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>In months, how long is the contract?</description>
    <inlineHelpText>In months, how long is the contract?</inlineHelpText>
    <label>Contract Length (# of months)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Renewable_Content__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Content__c</fullName>
    <description>What percent of the electricity comes from renewable sources?</description>
    <inlineHelpText>What percent of the electricity comes from renewable sources?</inlineHelpText>
    <label>Renewable Content (in %)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/REP_Profile__c.field-meta.xml
<CustomField>
    <fullName>REP_Profile__c</fullName>
    <label>REP Profile</label>
    <referenceTo>REP_Profile__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/REP_Profile__c/REP_Profile__c.object-meta.xml
<CustomObject>
    <label>REP Profile</label>
    <nameField>
        <label>REP Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>REP Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/REP_Profile__c/fields/Curent_CEHE__c.field-meta.xml
<CustomField>
    <fullName>Curent_CEHE__c</fullName>
    <label>Current CEHE Variable Rate (cents)</label>
    <precision>10</precision>
    <scale>5</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RenewalEmailController.cls
public with sharing class RenewalEmailController {
	
	public integer OfferCount {get;set;} //how many plans should there be?
	public string Orderid {get;set;}

	public RenewalEmailController() {		
	}

	public order__c getO(){
		return [select id, first_name__c, last_name__c, rep_profile__r.name, rep_profile__r.id, Plan_Expiration__c, 
			kWh_rate_1000__c, green_order__c
			from order__c
			where id=:Orderid];
	}

	public decimal getVariable(){
		list<rep_profile__c> reps = [select id, Curent_CEHE__c from rep_profile__c 
		where Curent_CEHE__c != null ];
		decimal total=0;
		for(rep_profile__c r:reps){
			total = total + r.Curent_CEHE__c;
		}
		return total/reps.size();
	}

	public list<resultsContainer> getOffers(){
		boolean greenonly = false;
		boolean TwelvePresent=false;

		if (getO().green_order__c) greenonly=true;

		string APAid=ShopRemote.GetAPAfromOrder(Orderid);
		list<resultsContainer> matches = ShopRemote.ShopByAPA(APAid);
		//results containers come back unscored, but with prices.

		if (greenonly){
			matches=greenOnlyFilter(matches);
		}

		for (resultsContainer rc:matches){
			rc.total_score=1/rc.price; //higher price ==> lower score!
		}
		matches.sort(); //sorts them by price
		
		//if last order was 100 renewable
		
		//take the top 3?
		list<resultsContainer> output = new list<resultsContainer>();

		for (integer x=0; x<(math.min(OfferCount, matches.size())); x++){
				output.add(matches[x]);
				if (matches[x].rateplan.plan__r.Contract_Length__c==12) TwelvePresent=true;			
		}

		//if there weren't any 12s in the mix
		if (!TwelvePresent){
			for (integer x=0; x<(matches.size()); x++){
				if (
					matches[x].rateplan.plan__r.Contract_Length__c==12 //it's a 12
					&& //it's not equal to at least one of the other two plans!
					(
						(matches[x].rateplan.plan__r.rep_profile__r.Name != output[0].rateplan.plan__r.rep_profile__r.Name) 
						||
						(matches[x].rateplan.plan__r.rep_profile__r.Name != output[1].rateplan.plan__r.rep_profile__r.Name) 
					)	
				) {
					output[2]=matches[x];
					x=100000;
				}	
			}	
		}

		return output;

	} 

	public static list<resultsContainer> greenOnlyFilter(list<resultsContainer> input){
		list<resultsContainer> output = new list<resultsContainer>();

		for (resultsContainer rc:input){
			if (rc.rateplan.plan__r.Renewable_Content__c==100){
				output.add(rc);
			}
		}
		output.sort();
		return output;

	}
}