force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Contract_Length__c.field-meta.xml
<CustomField>
    <fullName>Contract_Length__c</fullName>
    <description>How long is the contract (in months)</description>
    <inlineHelpText>12 for a 12 month contract, 0 for a month to month contract</inlineHelpText>
    <label>Contract Length</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>TrueCost account for this order.</description>
    <inlineHelpText>TrueCost account for this order.</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders (Parent Account)</relationshipLabel>
    <relationshipName>OrdersPlaced</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/TestControllerforREPOrderProcessing.cls
@istest
 public class TestControllerforREPOrderProcessing {
 
     public static testMethod void setupthedata(){
         account a=new account();
         list<order__c> orderlist = new list<order__c>();
         a.lastname='DummyLastName';
         insert a;
         list<account> alist= [select id from account where lastname = 'DummyLastName' limit 1];
         a=alist[0];
         for (integer x=0; x<25; x++){
            order__c o=new order__c(Parent_account__c=a.id);
                    
            o.contract_length__c = 5;                       
            insert o;
         }
         
         
     }
     static testMethod void loadAPage(){
         PageReference pageRef=page.neworders;
         test.setCurrentPageReference(pageref);
         OrderProcessing TheController= new OrderProcessing();
         TheController.getNewOrderList();
         TheController.getPendingConfirmationOrdersList();
         TheController.getConfirmedOrdersList();
         TheController.Approve();
         TheController.Renew();
         TheController.Confirm();
         TheController.Fail();
         //TheController.FinishFail();
         TheController.Fail();
         TheController.CancelFail();
         //TheController.OrderListResetter();
         TheController.startReject();
         //TheController.FinishReject();
         TheController.startReject();
         TheController.CancelReject();
     }

}

/*
@isTest
private class TestControllerforZipCodeSearch {

    static testMethod void myUnitTest() {
        // TO DO: implement unit test
        string ST='77066';
        PageReference pageRef=Page.CustomerServiceZipCodeCheck;
        Test.setCurrentPageReference(pageRef);
        ControllerforZipCodeSearch myPageCon=new ControllerforZipCodeSearch();
        mypageCon.getSearchText();
        myPageCon.setSearchText(ST);
        myPageCon.search();
        myPageCon.getResult();
        myPageCon.navigate();
        
        
        
    }
}*/