force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>These are Orders (signups with a REP) placed through TrueCost.</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Payment_Card_3_digit_code__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_3_digit_code__c</fullName>
    <label>Payment Card 3 digit code</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Card_Number__c.field-meta.xml
<CustomField>
    <fullName>Payment_Card_Number__c</fullName>
    <label>Payment Card Number</label>
    <length>16</length>
    <maskChar>asterisk</maskChar>
    <maskType>creditCard</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SSN__c.field-meta.xml
<CustomField>
    <fullName>SSN__c</fullName>
    <description>Social Security Number</description>
    <inlineHelpText>Social Security Number</inlineHelpText>
    <label>SSN</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/REPSSNdecryptREST.cls
@RestResource(urlMapping='/OrderSSN/*')

global  without sharing class  REPSSNdecryptREST {
	private final order__c o;
	public string ssn;
	
	public REPSSNdecryptREST(ApexPages.StandardController stdcontroller){ 
		
	}
	
	public string getSSN(){
		order__c myorder= getTheOrder(); 
		return myorder.ssn__c;

	}
	
	public order__c getTheOrder(){
		
		order__c[] o =[select id, SSN__C from order__C where id =: o.id];
		if (o.size()>0) {
			system.debug('============ the order is ============= ' + o[0] );
			return o[0];
		} 
		else {
			return null;
		}
	}
	@HttpGet
global static String doGet() {

			return null;
	

}

@HttpPost
    global static String doPost(RestRequest req, RestResponse res) {
    	string order = req.params.get('id');
    	system.debug('============ the order is ============= ' + order  );
        order__c[] o =[select id, SSN__C,payment_card_number__c,Payment_Card_3_digit_code__c from order__C where id = :order];

		if (o.size()>0) {
			
			system.debug('============ the ssn back is ============= ' + o[0] );
			return 'cc:'+o[0].payment_card_number__c+' ssn:'+ o[0].ssn__c+' 3 dig:'+o[0].Payment_Card_3_digit_code__c;
		} 
		else {
			return null;
		}
    }

	public string getidcheck(){
		id theorder = o.id;
		return theorder;
	}
}