force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Error_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Error_Line_Number__c</fullName>
    <label>Error Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Error_Stack_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Error_Stack_Trace_String__c</fullName>
    <label>Error Stack Trace String</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Process_Date__c.field-meta.xml
<CustomField>
    <fullName>Process_Date__c</fullName>
    <label>Process Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Queueable__c.field-meta.xml
<CustomField>
    <fullName>Queueable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True:  this async is processed by the queueable interface, False: this async is processed by scheduled batch</inlineHelpText>
    <label>Queueable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Slow__c.field-meta.xml
<CustomField>
    <fullName>Slow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</description>
    <inlineHelpText>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</inlineHelpText>
    <label>Slow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApplyClosestWeatherStation</fullName>
            </value>
            <value>
                <fullName>BuildTOULoadProfile</fullName>
            </value>
            <value>
                <fullName>ChatterPostTest</fullName>
            </value>
            <value>
                <fullName>ChatterPostTestParamIsMessage</fullName>
            </value>
            <value>
                <fullName>CheckCirro</fullName>
            </value>
            <value>
                <fullName>CheckContactChangesForCES</fullName>
            </value>
            <value>
                <fullName>CheckDirect</fullName>
            </value>
            <value>
                <fullName>CheckRecordsToSyncExist</fullName>
            </value>
            <value>
                <fullName>CheckSyncBatchStatusForOffice</fullName>
            </value>
            <value>
                <fullName>Choice Position Liquidation Future</fullName>
            </value>
            <value>
                <fullName>CreateChoicePositions</fullName>
            </value>
            <value>
                <fullName>DailyToMonthly</fullName>
            </value>
            <value>
                <fullName>KeepAlive</fullName>
            </value>
            <value>
                <fullName>LockChoiceRate</fullName>
            </value>
            <value>
                <fullName>lowCodeInventory</fullName>
            </value>
            <value>
                <fullName>MakeUHITCleanupCallout</fullName>
            </value>
            <value>
                <fullName>OldScheduledCleanup</fullName>
            </value>
            <value>
                <fullName>PIIfromOrder</fullName>
            </value>
            <value>
                <fullName>PlaceDirectOrder</fullName>
            </value>
            <value>
                <fullName>PlaceTriEagleOrder</fullName>
            </value>
            <value>
                <fullName>ProcessRecordLock</fullName>
            </value>
            <value>
                <fullName>RateExceptionChange</fullName>
            </value>
            <value>
                <fullName>RatingsUpdate</fullName>
            </value>
            <value>
                <fullName>RefreshAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RefreshPartnerAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RemoveExpirationDatesFromPreviousOrders</fullName>
            </value>
            <value>
                <fullName>SetREPofRecord</fullName>
            </value>
            <value>
                <fullName>SetTrueCostOrderRecordType</fullName>
            </value>
            <value>
                <fullName>StaticChoiceCosts</fullName>
            </value>
            <value>
                <fullName>TriEagleOrderCheck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org-wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/Keep_Async_Object_Batch_Running__c.field-meta.xml
<CustomField>
    <fullName>Keep_Async_Object_Batch_Running__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Uncheck this box to pause the async jobs.  To restart them, check the box and then execute the startschedular method</description>
    <inlineHelpText>Uncheck this box to pause the async jobs.  To restart them, check the box and then execute the startschedular method</inlineHelpText>
    <label>Keep Async Object Batch Running</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RepeatingBatch2.cls
global class RepeatingBatch2 implements Database.Batchable<sObject>, Database.AllowsCallouts {
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator('Select ID, Params__c, type__c, Error_Message__c, Error_Stack_Trace_String__c, Error_Line_Number__c, Process_Date__c, Retry_Count__c, Queueable__c from AsyncRequest__c where slow__c=false and queueable__c=false and (Process_Date__c = null or Process_Date__c <= ' + string.valueOf(date.today())+')');
    }
        
    global void execute(Database.BatchableContext BC, List<AsyncRequest__c> scope){
        AsyncRequestProcessor.processAsyncRequest(scope);
        //delete scope;
    }
    
    global void finish(Database.BatchableContext BC){
        //what creator of an autonomous AI doesn't at some point wish they'd included a kill switch?
        if (OrgWideSettings__c.GetOrgDefaults().Keep_Async_Object_Batch_Running__c){
        	ScheduleHandler.StartScheduler(0);
        }
    }
    
    public static void StartTheBatch()
    {
        RepeatingBatch2 rb = new RepeatingBatch2();
        Database.executeBatch(rb, 1);
    }
}