force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApplyClosestWeatherStation</fullName>
            </value>
            <value>
                <fullName>BuildTOULoadProfile</fullName>
            </value>
            <value>
                <fullName>ChatterPostTest</fullName>
            </value>
            <value>
                <fullName>ChatterPostTestParamIsMessage</fullName>
            </value>
            <value>
                <fullName>CheckCirro</fullName>
            </value>
            <value>
                <fullName>CheckContactChangesForCES</fullName>
            </value>
            <value>
                <fullName>CheckDirect</fullName>
            </value>
            <value>
                <fullName>CheckRecordsToSyncExist</fullName>
            </value>
            <value>
                <fullName>CheckSyncBatchStatusForOffice</fullName>
            </value>
            <value>
                <fullName>Choice Position Liquidation Future</fullName>
            </value>
            <value>
                <fullName>CreateChoicePositions</fullName>
            </value>
            <value>
                <fullName>DailyToMonthly</fullName>
            </value>
            <value>
                <fullName>KeepAlive</fullName>
            </value>
            <value>
                <fullName>LockChoiceRate</fullName>
            </value>
            <value>
                <fullName>lowCodeInventory</fullName>
            </value>
            <value>
                <fullName>MakeUHITCleanupCallout</fullName>
            </value>
            <value>
                <fullName>OldScheduledCleanup</fullName>
            </value>
            <value>
                <fullName>PIIfromOrder</fullName>
            </value>
            <value>
                <fullName>PlaceDirectOrder</fullName>
            </value>
            <value>
                <fullName>PlaceTriEagleOrder</fullName>
            </value>
            <value>
                <fullName>ProcessRecordLock</fullName>
            </value>
            <value>
                <fullName>RateExceptionChange</fullName>
            </value>
            <value>
                <fullName>RatingsUpdate</fullName>
            </value>
            <value>
                <fullName>RefreshAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RefreshPartnerAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RemoveExpirationDatesFromPreviousOrders</fullName>
            </value>
            <value>
                <fullName>SetREPofRecord</fullName>
            </value>
            <value>
                <fullName>SetTrueCostOrderRecordType</fullName>
            </value>
            <value>
                <fullName>StaticChoiceCosts</fullName>
            </value>
            <value>
                <fullName>TriEagleOrderCheck</fullName>
            </value>
            <value>
                <fullName>TrueCostLoginTracking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Facebook_ID__c.field-meta.xml
<CustomField>
    <fullName>Facebook_ID__c</fullName>
    <label>Facebook ID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/FacebookSSOLoginOnly.cls
global class FacebookSSOLoginOnly implements Auth.RegistrationHandler{

    global User createUser(Id portalId, Auth.UserData data){
        string extension = [select username from user where id = '00530000004bSMC'].UserName.substringAfterLast('.');
        system.debug(extension);
        user u;
        List<User> l = [SELECT Id FROM User WHERE UserName = :data.email or UserName = :(data.email+'.'+extension)];
            if (l.size() > 0) {
                u = l[0];
                System.debug('Found existing user record for '+data.username);
    
                // Update existing record
                u.Email = data.email;
                u.LastName = data.lastName; 
                u.FirstName = data.firstName;
                // Useful to save the Facebook ID in a custom field
                u.Facebook_ID__c = data.identifier;
    
                System.debug('Updating user record for '+data.username);
                
                update(u);
                return u;
            } else {
                return null;
            }
    }

    
    
    
    
    global void updateUser(Id userId, Id portalId, Auth.UserData data){
        string extension = [select username from user where id = '00530000004bSMC'].UserName.substringAfterLast('.');
        system.debug(extension);

        system.debug('Matched user with id ' + userId);
        User u = [select id, email, lastname, firstname, Facebook_id__c, contactid from user where email =: data.email or email =: (data.email+'.'+extension)];
    
        //Update the contact
        String cid = u.contactId;
        Contact c = [SELECT Id, AccountId from contact WHERE id=:cid];
        Account a = [SELECT Id, PersonEmail, firstname, lastname from account WHERE id=:c.accountID];
        a.personemail = data.email;
        a.firstName = data.firstName;
        a.lastName = data.lastName;
        update(a);
    
        AsyncRequest__c ASR = new AsyncRequest__c(Params__c = a.PersonEmail, type__c='TrueCostLoginTracking');
        insert ASR;
        
        u.email = data.email;
        u.lastName = data.lastName;
        u.firstName = data.firstName;
        u.Facebook_ID__c = data.identifier;
    
        update(u);
    }
}