force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Process_Date__c.field-meta.xml
<CustomField>
    <fullName>Process_Date__c</fullName>
    <label>Process Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Queueable__c.field-meta.xml
<CustomField>
    <fullName>Queueable__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>True:  this async is processed by the queueable interface, False: this async is processed by scheduled batch</inlineHelpText>
    <label>Queueable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Slow__c.field-meta.xml
<CustomField>
    <fullName>Slow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</description>
    <inlineHelpText>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</inlineHelpText>
    <label>Slow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApplyClosestWeatherStation</fullName>
            </value>
            <value>
                <fullName>BuildTOULoadProfile</fullName>
            </value>
            <value>
                <fullName>ChatterPostTest</fullName>
            </value>
            <value>
                <fullName>ChatterPostTestParamIsMessage</fullName>
            </value>
            <value>
                <fullName>CheckCirro</fullName>
            </value>
            <value>
                <fullName>CheckContactChangesForCES</fullName>
            </value>
            <value>
                <fullName>CheckDirect</fullName>
            </value>
            <value>
                <fullName>CheckRecordsToSyncExist</fullName>
            </value>
            <value>
                <fullName>CheckSyncBatchStatusForOffice</fullName>
            </value>
            <value>
                <fullName>Choice Position Liquidation Future</fullName>
            </value>
            <value>
                <fullName>CreateChoicePositions</fullName>
            </value>
            <value>
                <fullName>DailyToMonthly</fullName>
            </value>
            <value>
                <fullName>KeepAlive</fullName>
            </value>
            <value>
                <fullName>LockChoiceRate</fullName>
            </value>
            <value>
                <fullName>lowCodeInventory</fullName>
            </value>
            <value>
                <fullName>MakeUHITCleanupCallout</fullName>
            </value>
            <value>
                <fullName>OldScheduledCleanup</fullName>
            </value>
            <value>
                <fullName>PIIfromOrder</fullName>
            </value>
            <value>
                <fullName>PlaceDirectOrder</fullName>
            </value>
            <value>
                <fullName>PlaceTriEagleOrder</fullName>
            </value>
            <value>
                <fullName>ProcessRecordLock</fullName>
            </value>
            <value>
                <fullName>RateExceptionChange</fullName>
            </value>
            <value>
                <fullName>RatingsUpdate</fullName>
            </value>
            <value>
                <fullName>RefreshAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RefreshPartnerAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RemoveExpirationDatesFromPreviousOrders</fullName>
            </value>
            <value>
                <fullName>SetREPofRecord</fullName>
            </value>
            <value>
                <fullName>SetTrueCostOrderRecordType</fullName>
            </value>
            <value>
                <fullName>StaticChoiceCosts</fullName>
            </value>
            <value>
                <fullName>TriEagleOrderCheck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org-wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/Queueable_Process_Count__c.field-meta.xml
<CustomField>
    <fullName>Queueable_Process_Count__c</fullName>
    <description>how many asyncrequests will be processed in one queue?</description>
    <inlineHelpText>how many asyncrequests will be processed in one queue?</inlineHelpText>
    <label>Queueable Process Count</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AsyncQueue.cls
public class AsyncQueue implements Queueable, Database.AllowsCallouts {
	
	public void execute(QueueableContext context) {
		list<AsyncRequest__c> allArs = new list<AsyncRequest__c>();
		list<AsyncRequest__c> ars = new list<AsyncRequest__c>();
		boolean hasMore = false;

		// get record count to process
		OrgWideSettings__c ows = OrgWideSettings__c.getInstance();
        integer recCount = (Integer)ows.Queueable_Process_Count__c;

		try {
			allArs = [select id, name, Type__c, Params__c, Process_Date__c, CreatedDate, Queueable__c from AsyncRequest__c 
					where slow__c=false and Queueable__c = true and Type__c != 'QueueKickoff' and (Process_Date__c = null or Process_Date__c <=: date.today()) 
					order by CreatedDate];

			if (allArs.size()<=recCount){
				// max is less than or equal to count so send them all through
				ars = allArs;
			} else {
				// only pass the first x through and set hasMore to true
				hasMore = true;
				
				for (Integer x=0; x<recCount; x++){
					ars.add(allArs[x]);
				}
				system.debug('request size: ');
				system.debug(ars.size());
			}
		} catch (exception e){}

		
		if (ars.size() > 0){
			try{
				AsyncRequestProcessor.processAsyncQueueRequestList(ars, hasMore);
				
			} catch (exception e){
				system.debug('encountered a queueable interface error: '+e.getMessage());
			}
			//ID jobID = System.enqueueJob(new AsyncQueue());

			//system.debug(jobID);
		}
	}
}