force-app/main/default/objects/AsyncRequest__c/AsyncRequest__c.object-meta.xml
<CustomObject>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>AR-{0000}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AsyncRequest__c/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Process_Date__c.field-meta.xml
<CustomField>
    <fullName>Process_Date__c</fullName>
    <label>Process Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <label>Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Slow__c.field-meta.xml
<CustomField>
    <fullName>Slow__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</description>
    <inlineHelpText>Slow ASRs can get blocked by UHIT traffic update, etc.  Only check this box if your job can wait for hours (could be at least 8 during overnight hours)</inlineHelpText>
    <label>Slow</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AsyncRequest__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ApplyClosestWeatherStation</fullName>
            </value>
            <value>
                <fullName>BuildTOULoadProfile</fullName>
            </value>
            <value>
                <fullName>ChatterPostTest</fullName>
            </value>
            <value>
                <fullName>ChatterPostTestParamIsMessage</fullName>
            </value>
            <value>
                <fullName>CheckCirro</fullName>
            </value>
            <value>
                <fullName>CheckContactChangesForCES</fullName>
            </value>
            <value>
                <fullName>CheckDirect</fullName>
            </value>
            <value>
                <fullName>CheckRecordsToSyncExist</fullName>
            </value>
            <value>
                <fullName>CheckSyncBatchStatusForOffice</fullName>
            </value>
            <value>
                <fullName>Choice Position Liquidation Future</fullName>
            </value>
            <value>
                <fullName>CreateChoicePositions</fullName>
            </value>
            <value>
                <fullName>DailyToMonthly</fullName>
            </value>
            <value>
                <fullName>KeepAlive</fullName>
            </value>
            <value>
                <fullName>LockChoiceRate</fullName>
            </value>
            <value>
                <fullName>lowCodeInventory</fullName>
            </value>
            <value>
                <fullName>MakeUHITCleanupCallout</fullName>
            </value>
            <value>
                <fullName>OldScheduledCleanup</fullName>
            </value>
            <value>
                <fullName>PIIfromOrder</fullName>
            </value>
            <value>
                <fullName>PlaceDirectOrder</fullName>
            </value>
            <value>
                <fullName>PlaceTriEagleOrder</fullName>
            </value>
            <value>
                <fullName>ProcessRecordLock</fullName>
            </value>
            <value>
                <fullName>RateExceptionChange</fullName>
            </value>
            <value>
                <fullName>RatingsUpdate</fullName>
            </value>
            <value>
                <fullName>RefreshAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RefreshPartnerAccountActiveStateField</fullName>
            </value>
            <value>
                <fullName>RemoveExpirationDatesFromPreviousOrders</fullName>
            </value>
            <value>
                <fullName>SetREPofRecord</fullName>
            </value>
            <value>
                <fullName>SetTrueCostOrderRecordType</fullName>
            </value>
            <value>
                <fullName>StaticChoiceCosts</fullName>
            </value>
            <value>
                <fullName>TriEagleOrderCheck</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrgWideSettings__c/OrgWideSettings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Org-wide Settings</label>
</CustomObject>

force-app/main/default/objects/OrgWideSettings__c/fields/FastJobName__c.field-meta.xml
<CustomField>
    <fullName>FastJobName__c</fullName>
    <description>Job name used for the repeating batch job.  If it fails, you can change this name and try again.</description>
    <inlineHelpText>Job name used for the repeating batch job.  If it fails, you can change this name and try again.</inlineHelpText>
    <label>FastJobName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleHandler.cls
public class ScheduleHandler implements ScheduledDispatcher.IScheduleDispatched {
	
	public void execute(SchedulableContext sc)
    {
        system.abortJob(sc.getTriggerID());	// Always abort the job on completion
        RepeatingBatch2.StartTheBatch();
    } 

    public static String GetSchedulerExpression(Datetime dt) {
        return ('' + dt.second() + ' ' + dt.minute() + ' ' + dt.hour() + ' ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year());
    }

	private static Boolean ScheduledInContext = false;

    public static void StartScheduler(Integer AsyncCount)
    {
		if(AsyncCount>0)
		{
			List<AsyncRequest__c> newrequests = new List<AsyncRequest__c>();
	       	for(Integer x = 0; x< AsyncCount; x++) {
				newrequests.add(new AsyncRequest__c(Params__c = 'some parameters'));
	       	}
	       	insert newrequests;
		}
		/*else

		{
			List<AsyncRequest__c> requests = [Select ID, Params__c, Type__c from AsyncRequest__c Limit 1];
			if(requests.size()==0) return;
		}*/


    	if(ScheduledInContext) return;

		ScheduledInContext = true;

		OrgWideSettings__c ows = OrgWideSettings__c.getInstance();
		string jobname = ows.FastJobName__c;

        List<CronTrigger> jobs = [SELECT Id, CronJobDetail.Name, State, NextFireTime
                                  FROM CronTrigger where CronJobDetail.Name=:jobname];
    	if(jobs.size()>0 && jobs[0].state!='COMPLETED' && 
           jobs[0].state!='ERROR' && jobs[0].state!='DELETED') return;	// Already running

        Set<String> activejobstates = new Set<String>{'Queued','Processing','Preparing'};
		List<AsyncApexJob> apexjobs = [Select ID, ApexClass.Name from AsyncApexJob 
                                           where ApexClass.Name = 'RepeatingBatch2' And Status in :activejobstates];
		if(apexjobs.size()>0) return;  // The batch is running
    	
    	//if (Datetime.Now().addSeconds(60)>jobs[0].NextFireTime) return; //we're about to run it anyway, why bother scheduling another one?

    	if (jobs.size()>0) system.abortJob(jobs[0].id); //it exists, but not soon enough, so we delete it.

    	//if there aren't any more non-slow ASRs, grab a few from slow and make them non-slow
    	/*try{
    		if ([select count() from AsyncRequest__c where slow__c=false and (Process_Date__c = null or Process_Date__c <=: system.today())] ==0 && [select count() from AsyncRequest__c where slow__c=true and (Process_Date__c = null or Process_Date__c <=: system.today())]>500)
    		{
	            list<AsyncRequest__c> Slows = [select id, slow__c from AsyncRequest__c where slow__c=true and (Process_Date__c = null or Process_Date__c <=: system.today()) and Retry_Count__c = null order by createddate desc limit 3];
	            for (AsyncRequest__c slow:Slows){
	                slow.Slow__c=false;
	            }
	            update Slows;
	        }
    	} catch (exception e){}
        */

		try{
			System.schedule(jobname, 
	          GetSchedulerExpression(DateTime.Now().addSeconds(4)), 
	          new ScheduledDispatcher());
			}catch (exception e){}
    	
    }

}