force-app/main/default/objects/ValidZipCode__c/ValidZipCode__c.object-meta.xml
<CustomObject>
    <description>Zip Codes and their Corresponding TDSPs</description>
    <label>Zip Code</label>
    <nameField>
        <label>ValidZipCode Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zip Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ValidZipCode__c/fields/Served_by_TrueCost__c.field-meta.xml
<CustomField>
    <fullName>Served_by_TrueCost__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This zip code is served by TrueCost</description>
    <inlineHelpText>This zip code is served by TrueCost</inlineHelpText>
    <label>Served by TrueCost</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RESTZipCodeCheck.cls
@RestResource(urlMapping='/ZipCodeCheck/*')
    global class RESTZipCodeCheck{

    @HttpGet
    global static List<ValidZipCode__c> getAllZips() {
        String Zip = RestContext.request.params.get('zip');
        if (zip!=null){
        	return [SELECT Name, served_by_truecost__c from ValidZipCode__c where served_by_truecost__c = true and Name=:zip];
        } else return [SELECT Name, served_by_truecost__c from ValidZipCode__c where served_by_truecost__c = true];
       return null;
    }
    
    @HttpPost 
    global static boolean CheckAZip(string zipToCheck) {
        try{ 
            ValidZipCode__c vz = [SELECT id, Served_by_TrueCost__c from ValidZipCode__c where Name=:zipToCheck];
            return vz.Served_by_TrueCost__c;
        } catch(exception e){return false;}
    }
    
    
    
}